### ISSUE TITLE
[Feature request]: Disable All keyboard shortcut

### ISSUE THREAD

**Issue by nkbai** [hovancik/stretchly#1000]
### Version

- [X] I'm using version 1.7.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

macOS

### Operating System Version

macOS BigSur 11.4

### Problem description

Disable System shortcut like command+Tab command+Q etc. 
I cannot use the computer when break.

### Possible solution

it seems not work to register a Shortcut.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
I was not able to find anything that would allow this, but I'll keep this open, maybe someone knows of a way.

**Comment by hovancik** [comment]
This is pretty old and I don't think it's possible to disable system shortcuts, so closing. Sorry.
