### ISSUE TITLE
[Bug]: At times, the break page shows nothing

### ISSUE THREAD

**Issue by morningmoni** [hovancik/stretchly#1002]
### Version

- [X] I'm using version 1.7.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

macOS

### Operating System Version

11.2.1 (20D74)

### Reproduction steps

At times, the break page shows nothing (no progress bar or text)

### Expected Behavior

Shows the normal break page..

### Actual Behavior

At times, the break page shows nothing (no progress bar or text)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by morningmoni** [comment]
A screenshot is attached.

![image](https://user-images.githubusercontent.com/8191712/125730154-7e285ee8-78ef-4b16-82cc-da1fc326f2da.png)

**Comment by hovancik** [comment]
I believe I've fixed this issue in #978 so when new version is out, all should work fine.
