### ISSUE TITLE
[Bug]:   Intermittent crashes on linux during idle time

### ISSUE THREAD

**Issue by 1cg** [hovancik/stretchly#1005]
### Version

- [X] I'm using version 1.7.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

Linux

### Operating System Version

Pop!_OS 20.04 LTS (Ubuntu derivative)

### Reproduction steps

1. Run stretchly
2. walk away from computer for a while (1 hour or so)
3. Stretchly crashes
...
looks pretty consistent

### Expected Behavior

no crash

### Actual Behavior

crash

### Relevant log output

```shell
nothing else around this:

stretchly[722501]: segfault at 319e3bec3000 ip 00007f7cb63ef621 sp 00007ffc897ae850 error 4 in libappindicator3.so.1.0.0[7f7cb63e8000+c000]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, this is a bug in `libappindicator3`, see here: https://github.com/hovancik/stretchly/issues/633#issuecomment-716394124

**Comment by 1cg** [comment]
Ah, sorry for the duplicate spam...
