### ISSUE TITLE
[Feature Request]: Password protection

### ISSUE THREAD

**Issue by kumar007git** [hovancik/stretchly#1009]
### Version

- [X] I'm using version 1.7.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Windows

### Operating System Version

Windows 10 (19043.1110)

### Problem description

Password protect the settings and exiting the app to prevent kids from changing the settings or closing the app. This feature is useful for parents who want to install this app on their kids computers to ensure they take proper breaks.

### Possible solution

Password protect the settings and also to exit or close the app.

### Alternative solutions

None.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, I am using Electron.js, and therefore I am limited in what I do. So unfortunatelly I am not able to stop users from closing the app (via Task manager or however it is called in Windows.) Maybe there are some other apps that could prevent Stretchly from being closed? Not really a Windows user here...

Also, all settings are saved in simple file, so I can't prevent poeple from editing it. This could be changed but I don't plan to do that. Sorry.
