### ISSUE TITLE
Electrino

### ISSUE THREAD

**Issue by hovancik** [hovancik/stretchly#101]
Hey guys, 

there is a project to make electron more lightweight and I talked to it's dev. https://github.com/pojala/electrino

Stretchly might become it's test subject. Could be very interesting.

**Comment by cipri-tom** [comment]
Ahh, that would be awesome ! What is the progress on this ?

**Comment by hovancik** [comment]
I haven't tested it yet, as not a lot of api is implemented yet.

**Comment by decadent** [comment]
Might be detrimental for the development of Stretchly while it's still adding features and trying different workflows: if Electrino doesn't have much in the way of APIs, documentation and possibly libs, then people may have trouble customizing it to their needs.

**Comment by MichaelDimmitt** [comment]
When the Electrino progresses further can we expect an Electrino branch in this project? If nothing else I think it will be really cool to see how they are getting it to work and how a packaged app on that branch would compare to a packaged app on the master branch.

**Comment by styfle** [comment]
Electrino is basically dead. I reached out to the author several months ago on twitter and he was kind of overwhelmed.

**Comment by hovancik** [comment]
Yep, closing for now.

**Comment by styfle** [comment]
You might be interested in this list of alternatives for developing JS apps for the desktop https://github.com/styfle/awesome-desktop-js

**Comment by hovancik** [comment]
Thanks! Some interesting stuff there
