### ISSUE TITLE
[Feature request]:custom amount of minutes

### ISSUE THREAD

**Issue by Nicknaem** [hovancik/stretchly#1012]
### Version

- [X] I'm using version 1.7.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Problem description

I just wanted to set remainder in every 22 minutes and have 3 min break, surprised that I cant set custom amount of minutes, it would be nice to give users ability to set custom amount of minutes

### Possible solution

to be able to write custom amount of minutes when I click to the existing one 

### Alternative solutions

make slider to not restrict on every 5 minutes when moving 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Chealer** [comment]
What is your native language? Which duration would you want to customize?
