### ISSUE TITLE
[Feature request]: custom suggestions for time breaks

### ISSUE THREAD

**Issue by Nicknaem** [hovancik/stretchly#1016]
### Version

- [X] I'm using version 1.7.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Problem description

A clear and concise description of what the problem is.
I dont know if its possible to change time break suggestions with custom ones, I would like to be able doing that

### Possible solution

have some config file where current suggestions are listed, where client could alter, or add new suggestions for time breaks
in suggestions I mean texts that appear on mini/large breaks like "close your eyes and breath" ...

### Alternative solutions

better option will be to see suggestions list straight in options tab somewhere and have ability to edit current ones or add new suggestions

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, you can change break ideas by editing config file: 
- https://github.com/hovancik/stretchly#advanced-preferences
- https://github.com/hovancik/stretchly#editing-break-ideas
