### ISSUE TITLE
[Translation]: Its can possible add translation to "eye tips"?

### ISSUE THREAD

**Issue by alex-pancho** [hovancik/stretchly#1017]
### Version

- [X] I'm using version 1.7.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Windows

### Operating System Version

10

### Problem description

Can I add a translation to "eye tips"?
I'm currently using a localized version. Is it possible to translate tips during breaks? If so, I could help with Ukrainian. 

### Possible solution

unknow

### Alternative solutions

unknow

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alex-pancho** [comment]
[pic](https://i.imgur.com/aoQh0cD.png)

**Comment by hovancik** [comment]
Hi, it is currently not possible. Please see #310
