### ISSUE TITLE
[Feature request]: Adjustable pampering/flexibility/control level (allow sensible break window size)

### ISSUE THREAD

**Issue by Chealer** [hovancik/stretchly#1018]
### Version

- [X] I'm using version 1.7.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Problem description

I currently manage RSI using Workrave, which has major issues, on both of my PC-s. I find Stretchly promising at least on a technological level and would like to switch to it. Unfortunately Stretchly is hardly an option on my work PC since it is simply too obtrusive. With Workrave, my work is frequently interrupted, but at least, if a break starts at an inconvenient time, for example during a meeting, it is somewhat subtle. The microbreak window only occupies a small share (less than 10%) of the screen, and I can move it if it's still too inconvenient. Even the rest break window uses a minority of the screen. If I hear for example a message coming from Microsoft Teams during a rest break, I can tell at a glance if my boss is reporting an emergency or if a colleague merely sent a joke. I can tell if a compilation has failed since I left.

In contrast, with Stretchly, the vast majority of my large (2560x1440) screen is fully filled by the opaque break window, which can be neither moved nor resized. making the vast majority of other windows invisible. Microbreaks also cannot always be skipped.

### Possible solution

Obvious solutions would be to shrink the break window's size to a minimum or something closer to Workrave, and ideally allow moving it.

### Alternative solutions

RSI management utilities (Workrave included) have a tendency to pamper their users with obtrusiveness to some degree. This is surely a good thing for some users. For my part, I know the importance of taking breaks, and the interest of these applications is to remind me to take them rather than forcing me to.

The ideal is to allow each user to configure how flexible the utility is, which is what Workrave does. Stretchly already does that to some degree too, via its "Strict Mode" configuration section. I simply suggest giving that section a more general name like "Pampering/flexibility/obtrusiveness/control level" and adding settings to further control that. This could start as simply as adding a "Rest window size" setting with two radio boxes (Minimal/Large).

### Additional information

The following screenshot shows how obtrusive Stretchly's window is:
![image](https://user-images.githubusercontent.com/486141/129456732-abaca9e1-bec0-4b95-a77c-b933e8729a21.png)

The following screenshot shows how unobtrusive Workrave's equivalent window is:
![image](https://user-images.githubusercontent.com/486141/129288638-da209420-ebe6-431e-a199-cb0cbf2e472f.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
The goal of Stretchly is to enforce people to take break :) So right now I don't plan to add option that would support not taking breaks further. 

Anyway, you can change the size of the window, but the  it will not look nice with supersmall sizes: https://github.com/hovancik/stretchly#break-window-size- 

I would suggest reading about advanced options:https://github.com/hovancik/stretchly#advanced-preferences . For me it would more sense to play more with how your postpone system works (https://github.com/hovancik/stretchly#editing-postpone-functionality-) rather then changing window size.

**Comment by Chealer** [comment]
Hi @hovancik ,

> The goal of Stretchly is to enforce people to take break :) So right now I don't plan to add option that would support not taking breaks further.

Stretchly describes itself as "a cross-platform Electron app that reminds you to take breaks when working on your computer".
Its slogan also describes it as "The break time reminder app", not as an _enforcer_ app. If Stretchly developers want to force Stretchly users to take breaks, this should be mentioned in the description to avoid creating undue expectations. What I for one am looking for is just a _reminder_ utility, so had I known that Stretchly was about _imposing_ breaks, I would not have invested time into evaluating it.

> Anyway, you can change the size of the window, but the it will not look nice with supersmall sizes: https://github.com/hovancik/stretchly#break-window-size-
> 
> I would suggest reading about advanced options:https://github.com/hovancik/stretchly#advanced-preferences . For me it would more sense to play more with how your postpone system works (https://github.com/hovancik/stretchly#editing-postpone-functionality-) rather then changing window size.

Yes, I have no plans to use Stretchly at least in the short term, but thank you.

**Comment by Chealer** [comment]
Is there a reason why this ticket was closed?

**Comment by Chealer** [comment]
Please reopen

**Comment by hovancik** [comment]
Hi, as mentioned in my replies, you can already manage the break window size. 

I do not plan to implement other changes in this regard, so I closed this.

**Comment by Chealer** [comment]
I filed ticket #1561 to track this issue while rectifying and updating this one.
