### ISSUE TITLE
[Bug]: Features page covers more than features

### ISSUE THREAD

**Issue by Chealer** [hovancik/stretchly#1020]
### Version

- [X] I'm using version 1.7.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Reproduction steps

This does not report a behavioral bug.

### Expected Behavior

This does not report a behavioral bug.

### Actual Behavior

This does not report a behavioral bug.

### Additional information

[The _Features_ page of Stretchly's website](https://hovancik.net/stretchly/features/) covers features, but also contains considerable offtopic content, including at least the Contributors, Humans and Tools and License sections.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
How would you solve it? I pretty much copied the contents of Readme from Github

**Comment by Chealer** [comment]
Right :-/
I guess the strategy's first step could be to identify all content which is out of place and start with the easy parts.

The _Development_ section could move to a new page titled _Development_. That page could include the _Development_ and _Contributors_ section (as well as the contents currently in the _Report an issue_ page, if you want to keep navigation minimal).

The _Humans and Tools_ section could first be structured, cleaned up and formatted before determining what should go where, but much can visibly move to the _Research_ page. As for _License_ (and probably _Default behavior_), it could probably stay there given a wider title (perhaps _Description_).

**Comment by hovancik** [comment]
I've simply renamed it to "About". It's much more easier to maintain everything for me if it's on single page and same as Readme.
