### ISSUE TITLE
Where is the preference JSON file stored on Debian?

### ISSUE THREAD

**Issue by MartinHahner** [hovancik/stretchly#1021]
I have no `sudo` rights, so I installed stretchly via 
`dpkg-deb -x Stretchly_1.7.0_amd64.deb <CUSTOM_PATH>` to a custom folder.

Now, my tray icon is not working, so I wanted to open the first start dialog again, 
but I can not find my preference JSON file where I could set `isFirstRun` to `true`.

I also tried to remove the installation folder `<CUSTOM_PATH>` and installed stretchly again to a different path.
But even then the startup dialog does not appear, 
so the preference JSON must be stored somewhere outside that custom `<CUSTOM_PATH>`.

Please help.

**Comment by MartinHahner** [comment]
I also can only start `stretchly` via `stretchla --no-sandbox`, but I don't know if this info is relevant.

**Comment by hovancik** [comment]
Looks like something is wrong with your OS setup. You might wanna try https://github.com/hovancik/stretchly#linux-note 

`isFirstRun` only runs welcome window where you can set language, so that's not really needed to be done.

**Comment by MartinHahner** [comment]
@hovancik: Thanks for your reply.

> `isFirstRun` only runs welcome window where you can set language, so that's not really needed to be done.

Yeah, but from there I can also open the preferences via a preferences button, no?
At least that is how I reached the preferences at "FirstRun", but now I am stuck with those settings I set initially.

P.S.: I know it is hacky, but since I do not have `sudo` rights, I do not want to go down this line:
https://github.com/hovancik/stretchly#linux-note

**Comment by hovancik** [comment]
Ah, ok. From https://www.electronjs.org/docs/api/app#appgetpathname: 

> appData Per-user application data directory, which by default points to:

    %APPDATA% on Windows
    $XDG_CONFIG_HOME or ~/.config on Linux
    ~/Library/Application Support on macOS
