### ISSUE TITLE
[Feature request]: Prevent breaks from reset when locking the screen on Mac

### ISSUE THREAD

**Issue by ntn-x2** [hovancik/stretchly#1025]
### Version

- [X] I'm using version 1.7.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.4

### Problem description

I am not sure if it is a missing feature or a bug, but I would love to have breaks going even when I lock my Macbook Pro screen.
What happens now is that if I lock the screen to, e.g., go to the toilette, on my way back the break has disappeared and it is now considered focus time. I am not sure whether the current break is reset, or if the system has moved to the next slot already. I have tried also by disabling the automatic monitoring of system idle time, but it did not fix it. Any suggestions?

### Possible solution

Let the break time going even when Mac screen is locked.

### Alternative solutions

At least an option to set it ON and OFF?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, you can enable this via advanced settings, but it might now work well, as time behaves in weird ways during lock https://github.com/hovancik/stretchly#pause-breaks-on-suspendlock-
