### ISSUE TITLE
[Feature request]: Align long breaks with hourly boundaries

### ISSUE THREAD

**Issue by cameronsstone** [hovancik/stretchly#1029]
### Version

- [X] I'm using version 1.7.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur Version 11.6

### Problem description

I have meetings a lot during my day, and usually have to skip the long breaks as they happen in the middle of meetings. I'd like to be able to configure my long breaks to happen for the last 5 minutes of each hour so I can leave the meeting and remember to have my break. 

### Possible solution

The long break start time would have to expand from "Every X minutes" to a choice of
- Every X minutes
- The Xth minute of every hour.
- The Xth minute of every half-hour.
- (Maybe?) The Xth minute of every Y minutes.

### Alternative solutions

Need some UX guidance here. I don't have a flexible but intuitive solution.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, with technical choices I did in past, it would be very hard to do this, so unfortunately this won't happen. 

I have another app, called LaterOn (https://lateron.app) where you can set schedules like that, but it's not same as Stretchly: you will only get system notifications with the text you specify.
