### ISSUE TITLE
The app stays in the Dock on OS X

### ISSUE THREAD

**Issue by itay-grudev** [hovancik/stretchly#103]
v0.9.0

**Comment by hovancik** [comment]
HI, this is now expected behavior, so we can have tray tooltip showing some stuff. It's not working very well because of electron issue (https://github.com/electron/electron/issues/9447), but I am keeping it there for now.

**Comment by 12people** [comment]
@hovancik Have you thought about making it optional? The dock icon annoys me quite a bit.

**Comment by hovancik** [comment]
That could be done, the tray tooltip is buggy anyway.

**Comment by 12people** [comment]
Forked this into its own task: https://github.com/hovancik/stretchly/issues/106
