### ISSUE TITLE
[Feature request]: Adjustable break instructions reading time

### ISSUE THREAD

**Issue by jemail99** [hovancik/stretchly#1030]
### Version

- [X] I'm using version 1.7.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Linux

### Operating System Version

openSUSE Tumbleweed

### Problem description

When a mini break or break begins the user has to read the suggested instructions, this takes time.
I would like to see a buffer of say 5 seconds to allow the user to read and prepare for the break instructions before the actual timer starts to count down.
Also during the count down it would be useful to have a sound alert the user that they are half way through the countdown. This is useful when the user is instructed to do two things for 10 seconds each in a 20 seconds break and especially if the instruction is to close your eyes!

### Possible solution

A user adjustable pre mini break reading time and adjustable pre break reading time setting.
The user would have eg. 5 seconds to read instructions before mini break timer begins.
The user would have eg. 10 seconds to read instructions before break timer begins.
Ideally both reading times would be user configurable.

### Alternative solutions

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, I would suggest extending the duration of the break itself. Adding what you describe would rather complicate the app and I prefer to keep it simple.
