### ISSUE TITLE
[Feature request]: fix tray icon's shape

### ISSUE THREAD

**Issue by xuestrange** [hovancik/stretchly#1032]
### Version

- [X] I'm using version 1.7.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Linux

### Operating System Version

OS: Manjaro 21.1.6 Pahvo, kernel: Kernel: x86_64 Linux 5.13.19-2-MANJARO,  DE: GNOME 40.0

### Problem description

the tray icon in top bar will change to a icon with three dots inside every several seconds, and then change back soon, it's annoying, is there any way to fix tray icon showing?

this is the normal tray icon, and the changed icon's time is so short that I can't capture it.
![image](https://user-images.githubusercontent.com/59390321/138632376-d0d66619-1f81-43a1-b26e-81f4b3922a9f.png)

### Possible solution

change the preferences configuration file.

### Alternative solutions

revising source code is difficult for me 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by senpl** [comment]
It's indicator of refresh. But I guess not changing this during update could be done. Still it's not seems like huge issue. Just change check interval to bigger value and all should be just fine.

**Comment by hovancik** [comment]
Hi @xuestrange , that has to be something that your DE is doing, I mean the ... dots behavior. I would suggest filing the bug report there: if the icon stays the same, they should not show those ... dots.  

In Stretchly, I am updating tray menu every 10 seconds, as it contains time information for next break and few other things:

![image](https://user-images.githubusercontent.com/4745859/143769000-c90a1d0d-b544-47e1-b408-9733de82ba01.png)
