### ISSUE TITLE
[Feature request]: random popup feature

### ISSUE THREAD

**Issue by jyhub** [hovancik/stretchly#1033]
### Version

- [X] I'm using version 1.7.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Linux

### Operating System Version

ubuntu 20.04

### Problem description

Hi Jan,
I am specialized in relaxing people and would like to suggest a great feature for people behind a screen.
Taking time to relax our body and take time to breath is good but is just a part of our work well-being. The main (I think) is actually how to keep positive relaxed attitude in our mind to work together with fun. How ?
That's really not complicated : Actually, having a post-it on the screen with a big smile to remember to keep the relaxing attitude works really well ... but just for a while, because the post-it will have less and less effect and will have to finally be renewed. The principle on which we can focus is that the attention is solicited by anything new appearing in the vision (or audio) field. We could take advantage of that principle by using an automatic and of course random process to replace the post-it.
And the best is, more you solicit the attention less you need concentration about the correctness of your attitude: that is becoming progressively the natural position.

Stretchly could be a really simple trainer to do that.

Regards,
Jean-Yves

### Possible solution

To help training our attention to grow in more and more easy positive thinking we could use small random popup (shape, color, ..) displaying a random message from a (custom) list. Also, some parameters in the settings would help to drive the popup behaviors.

### Alternative solutions

- a block of post-it and a pen :)
- change job

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Sorry for late reply, I changed job and had no time for Stretchly.

Could you please explain what do you suggest? You mean popup with current messages but in random time?

**Comment by hovancik** [comment]
No response so closing.
