### ISSUE TITLE
[Feature request]: Add Arabic translation

### ISSUE THREAD

**Issue by dblh90** [hovancik/stretchly#1034]
### Version

- [X] I'm using version 1.7.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Linux

### Operating System Version

Ubuntu 20.04.3 LTS

### Problem description

No Arabic translation is provided!

### Possible solution

- Add Arabic translation `ar.json` file to hold all the Arabic labels.
- Add `flag-jo.svg` to show icon of language.

### Alternative solutions

Nothing alternate.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
:+1:  I see that you started working on translations in weblate :) thanks a lot! 

I have some code as work in progress, but once I am finished with it, I will create everything needed for new language and merge the weblate translations

**Comment by dblh90** [comment]
Thank you @hovancik
