### ISSUE TITLE
[Feature request]: 1. Show current time at the reminder window

### ISSUE THREAD

**Issue by choyy** [hovancik/stretchly#1037]
### Version

- [X] I'm using version 1.7.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Linux

### Operating System Version

Manjaro

### Problem description

1. It will be nice to show current time at the reminder window!

~~2. I don't know how other people think about it, but I hope that the reminder window won't be closed when break time is up until I come back to use the pc. It can be closed when the mouse is moved or a key is pressed or just use a button to close it.~~

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, how do you image it? Only show time or add showing of time to the current style? Do you use Stretchly in fullscreen? 

Regarding n2: I don't think that is feasible, with how Stretchly works, all is related to timers, so it would need rather big changes.

**Comment by choyy** [comment]
Hello! I use stretchly in fullscreen and so I think it's a good idea to **add** showing of time to the current style.
As to n2, now I think it doesn't matter since the current is good enough! So just ignore it.
Thanks!!

**Comment by hovancik** [comment]
I've added "Show current time in break window" as advanced option.
