### ISSUE TITLE
[Bug] The app doesn't detect Do Not Disturb mode on Linux

### ISSUE THREAD

**Issue by TheLightTwist** [hovancik/stretchly#1039]
As described above, when I'm enabling "Do Not Disturb" in Notifications widget on KDE Plasma, the app doesn't detect it.
I mean this one widget:
![image](https://user-images.githubusercontent.com/63810245/142639533-54892a76-373d-4a1d-bdfc-ab7175708bd7.png)

App version: 1.7.0
Installed from: AUR ([link](https://aur.archlinux.org/packages/stretchly-bin))
Operating System: Arch Linux
KDE Plasma Version: 5.23.3
KDE Frameworks Version: 5.88.0
Qt Version: 5.15.2
Kernel Version: 5.15.2-arch1-1 (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i5-8300H CPU @ 2.30GHz
Memory: 7.5 GB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 630

**Comment by hovancik** [comment]
Hi @TheLightTwist , when writing Stretchly, I did not find any library that would be detecting DND on Linux: https://github.com/hovancik/stretchly/blob/trunk/app/utils/dndManager.js 

I am even hiding that option from menu on Linux. 

I've tried googling again now, but I am not seeing anything :( There is probably no single standard in Linux land

**Comment by hovancik** [comment]
2023, still don't see any node library that would detect DND on Linux ;/
