### ISSUE TITLE
[Feature request]: Option to toggle on/off the break suspending feature when locking the pc.

### ISSUE THREAD

**Issue by ProxyNode1** [hovancik/stretchly#1049]
### Version

- [X] I'm using version 1.8.1

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 1904

### Problem description

Break suspends upon locking the PC.

### Possible solution

A toggle able option to check whether the user wants to suspend the break or not.

### Alternative solutions

An option in config.json

### Additional information

I would also like to keep the timer feature which activates only when there is an activity after the break.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
https://github.com/hovancik/stretchly#pause-breaks-on-suspendlock-
