### ISSUE TITLE
[Feature request]: Preview theme

### ISSUE THREAD

**Issue by pedlino** [hovancik/stretchly#1051]
### Version

- [X] I'm using version 1.8.1

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Linux

### Operating System Version

Ubuntu 18.04.6

### Problem description

Would be nice to have a Preview button in the Theme tab so that the user can see what changing the Appearance looks like.

### Possible solution

Pressing the Preview button shows the Strecthly window with the chosen Theme

### Alternative solutions

Does not apply

### Additional information

Maybe the Preview button could be placed to the right of the list showing the available Themes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, the color that is in the checkbox area is the thing that changes, so there's nothing else to preview.
