### ISSUE TITLE
[Bug] [L10n]:   Plural forms

### ISSUE THREAD

**Issue by ghost** [hovancik/stretchly#1056]
### Version

- [X] I'm using version 1.8.1

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### Expected Behavior

Weblate should allow translating singular forms without the variable, and allow more plural forms.

### Actual Behavior

Weblate does not allow translating singular forms without the variable, and uses only one plural form.

### Additional information

In Hebrew, we usually translate "%1 minute" as "minute"; We also have one word for "2 hours" in Hebrew (and Arabic), And these make the variable unneeded when translating the strings in these situations. Somehow, Weblate blocks string translations that miss that variable.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Not sure if I understand, but in translation file, here's how ie `hours` are (https://github.com/hovancik/stretchly/blob/trunk/app/locales/he.json): 

```
    "hours_one": "שעה",
    "hours_two": "{{count}} שעות",
    "hours_many": "{{count}} שעות",
    "hours_other": "{{count}} שעות",
```

this follows https://www.i18next.com/translation-function/plurals and in turn  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules/PluralRules 

Each language has different number of plurals

**Comment by yarons** [comment]
I understand, this is also incorrect, in Hebrew the second form lacks a placeholder as well.

The question was if it's possible to just ditch the placeholder completely so if the original string says: `{{ count }} hour`, can I will translate it to `שעה` without the placeholder? same goes for two hours

**Comment by hovancik** [comment]
So by "placeholder" you mean `{{ count }}`? I was able to remove in weblate it from my phone. I guess editing json would also do the trick. 

The question then is: 
Will strings like `About 1 hour 1 minute remaining` or `in about 1 hour 1 minute` be correctly translated/understood if you remove the numbers? 

In general, I am not familiar with Weblate and translations, it's good question to ask them what they expect.

**Comment by yarons** [comment]
Yes, it looks unnatural in English but saying a sentence like this in Hebrew is pretty natural: An hour and a minute remaining.

**Comment by hovancik** [comment]
Feel free to edit it out, then.

**Comment by ghost** [comment]
> Feel free to edit it out, then.

Somehow, Weblate enforces using the variable.

**Comment by hovancik** [comment]
I see, not sure why is that. But you can remove those strings by editing json right here in github: https://github.com/hovancik/stretchly/blob/trunk/app/locales/he.json

I have tried removing all `{{count}}` in my local code and all seemed to work fine, so I guess it's safe to do.

**Comment by ghost** [comment]
> I see, not sure why is that. But you can remove those strings by editing json right here in github: https://github.com/hovancik/stretchly/blob/trunk/app/locales/he.json
> 
> I have tried removing all `{{count}}` in my local code and all seemed to work fine, so I guess it's safe to do.

Thank you. Opened an pull request on https://github.com/hovancik/stretchly/pull/1071
