### ISSUE TITLE
[Bug]: Do not get upgrade 1.8.1 from Chocolatey

### ISSUE THREAD

**Issue by kkbruce** [hovancik/stretchly#1057]
### Version

- [ ] I'm using version 1.8.1

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

Windows

### Operating System Version

Windows 11 21H2

### Reproduction steps

1. choco upgrade stretchly
2. choco uninstall stretchly
3. choco install stretchly
...
**Reproduces how often:** [What percentage of the time does it reproduce?]
everytime

### Expected Behavior

upgrade to stretchly 1.8.1

### Actual Behavior

get stretchly 1.7.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, Chocolatey is community effort, it is not associated with Stretchly. Unless some volunteer upgrades it there, it won't get upgraded. TBH, I don't have a Windows machine, only some Virtualbox, and I don't use Windows.
