### ISSUE TITLE
[Bug]: Transparency option is not working

### ISSUE THREAD

**Issue by jojoclt** [hovancik/stretchly#1058]
### Version

- [X] I'm using version 1.8.1

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

Linux

### Operating System Version

Ubuntu 21.10

### Reproduction steps

1. Enable transparency checkbox in theme section
...
**Reproduces how often:** 100%

### Expected Behavior

In between the breaks, the dialog should be transparent

### Actual Behavior

It is shown in solid color

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Should be fixed in https://github.com/hovancik/stretchly/pull/1054
