### ISSUE TITLE
[Bug]: Stretchly is intercepting Play/Pause media key

### ISSUE THREAD

**Issue by kazerniel** [hovancik/stretchly#1059]
### Version

- [X] I'm using version 1.8.1

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

Windows

### Operating System Version

Windows 10 v1809

### Reproduction steps

When trying to register a global hotkey in Winamp, it says my keyboard's Play/Pause media key is already registered to another application. I used Microsoft's Spy++ following [this](https://stackoverflow.com/a/43645062/12215117) guide, and it showed me that Stretchly is using that hotkey, even though these settings are left on default:

    "pauseBreaksShortcut": "",
    "resumeBreaksShortcut": "",

### Expected Behavior

To not use a hotkey it's not set to use.

### Actual Behavior

See above. Using the hotkey doesn't seem to do anything in Stretchly itself.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kazerniel** [comment]
Nvm, it stopped doing it O.o

**Comment by kazerniel** [comment]
Ok so apparently the media keys only pause/play Winamp, while the Stretchly break window is active.

**Comment by hovancik** [comment]
Hi, can you show me what that app says? Stretchly only registers shortcuts if they are set in preferences. If something gets registered, then it must be some weird Electron.js thing

**Comment by kazerniel** [comment]
Sorry, I can't reproduce it right now, it sort of comes and goes 🤔 I can take a screenshot of it the next time it happens.

**Comment by kazerniel** [comment]
Got it:
![stretchly media hotkey 1](https://user-images.githubusercontent.com/5689996/147828787-cd579abd-927e-4afb-88e8-3aa79a9c2388.png)
![stretchly media hotkey 2](https://user-images.githubusercontent.com/5689996/147828789-67822a5c-d09f-4b08-9a3c-a2287d66e241.png)
![stretchly media hotkey 3](https://user-images.githubusercontent.com/5689996/147828790-aab0bc2c-2a2a-4e86-887c-4df2cc58807a.png)
![stretchly media hotkey 4](https://user-images.githubusercontent.com/5689996/147828791-f8558495-054f-4a00-a430-106b712a6067.png)
![stretchly media hotkey 5](https://user-images.githubusercontent.com/5689996/147828794-2648ec40-428b-42aa-9776-f5102a9a845e.png)
![stretchly media hotkey 6](https://user-images.githubusercontent.com/5689996/147828795-fc71a9b4-7f96-47a1-8df3-641d9ab9066b.png)

**Comment by hovancik** [comment]
Thanks! So what are those screenshots saying? Was it again when break was active?

**Comment by kazerniel** [comment]
Those are the screenshots I got when following through the steps of this guide: https://stackoverflow.com/questions/829007/find-out-what-process-registered-a-global-hotkey-windows-api/43645062#43645062

As far as I understand, in the last window it identifies Stretchly as the process that registered the "Media Play Pause" global hotkey.

The break wasn't active at that time.

**Comment by hovancik** [comment]
I am not setting such a hotkey in my code, but looks like there is an issue in Electron: https://github.com/electron/electron/issues/32385 

I don't have youtube videos playing, like in that issue, but I play sounds (ie. Break finished). 

Can you try disabling sounds from Preferences -> Theme and see if issue is still there? Restart of Stretchly or maybe better whole computer would be needed I guess to make sure OS doesn't hold that shortcut after Stretchly has been restarted

**Comment by kazerniel** [comment]
Stretchly doesn't seem to intercept the hotkey if I disable sounds.

Not 100% sure if it's a consistent behaviour, as the bug hasn't appeared consistently either.

I can let you know if it changes behaviour, for now I can leave the sound off to avoid the bug.

**Comment by hovancik** [comment]
:+1: Thanks for trying! I guess we'll have to wait for Electron issue to be fixed. Can't think of any workaround right now

**Comment by hovancik** [comment]
So the electron issue has been fixed, so hopefully next version of Stretchly will work fine.

**Comment by hovancik** [comment]
@kazerniel did you have a chance to check new version?

**Comment by kazerniel** [comment]
I turned back the sound now and Stretchly seems to not intercept the hotkey anymore. The bug wasn't consistent, so can't be 100% sure it's gone, but for now it seems fixed, and I'll comment here if that changes :)
