### ISSUE TITLE
[Feature request]: allow to load an html file when the pause fire

### ISSUE THREAD

**Issue by rid3r45** [hovancik/stretchly#1066]
### Version

- [X] I'm using version 1.8.1

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

macOS

### Operating System Version

MacOSX 10.13.6

### Problem description

It would be great when a pause fire to allow to load an html page. (stored locally). It is something you could allow? Sincerely.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, what would be on such a website? I mean: JS, nodejs? With electron's security model, it would be easier for you to fork repo and edit break files as you wish.

**Comment by hovancik** [comment]
No answer and I don't plan to implement this, so closing. Sorry.
