### ISSUE TITLE
[Bug]:   No no tray icon on macOS Big Sur v11.6.1

### ISSUE THREAD

**Issue by lexabug** [hovancik/stretchly#1068]
### Version

- [X] I'm using version 1.8.1

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur  v11.6.1

### Reproduction steps

1. Install with the dmg file.
2. Open the app for the first time and choose language.
3. No tray icon displayed, but there is a process in the Activity Monitor.
4. Also when I try to execute a command like `/Applications/Stretchly.app/Contents/MacOS/Stretchly mini -T "Stretch up"` it fails out with error like
```
Stretchly command instance: started

Forwarding command to main instance
[21707:1209/125027.765960:ERROR:mach_port_rendezvous.cc(310)] bootstrap_look_up net.hovancik.stretchly.MachPortRendezvousServer.1: Permission denied (1100)
```
...
**Reproduces how often:** 100%

### Expected Behavior

The tray icon is displayed, so i can get access to the prefs + commands are executed w/o failures.

### Actual Behavior

1. No tray icon displayed, but there is a process in the Activity Monitor.
2. Also when I try to execute a command like `/Applications/Stretchly.app/Contents/MacOS/Stretchly mini -T "Stretch up"` it fails out with error like
```
Stretchly command instance: started

Forwarding command to main instance
[21707:1209/125027.765960:ERROR:mach_port_rendezvous.cc(310)] bootstrap_look_up net.hovancik.stretchly.MachPortRendezvousServer.1: Permission denied (1100)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, the issue with command line interface was fixed today so next release should have it (#1069) - tested on Linux. 

Regarding icon: does this happens all the time? Sometimes for me I don't see icon (I think it's some weird Electron.js bug) but when I kill it and run again, all is fine.

**Comment by lexabug** [comment]
> Regarding icon: does this happens all the time? Sometimes for me I don't see icon (I think it's some weird Electron.js bug) but when I kill it and run again, all is fine.

Hi Jan.
I'm sorry for the delay in my response.
The issue w/ the tray icon is a permanent one for me. I haven't seen it since the time I installed the app. Killing and restarting the app doesn't do the trick.
BTW is there a command that I can use to display the preferences' window, so I can control the settings at least?

**Comment by hovancik** [comment]
Hi, there is no command to open prefs, but you can edit it by config file: https://github.com/hovancik/stretchly#advanced-preferences.

on macos Stretchly folder should be located in `~/Library/Application Support`. You should also be able to find logs there. 

How did you install Stretchly? Can you try reinstall? Are you running from Apps folder?  Also maybe try changing macOS theme? Dark vs Light.

**Comment by lexabug** [comment]
I insalled Stretchly with the dmg file downloaded from the releases page of the git repo. I've just tried to reinstall, change the theme to the light one and the result is the same. And I'm running it from the Apps folder.

**Comment by hovancik** [comment]
Did you manage to find the logs? I don't see what could go wrong :(

**Comment by lexabug** [comment]
I've just installed the most recent version from the releases page (v1.9.0). I've found logs in the logs directory, but the only entry there says `[2022-01-24 09:24:00.874] [info]  Stretchly: checking for new version (local: v1.9.0, remote: 1.9.0)`. So nothing abnormal there :(

**Comment by hovancik** [comment]
Sorry for late reply, bit busy nowadays :( 

Do you only have that one line? Should be a bit more lines, like this: 

```
[2022-02-21 14:40:24.645] [info]  Stretchly: initializing...
[2022-02-21 14:40:24.655] [info]  Stretchly: loading preferences
[2022-02-21 14:40:24.664] [info]  Stretchly: starting Idle time monitoring
[2022-02-21 14:40:24.664] [info]  Stretchly: starting Do Not Disturb monitoring
[2022-02-21 14:40:26.499] [info]  Stretchly: checking for new version (local: v1.9.0, remote: 1.9.0)
```

Looks like that Stretchly does not manage to start at all. But not sure how, never seen behavior like that

**Comment by lexabug** [comment]
> Sorry for late reply, bit busy nowadays :(
> 
> Do you only have that one line? Should be a bit more lines, like this:
> 
> ```
> [2022-02-21 14:40:24.645] [info]  Stretchly: initializing...
> [2022-02-21 14:40:24.655] [info]  Stretchly: loading preferences
> [2022-02-21 14:40:24.664] [info]  Stretchly: starting Idle time monitoring
> [2022-02-21 14:40:24.664] [info]  Stretchly: starting Do Not Disturb monitoring
> [2022-02-21 14:40:26.499] [info]  Stretchly: checking for new version (local: v1.9.0, remote: 1.9.0)
> ```
> 
> Looks like that Stretchly does not manage to start at all. But not sure how, never seen behavior like that

I've upgraded to the Monterey recently. And the situation is the same :(
That line is the only one i see in the `~/Library/Application Support/Stretchly/main.log`. However I see the main process and helpers running and the popup appears. So the issue w/ the tray icon persists: I don't see it and cannot open preferences :(

**Comment by hovancik** [comment]
Do you happen to have some antivirus? 

I am out of ideas :(

**Comment by hovancik** [comment]
Hi, is still issue in the latest version?

**Comment by lexabug** [comment]
Hi @hovancik. No, it's not a problem anymore. And I think the issue was related to the usage of the dozer app. I think it made some apps in the tray to disappear completely. So I decided to disable it.
Thanks.
