### ISSUE TITLE
Flattr counter is broken

### ISSUE THREAD

**Issue by 12people** [hovancik/stretchly#107]
This relates to the website rather than to the app.
The counter for Flattr, and perhaps some other services, is broken, stuck at 0: https://hovancik.net/stretchly/ .

**Comment by hovancik** [comment]
Hi, maybe it takes some processing on the flattr side? When I login to flattr I do not see any flattrs as well. 

Many thanks if you contributed!

**Comment by 12people** [comment]
I guess the counter increases at the end of the month, when payments are made out. ¯\_(ツ)_/¯
We'll see.

**Comment by hovancik** [comment]
My balance was increases ;] 
I guess counter is broken on flattr side.
