### ISSUE TITLE
[Bug]:   White-Gray Screen Buttons not avaliable

### ISSUE THREAD

**Issue by serhattural** [hovancik/stretchly#1078]
### Version

- [X] I'm using version 1.8.1

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Reproduction steps

1. Skip to next break
2.
3.
...
Reproduces how often: Always
![st](https://user-images.githubusercontent.com/15214526/147245846-3ece314d-2d7c-44fe-abe3-5398ee92f240.jpg)

### Expected Behavior

I expected to see non blank break screen.

### Actual Behavior

In 1.7 version I works as expected. But 1.8 and 1.81 versions I see a blank screen issue on break screen.

### Preferences

```shell
changing theme settings doesnt affect.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Just fixed that the other day in #1073 , please wait for new release :)
