### ISSUE TITLE
[Bug]:   high cpu usage since macOS Big Sur

### ISSUE THREAD

**Issue by b-hal** [hovancik/stretchly#1079]
### Version

- [X] I'm using version 1.9.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur (intel)

### Reproduction steps

1. Start Strechly
2. open Activity Monitor (Utilities)
3. select all processes; sort by % cpu 
...
**Reproduces how often:** 100% (every time)

### Expected Behavior

CPU Activity of process Stretchly should be less than 1%

### Actual Behavior

CPU Activity of process Stretchly is more than 42% 

### Additional information

```shell
The high cpu usage was not seen at macOS Mojave and started with macOS Big Sur.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by przprz** [comment]
Had similar issue with macOS Monterey. Restoring default settings seems to have fixed high CPU usage for me.

**Comment by hovancik** [comment]
What were the settings you had changed @przprz ? 

@b-hal have you tried restoring defaults as was suggested? I would also try restarting whole macOS. Stretchly is built with ElectronJS which is known to be resource hungry, so there might be some leak in it.

**Comment by hovancik** [comment]
Looks like it's related to the Electron, indeed: https://github.com/electron/electron/issues/31916

**Comment by b-hal** [comment]
indeed, to delete the prefs ( /Users/xxxx/Library/Application Support/Stretchly ) was the solution. Thank you for your support!

**Comment by b-hal** [comment]
I checked it and the  CPU Activity of process Stretchly will be more than 42% if I use the 
"appExclusions": [   
with  macOS Big Sur (intel). (Tested with Version 1.9.0)

**Comment by hovancik** [comment]
I would say that is expected: app exclusion compares all running processes against the list in preferences every second :(

**Comment by b-hal** [comment]
But this did not happen in macOS Mojave. For me it started after the update to macOS Big Sur. (Because I skip Catalina, I can´t say anything about Catalina.)

**Comment by hovancik** [comment]
Ah, gotcha. Will try to on my mac when I have a chance.

**Comment by hovancik** [comment]
Same here on my mac, but I am not really surprised as it tries to find the item in hundres of items every second. 

I am using `includes` which they say is [the fastest](https://towardsdatascience.com/should-you-use-includes-or-filter-to-check-if-an-array-contains-an-item-1a8365dfc363). I guess the 1 second could be made bigger but then it's less useful.

**Comment by b-hal** [comment]
I think to make 'the 1 second could be made bigger ' is the right way.

I see 2 use cases for the appExclusions function:
1. Do not "Break" and block the screen!
2. halt the timer for the next "Break" ?

Case 1 is important, I don´t know about case 2. 
To implement  >Do not "Break" and block the screen<  it is enough to check the appExclusions before a break starts. 
Additional checking every 10 or more seconds for case 2 and to change the status of the menu-icon should be sufficient.

**Comment by hovancik** [comment]
I've added simple option to specify interval. Will be out in next release.
