### ISSUE TITLE
Translations 

### ISSUE THREAD

**Issue by jony0008** [hovancik/stretchly#108]
Would be great to have stretchly in different languages. I can recommend Crowdin or Weblate for managing the translations.

**Comment by hovancik** [comment]
Hi, this is on my todo list, I'll add your recommendations

**Comment by aGoogleFan** [comment]
I would be glad to help you add Persian/Farsi language, but I donnu how.

**Comment by hovancik** [comment]
@aGoogleFan the easiest would be to create a PR. Do you know how to do it?

**Comment by aGoogleFan** [comment]
unfortunately, I don't know.
i would be appreciate if you link me to an instruction about doing such a job.

**Comment by hovancik** [comment]
@aGoogleFan  what platform are you on? 

github has docs here: https://help.github.com/articles/about-pull-requests/ 

if you are not familiar with git in general, this might be too hard
