### ISSUE TITLE
[Bug]: Transparency option is not working on macOS

### ISSUE THREAD

**Issue by skyran1278** [hovancik/stretchly#1082]
### Version

- [X] I'm using version 1.9.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.1

### Reproduction steps

1. Enable transparency checkbox in theme section

...
**Reproduces how often:** 100%

### Expected Behavior

In between the breaks, the dialog should be transparent

### Actual Behavior

It is shown in solid color

### Additional information

```shell
It is work on Windows, but not on macOS.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Works as well on Linux. Not sure why macOS is broken ;/ For me, it is transparent for few seconds and then it is no.

**Comment by hovancik** [comment]
Probably related to this bug in Electron: https://github.com/electron/electron/issues/16212

**Comment by hovancik** [comment]
This seems to be fixed in latest version. Can you try? All good for me.

**Comment by skyran1278** [comment]
I have installed 1.10.0 version, but still have same problem.

**Comment by skyran1278** [comment]
Maybe it's because shows breaks in full screen setting. 
On macOS this will open a new window, so transparency will not take effect.
Thank you.

**Comment by hovancik** [comment]
so it's fine then? I don't know how it should behave correctly

**Comment by skyran1278** [comment]
it's fine. thank you.
