### ISSUE TITLE
[Feature request]: Don't trigger break when mouse is down

### ISSUE THREAD

**Issue by sfelshin** [hovancik/stretchly#1094]
### Version

- [X] I'm using version 1.9.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.6.2

### Problem description

Stretchly pops up a break even when the mouse is currently down. If I'm in the middle of dragging something, odds are that Stretchly's banner covers where I'm dragging from and/or to.  If I release the mouse, I'll drop whatever I'm dragging and won't be able to see where I dropped it—perhaps hidden inside a folder—and I may not be able to Undo the operation.  If I hold the mouse down through the break, that's an ergonomic nightmare, even worse than no break at all.

### Possible solution

If the mouse is down, don't trigger a break. Then go ahead and trigger a break, either immediately on mouse up, or whenever some clock cycle would ordinarily trigger Stretchly to check whether it's time for a break—either way is fine by me.  Of course, before breaking, check again to make sure the mouse isn't down again.

Compare #1007. My feature request should be easier because there's no question of what constitutes "currently" or "typing". Either the mouse is down or the mouse is up.

### Alternative solutions

I try to find "safe" places to drop things I'm in the middle of dragging, but depending on what I'm doing there may not be a visible "safe" place.  Plus, it's physically and mentally fatiguing to hold the mouse down while scanning the edges of the screen (especially when Stretchly has just broken me out of my deep concentration on just one thing to suggest that I do one thing at a time!).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
I searched the web, but don't see any way how I could possibly detect that user is draging ;/

**Comment by sfelshin** [comment]
Thank you. It doesn't matter if the user is dragging or not—it only matters if the mouse is currently down.  Is it possible to detect that?  Here are my results of a quick search, but I confess I haven't read the pages I found.
* https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/EventOverview/HandlingMouseEvents/HandlingMouseEvents.html
* https://stackoverflow.com/questions/40886732/macos-detect-if-mouse-button-is-down-in-keydown
* https://stackoverflow.com/questions/38278668/how-to-detect-right-mouse-down-and-other-mouse-down-while-left-mouse-dragged-on
* https://apple.stackexchange.com/questions/142814/run-an-applescript-on-mouse-down
* https://discussions.apple.com/thread/2264626
* https://stackoverflow.com/questions/2166228/catching-mousedown-events-of-subviews-cocoa-osx
* https://apple.stackexchange.com/questions/268529/mouse-click-event-being-fired-on-right-mouse-down-and-right-mouse-up
* https://stackoverflow.com/questions/6753727/mouseentered-event-disabled-when-mousedown-nsevents-mac
* https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onmousedown
* https://javascript.info/mouse-events-basics

**Comment by hovancik** [comment]
Yes, that would work in case there is stretchly windows focused. App can't detect events if it's not active, as far as I know.

**Comment by sfelshin** [comment]
When Stretchly pops up, does it grab focus?  Maybe it could pop up its banner as usual, realize the mouse is down, and immediately go away again.  It would be a little disconcerting to see it jump up for a moment, but not really disruptive.  One could hold the mouse down for an extra instant while waiting for Stretchly to go away without much hand strain.  I'd love this feature.  If some people would hate it, I suppose it could be controlled by a preference setting.

**Comment by hovancik** [comment]
Focus stays in the previous window, not Stretchly.

**Comment by sfelshin** [comment]
😞

**Comment by hovancik** [comment]
As I don't see a way how to fix this, I will close the issue. Sorry :(
