### ISSUE TITLE
[Feature request]: Custom colors and custom text during breaks

### ISSUE THREAD

**Issue by snowfoldart** [hovancik/stretchly#1098]
### Version

- [X] I'm using version 1.9.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Problem description

Hello. I love the function of this program and the way it pops up on screen. I have two issues though, the limited color choice, and i can't choose what it says or exactly when to pop up. I want to use this for stretching but it would also really help my life if i can customize the long breaks to let me know what i should be doing on my schedule, if the breaks could be scheduled to specific times it would be absolutely amazing and have way more utility. 

### Possible solution

Some solutions could be the ability to choose colors with hex codes or RGB values,

As for the custom text, in preferences a panel to choose what the break pop up says would be awesome

### Alternative solutions

Other solutions for the colors could be a color swatch of every color. For schedules, a way to schedule a long or mini break at 09:00 or 13:00, and choose what it says.

### Additional information

I am an artist and want to use this to prevent wrist injury or to help me schedule my day better, and i believe this is the perfect app for it with the way it can pop up in a fullscreen with the beautiful UI, timer, and sounds.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, I don't plan to add breaks at specific times, but you can set custom texts and color by editing configuration file: https://github.com/hovancik/stretchly#advanced-preferences
