### ISSUE TITLE
[Bug]:   Can't uninstall old version?

### ISSUE THREAD

**Issue by DanijelDomazet** [hovancik/stretchly#1106]
### Version

- [ ] I'm using version 1.9.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

Linux

### Operating System Version

Ubuntu 20.04

### Reproduction steps

How do I update the app? 

- I had ver 1.9 installed. 
- I downloaded ver 1.10, installed the Stretchly_1.10.0_amd64.deb using the Ubuntu Software updater. 

However, now I have 2 versions in parallel, two shortcuts, etc. 

I tried `sudo apt remove stretchly`, but this removed 1.10. 

How do I remove 1.9?

### Expected Behavior

After installing 1.10, I expected 1.9 to be uninstalled.

### Actual Behavior

Both versions are on the system. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
How did you install 1.9? 

I am installing manually with `sudo dpkg -i stretchly.deb` and never had any issue. 

My guess is that you installed 1.9 and 1.10 with different methods, thus they are not rewriting themselves.

**Comment by DanijelDomazet** [comment]
I don't remember how I installed the first one.

Strange thing is: it's been a month now, and I just checked both versions: they are both 1.10! Seems like the 1.9 auto updated to 1.10 in the meantime.

So I removed the 2nd install: `sudo apt remove stretchly`, and now I have only one version. 

Still don't know how to manually update or (if I ever want to) uninstall the current installation, the first one I installed but not remember how...?

**Comment by hovancik** [comment]
I've updated snap package few days ago, so I think it's snap package :) Ubuntu uses those :) 

maybe try `snap list`

**Comment by DanijelDomazet** [comment]
Yes! `snap list` and there it is!

**Comment by hovancik** [comment]
Great 👍
