### ISSUE TITLE
[Bug]:   Window is grey for several seconds before rendering the theme

### ISSUE THREAD

**Issue by foundryspatial-duncan** [hovancik/stretchly#1111]
### Version

- [X] I'm using version 1.10.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

Linux

### Operating System Version

Ubuntu 20 with Cinnamon desktop

### Reproduction steps

1. Wait for a long or short break to happen
...
**Reproduces how often:** 100%

### Expected Behavior

The window pops up and begins counting down, with the selected theme colors.

### Actual Behavior

The window pops up as a grey square, with a white line where the progress bar should be. No other text is visible. After ~8 seconds, the window content loads.

### Relevant log output

```shell
Node.js: 16.13.0
            Chromium: 98.0.4758.82,
            Electron: 17.0.1
          
(nothing unusual in the logs, the window does pop up on time, but it takes 10 seconds to load)
```

### Additional information

```shell
I recently upgraded to 1.10.0, this didn't happen before (In 1.6.0, I think)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by foundryspatial-duncan** [comment]
It looks like the delay gets longer with the system uptime. I put my PC to sleep rather than shutting it down last night, and today the break windows are grey for 15 seconds before they render and show the timer with only 5 seconds left :laughing:

**Comment by hovancik** [comment]
Yeah there was some change in electron some time ago and Stretchly is unable to start with correct color since then :(

How's your computare usage? I noticed that when in heavy use, similar things happen to me, but not that bad (usually like 5 seconds). Stretchly uses electron which is not resource friendly. 

I guess I could rework Stretchly to open break when everythiing is ready, but kinda afraid, as any time I change that code, many bugs appear :) that's the life with electron

**Comment by hovancik** [comment]
related: https://github.com/hovancik/stretchly/issues/1048 
https://github.com/hovancik/stretchly/issues/1043
https://github.com/hovancik/stretchly/issues/1044

**Comment by foundryspatial-duncan** [comment]
My ram and CPU usage seem just fine, but the delay gets longer and longer throughout the day. By the end of a work day, sometimes it's a 15-second delay on a 20-second break

edit: if it helps, I'm also using a lot of electron apps at the same time. But they all render just fine (and older versions of Stretchly did as well)

**Comment by hovancik** [comment]
I've made some changes in #1136 so this will hopefully disappear on next update.

**Comment by hovancik** [comment]
Note to self: more changes in #1176
