### ISSUE TITLE
[Feature request]: Toggle pause/resume breaks with single shortcut

### ISSUE THREAD

**Issue by SimSon2710** [hovancik/stretchly#1112]
### Version

- [X] I'm using version 1.10.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### Problem description

Right now in the config.json one can set a shortcut for "pauseBreaksShortcut" and "resumeBreaksShortcut". If I set the same shortcut for both options, nothing happens (or it always resumes?). So, it would be nice that if I set the same shortcut for both, it would toggle between pausing and resuming breaks.

### Possible solution

If the shortcuts for "pauseBreaksShortcut" and "resumeBreaksShortcut" are the same, and the shortcut was pressed, check whether breaks are paused or running. If they are already paused, run "resumeBreaksShortcut", else, run "pauseBreaksShortcut".

### Alternative solutions

Another option would be to implement a flag "toggleBreaksShortcut" which on default is None. If it's set to a shortcut and both, "pauseBreaksShortcut" and "resumeBreaksShortcut", aren't set, this shortcut is used to toggle between resuming and pausing breaks.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
That's good point. TBH I am not sure why I separated those. There probably was some reason. Will have to check the code to try to remember.
