### ISSUE TITLE
[Bug]:  mini breaks, break for:  time display (utils.minutes)

### ISSUE THREAD

**Issue by Alekselion** [hovancik/stretchly#1113]
### Version

- [X] I'm using version 1.10.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### Reproduction steps

1. go to tab 'Shedule'
2. change break for (mini breaks) to 3 minutes and 30 seconds

### Expected Behavior

display 3m 30s or 3 minutes and 30 seconds

### Actual Behavior

display 'utils.minutes' 
![screen](https://github.com/Alekselion/sandbox/blob/master/bug.jpg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Thanks for the report :) Does this happen every time?

**Comment by Alekselion** [comment]
Yes, wherever time is not whole (1m 30s, 2m 30s, 3m 30s and etc.) четверг, 17 марта 2022г., 15:46 +03:00 от Jan Hovancik  ***@***.*** :
