### ISSUE TITLE
error: cannot find signatures with metadata for snap

### ISSUE THREAD

**Issue by mwoz123** [hovancik/stretchly#1117]
Error:
```
marcin@pc:~$ sudo snap install ./Pobrane/Stretchly_1.10.0_amd64.snap 
error: cannot find signatures with metadata for snap "./Pobrane/Stretchly_1.10.0_amd64.snap"
```

workaround: 
`marcin@pc:~$ sudo snap install ./Pobrane/Stretchly_1.10.0_amd64.snap  --dangerous`

source:
https://askubuntu.com/questions/822765/snap-install-failure-error-cannot-find-signatures-with-metadata-for-snap

**Comment by hovancik** [comment]
I am using https://www.electron.build/configuration/snap

doesn't look like there is any support for any kind of signature ;/

**Comment by mwoz123** [comment]
My bad. Sorry. Had something wrong with SnapDeamon, after reisntallation Strechly snap works fine
