### ISSUE TITLE
When I am in a Zoom meeting, stretchly doesn't interupt me, but when I'm in a Microsoft Teams meeting it continues to run.  How can I change this?[Bug]:   

### ISSUE THREAD

**Issue by rachsmac** [hovancik/stretchly#1120]
### Version

- [X] I'm using version 1.10.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### Reproduction steps

1. start a teams meeting
2. stretchly still comes up on the screen overlaying the meeting
3.
...
**Reproduces how often:** [What percentage of the time does it reproduce?]

### Expected Behavior

Pause breaks while teams meeting is running

### Actual Behavior

breaks are not paused they continue to run

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chchen2021** [comment]
On macOS, it seems to be the reverse problem. If I put Teams in the exclusion list, then Stretchly will be paused indefinitely when Teams is first launched, and continue to be paused even after Teams is closed. The only remedy is a restart. In contrast, Zoom works as expected.

**Comment by hovancik** [comment]
Could you please paste your configuration file?

By default, Stretchly does not check for any other apps, but if the app sets system-wide Do not disturb mode, Stretchly follows it.

**Comment by chchen2021** [comment]
This is my app exclusion settings in config.json. I am on the latest macOS Monterey, and on Stretchly 1.9.0 (to avoid the timeToBreakInTray bug).  Zoom works fine, but Teams lead to an indefinite pause even after quitting the GUI. I should add that Microsoft apps sometimes do weird things in the background, so I am not sure if this is a Stretchly issue or a Teams issue. 

```
	"appExclusions": [
    	{
			"rule": "pause",
			"active": true,
			"commands": [
				"/Applications/zoom.us.app",
				"Microsoft Teams"
			]
    	}
	]
```

**Comment by rachsmac** [comment]
Sorry I don’t know how to do that. I guess my issue then is figuring out how to make teams set windows to do not disturb while in a meeting. I will keep researching.

**Comment by hovancik** [comment]
@rachsmac did you set `appExclusions`?

@chchen2021 could you paste the log here? There are messages about what Stretchly does when `appExclusions` are set.

**Comment by chchen2021** [comment]
@hovancik Teams now works so I cannot reproduce the problem. I do not know what is different now, but I know I updated Teams once after posting above.

 AppExclusions continues to work for Zoom, my primary app for remote meetings. This is a great function. Thank you!

**Comment by fdawans** [comment]
Hello, 

Thank you for the app, it's very useful!

However, I have the same issue as @chchen2021 on macOS.
If I start Teams, Stretchly stops (it's in appExclusions).
Then when quit Teams, Stretchly stays in pause indefinitely (even after a Stretchly restart!)

As you can see, Teams is not in Activity Monitor.
<img width="492" alt="image" src="https://user-images.githubusercontent.com/53601011/201399494-0ae817a9-80de-4923-ab45-811cb769a241.png">


Settings:
```
	"appExclusions": [
		{
			"rule": "pause",
			"active": true,
			"commands": [
				"Microsoft Teams"
			]
		}
	],
```

Log:
```
[2022-11-11 18:48:10.929] [info]  Stretchly: initializing...
[2022-11-11 18:48:10.949] [info]  Stretchly: loading preferences
[2022-11-11 18:48:10.962] [info]  Stretchly: starting Idle time monitoring
[2022-11-11 18:48:10.965] [info]  Stretchly: starting Do Not Disturb monitoring
[2022-11-11 18:48:10.966] [info]  Stretchly: starting App exclusions monitoring
[2022-11-11 18:48:11.264] [info]  Stretchly: loading default break ideas
[2022-11-11 18:48:11.382] [info]  Stretchly: loading default break ideas
[2022-11-11 18:48:12.045] [info]  Stretchly: pausing breaks as 'pause' exclusion found running: 'Microsoft Teams'
```

**Comment by hovancik** [comment]
@fdawans please try checking "Details" tab, it is more exact. You should for the process that appears when you are in the meeting. Teams have many processes and you need to figure out whether there is some with specific one that appears during the meeting. Right now, Stretchly pauses when any process with the name you specified is running, so when you start Teams, Stretchly will pause.

**Comment by fdawans** [comment]
I am a new mac User - I cannot find the details tab?
When I said that I quit Teams, I meant to say that I kill (CMD+Q) Teams after my meeting.
So there should not be any processes remaining.

However, Stretchly is still in pause.

**Comment by hovancik** [comment]
Ah, ok, I thought you are on a Windows machine :) On macOS you should use Activity Monitor

**Comment by hovancik** [comment]
If you don't see Teams processes there, other apps might be better in showing more tasks: https://alternativeto.net/software/activity-monitor/?platform=mac

**Comment by fdawans** [comment]
I started to use Stretchly again, it seems to be restarting properly after killing Teams.. So it's working now - no idea what happened.
