### ISSUE TITLE
[Bug]: Portuguese and Brazilian labels are switched (Brasileiro <-> Português)

### ISSUE THREAD

**Issue by unstablectrl** [hovancik/stretchly#1121]
### Version

- [X] I'm using version 1.10.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 21H2

### Reproduction steps

1. install and open the app
2. look at the welcome screen

### Expected Behavior

The label of the Brazilian and Portuguese options to be set correctly by switching one with the other

### Actual Behavior

The Brazilian label has the Portuguese flag and vice versa

### Additional information

```shell
This here:
https://github.com/hovancik/stretchly/blob/5bb8047dc0ccd2c4dc3f16713757b2dc40875f07/app/welcome.html#L205-L218

Only the labels text should be switched.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Thanks for the report :) PR welcome, should be easy as you say. Worth checking if Preferences is OK.
