### ISSUE TITLE
[Feature request]: Sync between multiple computers

### ISSUE THREAD

**Issue by infabls** [hovancik/stretchly#1123]
### Version

- [X] I'm using version 1.10.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Windows

### Operating System Version

Windows 10 19041.331

### Problem description

Thank you very much for your work. This has been saving my back and eyes for half a year now.
I would like to see synchronization between multiple devices.
I work on 2 machines at the same time. It would be desirable to synchronize breaks on them. And in my dreams I would also synchronize breaks on the phone. So that I can not stick to the phone, instead of rest

### Possible solution

A local web server that would share break state.
When a break starts on one computer, a command is sent to all connected on the network

### Alternative solutions

I really don’t want to complicate and add authorization and registration
From simple solutions, I suggest github gists

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Well, there was such a request before, but that's beyond my skill/time that I have available. Sorry :( 

Stretchly does have command line interface, so I would suggest writing some script in your preferred language and control Stretchly instances in such a way.
