### ISSUE TITLE
[Feature request]: Larger long break after X amount of breaks. 

### ISSUE THREAD

**Issue by gostbento** [hovancik/stretchly#1126]
### Version

- [X] I'm using version 1.10.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Windows

### Operating System Version

windows 10  1.10.0

### Problem description

The main Idea is to use it as a pomodoro timer. 
so every 30 minutes I take a 5 min break but after 2 hours I would like to set up a longer break 

### Possible solution

adding a longer break after X long breaks 
I would but by default a 30 minute break 2 hours 

### Alternative solutions

<3 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
So you mean basically another type of break? That would be hard to do. 

What I suggest is: 
- change mini break to 30 minutes and set it 5 minutes long
- change long break to desired value

In UI, you can see Long Breaks as "every X minutes" but under the hood it's "give me Long Break after N of Mini Breaks"
