### ISSUE TITLE
[Bug]:   I cannot access the Stretchly app preferences because the app does not open.  How do I access preferences?

### ISSUE THREAD

**Issue by kerse012** [hovancik/stretchly#1127]
### Version

- [X] I'm using version 1.10.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

Windows

### Operating System Version

Windows Version 21H2 (OS Build 19044.1586)

### Reproduction steps

1. Locate the Stretchly app icon using the start menu.
2. Click on the Stretchly app icon in the start menu.

### Expected Behavior

I expect the app to open and give me the option to click on preferences.

### Actual Behavior

The app doesn't open at all.  It looks like it's going to open because my mouse icon will spin for a second but nothing pops up.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kerse012** [comment]
@hovancik - I love this app so far but not being able to access the preferences is an issue.  I would like to share with my co-workers.  Please help as soon as possible.  Thanks!

**Comment by hovancik** [comment]
Hi, there is no window by default, it only shows breaks when it is time. Search for Stretchly icon in tray and click on it, then you can access the menu and preferences.

**Comment by hovancik** [comment]
tray is here: 

![image](https://user-images.githubusercontent.com/4745859/160631846-746cef0c-38b5-443d-8e1b-c783d107a855.png)

it might be hidden under `^` icon

**Comment by qbee2u** [comment]
I can get to the icon just fine, but it still does not open no matter what I try.

**Comment by hovancik** [comment]
Could you please show me the screenshot with the icon?

**Comment by qbee2u** [comment]
Here's the screenshot...I've tried opening it multiple times from both destinations but nothing happens.

***@***.***

Thank you for your help with this - I really like the program and want to be able to use it.

Erica

**Comment by hovancik** [comment]
Can you attach it via github website? It's not showing when via email.

**Comment by hovancik** [comment]
No reply for long time, so closing this. Please let me know if this is still issue with the latest version 1.12
