### ISSUE TITLE
[Feature request]: 

### ISSUE THREAD

**Issue by ttodua** [hovancik/stretchly#1129]
### Version

- [X] I'm using version 1.10.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Windows

### Operating System Version

Win 10

### Problem description

When the popup appears, by default (after initial installation), it is not a full-screen, and user needs to explicitly set it to full screen.  I think, that by default, it should be full-screen, because, this is the purpose of the user (when he installs app) to block from screen. So, with non-full screen, there are still areas where user might be still steering to the visible areas of screen.

### Possible solution

Make full-screen as default, instead of non-full-screen.

### Alternative solutions

even this or that way, it might be good, that  when popup appears there was one-time message (a small font-size message in the lower right corner or somewhere, saying 'change fullscreen' which goes to options. so, user can be informed about that capability from the beggining. )

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi and thanks for the feedback. The reason behind Window being default is simple: Fullscreen is bunch of hacks and quite often it is buggy ;( Even worse when combined with multiple screens or some other specific stuff. And the same is for macs and linux ;/

**Comment by ttodua** [comment]
thanks, I understand. however, if so, can you increase the 'popup' size more, so there are not large-visible areas on the edges. as I remind, on my pc, around 10% of screen were being visible beyond the popup.

**Comment by hovancik** [comment]
you can edit the size of the window, if you want: 
https://github.com/hovancik/stretchly#advanced-preferences=
https://github.com/hovancik/stretchly#break-window-size-=

**Comment by ttodua** [comment]
thanks for reply. I see, editing is possible, I just thought about 'defaulting' that value upon installation. but as you wish, thanks anyway.
