### ISSUE TITLE
[Feature request]: Adding custom exercise prompts

### ISSUE THREAD

**Issue by Chlikaflok** [hovancik/stretchly#1133]
### Version

- [X] I'm using version 1.10.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Windows

### Operating System Version

Windows 10 21H2

### Problem description

I want to add a few custom exercise prompts, but I can't open the local .pak file to add them in. I'm guessing the .json on the git repo is converted to .pak at some point in app packaging. I can easily edit json files, but I don't know how to open/edit pak files.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Please see information in readme
https://github.com/hovancik/stretchly#advanced-preferences

**Comment by Chlikaflok** [comment]
I did read the readme, but apparently I should get to my eye doctor soon because I missed that section. Thank you!

**Comment by hovancik** [comment]
No worries, there's a lot of stuff in there:)
