### ISSUE TITLE
[Bug]:   Break windows crash if putting screen to sleep

### ISSUE THREAD

**Issue by LucasZhan** [hovancik/stretchly#1134]
### Version

- [X] I'm using version 1.10.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

macOS

### Operating System Version

Mac OS 12.3

### Reproduction steps

1. open stretchly
2. set hot corners --> put display to sleep
3. activate 'put display to sleep' via hot corners
4. stretchly break disapear
...
**Reproduces how often:** [What percentage of the time does it reproduce?]
every time

### Expected Behavior

nothing happen, stretchly break continue.

### Actual Behavior

stretchly break disapear if I 'put display to sleep' via hot corners.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
This is expected, you change this behavior via editing preferences file
https://github.com/hovancik/stretchly#advanced-preferences=
https://github.com/hovancik/stretchly#pause-breaks-on-suspendlock-=

**Comment by LucasZhan** [comment]
> This is expected, you change this behavior via editing preferences file https://github.com/hovancik/stretchly#advanced-preferences= https://github.com/hovancik/stretchly#pause-breaks-on-suspendlock-=

Thanks a lot!
