### ISSUE TITLE
Versions 0.8.1 is better than 0.9.0

### ISSUE THREAD

**Issue by gromchen** [hovancik/stretchly#114]
I use 0.8.1 because 0.9.0 has a couple of issues. First, it does not show itself when I'm in another fullscreen app. Second, it has dock icon which is always present. Will it be fixed in next versions?

**Comment by hovancik** [comment]
what app for fullscreen? 
dock icon will be configurable in next version

**Comment by gromchen** [comment]
Any app on a mac if it's in fullscreen. Stretchly does not show the window with the break, I just hear sound from time to time.

**Comment by hovancik** [comment]
Not happening on master branch so I guess that was some issue with electron version used on 0.9.0. I will close this once I release new version.

**Comment by gromchen** [comment]
Thank you.
