### ISSUE TITLE
[Bug]:   Stretchly doesn't respect DND in MacOS Monterey

### ISSUE THREAD

**Issue by ghost** [hovancik/stretchly#1144]
### Version

- [X] I'm using version 1.10.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

macOS

### Operating System Version

MacOS Monterey 12.3.1

### Reproduction steps

1.Enable Do not disturb mode
2.trigger or wait for a break
3.Break still shows up
...
**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Expected Behavior

1. Enable Do Not Disturb Mode
2. Stretchly should stop showing breaks for the duration that DND is on.

### Actual Behavior

1. Enable Do Not Disturb Mode
2. Stretchly continues showing breaks for the duration that DND is on.

### Relevant log output

```shell
https://controlc.com/55469b3b
```

### Preferences

```shell
breakPlanner: {reference: startMicrobreakNotification,
            timeleft: About 14 minutes remaining,
            breakNumber: 2,
            postponesNumber: 0,
            Do Not Disturb: false}
            
            settingsFile: /Users/rodllag/Library/Application Support/Stretchly/config.json
            
            logsFile:  /Users/rodllag/Library/Logs/Stretchly/main.log
            Node.js: 16.13.0
            Chromium: 98.0.4758.82,
            Electron: 17.0.1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi and thanks for the report. 

I do not have Monterey to test unfortunately, as my macbook does not get updated anymore ;/ There is also no issue currently opened for upstream: https://github.com/felixrieseberg/macos-notification-state/issues

**Comment by ghost** [comment]
Hi,
I could help you test if that is workable…
I’m sure many of us regular users will have updated our OS and have noticed this DND issue to be often requested.

> There is also no issue currently opened for upstream: https://github.com/felixrieseberg/macos-notification-state/issues
> 

Sorry but I didn’t understand what you meant here.

Cheers,
R

**Comment by hovancik** [comment]
That is the library I use to check for DND. WIth new OS versions, it's often their support needs to be added

**Comment by ghost** [comment]
Right, I had assumed it was something along those lines. 
Do you think submitting an issue will help? Is the dev active?

**Comment by hovancik** [comment]
Ah, it seems to be fixed in newer version: https://github.com/felixrieseberg/macos-notification-state/issues/26 

My local is not version 2, yet. Will need to check why is that

**Comment by ghost** [comment]
That’s great news!

**Comment by hovancik** [comment]
Well, there is one more issue: https://github.com/felixrieseberg/electron-notification-state/issues/7 . Hopefully it gets solved fast.

**Comment by ghost** [comment]
Yeah! Me too.

👍👍

**Comment by axelcostaspena** [comment]
Is this the same as #1080?

**Comment by hovancik** [comment]
Ah yeah, let's close this one as it's duplicate.
