### ISSUE TITLE
[Feature request]: Finer control over schedule times

### ISSUE THREAD

**Issue by Intuos5** [hovancik/stretchly#1149]
### Version

- [X] I'm using version 1.10.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Problem description

The schedule settings are a bit lacking for my liking. I would prefer to set the long break times per minute increments, instead of in five minute increments for short breaks or ten minute increments for long breaks. That is because, the default increments are just a tad too long for me personally.

### Possible solution

Ideally, I would like to type in the exact "Break for" and "Every minute" increments in an input box to the right of the sliders.

### Alternative solutions

Alternatively, the sliders could have finer increments, but that may make them a little harder to set up right. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi and thanks for  the feedback. I don't plan to change the UI, but you can edit it via preferences file: https://github.com/hovancik/stretchly#advanced-preferences=
