### ISSUE TITLE
[Bug]:   Long Break for 25 minutes 

### ISSUE THREAD

**Issue by 13banda** [hovancik/stretchly#1150]
### Version

- [X] I'm using version 1.10.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

Linux

### Operating System Version

Ubuntu

### Reproduction steps

1.
2.
3.
...
**Reproduces how often:** [What percentage of the time does it reproduce?]

### Expected Behavior

Unable to set longer break for 25 minutes

### Actual Behavior

Need to enable longer break for 25 minutes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, for longer breaks than UI allows, please use preferences file: 

https://github.com/hovancik/stretchly#advanced-preferences=

Value is called `breakDuration` and is in ms.
