### ISSUE TITLE
[Feature Request] Being able to configure a series of message

### ISSUE THREAD

**Issue by JOduMonT** [hovancik/stretchly#1155]
### Version

- [X] I'm using version 1.10.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Linux

### Operating System Version

Debian testing

### Problem description

Would it be possible to let the user configure the message?

### Possible solution

In that case, your apps would help me by taking a break and remembering me my motivation/goal/task for the week/month ...

### Alternative solutions

A clear and concise description of what you want to happen.It could be even more powerful by being able to connect it to a calendar caldav or ics.

### Additional information

Thank you for the configuration

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
You can set custom messages, but they are shown randomly: 
https://github.com/hovancik/stretchly#advanced-preferences=
https://github.com/hovancik/stretchly#editing-break-ideas=
