### ISSUE TITLE
[Bug]: On MacOS12.4 (21F79) when clicking in the "Schedule" tab in the preference, in French language, there is no response

### ISSUE THREAD

**Issue by rbarnat** [hovancik/stretchly#1158]
### Version

- [X] I'm using version 1.10.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

macOS

### Operating System Version

MqcOS Monterey12.4 (21F79)

### Reproduction steps

1.Launch Strechly
2.clik on the top bar icon and select "Preferences"
3.On tab "Settings" select language "Francais"
4.Click on tab "Schedule"
5. No respons, have to restart app
...
**Reproduces how often:** [100%]

### Expected Behavior

see Schedule settings in french

### Actual Behavior

no response

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Could you please attach the log? Thanks!

**Comment by hovancik** [comment]
No reply so closing, please let me know if this is still an issue in 1.12 and try attaching logs.
