### ISSUE TITLE
[Bug]: possible memory leak, stretchly using 1 GB of RAM memory causing laggy notification windows

### ISSUE THREAD

**Issue by rafalslaby** [hovancik/stretchly#1161]
### Version

- [X] I'm using version 1.10.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

Linux

### Operating System Version

Ubuntu 20.04.4 LTS

### Reproduction steps

Just keep the app running for some time and observe increasing memory usage in the process manager.

### Expected Behavior

Memory used not increasing with time. Notification windows poping up the same way all the time.

### Actual Behavior

Memory used is increasing with time. I've seen it going up 150MB in 1 day and reaching 1GB. At the same time the notification windows are getting laggy - they start as an empty gray window and it takes 3 seconds to load (when I see the timer it already says 17 seconds left instead of 20 seconds left)

### Additional information

I'm not sure, but I think it started with the latest update. I've been using stretchly the same way for some time now (btw great app) and this seems to be a new problem after the latest update.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi and thanks for  the report. Does the number of processes change? There was issue in the past with then not closing, that should be fixed.

**Comment by rafalslaby** [comment]
Hey, I just checked and the number of processes stays the same. Stretchly spawned 7 processes, main one consuming 600MB. After the restart it's still 7 processes, main one consumes 130MB.
[stretchly_processes.txt](https://github.com/hovancik/stretchly/files/8967337/stretchly_processes.txt)

**Comment by hovancik** [comment]
I am checking on my Debian and all seems fine, my process are all less then 50MBs (after few hours, pretty much the same as when I started Stretchly). How did you install? (I am using deb package)

**Comment by rafalslaby** [comment]
Just `sudo apt install ./Stretchly_1.10.0_amd64.deb` I'm pretty sure it was downloaded from github releases - https://github.com/hovancik/stretchly/releases/download/v1.10.0/Stretchly_1.10.0_amd64.deb

**Comment by rafalslaby** [comment]
Hmm, maybe it's because I click "skip this break" all the time :D Some data from today - memory usage 625M
![image](https://user-images.githubusercontent.com/26134501/177845790-8c938c37-45b8-4df8-9584-070ac71f4af7.png)

**Comment by hovancik** [comment]
What are your preferences? Did you make any changes to defaults?

**Comment by rafalslaby** [comment]
AFAIR only the schedule:
![image](https://user-images.githubusercontent.com/26134501/179160224-31dc76f7-3e68-4f3e-a2a8-c18cfda90394.png)
I'll restore defaults and observe for a couple of days

**Comment by hovancik** [comment]
Okay, thanks! I think usage goes quite high if eg. people enable Pause/Resume rules via advanced config.

**Comment by rafalslaby** [comment]
Nope it behaves the same way with default config. Memory usage went to 750MB after some time:
![image](https://user-images.githubusercontent.com/26134501/186445891-ce61f309-1945-43ff-b2e3-8d6986925976.png)

**Comment by hovancik** [comment]
Hi, is this still an issue with 1.12?

**Comment by rafalslaby** [comment]
Sorry, I can't verify it at the moment (as verification requires running stretchly for days). Consider closing the issue for now and worst case we can reopen if it's still persists. (also, a reminder - as far as I'm concerned, this is just a minor issue with a simple workaround, so I don't mind if we just ignore it, I just wanted to let you know about it)

**Comment by hovancik** [comment]
No worries, I'll close this then, probably related to ElectronJS memory management. Thanks!

**Comment by AntonOfTheWoods** [comment]
@hovancik , I get this also (~1GB mem), running 1.17.1 from snaps on Ubuntu. I also see this when running for days and regularly delay breaks (pretty much every time, I will delay for a couple of minutes, which also means I have changed the defaults). I'm pretty sure there is a memory leak somewhere, though accept that "just restart the app" might be the best use of everyone's time...

**Comment by hovancik** [comment]
Can you try making screenshot of process manager when you start and then after some time again? 

ElectronJS is memory hungry and 1GB is probably not that much for it (as it packages Node and Chromium for each app)

**Comment by fkentwicklung** [comment]
<img width="950" height="46" alt="Image" src="https://github.com/user-attachments/assets/b522a0fe-1ec8-40bc-82cd-490db487015f" />
Same problem here. I killed the process and started it fresh, and it shows that usage from the very start. I am using Pop Os with Cosmic

**Comment by AntonOfTheWoods** [comment]
I'm (at this very second) getting claude to create a gnome extension to basically do everything stretchly does. It is now a real pain on wayland (can only do one screen, etc.) and electron is just way too heavy for what it's doing. I'll post back when it's in GH

**Comment by fkentwicklung** [comment]
i found Stretchly after trying some other apps, which either did not work correctly or at all, exactly because of Wayland -.-
Stretchly works much better, but it has this high Ram usage. Thanks for your effort

**Comment by AntonOfTheWoods** [comment]
@fkentwicklung it is waiting for a review from an extension store person but will be at

https://extensions.gnome.org/extension/10784/hardbreak/

When it gets approved [hardbreak](https://github.com/AntonOfTheWoods/hardbreak) . The version I submitted is [v1.0.1](https://github.com/AntonOfTheWoods/hardbreak/releases/tag/v1.0.1)

This should be basically zero memory - full gnome integration. The config and activation is in Gnome Extensions.

And @hovancik thanks for stretchly - I basically asked Claude to give me exactly what you did, but for Gnome 50+ only - without your awesome work I wouldn't have known what to ask for!
