### ISSUE TITLE
[Feature request]: Display break popup on all screens

### ISSUE THREAD

**Issue by voneff** [hovancik/stretchly#1163]
### Version

- [X] I'm using version 1.10.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro  Version 21H1

### Problem description

Stretchly used to show the „break“ overlay on all of my (two) screens. After updating today, it only shows the popup on my main screen (and I can continue working on my other monitor ;-P).

This might be a related issue:
https://github.com/hovancik/stretchly/issues/1109

It would be great to include the option once again to show the break overlay on all screens.

### Possible solution

Introduce a toggable option in the settings to show the popup on all screens.

### Alternative solutions

Show the popup on all screens, always.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
What do you mean by `Introduce a toggable option in the settings to show the popup on all screens.` 

There is currently such an option called "Show breaks on all monitors"

**Comment by voneff** [comment]
Hi, sorry, yes, that setting obviously exists already. It's weird though: In the office, the break popup is shown on both my screens, on my home setup, it's only shown on the main monitor. This was definitely different before the update.

**Comment by hovancik** [comment]
My guess is that OS versions are different on those 2 machines? Microsoft tends to change these things regularly. It's long time since I hade Windows, but I remember people have to do some display settings for it to work ok.

**Comment by hovancik** [comment]
Hi, is this still issue with 1.12?
