### ISSUE TITLE
on Mac cmd+tab defeats full-screen breaks

### ISSUE THREAD

**Issue by dorkypants** [hovancik/stretchly#1167]
On a Mac with multiple desktops and Stretchly set to full screen breaks, hitting cmd+tab to switch to the next desktop gets around Stretchly's green-screen

**Comment by hovancik** [comment]
Hi, yeah, Stretchly is regular window, so you can break it with Cmd+tab. It's been like that since forever and  there is no solution that I know of :(

**Comment by ghost** [comment]
this works :
https://github.com/hovancik/stretchly/issues/1232#issuecomment-1543447627
