### ISSUE TITLE
[Bug]: Stretchly preferences windows does not fit in smaller displays

### ISSUE THREAD

**Issue by Arasteh** [hovancik/stretchly#1170]
### Version

- [X] I'm using version 1.10.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

Windows

### Operating System Version

Windows 11 21H2

### Reproduction steps

1. Open Stretchly preferences window
2. Switch to 'Schedule' or 'Theme' tab
3. If you are on a small display (HD for example), the window will not fit in display.
...
**Reproduces how often:** [What percentage of the time does it reproduce?]

### Expected Behavior

I expect that scrollbar should appear in such cases, so that I could scroll through all settings.

### Actual Behavior

There is no scrollbar, unless you maximize the window. Now if you restore the window, the scrollbar will stay there.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
What's the size of the monitor? By default the height of prefs is 530 pixels.

**Comment by Arasteh** [comment]
1366x768

**Comment by hovancik** [comment]
Thanks, I see. All good on Linux, so must be some Windows specific thing.

**Comment by hovancik** [comment]
Btw, could you please make a screenshot? I wonder, do you see the whole Stretchly window, or only part?

**Comment by Arasteh** [comment]
The window size is fine when on the first page:
![Stretchly 1](https://user-images.githubusercontent.com/2681222/180841260-ca6a10da-14ef-4af5-ac88-027087112b8f.png)

But when I switch to 'Schedule', some of prefs do not fit in the window:
![Stretchly 2](https://user-images.githubusercontent.com/2681222/180841266-070ca785-6a94-4d1f-994f-5f2f62dc6ad5.png)

After I double click on the upper edge, scrollbar appears and I can scroll to bottom of the prefs:
![Stretchly 3](https://user-images.githubusercontent.com/2681222/180841280-0063a4fa-0fd2-4e78-9405-6c65f20124a9.png)

**Comment by hovancik** [comment]
I don't have Windows to test, but hopefully this will be fixed. Seems to work as I would expect in Mac.
