### ISSUE TITLE
Countdown/timer does not appear on the screens

### ISSUE THREAD

**Issue by llmiller** [hovancik/stretchly#118]
Hello - not sure if this is how I document an issue, but ... I have Stretchly installed on my Win 10 computer. I have configured it to come up for short breaks every 20 minutes and longer breaks every 90 minutes. On both of these screens, I don't see the timer. So I forget (if I'm very hard at work) if what I'm seeing is a 10-second break or a 5 minute break. I don't see how to configure the timer in the 'settings' area.
![2017-08-03_12-47-29](https://user-images.githubusercontent.com/26468302/28940809-254ee9a2-7853-11e7-9568-c84d1c15dc90.png)

**Comment by hovancik** [comment]
Countdown timer should be always visible. What version are you using? Make sure you have the latest. Timer was not there in older versions.

**Comment by llmiller** [comment]
I just downloaded the software yesterday but I must've gotten it from a website that had an old version.
Thank you - I'm uninstalling and re-installing from your list here. :)

**Comment by hovancik** [comment]
Awesome, let me know if it's OK, so we can close this issue.
