### ISSUE TITLE
[Bug]:   tray icon menu UI issues on Ubuntu 20.04 Gnome

### ISSUE THREAD

**Issue by samegens** [hovancik/stretchly#1180]
### Version

- [X] I'm using version 1.10.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

Linux

### Operating System Version

Ubuntu 20.04

### Reproduction steps

1. Install Stretchly 1.10.0
2. Start Stretchly
3. Notice that every 10 seconds, the tray icon flickers: it changes for a moment to an ellipsis (...) icon and then switches back to the regular icon.
4. Open the tray menu, open one of the submenus, for example 'skip to the next', wait for 10 seconds and notice that the submenu will close of its own.
...
**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Expected Behavior

I expect to not have an icon that flickers, or only when it actually needs to change.
I expect submenus in the tray menu to stay open until I select something or I close the menu.

### Actual Behavior

- every 10 seconds, the tray icon flickers,
- submenus in the tray menu are closed automatically after 10 seconds

### Relevant log output

```shell
None.
```

### Additional information

```shell
This is caused by always calling appIcon.setImage and appIcon.setContextMenu from updateTray which is called every 10 seconds. Interestingly when I comment out one of them (doesn't matter which one), the flicker is gone.

I have a fix on my system where Stretchly remembers the previous icon path and menu template and only calls setImage when the new icon path is different and only calls setContextMenu when the new menu template is different. This fixes the issues on my machine. I can turn this into a PR if that's helpful.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi it's flicking every 10 seconds because tray meny shows times to next breaks and I want them to be up to date (as it changes constantly). 

I am on Debian with KDE and no flickering is happening, must be something with Gnome. What version is it?

**Comment by hadley8899** [comment]
I have this same issue

OS: Ubuntu 22.04.1 LTS x86_64
Kernel: 5.15.0-46-generic

This is on GNOME 42.2

In /var/log/syslog

Aug 11 14:53:55 ryan-Z370P-D3 ubuntu-appindicators@ubuntu.com[4651]: Stretchly1, Impossible to lookup icon for 'Stretchly1_23-panel' in path /run/user/1000/snap.stretchly/.org.chromium.Chromium.CcLVQe
Aug 11 14:53:55 ryan-Z370P-D3 ubuntu-appindicators@ubuntu.com[4651]: unable to update icon for Stretchly1

Hope this helps

**Comment by hovancik** [comment]
Maybe try https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/176#issuecomment-1164221529 ?

**Comment by samegens** [comment]
I tried disabling the extension ubuntu-appindicators@ubuntu.com and installing tray-icons@zhangkaizhao.com and indeed the flicker every 10 seconds is gone. However, the menu behavior is even worse: the whole menu is completely closed every 10 seconds. 
So my preferred solution is to only update the tray menu when something changes. Most of the time, only once per minute does it need to change. See my proposed fix: https://github.com/hovancik/stretchly/compare/trunk...samegens:stretchly:fix/tray-menu-issues

**Comment by hovancik** [comment]
@samegens cool :) Could you please make a PR, so I can try it out?

**Comment by samegens** [comment]
Thanks! I didn't have time yet to properly finish this.
