### ISSUE TITLE
[Bug]: Fix Break Message Typo

### ISSUE THREAD

**Issue by martineizayaga** [hovancik/stretchly#1181]
### Version

- [X] I'm using version 1.10.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

Windows

### Operating System Version

Edition	Windows 11 Enterprise Version	21H2 Installed on	‎7/‎19/‎2022 OS build	22000.795 Serial number	PF3MLV31 Experience	Windows Feature Experience Pack 1000.22000.795.0

### Reproduction steps

View break message

### Expected Behavior

There's a hand squeeze message that goes, "Squeeze a pair of balled-up socks or a soft rubber ball, hold for 5 seconds. Repeat whole process few times."

### Actual Behavior

It should say, "Squeeze a pair of balled-up socks or a soft rubber ball, hold for 5 seconds. Repeat whole process a few times."

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi and thanks! 

Feel free to create a PR, you can pretty much search and replace in whole project.
