### ISSUE TITLE
[Feature request]: Setting Mini Breaks in interval of 1, 2, 3 or 4 minutes

### ISSUE THREAD

**Issue by krasimirkrustev** [hovancik/stretchly#1182]
### Version

- [X] I'm using version 1.10.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Windows

### Operating System Version

Windows 10 21H2

### Problem description

At the moment you can set the Mini Breaks to be every 5 minutes.

### Possible solution

I would like to be able to set the Mini Breaks in interval of less than 5 minutes (1, 2, 3, or 4 minutes).

### Alternative solutions

I would like to be able to set the Mini Breaks in interval of less than 5 minutes (1, 2, 3, or 4 minutes).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, in the UI, I had to make design changes what is possible and what is not. 

You can change the value to whatever value (outside of the UI) you want via editing config file: 
https://github.com/hovancik/stretchly#advanced-preferences 

Value is called `microbreakInterval: 600000,` and it's in `ms`
