### ISSUE TITLE
[Feature request]:  add longBreakIdeas & longBreakIdeas to Farsi lang ( fa.json)

### ISSUE THREAD

**Issue by themehran** [hovancik/stretchly#1183]
### Version

- [X] I'm using version 1.10.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Linux

### Operating System Version

Linux pop-os 5.18.10-76051810-generic #202207071639~1659108431~22.04~c9172fb SMP PREEMPT_DYNAMIC Fri J x86_64 x86_64 x86_64 GNU/Linux

### Problem description

it would be great to have Stretch ideas in Persian 

### Possible solution

i could add required Translation to fa.json and push changes

### Alternative solutions

there is no other solution :)

### Additional information

not required

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi and thanks! Please use the weblate: https://hosted.weblate.org/engage/stretchly/ :)
