### ISSUE TITLE
Ubuntu 20.04 LTS > user > Startup Applications > /snap/bin/stretchly : does not effect stretchly startup on logon

### ISSUE THREAD

**Issue by bentonmacdonald** [hovancik/stretchly#1187]
Please advise fix.

![Screenshot from 2022-08-10 10-42-07](https://user-images.githubusercontent.com/39969990/183774233-83e56260-ad67-46ae-8e68-a5e204956beb.png)
.

**Comment by hovancik** [comment]
Isn't that question for Ubuntu to ask? TBH no idea how autostart work in Ubuntu. 

In Debian and KDE, this works for me: 

![image](https://user-images.githubusercontent.com/4745859/183945811-c12a3f12-a046-46f1-a9c9-ff729a404b8e.png)

**Comment by bentonmacdonald** [comment]
Thank you for your response
