### ISSUE TITLE
[Bug]:   can't uninstall 1.10.0 on win10

### ISSUE THREAD

**Issue by xuan-wang** [hovancik/stretchly#1188]
### Version

- [ ] I'm using version 1.11.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

Windows

### Operating System Version

win10 21H2

### Reproduction steps

1.when version 1.11.0 update reminded me, I downloaded the new installer.
2.after double clicking the new installer, it will ask me to close the running old version, and I choose Yes.
3.the old version was closed because I saw the icon disappered from the status bar.
4.after a few seconds, a pop-up window reminds me the old version is still running and retry the installer after closing it manually.
5.I checked the on-going processes, but none of Stretchly related process is running.
6.I closed the start-up function in old version, and then restarted the system. Neither the uninstaller of old version nor the intaller of new version can accomplish because of the same judgement of unclosed old version.
...
**Reproduces how often:** [What percentage of the time does it reproduce?]

### Expected Behavior

Old version can be uninstalled successfully, new version can be installed.

### Actual Behavior

Old version can't be uninstalled.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, do you remember how you installed in the first place? Maybe you used `winget` or something like that?

**Comment by xuan-wang** [comment]
I installed through the Stretchly.Setup.xxx.exe.
Only version 1.10.0 can't be unintalled.

**Comment by hovancik** [comment]
Sorry, but I am not sure how to help :( Maybe try some of the uninstall software? https://www.lifewire.com/free-uninstaller-programs-2625188

Also, what comes to mind is to make sure that you run installer as admin user.

**Comment by xuan-wang** [comment]
I resolved the problem by reinstalling the version 1.9.0. This version can cover the 1.10.0 version directly, without giving the unclosed process reminder, and can be uninstalled normally. Then, I installed the latest version 1.11.0.

**Comment by hovancik** [comment]
Okay, glad that worked. Must have been some glitch with 1.10, then.
