### ISSUE TITLE
[Bug]:   microsoft defender smartscreen prevented an unrecognized app

### ISSUE THREAD

**Issue by opzetto** [hovancik/stretchly#1189]
### Version

- [X] I'm using version 1.11.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Reproduction steps

1. download the latest (v1.11.0) install.exe to windows 10
2. double click install file
3. windoes 10 report: microsoft defender smartscreen prevented an unrecognized app. 
...
**Reproduces how often:** [What percentage of the time does it reproduce?]
Everytime

### Expected Behavior

stretchly installment window

### Actual Behavior

`microsoft defender smartscreen prevented an unrecognized app.` window pop up

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, this happens often with electron based apps :( The only thing you can do, if you downloaded the app from the official page, and you trust this, you can tell your antivirus that it's false positive. After few people do the same, the warning disappears. 

This happens every now and then.
