### ISSUE TITLE
1.11.0 installer thinks Stretchly 1.10.0 still running

### ISSUE THREAD

**Issue by rob-stewart** [hovancik/stretchly#1190]
I have tried installing the latest version using the Windows installer. It reaches the point of trying to stop the running Stretchly, but says "Stretchly cannot be closed. Please close it manually...." When I check, Stretchly is not running.

Upon starting Stretchly, I see five processes in Task Manager. When I manually quit Stretchly, all five disappear from Task Manager. Still, the installer thinks Stretchly is running.

The same thing happened after a reboot (and auto-start of Stretchly).

In the meantime, of course, Stretchly continues to remind me that there's a new version available!

**Comment by hovancik** [comment]
Hi, please use this workaround: https://github.com/hovancik/stretchly/issues/1188#issuecomment-1221524124

**Comment by rob-stewart** [comment]
Does this retain settings?

Rob

**Comment by hovancik** [comment]
Hi, I think it should. Looking at changelog, I did not do any preferences witchery.
