### ISSUE TITLE
Stretchly closes with cmd when launching from batch script

### ISSUE THREAD

**Issue by cavazos-apps** [hovancik/stretchly#1191]
Prerequisites

I'm using latest version: v1.11.0
I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

I use a batch script to launch all necessary programs I use for work in the morning, Stretchly being one. It appears Stretchly tries launching in the CMD prompt but when the window closes, Stretchly does too. It only runs as long as the CMD is open. 

Its possible I am missing something. Using `stretchly` or `stretchly help` from the CMD is unrecognized.

**Comment by hovancik** [comment]
please fill the issue form https://github.com/hovancik/stretchly/issues/new?assignees=&labels=&template=bug_report.yml&title=%5BBug%5D%3A+++
