### ISSUE TITLE
Stop associating flag and one lang

### ISSUE THREAD

**Issue by anborg** [hovancik/stretchly#1196]
### Version

- [X] I'm using version 1.11.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

macOS

### Operating System Version

HumanRace-can-be-wicked

### Reproduction steps

<img width="221" alt="image" src="https://user-images.githubusercontent.com/56970398/188484802-4aede18c-0d5b-455a-a924-7529b3deac64.png">

Please stop associating India = OneLang.

India is made up of 100s of languages and ethnicities. They are so far peceful because - there is some respect in govt level for other languages (forced/threatened respect, not natural respect). That respect is erroding in many levels in past few decades.

JUST REMOVE Language-flag relation,  those are not true for multi-nation political entities. DO NOT mix politics/citizenship  and language/ethnic. 

Prevent a future Yugur multi decades from now.[india = 100s of ethnic/languages]. This association of Country=language erases other language group among collective memory of the word, thus an elected/dictator can do away with diversity.  Want historical evidence in past few decades? Ask.

Pretty simple : Just use the script of language without flag icons.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, I am not sure whether I understand the connections you make. Most of the countries in the world has more than 1 official language. We have 2 languages associated with Indian flag right now and anyone can add new language. 

![image](https://user-images.githubusercontent.com/4745859/190848333-ae985327-ffaa-495b-ad11-557c56962555.png)

**Comment by hovancik** [comment]
#1575
