### ISSUE TITLE
[Feature request]: More accurate countdown timer

### ISSUE THREAD

**Issue by shenanigans123** [hovancik/stretchly#1197]
### Version

- [X] I'm using version 1.11.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Windows

### Operating System Version

7, 10

### Problem description

During a break, the countdown timer showing the remaining time is rounded up to the nearest minute but only when the remaining time is over 1 minute. Especially frustrating is the timer goes from showing "About 2 minutes" straight to 60 seconds and below, which feels misleading since we never see "About 1 minute".

### Possible solution

Request - allow us to see exact time remaining in minutes and seconds.

### Alternative solutions

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Well, I took the inspiration from how Apple shows time: at least on the installer at the time when I added that functionality. TBH, I am not sure what is the correct way to do it.

**Comment by shenanigans123** [comment]
Another option is using within 30 seconds to decide where the "nearest" minute is, for example:

0-60s: shows exact seconds
1m-1m30s: "about 1 minute"
1m31s-2m30s: "about 2 minutes"
2m31s-3m30s: "about 3 minutes"
etc

That way you're always accurate to the nearest 30 seconds, at least.

**Comment by hovancik** [comment]
There's also this library: https://www.npmjs.com/package/humanize-duration
