### ISSUE TITLE
[Bug]:   Right side content padding or inset is inconsistent with left side

### ISSUE THREAD

**Issue by yo1995** [hovancik/stretchly#1198]
### Version

- [X] I'm using version 1.11.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.5.1

### Reproduction steps

1. A mini break or long break starts
2. The UI inconsistency happens
...
**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Expected Behavior

The padding on both side of the content should be the same.

### Actual Behavior

![right-inset](https://user-images.githubusercontent.com/9660181/188991331-1d08310a-34ec-4d44-a3d9-9b111d7be067.png)

When Stretchly is displayed on a vertical screen resolution, the content inset, or the padding, on the right side is not the same as left side. See the padding of the timer's progress bar is 0 pixels to the right edge.

In Apple's autolayout words, the leading and trailing constraints aren't symmetric. In SwiftUI words, the left and right padding aren't the same, and the detail content view needs more right padding.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
What's your resolution? I am testing on my screen and all looks fine.

![image](https://user-images.githubusercontent.com/4745859/190848113-f540813e-4587-4a5a-ab3a-aba4c6149676.png)

**Comment by yo1995** [comment]
> What's your resolution? I am testing on my screen and all looks fine.

It is 1080x1920, using the default setting

![image](https://user-images.githubusercontent.com/9660181/191552088-e75b4088-e4aa-4478-bb34-1638e0197372.png)

**Comment by hovancik** [comment]
TBH, I am not sure. I've checked the CSS code and I see no issue :(

**Comment by yo1995** [comment]
I'm OK to close this issue as it is not a functional problem. I can also take a glance if you can point me to the code that places the text boxes. Thank you again for creating this tool!

**Comment by hovancik** [comment]
That would be great :) 

HTML and CSS is rather simple, I hope :) 

There are 2 files for Mini and Long Break: 

https://github.com/hovancik/stretchly/blob/trunk/app/break.html#L14
https://github.com/hovancik/stretchly/blob/trunk/app/microbreak.html#L14

You can see what CSS files are loaded, but probably this one is the most interesting: 
https://github.com/hovancik/stretchly/blob/trunk/app/css/break.css

![image](https://user-images.githubusercontent.com/4745859/208685752-baf4c157-1e9e-46fe-b38a-0661c84a0112.png)

If you change advanced option to show breaks as regular windows, you can then hit Chrome shortcut to inspect and play with the regular dev tools :) 

https://github.com/hovancik/stretchly#make-stretchly-show-breaks-as-regular-windows--

**Comment by adevade** [comment]
Can confirm that this bug is happening on my 1080x1920 monitor as well. Using the fullscreen option.

I'm on Win 11, with 3 screens where two is 1080p and the laptop is closer to 4K. The laptop display has 150% scaling in Windows. 

![image](https://user-images.githubusercontent.com/1066486/232407449-4da7a39d-e663-4493-84c0-c506def9c530.png)

**Comment by adevade** [comment]
After checking the CSS, I believe that this is causing the bug: 
https://github.com/hovancik/stretchly/blob/481a0b72f9d4c176f1f620d5982d49e66895fb93/app/css/commons.css#L168-L172

The `width` is checking the viewport height (using`vh`), and should be checking the width (using `vw`).

**Comment by hovancik** [comment]
@adevade great, do you wanna create a PR? It would help as I was not able to reproduce this on my monitor.

**Comment by adevade** [comment]
@hovancik I created a [Codepen that demonstrates a solution](https://codepen.io/adevade/pen/PoyzNKw?editors=0100).

The grid has 100px on each side of the content. This gets too narrow on tall screens. The width of my vertical monitor is 1080px, but half the height 50vh = 1920px/2 = 960px. Then add the grid padding of 200px 960+200 = 1160px. So the progress bar is wider than the screen, and overflows to the right.

I think using only `50vw` will make the progress bar much wider on horizontal screens than it is today. Using `min(50vw, 50vh)` will use the smallest available of the two. This should fix the issue on vertical screens and keep the same width as before on horizontal screens.

If you think this is a good solution I can submit a simple PR with this change 👍

**Comment by hovancik** [comment]
Looks good 👍
