### ISSUE TITLE
[Bug]: Screensaver stop breaktimer

### ISSUE THREAD

**Issue by AugustasV** [hovancik/stretchly#1199]
### Version

- [X] I'm using version 1.11.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

macOS

### Operating System Version

Monterey 12.5.1 

### Reproduction steps

1. Break timer full screen started
2. Screensaver kick in
3. Break automatically stopped.
...
**Reproduces how often:** Always

### Expected Behavior

Even if screensaver starts, break timer still going.

### Actual Behavior

If screen saver kick in and I move a mouse, breaktimer already gone.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, please try editing this preference in config file: https://github.com/hovancik/stretchly#pause-breaks-on-suspendlock-

https://github.com/hovancik/stretchly#advanced-preferences

**Comment by AugustasV** [comment]
It worked! Somehow I didn't spot that option by myself.
