### ISSUE TITLE
[Feature request]: A more visible tray icon for Windows Dark theme

### ISSUE THREAD

**Issue by vahidm90** [hovancik/stretchly#1209]
### Version

- [X] I'm using version 1.12.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 21H2 build 22000.978

### Problem description

The current tray icon is almost invisible when using Windows Dark mode. [See Attached Picture]
![dark-mode-tray](https://user-images.githubusercontent.com/49893905/192963341-cfbbd47f-a8b0-44dc-99a4-c1e5cb7954db.png)

### Possible solution

Maybe use a "white-washed" icon? or use bright colors? or bright outlines? or a bright back-shadow?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, you change the icon in Preference :)
