### ISSUE TITLE
[Feature request]: May I contribute a Galician (gl) translation?

### ISSUE THREAD

**Issue by lorenzogrv** [hovancik/stretchly#1211]
### Version

- [X] I'm using version 1.12.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Linux

### Operating System Version

Manjaro i3

### Problem description

I natively speak [Galician](https://en.wikipedia.org/wiki/Galician_language) and have translated Stretchly for personal use.

I would like to contribute the translation for the project, but as stated at the contributing guidelines I first open this issue to ask if such translation could fit :wink: 

### Possible solution

I have the knowledge needed to contribute the needed json file with locales at `app/locales/gl.json`, plus changes needed at `app/welcome.html` and `app/preferences.html`. I have also a flag at `app/images/flags`

### Alternative solutions

I would like to know if you could accept a pull request with the relevant files, plus some guidance after pull request is opened to tell me if any changes are needed to meet the coding standards etc.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
That would be great :) 

You could use weblate to add it, or if you want, you can run stretchly locally with npm and check them at the same time. 

There are 2 files that needs to be edited as well: preferences.html and welcome.html (add option to use this language)

Let me know :)

**Comment by lorenzogrv** [comment]
Nice! :smile: 

I duplicated & edited other locale file. I've added the option at welcome and preferences too. The flag source comes from wikimedia.

Will open the PR now, tell me if anything is wrong or needs changes.
