### ISSUE TITLE
[Bug]: Unit of time is always displayed in English

### ISSUE THREAD

**Issue by Pluspeeeeed** [hovancik/stretchly#1214]
### Version

- [X] I'm using version 1.12.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro for Workstations  22H2 22621.608 

### Reproduction steps

1. Start Stretchly
2. Select "简体中文"(Simplified Chinese) in Settings
3. Right click on tray icon of Stretchly

**Reproduces how often:** 100%

### Expected Behavior

First line of context menu shows `下次小憩 大约 10 分后`.

### Actual Behavior

First line of context menu shows `下次小憩 大约 10 minutes后`.

### Preferences

```shell
{
	"microbreakDuration": 20000,
	"microbreakInterval": 600000,
	"breakDuration": 300000,
	"breakInterval": 2,
	"breakNotification": true,
	"microbreakNotification": true,
	"breakNotificationInterval": 30000,
	"microbreakNotificationInterval": 10000,
	"microbreak": true,
	"break": true,
	"microbreakStrictMode": false,
	"breakStrictMode": false,
	"morningHour": 6,
	"microbreakPostpone": true,
	"breakPostpone": true,
	"microbreakPostponeTime": 120000,
	"breakPostponeTime": 300000,
	"microbreakPostponesLimit": 1,
	"microbreakPostponableDurationPercent": 30,
	"breakPostponesLimit": 1,
	"breakPostponableDurationPercent": 30,
	"mainColor": "#478484",
	"transparentMode": true,
	"opacity": 0.9,
	"audio": "crystal-glass",
	"volume": 1,
	"fullscreen": true,
	"ideas": true,
	"naturalBreaks": true,
	"naturalBreaksInactivityResetTime": 300000,
	"allScreens": true,
	"useIdeasFromSettings": false,
	"language": "zh-CN",
	"notifyNewVersion": true,
	"isFirstRun": false,
	"posLatitude": 0,
	"posLongitude": 0,
	"useMonochromeTrayIcon": true,
	"useMonochromeInvertedTrayIcon": true,
	"silentNotifications": false,
	"monitorDnd": true,
	"microbreakStartSoundPlaying": false,
	"breakStartSoundPlaying": false,
	"themeSource": "system",
	"endBreakShortcut": "CmdOrCtrl+X",
	"breakWindowWidth": 0.85,
	"breakWindowHeight": 0.85,
	"checkNewVersion": true,
```

### Additional information

```shell
The word `minutes` in the sentence `下次小憩 大约 10 minutes后` should be Chinese character `分`, which is part of the value of the key `minutes_other` written in `app/locales/zh-CN.json`.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
so i fixed the code, but it's a bit different then what you wrote: 
![image](https://user-images.githubusercontent.com/4745859/195984034-a31d2c16-dcb7-4291-8b7c-09ff3a3baab1.png)

I am using a library that gives me the translations
