### ISSUE TITLE
[Bug]:   App is damaged and should be deleted

### ISSUE THREAD

**Issue by roubaobaozi** [hovancik/stretchly#1218]
### Version

- [X] I'm using version 1.12.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.6

### Reproduction steps

1. Install using installer on Releases page, the arm64.dmg (I'm on M1)
2. Right-click on .app in /Applications, Open
3. Get error message that app is damaged and should be moved to bin

<img width="372" alt="image" src="https://user-images.githubusercontent.com/5126295/196820160-d1974fb4-fe68-4c53-aa7e-c069281d6023.png">

**Reproduces how often:** 100%, has been happening since release v1.11.0

### Expected Behavior

App should open and work

### Actual Behavior

Apple deems app damaged and to be moved to bin

### Relevant log output

```shell
I can't get logs as I can't even open the app
```

### Preferences

```shell
Also cannot load up Stretchly to the point of being able to use the shortcut to open the preferences file
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Could you try redownloading or doing so from different browser? This usually means that file was not downloaded correctly

**Comment by roubaobaozi** [comment]
Hi! I've tried it a few times from different browsers (Chrome, Brave, Firefox Dev Edition) from the releases page, as well as from brew (though I think that's just pointing to the same link as the releases?) and it never works. I just tried it again then in Edge and still have the same result.

FWIW the .dmg opens fine, I can install Stretchly.app into /Applications, just the opening of the Stretchly.app from there is the one saying it's damaged.

**Comment by rd-pong** [comment]
Have you done the [app signing part](https://github.com/hovancik/stretchly#application-signing) in the readme?

**Comment by roubaobaozi** [comment]
> Have you done the [app signing part](https://github.com/hovancik/stretchly#application-signing) in the readme?

Oh no! Thank you!

I simply upgraded to the new versions when the older Stretchly app displayed a popup asking me to.

Might be worthwhile updating the message in the popup to explain "go read the readme on upgrade from x version"?

But that works for me, thanks
