### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by davidlinker** [hovancik/stretchly#1219]
During mini-breaks, by the time you read the instructions, stand up from your desk and start the exercise, already a few seconds have passed.  In fact, sometimes it takes a few seconds before the instructions appear.  It would be great if there was an option to only start the timer say 5 seconds after the break starts, to give time for this.  I have the default 20seconds, which is a good time, but 30 seconds (the next allowed break length) is too long.  Many exercises involve alternating your left and right and losing the first five seconds makes this impossible.

**Comment by hovancik** [comment]
Hi, you can set duration to any time by editing config file: https://github.com/hovancik/stretchly#advanced-preferences

Stretchly is built with Electron, which is resource hungry, therefore it is possible that on some computers, break idea appears only after few seconds ;/
