### ISSUE TITLE
Alternate full screen behaviour

### ISSUE THREAD

**Issue by Quitch** [hovancik/stretchly#122]
Full screen apps should cause Stretchly to engage different behaviour, as having your screen disappear is not always desirable and can lead to videos continuing to play, or in the case of games, Stretchly failing to take over the screen correctly or getting you killed. Where a fullscreen app is detected I think Stretchly should offer the following options:

1. Issue a five second warning sound so that the user can pause whatever it is (good for videos, not necessarily for games due to cutscenes etc.)
2. Play a sound (and repeat every minute) until the user triggers the break (better for games)
3. Block breaks while fullscreen mode enabled

**Comment by hovancik** [comment]
Unfortunately, there is no way that I know of to detect behavior of others apps, so I can't find whether you are on fullscreen.   

related #111
