### ISSUE TITLE
Offer to sign binary

### ISSUE THREAD

**Issue by SubJunk** [hovancik/stretchly#1220]
Hi, I'd like to contribute to this project by signing the macOS binaries. I have been using the app for a while and really appreciate it. Let me know if you want that and I can set it up

**Comment by hovancik** [comment]
What do you mean by signing binary? I've tried to register developer account with Apple, but they refused my application and they support was not helpful.

**Comment by SubJunk** [comment]
I meant I could sign and notarize the macOS binaries so that macOS doesn't make it hard for users to run the program. Why did they refuse your application?

**Comment by hovancik** [comment]
They did not give me any reason: https://hovancik.net/blog/2021/07/03/this-is-why-i-ll-probably-never-sign-my-apps-for-macos/

I am building dmg on CI: https://github.com/hovancik/stretchly/blob/trunk/.github/workflows/build.yml and to be honest, if I can't sign with my certificate, I don't think it's trustworthy to sign with someone else's cert

**Comment by SubJunk** [comment]
I don't see why it matters whose signature is used, but ok
