### ISSUE TITLE
[Feature request]: Fixed time breaks

### ISSUE THREAD

**Issue by alanalvarado** [hovancik/stretchly#1221]
### Version

- [X] I'm using version 1.12.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Windows

### Operating System Version

22H2

### Problem description

Sometimes I have to reboot my computer and Stretchly timer gets reset, as a result I don't take breaks regularly enough.

### Possible solution

Add a way to have FIXED breaks, for example 4:25 start 5 minutes break no matter what, then at 4:55
And long breaks each two hours for example 2:00 to 2:30, 4:30 to 5:00

The breaks should be enforced no matter what. Even if I'm in the middle of a video conference with the justice league.

### Alternative solutions

I've considered to switch profession from programmer to door-to-door salesman.
At least I would walk the whole day.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, it would be too complicated to add this to Stretchly, as at the beginning I chose different way. 

You should checkout my other app, called [LaterOn](https://lateron.app), which goes in a different direction. But it's not the same thing as Stretchly.
