### ISSUE TITLE
[Bug]:   Unable to install stretchly on an M1 due to "hdiutil: attach failed - no mountable file systems"

### ISSUE THREAD

**Issue by ylhan** [hovancik/stretchly#1224]
### Version

- [X] I'm using version 1.12.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey v12.6

### Reproduction steps

1. Followed instructions to install through brew
2. Executed `brew update && brew install --cask --no-quarantine stretchly`
3. The following error is returned
```
~ brew update && brew install --cask --no-quarantine stretchly
Already up-to-date.
==> Caveats
This application is not signed. See https://github.com/hovancik/stretchly#application-signing for details.

==> Downloading https://github.com/hovancik/stretchly/releases/download/v1.12.0/stretchly-1.12.0-arm64.dmg
Already downloaded: /Users/allen/Library/Caches/Homebrew/downloads/a54ed94c04df64177f3e7a6aa7def63dfc47aade78c2372569af4bba7232ce43--Stretchly-1.12.0-arm64.dmg
==> Installing Cask stretchly
Warning: macOS's Gatekeeper has been disabled for this Cask
hdiutil: attach failed - no mountable file systems
==> Purging files for version 1.12.0 of Cask stretchly
Error: Failure while executing; `hdiutil attach -plist -nobrowse -readonly -mountrandom /private/tmp/d20221027-35338-vwzikd /private/tmp/d20221027-35338-vwzikd/a54ed94c04df64177f3e7a6aa7def63dfc47aade78c2372569af4bba7232ce43--Stretchly-1.12.0-arm64.cdr` exited with 1. Here's the output:
hdiutil: attach failed - no mountable file systems
```
4. Tried to install from dmg as well but it does not open
...
**Reproduces how often:** 100%

### Expected Behavior

Stretchly to be installed and usable

### Actual Behavior

Stretchly fails to install due to dmg not opening and brew error above

### Relevant log output

```shell
~ brew update && brew install --cask --no-quarantine stretchly
Already up-to-date.
==> Caveats
This application is not signed. See https://github.com/hovancik/stretchly#application-signing for details.

==> Downloading https://github.com/hovancik/stretchly/releases/download/v1.12.0/stretchly-1.12.0-arm64.dmg
Already downloaded: /Users/allen/Library/Caches/Homebrew/downloads/a54ed94c04df64177f3e7a6aa7def63dfc47aade78c2372569af4bba7232ce43--Stretchly-1.12.0-arm64.dmg
==> Installing Cask stretchly
Warning: macOS's Gatekeeper has been disabled for this Cask
hdiutil: attach failed - no mountable file systems
==> Purging files for version 1.12.0 of Cask stretchly
Error: Failure while executing; `hdiutil attach -plist -nobrowse -readonly -mountrandom /private/tmp/d20221027-35338-vwzikd /private/tmp/d20221027-35338-vwzikd/a54ed94c04df64177f3e7a6aa7def63dfc47aade78c2372569af4bba7232ce43--Stretchly-1.12.0-arm64.cdr` exited with 1. Here's the output:
hdiutil: attach failed - no mountable file systems
```

### Preferences

```shell
N/A (not installed)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
I don't have m1 to check unfortunately :( 

Googling around found similar issues with electron apps but no answers there: https://github.com/balena-io/etcher/issues/3086 https://github.com/evolus/pencil/issues/622

So tried searching this error in electron or electron-builder, but no luck

**Comment by ylhan** [comment]
It's super strange because stretchly installed on my other m1 just fine.

**Comment by ylhan** [comment]
@hovancik found the root cause. I was trying to install stretchly on my work laptop so I don't stare at the screen for 8 hours straight. JAMF (apple device management software 🤮) has a setting that prevents software from being installed without direct approval from admin. Super annoying but completely unrelated to stretchly itself. Thank you for the quick turn around!
