### ISSUE TITLE
[Feature request]: show remaining time on the bar 

### ISSUE THREAD

**Issue by yufanme** [hovancik/stretchly#1228]
### Version

- [X] I'm using version 1.12.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

macOS

### Operating System Version

mac os 10.15.7

### Problem description

I always want to check how much time left to the next break, but I have to move my cursor to the bar of my mac and click the icon of stretchly.

### Possible solution

I want to have the option in setting menu, that the remaing time will show on the bar of my mac, so that I will not need to click the icon every time when I want to check how much time to the next break.
Thx.

### Additional information

no

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, you can enable time shown in tray to the next break :) 

Read more about advanced settings: https://github.com/hovancik/stretchly#advanced-preferences
https://github.com/hovancik/stretchly#show-time-to-the-next-break-in-menubar-icon--
