### ISSUE TITLE
[Feature request]: (simple) Deactivate TAB-ing out in strict mode

### ISSUE THREAD

**Issue by Craftit7** [hovancik/stretchly#1232]
### Version

- [X] I'm using version 1.12.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.0

### Problem description

I'm always frustrated that I can simply tab out of the window even in strict mode.

### Possible solution

Disable the keystrokes (cmd + tab)

### Alternative solutions

I tried turning off cmd + tab from the settings, but of course this wasn't good as I still wanted to switch between my apps when the break isn't running.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ghost** [comment]
On Mac for disabling `cmd` + `tab` **only** in Stretchly use Karabiner:
https://github.com/pqrs-org/Karabiner-Elements
"Karabiner-Elements is a powerful utility for keyboard customization on macOS Sierra or later."


- install karabiner from they official site:
https://karabiner-elements.pqrs.org/
or homebrew:
brew install --cask karabiner-elements

- give macos permissions:
https://karabiner-elements.pqrs.org/docs/getting-started/installation/

- in: ~/.config/karabiner/assets/complex_modifications/stretchly_cmd_disable.json
put:
```
{
  "title": "Disable cmd + tab in Stretchly",
  "maintainers": [
    "jg"
  ],
  "rules": [
    {
      "description": "Disable cmd + tab in Stretchly",
      "manipulators": [
        {
          "type": "basic",
          "conditions": [
            {
              "type": "frontmost_application_if",
              "bundle_identifiers": [
                "^net\\.hovancik\\.stretchly$"
              ]
            }
          ],
          "from": {
            "key_code": "tab",
            "modifiers": {
              "mandatory": [
                "left_command"
              ]
            }
          },
          "to": [
            {
              "key_code": "vk_none"
            }
          ]
        },
        {
          "type": "basic",
          "conditions": [
            {
              "type": "frontmost_application_if",
              "bundle_identifiers": [
                "^net\\.hovancik\\.stretchly$"
              ]
            }
          ],
          "from": {
            "key_code": "tab",
            "modifiers": {
              "mandatory": [
                "right_command"
              ]
            }
          },
          "to": [
            {
              "key_code": "vk_none"
            }
          ]
        }
      ]
    }
  ]
}
```

in Karabiner 
in setting: 
-> `complex Modifications`
   `+ Add rule`
`enable:`
"Disable cmd + tab in Stretchly"

dont forget to enable `strick mode` in Strechly (disable cmd + x).
