### ISSUE TITLE
[Feature request]: appExclusion stop Stretchly when app window is active

### ISSUE THREAD

**Issue by russarr** [hovancik/stretchly#1233]
### Version

- [X] I'm using version 1.12.0

### Existing requests

- [X] I've checked Existing requests

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Problem description

My question/fuature request is about "appExclusions" preferenses.
Is there any way to pause/resume stretchly when app window is active, not if app just running.

### Possible solution

It would be convenient if Stretchly paused when I switch to the window of the specified application and resume when I switch off.

### Alternative solutions

Second solution. I'm use two monitors. Stretchly can not show the message on the monitor where the application window is active.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, I don't think it's possible. I found the package, that checks running processes, but I don't see any package, that would tell me when the app is in active window :( 

As for your alternative solution, you can specify which window you want breaks to appear, but I guess it's not 100% what you need. 

https://github.com/hovancik/stretchly#monitor-to-show-breaks-on-
