### ISSUE TITLE
[Bug]:   I can not set 45 minutes for long break (it jumps evey 10 minutes notby minute or I can not edit this)

### ISSUE THREAD

**Issue by ChameleonRed** [hovancik/stretchly#1237]
### Version

- [X] I'm using version 1.12.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Reproduction steps

1. Open settings and try to set long break to 45 minutes.
2.
3.
...
**Reproduces how often:** [What percentage of the time does it reproduce?]

### Expected Behavior

Possibility to set 45 minutes or with gradation with minutes or allow edit value with keyboard - one of solution is enough.

### Actual Behavior

I can set 40 or 50 minutes not my favorite 45.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, I've added explanation to readme: https://github.com/hovancik/stretchly#advanced-preferences

**Comment by ChameleonRed** [comment]
Explanation is very good but if you want to fix just allow user to edit with slider.
I am programing many GUI and I think that it should easier.

User need to specify long break time and also postpone +5, +10, +15, minutes ... or skip (maybe +5 -5 min for postpone or other value from preferences).

In this tool I can not specify long break and also postpone.

Maybe I just fix in and compile or write same in Python from scratch with less functionality. I was using Workrave but it stopped working with current Windows (some Windows API change?).

**Comment by hovancik** [comment]
Are you trying to set duration or interval? Interval is `after number of mini breaks` so it depends on interval of Mini Breaks

**Comment by ChameleonRed** [comment]
I will try ... - I found that fixing gradation is simple.

**Comment by ChameleonRed** [comment]
It is only nee to change this file https://github.com/hovancik/stretchly/blob/trunk/app/preferences.html.

Whatever I do not know how to compile node.js to application that is only problem.

```
      <div>
        <label data-i18next="preferences.schedule.breakFor" data-same-width-label for="longBreakFor"></label>
        <input type="range" min="1" max="60" step="1" list="tickmarksLongBreakFor" name="breakDuration" data-divisor="60000" id="longBreakFor">
        <datalist id="tickmarksLongBreakFor">
          <option value="10"></option>
          <option value="20"></option>
          <option value="30"></option>
          <option value="40"></option>
          <option value="50"></option>
        </datalist>
        <output data-unit="minutes"></output>
      </div>
```

**Comment by ChameleonRed** [comment]
I send pull request ... https://github.com/hovancik/stretchly/pull/1239

I do not describe it because list of question are too long to read for this small change and I do not understand some or they are unrelated to change.

I do not use node.js to create application so forgive me that I do not understand some question but it should work I think - check yourself if you want.

**Comment by ChameleonRed** [comment]
I found that changing mini break have some impact on long break so I can set 45 min.
Only one problem which I found that is counts even I am AFK after break so it need to be reset manual.
So if I take longer break (than longer for example 30 minutes) it start count not after key/mouse.

**Comment by hovancik** [comment]
Long Breaks depend on Mini Breaks as I mentioned here: 

> Are you trying to set duration or interval? Interval is `after number of mini breaks` so it depends on interval of Mini Breaks

AFK behavior can be set up as well, see more here: https://github.com/hovancik/stretchly#natural-breaks-inactivity-time-
You can also disable idle time detection in preferences

**Comment by weiweihuanghuang** [comment]
I'm having this issue too where I would like to set long break intervals independent of short breaks – i.e. my short breaks are every 20 minutes but I would like to take a long break every 45 minutes.

**Comment by hovancik** [comment]
@weiweihuanghuang sorry, but I do not plan to change that. The behavior where long breaks depends on short one is a design decision I did when I started Stretchly and would be too big to rework ;/
