### ISSUE TITLE
[Feature request]: please translate advertisement text to target language.

### ISSUE THREAD

**Issue by rahimi52** [hovancik/stretchly#1240]
### Version

- [X] I'm using version 1.12.0

### Existing requests

- [X] I've checked Existing requests

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

Windows

### Operating System Version

Windows 10 19044.2251

### Problem description

please translate advertisement text to target language. i am ready to help for translate your text to **persian**.

### Possible solution

translate advertisement text to target language

### Alternative solutions

i am ready to help for translate your text to persian.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, what do you mean by advertisement? Break messages?

You translate via weblate: https://github.com/hovancik/stretchly#translations

**Comment by rahimi52** [comment]
> Hi, what do you mean by advertisement? Break messages?
> 
> You translate via weblate: https://github.com/hovancik/stretchly#translations

Hi hovancik.
I Translate Some Break Texts. But it seems that if some Breaks have pictures, it will be much clearer.
For example this Break:
"Stand up and do a lunge. Hold for 10 seconds, then do the other leg."
I didn't know what the "lunge" was. I searched and saw image.

Thanks for good job hovancik.

**Comment by hovancik** [comment]
Hi and thanks for the feedback as well. I was thinking about adding images, but that would be rather hard, as in fact, the best would be to add videos, but that would be expensive to do.
