### ISSUE TITLE
[Feature request]: Stretchly as browser addon

### ISSUE THREAD

**Issue by locua** [hovancik/stretchly#1242]
### Version

- [x] I'm using version 1.12.0

### Existing requests

- [X] I've checked Existing requests

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

Linux

### Operating System Version

Cross platform

### Problem description

Noticed stretchly has quite a big memory footprint for such simple app. Do you this could be reduced by rewriting it as a browser plugin. It would remain cross-platform and maybe be smaller as it would just hijack the browser instance that (is likely) already open.  

Would work for me as I have a usually browser based workflow.

### Possible solution

Not so much asking for you to implement it, but just to gather any thoughts. Might have play at implementing it myself if I find the space.

### Alternative solutions

Just any technical thoughts about Stretchly as a browser extension.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by locua** [comment]
I'm already thinking it might be harder to take over the display via browser.

**Comment by hovancik** [comment]
Hi, I have a small web version at https://web.stretchly.net . But yeah, as you say, I don't think you can take over screen via browser. 

I don't have any knowledge of how browser extensions go, but feel free :)
