### ISSUE TITLE
[Bug] Preferences do not affect default break settings on first start

### ISSUE THREAD

**Issue by hstevemcdonald** [hovancik/stretchly#1243]
Not sure if this is a bug or intentional.

When you install and start the app the very first time, mini breaks are enabled.  For me, I do not use mini breaks so after it had started, I went into Preferences to disable it. The 'next' break still included the mini break I had now disabled.  I had to use 'Reset breaks' to remove the pending mini break.

Ideally, I think if I have disabled mini breaks I do not want to have a scheduled mini break still occur.  Perhaps this is intentional??

**Comment by hovancik** [comment]
Hi, yeah, this is kind of accepted bug. When you change preferences, I do not reset them, but wait for the next scheduler to make them "be applied". I've tried to do it in a way, that they would behave in a way that you describe, but I had some issues with it and never found solution for it... 

There is another issue where this is discussed, so I will close this one.

**Comment by hovancik** [comment]
I'm making new issue for brainstorming how this should work: #1248
