### ISSUE TITLE
[Bug]:   Error: Cask 'stretchly' is unavailable 

### ISSUE THREAD

**Issue by stijn-at-work** [hovancik/stretchly#1244]
### Version

- [ ] I'm using version 1.12.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.6

### Reproduction steps

1. brew update && brew install --cask stretchly
2.
3.
...
**Reproduces how often:** [What percentage of the time does it reproduce?]
always

### Expected Behavior

install stretchly

### Actual Behavior

Error: Cask 'stretchly' is unavailable: No Cask with this name exists.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
According to web, it should be there: https://formulae.brew.sh/cask/stretchly#default . I can also see the code: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/stretchly.rb

If your issue persists, you should talk to folks here: https://github.com/Homebrew/homebrew-cask

**Comment by stijn-at-work** [comment]
My homebrew-cask installation was corrupt. After reinstalling homebrew-cask i was able to install it. 
Thanks for pointing me in the right direction.

---
$ brew doctor > Warning: Homebrew/homebrew-cask was not tapped properly! Run:
  rm -rf "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask"
  brew tap homebrew/cask

$ rm -rf "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask"
$ brew tap homebrew/cask
$ brew search stretchly
$ brew install stretchly

**Comment by hovancik** [comment]
Glad to help :)
