### ISSUE TITLE
[Bug]:   Can't access Advanced Preferences

### ISSUE THREAD

**Issue by EmmaXl8** [hovancik/stretchly#1256]
### Version

- [X] I'm using version 1.13.1

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

Windows

### Operating System Version

Win 10 Pro 19045.2364

### Reproduction steps

1. Go to About section
2. Use shortcut Ctrl+D
3. Nothing appears to happen
...
**Reproduces how often:** [What percentage of the time does it reproduce?]
Always

### Expected Behavior

The shortcut Ctrl+D should display a link to the preferences file

### Actual Behavior

The shortcut doesn't seem to do anything. I've looked for the JSON file here: C:\Users\[username]\AppData\Local\Programs\Stretchly and in the subfolders, but can't find Advanced Preferences.

### Additional information

```shell
I've recently installed Stretchly, so this might be a beginner's issue. Please be patient with me!
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, all seems to work fine for me. You should see something like this: 

![image](https://user-images.githubusercontent.com/4745859/210138006-15eaa6fc-be18-463f-bf6d-60973d9c4e4c.png)

File is called `config.json`

**Comment by EmmaXl8** [comment]
Thanks for the screenshot! I definitely don't see stats or the file paths when I use the Ctrl+D shortcut in the About window. I even uninstalled and re-installed with administrator privileges, but it makes no difference.

Not to worry, I've now located the config file (I was looking in Local instead of Roaming) and have edited some of the parameters.  

Happy New Year!

**Comment by hovancik** [comment]
Okay, I'll close this then  :) All the best to you as well :)
