### ISSUE TITLE
[Bug]:   

### ISSUE THREAD

**Issue by currys-veracitek** [hovancik/stretchly#1258]
### Version

- [X] I'm using version 1.13.1

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 10.0.19044

### Reproduction steps

1. Go to https://hovancik.net/stretchly/downloads/
2. Under Downloads, Windows, the first line of the section, click on the link labeled "installer"
Reproduces how often: 100%

### Expected Behavior

Download latest stable release.

### Actual Behavior

Downloads 1.13.0, latest is 1.13.1, the link just didn't get updated on the last release. 
I noticed it because I ran into issue #1253 -- thank you for your prompt handling of issues so I could resolve that!
Perhaps you can modify the link to always download the latest. Based on https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases, I found that this link works:
 
https://github.com/hovancik/stretchly/releases/latest/download/Stretchly-Setup-1.13.1.exe

If you modified your release process to always include a Stretchly-Setup.exe file you could have a constant link of:

https://github.com/hovancik/stretchly/releases/latest/download/Stretchly-Setup.exe

Likely applies to links for the other platforms too.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Thanks! I've made changes to website but forgot to push :) Thanks for noticing, should be fine now.
