### ISSUE TITLE
[Bug]:   

### ISSUE THREAD

**Issue by Mkayxxx** [hovancik/stretchly#1260]
### Version

- [X] I'm using version 1.13.1

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

macOS

### Operating System Version

mac os latest

### Reproduction steps

i am still able to skip strict mode breaks on mac os , unfortunately ! ctrl + tab and it switches to another app leaving the stretchly somewhere in background.

### Expected Behavior

no ctrl+tab would make stretchly go away 

### Actual Behavior

i am able to switch to any other app that is running, making the stretchly blocking screen disappear

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Stretchly is regular app, and Ctrl+Tab is system shortcut. I have not found a way how that could be disabled :(

**Comment by Mkayxxx** [comment]
Thanks

Jan Hovancik ***@***.***> (šajā datumā: Se, 2023. g. 7. janv.
11:26) rakstīja:
