### ISSUE TITLE
[Bug]:   On Manjaro with i3wm I don't see icon.

### ISSUE THREAD

**Issue by Migacz85** [hovancik/stretchly#1264]
### Version

- [X] I'm using version 1.13.1

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

Linux

### Operating System Version

Linux, manjaro 5.15.85-1

### Reproduction steps

open the app.

### Expected Behavior

tray icon appear.

### Actual Behavior

tray icon is not appearing.

### Preferences

```shell
Because of that I can't edit perferences.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Looks like similar to #1259 .

What happens if you `killall stretchly` and then start Stretchly again?

**Comment by Migacz85** [comment]
Same.

**Comment by hovancik** [comment]
Sorry, but same as 1259, meaning that after restarting app you see icon, or same in a sense that no icon even after restart?

**Comment by Migacz85** [comment]
Same issue. The icon don't appear.

**Comment by hovancik** [comment]
Thanks for the update! Electron has recently changed the tray implementation which i3 seems not to support: 
https://github.com/electron/electron/issues/36602#issuecomment-1370645436

**Comment by hovancik** [comment]
Looks like there is a PR with fix, but not yet merged: https://github.com/electron/electron/pull/36815/ 

Btw, they changed to https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/
