### ISSUE TITLE
I don't notice the pauses when I'm in fullscreen (OSX)

### ISSUE THREAD

**Issue by BitPuffin** [hovancik/stretchly#127]
So if an application is running in fullscreen mode on OSX (such as a video, web browser, or emacs) when stretchly pauses trigger they do not show up over the application. It also doesn't steal the focus from the application so basically the notification goes entirely unnoticed. Since I'm probably in full screen most of the time, this makes it so that stretchly barely helps me at all.

**Comment by hovancik** [comment]
I've tried with atom and firefox and works fine for me. What browser or video player do you use? 
Also, are you on 0.10.0? I've released it yesterday.

**Comment by BitPuffin** [comment]
I think it happens with both firefox and chrome, though I suspect it has been chrome most of the time. By fullscreen, I mean when you click the button that moves the window to its own fullscreen desktop sort of. Not just maximizing it so that it takes up the most space. Not just the way you get it by alt-clicking the green button.

I haven't yet tried 0.10.0, I installed it earlier though!

**Comment by hovancik** [comment]
This was an issue in previous version. Should be fixed in 0.10.0.

**Comment by BitPuffin** [comment]
I still have the same problem in 0.10.0

**Comment by BitPuffin** [comment]
I can also just move to a separate virtual desktop in general and the window stays behind.

**Comment by hovancik** [comment]
It works fine for me. Maybe some another app interferes or something? How do you run those apps? 

<img width="1680" alt="screen shot 2017-08-21 at 19 13 17" src="https://user-images.githubusercontent.com/4745859/29530604-db1a6982-86a4-11e7-8130-e1b428a3357e.png">

**Comment by BitPuffin** [comment]
Just clicking the green button that makes OSX create like a separate virtual desktop to run the app in fullscreen. So you can switch between things with control+arrowkeys. When I run it like that the stretchly window doesn't show up. My current workaround has been to make stretchly window also go fullscreen which steals away focus from what I'm doing. But that's fairly annoying. But at least I don't miss out on the break.

I'm not sure what's wrong. Could there be a permission or something that you need to grant stretchly before it can show up above a fullscreen window?

**Comment by hovancik** [comment]
Ah, what is that green button? Not sure if we do the same thing. What I do is `cmd+shift+f` or the third button: 

![screen shot 2017-08-22 at 17 09 24](https://user-images.githubusercontent.com/4745859/29572484-c3a97302-875c-11e7-89f1-c15ff4211f46.png)


 Do you have one app that way or more? I've tried only with one. I don't know about any permission needed.

**Comment by BitPuffin** [comment]
Yea the third button. I guess it's not green in your colour scheme :)

I'll try cmd+shift+f later to confirm that it's the same.

I think it's usually more than one app in fullscreen. I may be that I have observed the same thing with only one app but not 100% sure.

**Comment by BitPuffin** [comment]
Ok so `cmd+shift+f` is not the same as clicking the third button. I do suspect that you'd get the popup if you do the `cmd+shift+f` fullscreen but not if you click the third button.

**Comment by hovancik** [comment]
Let's have some testing scenarios:

- open chrome and go fullscreen with button, swipe to normal screen, open firefox and go fullscreen - breaks shows up
- open chrome and go fullscreen with button, swipe to normal screen, open firefox and go fullscreen, swipe to chrome - break shows

**Comment by BitPuffin** [comment]
Hm weird now I can't even reproduce my own issue that reliably did not work. Can't tell what the bug is then. Maybe some weird edge case in OSX?

**Comment by hovancik** [comment]
I guess so. Let's close it for now and reopen when we have something reproducible?

**Comment by BitPuffin** [comment]
Yep! Or at least re-open if it occurs again.
