### ISSUE TITLE
[Bug]: Windows 11, Error witchout explanation

### ISSUE THREAD

**Issue by fspade** [hovancik/stretchly#1270]
### Version

- [x] I'm using version 1.13

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### Reproduction steps

1. Start Stretchly
2. Bang!
3. Happens every time
...
**Reproduces how often:** [What percentage of the time does it reproduce?]

### Expected Behavior

Running Stretchly

### Actual Behavior

none

### Relevant log output

```shell
not found, no chance to do Ctrl/Cmd + D
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fspade** [comment]
Sorry, I thought it was version 1.31 which I got from Chip.de, but downloading 1.31 from the home page fixed it.
Sorry for bothering you.

**Comment by hovancik** [comment]
:+1:  glad it works
