### ISSUE TITLE
[Feature request]: off during presnetations

### ISSUE THREAD

**Issue by drorliran** [hovancik/stretchly#1276]
Thanks for the amazing breaking app, 
I find it problematic that the breaks pop up during the presentation of  PPT presentations, is there a possibility for excluding this situation? 
I tried excluding the PPT app, but then it paused the breaks while I am editing a presentation, or even when the app is open, which is something I am not interested in.

**Comment by hovancik** [comment]
please follow this issue, but currently what you ask is not possible with Stretchly

https://github.com/hovancik/stretchly/issues/355#issuecomment-1455022953
