### ISSUE TITLE
[Bug]:   timer resets while put displays to sleep

### ISSUE THREAD

**Issue by Yoho777** [hovancik/stretchly#1279]
### Version

- [X] I'm using version 1.13.1

### Known issues

- [X] I've checked Known issues

### Existing issues

- [x] I've checked Existing issues

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.5.1

### Reproduction steps

Take default value for the preference, put display to sleep with hot corners and wake it up immediately

### Expected Behavior

remembers the timing progress as usual

### Actual Behavior

The timer restores its status as "next mini break in about 10 mins and next long break after 2 mini breaks" no matter what it was

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JamesMatt** [comment]
Please fix this issue, if the screen sleep time is set to be less than the stretchly rest time, we will mistakenly use the computer early.

**Comment by hovancik** [comment]
Hi, Stretchly is currently not aware of times passed when it is paused/reset. Please follow for the updates on this here: #1248 or possibly disable that feature: https://github.com/hovancik/stretchly#pause-breaks-on-suspendlock-
