### ISSUE TITLE
[Feature request]: Hide icon from the menu bar / tray

### ISSUE THREAD

**Issue by ghost** [hovancik/stretchly#1283]
### Version

- [X] I'm using version 1.13.1

### Existing requests

- [X] I've checked Existing requests

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

macOS

### Operating System Version

Monterey 12.6.3

### Problem description

I need to hide it from menu bar.

### Possible solution

An option to hide the icon from the menu bar. In that case, the app features will be accessible by clicking on the app from launchpad.

### Alternative solutions

Nothing.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
This could be done as an advanced option

**Comment by unixerius** [comment]
I would very much appreciate that too. Apps like OneDrive will hide their icon from you, so it'd be cool if Stretchly did as well.
