### ISSUE TITLE
[Bug]:   apk file cannot be installed

### ISSUE THREAD

**Issue by ZhuZheart98** [hovancik/stretchly#1289]
### Version

- [X] I'm using version 1.13.1

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

Other (specify below)

### Operating System Version

HarmonyOS3.0.0.202

### Reproduction steps

1. download the [Stretchly-1.13.1.apk] into my phone.
2. install it and there is "error".

### Expected Behavior

The Operating System HarmonyOS3.0.0.202 in my phone is based on the Android, so the apk file can be installed in my phone.

### Actual Behavior

However, it cannot be installed and an unknown error occurred.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Apk in this case is not for android, but Alpine Linux APK https://docs.alpinelinux.org/user-handbook/0.1a/Working/apk.html. There is no Android version of Stretchly, sorry.

**Comment by ZhuZheart98** [comment]
Thanks~
