### ISSUE TITLE
Schedule: ability to trigger breaks at specific times of day.

### ISSUE THREAD

**Issue by ernest4** [hovancik/stretchly#1290]
### Version

- [X] I'm using version 1.13.1

### Existing requests

- [X] I've checked Existing requests

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.2.1

### Problem description

I need an app to turn off the computer at night time to push me go to sleep. I need it to trigger once a day every day at same time evening e.g. 11pm. The break needs to be unstoppable and unskippable.

### Possible solution

Simple setting to allow setting a break to happen on schedule on specific time of day every day.

### Alternative solutions

none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, I will close this as I do not plan to implement this any time soon. My other app has this option, but it's a bit different than Stretchly. It's called LaterOn and it allows you to specify custom notifications/reminders on custom schedule: https://lateron.app/
