### ISSUE TITLE
[Feature request]: Add autoupdate to stretchly

### ISSUE THREAD

**Issue by Yoneo** [hovancik/stretchly#1299]
### Version

- [X] I'm using version 1.13.1

### Existing requests

- [X] I've checked Existing requests

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

Windows

### Operating System Version

10

### Problem description

I like the regular updates of stretchly. But it takes too much time to install them.

### Possible solution

Stretchly should have the ability to make autoupdates. There should be an option to enable/disable the autoupdates in settings. The autoupdate should install without the need for confirmation.

### Alternative solutions

An alternative would be to publish stretchly in windows store. There are autoupdates possible by default.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
You can also use `winget` https://learn.microsoft.com/en-us/windows/package-manager/winget/upgrade

**Comment by afonseca08** [comment]
This may help:
https://www.electronjs.org/docs/latest/api/auto-updater

**Comment by hovancik** [comment]
I've added Stretchly to the windows store. I don't plan to add auto-updater.
