### ISSUE TITLE
Option to display no advices during breaks

### ISSUE THREAD

**Issue by cloo** [hovancik/stretchly#130]
I often find the repeated texts annoying, and would prefer to stay with a clean black box, containing only a countdown. 

Also, some texts (like the one about bathrooms in the office), sometimes appear in weird and useless situations: when I'm working in a cafe or home, or when I'm having a coleague by my side. 

Alternatively, I'd suggest a settings page, where you could select which messages you find useful, or even write your own.

**Comment by hovancik** [comment]
Thanks for the idea. It's easily done so it will be added soon (no break ideas window).

You can edit break ideas, but it's not "easy" right now 
https://github.com/hovancik/stretchly#editing-breakmicrobreak-ideas

**Comment by cloo** [comment]
Brilliant, thanks!
Editing config files is probably easy, at least for github crowd, but finding this config file somehow isn't self explanatory, at least on windows :)
So I thought of another suggestion: a link to config file would be really convenient, and then stretchly would gain a nice sense of hackable!

**Comment by hovancik** [comment]
Thanks :) You can see path to the config in About window with `Ctrl/Cmd+d`
