### ISSUE TITLE
[Feature request]: Flexible Screen Blocking Hours

### ISSUE THREAD

**Issue by JanChec** [hovancik/stretchly#1312]
### Version

- [X] I'm using version 1.14.0

### Existing requests

- [X] I've checked Existing requests

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

Other (specify below)

### Operating System Version

Windows 11 and Linux

### Problem description

Currently, the app blocks the screen at regular intervals that the user sets, but it does it all the time regardless of the time of day. I often work at odd hours or on weekends and I don't want to be interrupted during my off-hours.

### Possible solution

So, my suggestion is to add a feature that allows users to set specific hours during which the screen-blocking feature is active. For instance, I would love to set the app to only block the screen between 9:00 am and 5:00 pm on weekdays, but not outside of those hours.

### Alternative solutions

The alternative would be to simply close and turn on the app, but I would like to avoid having to remember to turn it on every time.

### Additional information

I think this would be a great feature because it would give users more flexibility to tailor the app to their work schedule. Thanks for considering this feature, and keep up the great work!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Thanks for the feedback, please follow the updates here: #342
