### ISSUE TITLE
REQUEST NEW FEATURE

### ISSUE THREAD

**Issue by anjo999** [hovancik/stretchly#1315]
I write here because I dont find the section about "request new feature":

I NEED the option for a sound when the pre notification and decide how many notification will appear before each pause. because the banner is too quick. 
I would love to have a countdown.... persistent notification with countdown.
thanks

**Comment by hovancik** [comment]
Hi, the template is here: https://github.com/hovancik/stretchly/issues/new/choose

You can change the time before break when the notification will appear, but that's it. I do not plan to change that. 

https://github.com/hovancik/stretchly#editing-break-notification-interval-
