### ISSUE TITLE
[Feature request]: Verify Flatpak on Flathub

### ISSUE THREAD

**Issue by jwillikers** [hovancik/stretchly#1319]
### Version

- [X] I'm using version 1.14.0

### Existing requests

- [X] I've checked Existing requests

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

Linux

### Operating System Version

Fedora Silverblue 38

### Problem description

There's a new Flathub website where it is possible mark apps as verified. This is described in the new [About](https://flathub.org/about) page.

### Possible solution

@hovancik, if you login to the Flathub website with your GitHub account, it should automatically associate the Stretchly Flatpak with your account. You can then follow the instructions in the [Developer Settings](https://flathub.org/apps/manage/net.hovancik.Stretchly) page for Stretchly to perform Website verification.

### Alternative solutions

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
:+1:
