### ISSUE TITLE
[Feature request]: Show images in Break Window

### ISSUE THREAD

**Issue by Overload119** [hovancik/stretchly#1324]
### Version

- [X] I'm using version 1.14.0

### Existing requests

- [X] I've checked Existing requests

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

Windows

### Operating System Version

M2 Macbook Pro 2023 - Ventura

### Problem description

In the same way that we can customize the break ideas I'd like to point to a folder of "motivational images" that show during the break period. 

### Possible solution

A new preference option (Locate Folder)
A toggle perference (Enable/Disable)

### Alternative solutions

N/A

### Additional information

I can implement this feature, so I plan on forking this project and adding it but would like pointers so I can do it in a way to merge it back upstream if people want this. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi there, there is issue already opened with some people wanted to implement but never happened. Can you comment there? I would like to make sure we know what we do  before we write code :) 

I think this comment is important to answer: https://github.com/hovancik/stretchly/issues/160#issuecomment-603769121
