### ISSUE TITLE
[Feature request]: expose stretchly actions for accessibility reasons

### ISSUE THREAD

**Issue by saidelike** [hovancik/stretchly#1335]
### Version

- [X] I'm using version 1.14.1

### Existing requests

- [X] I've checked Existing requests

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

Windows

### Operating System Version

Windows 10 22H2

### Problem description

See at the end of this message on why this feature is important for accessibility reasons.

I am aware of the 2 following shortcuts already available:

```
{
    ...
	"endBreakShortcut": "CmdOrCtrl+X",      // Postpone/Finish Break Shortcut https://github.com/hovancik/stretchly#postponefinish-break-shortcut
	"pauseBreaksToggleShortcut": "",        // Toggling between Pause Breaks and running breaks https://github.com/hovancik/stretchly#toggle-breaks-shortcut
```

I would be nice to have a way to define shortcuts for the following options:

```
    skipToNextMiniBreakShortcut
    skiptoLongMiniBreakShortcut
    resetBreakShortcut
```

That would be particularly useful for accessibility reasons.

Even if the shortcuts are not defined and left for the users to be defined, that would be sufficient. Otherwise I can suggest:

```
    skipToNextMiniBreakShortcut: "CmdOrCtrl+F18"
    skiptoLongMiniBreakShortcut: "CmdOrCtrl+F19"
    resetBreakShortcut: "CmdOrCtrl+F20"
```

### Possible solution

do something similar to `endBreakShortcut` and `pauseBreaksToggleShortcut`?

### Alternative solutions

N/A

### Additional information

This feature is very important for accessibility users where you can't use a keyboard or a mouse. Or if you have a health condition that means you need to reduce your use of keyboard and mouse (e.g. if you have to use your voice to control your computer).

Exposing the stretchly actions with global shortcuts would allow to configure a typical accessibility voice software to automatically input the `resetBreakShortcut` shortcut configured in stretchly (e.g. "CmdOrCtrl+F20") when saying something like "STRETCHLY RESET BREAK". But we can't do that if stretchly does not expose that shortcut.

It is all the more important for a software like stretchly to take into account accessibility problems because the whole point of stretchly is to make sure the person using the computer is in a good health. So forcing them to use a mouse if they can't for health reason is not the best thing in the world :) Joke appart, I love stretchly and it is a great tool so thanks for all it provides!

NOTE: It is related to https://github.com/hovancik/stretchly/issues/791 but I created a new issue to explain a lot more of the requirements and reasons.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi and thanks for feedback, I plan to implement shortcuts but this is queestion of me finding enough free time ;/
