### ISSUE TITLE
[Bug]:   Going into sleepmode stops the break in Windows

### ISSUE THREAD

**Issue by omeritzics** [hovancik/stretchly#1336]
### Version

- [X] I'm using version 1.14.1

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 22H2

### Reproduction steps

1. Start a break
2. Go into sleep mode
3. Awake the system

**Reproduces how often:** Every time you wake up the system in the middle of a break.

### Expected Behavior

The break should keep going.

### Actual Behavior

The break immediately stops.

### Relevant log output

```shell
breakPlanner: {reference: startMicrobreak,
            timeleft: נותרו 9 דקות 5 שניות,
            breakNumber: 1,
            postponesNumber: 0,
            Do Not Disturb: false}
            
            settingsFile: C:\Users\Omer\AppData\Roaming\Stretchly\config.json
            
            logsFile:  C:\Users\Omer\AppData\Roaming\Stretchly\logs\main.log
            Node.js: 18.15.0
            Chromium: 114.0.5735.45,
            Electron: 25.0.1
```

### Additional information

This bug only occurs on Windows, from what I know.

Regardless, thank you for this app, it helps me a lot :)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi that is expected behavior. You can change via advanced preferences: 
https://github.com/hovancik/stretchly#advanced-preferences
https://github.com/hovancik/stretchly#pause-breaks-on-suspendlock-
