### ISSUE TITLE
[Feature request]: Left click taskbar context menu

### ISSUE THREAD

**Issue by generrosity** [hovancik/stretchly#1345]
### Version

- [X] I'm using version 1.14.1

### Existing requests

- [X] I've checked Existing requests

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

Windows

### Operating System Version

Win11 22h2

### Problem description

Suggesting to add left click on the Windows tasktray icon to open the same menu. 

It seems these days that clicking on tasktray icons at all brings up the menu as typically they are hidden from sight anyway.

### Possible solution

Left click triggers the same right click menu.

### Alternative solutions

Perhaps as an option?

Also, some apps respond to a double-left-click to open preferences without navigating to the menu first.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, how does it work now on Windows? (Linux user here). 

Checking the docs, seems like Electron has following events (for some platforms)
- `click` event - https://www.electronjs.org/docs/latest/api/tray#event-click
- `right click` event - https://www.electronjs.org/docs/latest/api/tray#event-right-click-macos-windows
- `double click` event - https://www.electronjs.org/docs/latest/api/tray#event-double-click-macos-windows

I am not using any specific event, just creating menu here: https://github.com/hovancik/stretchly/blob/trunk/app/main.js#L1150C15-L1150C29, so I guess Electron takes `click` event and do whatever it does for that platform.

**Comment by generrosity** [comment]
Thanks for your consideration!

Currently, only right click does anything.

I did a bit of googling, GitHub com/electron/electron/issues/ 1393 ... Looks like there is a tray.on clicked function tray.popcintextmenu?

Thanks for taking a squiz :)
