### ISSUE TITLE
[Feature request]: Enable input of custom messages that Stretchly rotates through for breaks

### ISSUE THREAD

**Issue by weiweihuanghuang** [hovancik/stretchly#1347]
### Version

- [X] I'm using version 1.14.1

### Existing requests

- [X] I've checked Existing requests

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.6.1

### Problem description

It would be very handy for Stretchly to display custom message for every short break – and specifically to cycle through a list of them. I would like to do this so that I can input a custom list of stretches that stretchly can cycle through for to do every short break. 

### Possible solution

Have an input section in the settings where each line is the message that Stretchly can cycle through and display for short breaks and long breaks.

### Alternative solutions

I can't think of a solution that would use Stretchly's current features.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi @weiweihuanghuang , you can do that already by editing Stretchly's configuration file :) 
More here: 
https://github.com/hovancik/stretchly#advanced-preferences
https://github.com/hovancik/stretchly#editing-break-ideas
