### ISSUE TITLE
[Feature request]: Allow to choose "Main Display" for alerts or take from OS

### ISSUE THREAD

**Issue by Edgaras91** [hovancik/stretchly#1352]
### Version

- [X] I'm using version 1.14.1

### Existing requests

- [X] I've checked Existing requests

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### Problem description

There is only 1 tickbox: "Show breaks on all monitors". If that is unticked, it displays on "hardware's" primary monitor (whatever your graphics card classifies that HDMI port to be their 1st display) instead of using Windows OS "Primary Display" tick.

![image](https://github.com/hovancik/stretchly/assets/32236075/23a6fb6b-baeb-4991-a163-675b2be865ce)
In my example, the alerts are always happening on 2nd screen (the screen I happen to screen share in my meetings)

It would be nice if by default it would choose the OS main display, or give some sort of an option. Displaying on non-main display is giving an unexpected user experience. 

A lot of people can just get lucky, that their primary hardware monitor matches the OS monitor, but not for some like me.

### Possible solution

Display alerts on OS Main display

### Alternative solutions

Give an option to above "possible solution"

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, you can set that via advanced preferences: 
- https://github.com/hovancik/stretchly#advanced-preferences
- https://github.com/hovancik/stretchly#monitor-to-show-breaks-on-

Unfortunate truth is that Electron's/Chromium's implementation of this is not without bugs so especially with Windows OS it's more about luck, I guess?

**Comment by Edgaras91** [comment]
> Hi, you can set that via advanced preferences:
> 
>     * https://github.com/hovancik/stretchly#advanced-preferences
> 
>     * https://github.com/hovancik/stretchly#monitor-to-show-breaks-on-
> 
> 
> Unfortunate truth is that Electron's/Chromium's implementation of this is not without bugs so especially with Windows OS it's more about luck, I guess?

Thank you, changing "screen" from "primary" to "2" in config.json fixed the issue.
Strange how "2" is the "1" from the screenshot on Windows (11).
