### ISSUE TITLE
[Feature request]: Automatically reload settings.json without restarting

### ISSUE THREAD

**Issue by Glinte** [hovancik/stretchly#1359]
### Version

- [X] I'm using version 1.14.1

### Existing requests

- [X] I've checked Existing requests

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

Windows

### Operating System Version

Windows 10 22H2

### Problem description

I changed the built-in break ideas to `"enabled": false` and added some of my own, only to find out that it doesn't quite work. Quit and restart fixes everything but that was a bit unexpected.

### Possible solution

Make Stretchly reload settings.json every break? Not sure how jank that will be

### Alternative solutions

Alternatively just add a line in the Custom ideas toggle that mentions that restarting is required

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi there, I recommend to always quit Stretchly before editing preferences file, because not doing it can cause errors. Sorry about it.
