### ISSUE TITLE
[Feature request]: Keep Break Running When Screen Locked

### ISSUE THREAD

**Issue by whispy** [hovancik/stretchly#1364]
### Version

- [X] I'm using version 1.14.1

### Existing requests

- [X] I've checked Existing requests

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

macOS

### Operating System Version

Ventura 13

### Problem description

I work in a coworking space where others can access my computer, if it is unlocked. When Stretchly activates a break, I often like to walk around the floor or even out to the street. However, I don't want to leave my computer unsecured while I do this!

I run my breaks in `Windowed` mode, with the window width and height set to `1`. This basically gives me the same effect as a fullscreen break, while allowing me to still see what's behind the break window (with opacity `0.8`) to write down notes in my notebook during the break.

Stretchly's current behavior is to immediately end a running break when the screen is locked.

### Possible solution

Keep running the break when the screen is locked.

### Alternative solutions

Alternatively and much less secure (but enough to prevent casual snooping): add the ability to keep the Stretchly break screen activated when a break is over _until a password_ has been typed on the break screen.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
This is already in advanced preferences :) https://github.com/hovancik/stretchly#pause-breaks-on-suspendlock-

**Comment by whispy** [comment]
Whoops, I missed that. Thanks!
