### ISSUE TITLE
[Bug]:   FortiClient 7.0.9 detects Virus FSA/RISK_HIGH//2000006931 in extracted file fastlist-0.3.0-x86.exe during installation

### ISSUE THREAD

**Issue by craiglahote** [hovancik/stretchly#1365]
### Version

- [X] I'm using version 1.14.1

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22H2 22621.2213

### Reproduction steps

Detection occurs during attempted installation using Stretchly-Setup-1.14.1.exe

### Expected Behavior

No malware detection

### Actual Behavior

Malware reported and installation file quarantined by Fortinet FortiClient.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, this seems to be false positive: https://github.com/MarkTiedemann/fastlist/issues/2

From what I read most of the major antiviruses are not longer marking this as issue: https://www.virustotal.com/gui/file/017411f3b0b5c0402cc3b2cb87c32c6fc71abd82e5b17ea6108990096c75a65d/detection
