### ISSUE TITLE
[Feature request]: Ability to pause Stretchly via menubar in strict mode

### ISSUE THREAD

**Issue by cyniphile** [hovancik/stretchly#1366]
### Version

- [X] I'm using version 1.14.1

### Existing requests

- [X] I've checked Existing requests

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

macOS

### Operating System Version

macOS 13.4.1 (c) (22F770820d)

### Problem description

When I don't have strict mode enabled, I always develop a bad habit of skipping breaks. 

That said, if the break timer pops up during a zoom or teams meeting, I need to skip them pretty urgently. 

I know you can pause stretchly when certain apps are open, but this feature does not work very well:
- I leave teams open because it is a chat application as well as a video call application, so stretchly is always paused
- Zoom, too, often stays open in the background. 

### Possible solution

Right now, you can click on the menubar stretchly icon to pause it temporarily. It takes a couple clicks, so it is much harder to develop a habit of pausing it every break. However, this pause function is disabled during strict mode. I would like there to be an option to have this enabled during strict mode, so that if stretchly pops up during a meeting I can fairly quickly pause it when I need to. 

### Alternative solutions

No others idea in mind at the moment, but I'll take the opportunity to say thanks for a great app!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AvgustPol** [comment]
@cyniphile hi there

# Short Reply
### Workaround  MacOs
Mac: Block you screen using `Control + Command + Q` shortcut 

### Workaround for Windows 10 & 11 
Block you screen using `WIN + L` shortcut 

# More details for you 
I'm not sure if it will work for you on Mac. I'm using it on Windows and I`ve disabled skipping option (strict mode) 

### Context 
If I'm on call or I need to logging for something urgent - workaround to lock my screen and log in again - this resets Strechly from blocking the screen 

### Please verify 
Chat PT telling me that on a Mac, you can quickly lock the screen by pressing `Control + Command + Q`. Does the trick just like WIN+L on Windows. 😎

**Comment by cyniphile** [comment]
This is unfortunately not an acceptable workaround, as it forced me to lock my screen during the middle of a call. Since I use my computer for work, this would cause disruptions.

**Comment by hovancik** [comment]
Well, the solution here is for Microsoft and Zoom to turn on system Do not disturb mode when meeting has started. Maybe it's possible already? 

Or similar to what @AvgustPol said, but turn on DND by some shortcut.

**Comment by cyniphile** [comment]
Don't think there is a way to turn on DnD when zoom/teams are in a call. It is only just when the app is opened and closed, so the same problem when using, say, teams for chat (always open). I guess I can use the keyboard shortcut for DnD, but not ideal as the shortcut just turns on DnD mode, and then I have to remember to turn it off.

**Comment by cyniphile** [comment]
This turns out to not be a good solution anyway, because turning on DnD mid pause does not close/hide the stretchly pop (confirmed that "Show even in DnD mode" option was disabled.

**Comment by cyniphile** [comment]
@hovancik since you are on the thread, also wanted to take the time to say thank you for Stretchly. I've been using it for years and I find it dramatically improves my vision.

**Comment by cyniphile** [comment]
My workaround is to simply quit stretchly if it pops up at a bad time, and set a cron to conditionally open it again every half hour.

**Comment by hovancik** [comment]
Sorry guys it took so much time, but life is life. Once new version is out, you will be able to specify advanced option to enable this behavior: https://github.com/hovancik/stretchly?tab=readme-ov-file#show-break-actions-skip-pause-reset-in-strict-mode

**Comment by cyniphile** [comment]
wow was not expecting this. Thanks so much!
