### ISSUE TITLE
Suggestion: only give notifications for rest breaks

### ISSUE THREAD

**Issue by SjoerdOptLand** [hovancik/stretchly#137]
I like the notifications for rest breaks, because I can finish my sentence before the fullscreen break appears. This way, I have no excuse for 'quickly' finishing up (which, of course, always finally causes me to ignore the break).

Microbreaks are so short, on the other hand, that I can keep the rest of my sentence in mind, and continue after stretching my legs. The -30 seconds notifications actually distracts me from my work.

Would it be possible to only display notifications for rest breaks? Or make that optional (but watch out: I love your minimalistic settings screen, keep it like that!)

**Comment by hovancik** [comment]
Thanks, that could be done, I'll think about it.

**Comment by hovancik** [comment]
on master now
