### ISSUE TITLE
[Bug]:   openSUSE Tumbleweed 20230906 Breaks Stretchly

### ISSUE THREAD

**Issue by richardstevenhack** [hovancik/stretchly#1373]
### Version

- [X] I'm using version 1.14.1

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

Linux

### Operating System Version

openSUSE Tumbleweed 20230906 snapshot

### Reproduction steps

1. Start program from either AppImage or RPM installation.
2. Click "skip to next long break"
3. Windows opens with large flickering blue background.
...
**Reproduces how often:** [What percentage of the time does it reproduce?]
100 Percent.

### Expected Behavior

I expect the window to open for the required five minutes, the length of the long break, and show the usual countdown bar and other features.

### Actual Behavior

The window opens with the entire window a deep blue color, with a wide white band in the center stretching from one side to the other. See this screenshot:
![Screenshot_20230918_003824](https://github.com/hovancik/stretchly/assets/44449170/4611fc18-677b-404b-bebc-e5b2c67188f3)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by richardstevenhack** [comment]
Update: I uninstalled Stretchly completely, including deleting the .config files. I then downloaded the tarball version and ran it directly from the untarred executable. This strangely works! Go figure: the AppImage and the RPM don't work, but the tarball version does.

**Comment by hovancik** [comment]
Seems like some dependency issue. From what I understand AppImage packages also dependencies. There is open similar issue #1266, but this is out of my knowledge unfortunately ;/
