### ISSUE TITLE
Ugly error when starting stretchly if it's already running

### ISSUE THREAD

**Issue by tom-a-horrocks** [hovancik/stretchly#138]
Better behaviour would be to do nothing, or show an 'already running' dialog,

![image](https://user-images.githubusercontent.com/6022830/30944966-07f4b8da-a42e-11e7-824a-9001061a06d1.png)

**Comment by hovancik** [comment]
You are on Windows, right? Can't reproduce on Mac/Linux.

**Comment by tom-a-horrocks** [comment]
Yeah that's correct. I've gotten the same error on a Windows 10 and Windows 7 machines.

**Comment by hovancik** [comment]
Related:  https://github.com/electron/electron/issues/9392
