### ISSUE TITLE
"Pause indefinitely" switches back on 

### ISSUE THREAD

**Issue by cloo** [hovancik/stretchly#139]
Stretchly starts suggesting breaks automatically after each computer wake up, even when "pause indefinitely" was used and "start at login" disabled.

**Comment by hovancik** [comment]
Thanks for reporting, I see where the problem is and will try to fix ASAP.

**Comment by hovancik** [comment]
So I was thinking about this: 
- right now when stretchly sees that machine goes to sleep, it does "Pause indefinitely" by itself
- when machine wakes up, it resumes breaks

So the question is: should it stayed in "Pause indefinitely" mode when user used "Pause indefinitely" before going to sleep? 

Not sure, what do you folks think? I'm moving towards: It should resume breaks.

**Comment by hovancik** [comment]
Ok, so i changed my mind. Indefinite pause will be kept after resume, others will not be kept.
