### ISSUE TITLE
[Bug]: Flatpak build for Stretchly v1.15.0 is encountering errors

### ISSUE THREAD

**Issue by mcmxcdev** [hovancik/stretchly#1400]
### Version

- [ ] I'm using version 1.15.1

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

Linux

### Operating System Version

Ubuntu 23.10

### Reproduction steps

1. See that Stretchly v1.15.0 was released
2. Run flatpak upgrade
3. No new release seem to have been registered to upgrade to

### Expected Behavior

Flatpak can install the latest version release of Stretchly

### Actual Behavior

Both v1.15.0 as well as 1.15.1 are currently having a breaking build on: https://github.com/flathub/net.hovancik.Stretchly/pull/8

This means that Flatpak users are still on 1.14.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mcmxcdev** [comment]
Consider this resolved, as https://github.com/flathub/net.hovancik.Stretchly/pull/8 was just merged.

**Comment by hovancik** [comment]
🥳
