### ISSUE TITLE
[Bug]:   Does not install on macOS Sonama 14.1.1 (23B81) with Apple Silicon

### ISSUE THREAD

**Issue by jamesholland-uk** [hovancik/stretchly#1404]
### Version

- [X] I'm using version 1.15.1

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

macOS

### Operating System Version

14.1.1 (23B81)

### Reproduction steps

1. Download (I tried both `brew` and the latest .dmg release from GitHub) Stretchly on an Apple Silicon macOS machine running Sonama (`14.1.1 (23B81)` in my case)
2. Install Stretchly
3. Open Stretchly, get error message: `“Stretchly.app” is damaged and can’t be opened. You should move it to the Bin.`
![Screenshot 2023-11-24 at 10 05 19](https://github.com/hovancik/stretchly/assets/6574404/c4a694ee-48a0-4d2f-8cd1-2889d1f580a8)

**Reproduces how often:** 100%

This works fine on my Apple Silicon Macbook Pro (MacBook M1) which is still running Ventura (13.6.2)

### Expected Behavior

Stetchly should open

### Actual Behavior

Stetchly fails to open

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by leowill01** [comment]
same issue on both my M2 macbook air and M2 ultra mac studio running sonoma 14.1.1

**Comment by hovancik** [comment]
Hi guys, did you follow instractions here? https://github.com/hovancik/stretchly#macos

You might need to run `    sudo xattr -r -d com.apple.quarantine /Applications/Stretchly.app`

**Comment by jamesholland-uk** [comment]
That fixed it, thank you

**Comment by heartpunk** [comment]
JFYI, I had to do this even with passing the `no-quarantine` option to `brew install`, perhaps the docs need updated?

**Comment by hovancik** [comment]
@heartpunk could you please be more specific? What do you mean by "had to do this"?  Did you pass `no-quarantine` with `--`? I am checking brew docs and `--no-quarantine` should still be supported
