### ISSUE TITLE
[Feature request]: Disallow pressing Super key during break to avoid user from quitting Stretchly

### ISSUE THREAD

**Issue by mcmxcdev** [hovancik/stretchly#1411]
### Version

- [X] I'm using version 1.15.1

### Existing requests

- [X] I've checked Existing requests

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

Linux

### Operating System Version

Ubuntu 23.10

### Problem description

I find myself being sneaky and pressing the Super key during a break and then quitting Stretchly from the taskbar and restarting it which resets the breaks. 

In strict mode, there should ideally be no way to work around having to take a break.

### Possible solution

Ideally, the Super key is disabled during a break so that there is no option left to skip it.,

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
This has been discussed previously but I never found a way to do this with NodeJS/ ElectronJS

https://github.com/hovancik/stretchly/issues/900
https://github.com/hovancik/stretchly/issues/411
and few more

**Comment by mcmxcdev** [comment]
All clear. After reading into it a bit, it looks like this still can't be solved, so I will get this closed.
