### ISSUE TITLE
[Feature request]: migrate tests to vitest

### ISSUE THREAD

**Issue by cany748** [hovancik/stretchly#1417]
### Version

- [X] I'm using version 1.15.1

### Existing requests

- [X] I've checked Existing requests

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 23H2

### Problem description

Migrate to vitest offers many benefits:
1) speed
2) ESM and TS support
3) many new features

### Possible solution

Сan migrate tests to vitest, I can create a PR. I have already migrate the tests and it works great!

### Alternative solutions

Сan use jest for tests or just leave it as is.

### Additional information

https://github.com/cany748/stretchly

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
What would it mean for the project setup? Right now I prefer no TS and such as I am building on CI and new dependencies usually means more issues with each new release I try to make. These dependencies tend to break random stuff and it is really painful and wasteful to spend hours trying to figure out WTF on each Stretchly release :(

**Comment by cany748** [comment]
Migration to Vitest will get rid of: "chai", "chai-as-promised", "mocha", "sinon". Vitest is a flexible, well-tested, actively developing tool.

**Comment by hovancik** [comment]
Well, if you say that you have done the changes already, feel free to make a PR and I will take a look
