### ISSUE TITLE
[Bug]:   Stretchly-1.15.1-1.x86_64 RPM conflicts with file from package slack

### ISSUE THREAD

**Issue by Zinkelburger** [hovancik/stretchly#1420]
### Version

- [X] I'm using version 1.15.1

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

Linux

### Operating System Version

Fedora Linux 39

### Reproduction steps

1. Download the 15.1 RPM file from github
2. sudo rpm -i Stretchly-1.15.1.x86_64.rpm
3. Get an error about a conflicting package
...
Reproduces every time

### Expected Behavior

I expected stretchly to install

### Actual Behavior

The stretchly rpm fails to install and gives an error about conflicting packages

### Relevant log output

```shell
sudo rpm -i Stretchly-1.15.1.x86_64.rpm 
	file /usr/lib/.build-id/21/d4e07fcf10f30bb538db018c3691202f7496ca from install of Stretchly-1.15.1-1.x86_64 conflicts with file from package slack-4.35.131-0.1.el8.x86_64
	file /usr/lib/.build-id/31/67ad6b32c635dff5a94dad8a8d2d4da669974d from install of Stretchly-1.15.1-1.x86_64 conflicts with file from package slack-4.35.131-0.1.el8.x86_64
	file /usr/lib/.build-id/a9/049dae268525b4a336acaefd7bf30dc6fa31e6 from install of Stretchly-1.15.1-1.x86_64 conflicts with file from package slack-4.35.131-0.1.el8.x86_64
	file /usr/lib/.build-id/b3/ae6bf4d0e66496320a9e91f34c0137908b4699 from install of Stretchly-1.15.1-1.x86_64 conflicts with file from package slack-4.35.131-0.1.el8.x86_64
	file /usr/lib/.build-id/c4/365b54e986bd0438cc73557905d9040fd9b47e from install of Stretchly-1.15.1-1.x86_64 conflicts with file from package slack-4.35.131-0.1.el8.x86_64
	file /usr/lib/.build-id/d6/dbb4c112131521d32d30fcbb6e290f8bbfd58c from install of Stretchly-1.15.1-1.x86_64 conflicts with file from package slack-4.35.131-0.1.el8.x86_64
	file /usr/lib/.build-id/e7/d5fe2cd951b5c7111544c56de2b95a6c82070d from install of Stretchly-1.15.1-1.x86_64 conflicts with file from package slack-4.35.131-0.1.el8.x86_64
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi and thanks for the report, will try to fix this

Related https://github.com/ferdium/ferdium-app/issues/416

**Comment by hovancik** [comment]
@Zinkelburger could you try this version? https://conta.noho.st/nextcloud/s/EMckRmW3wneBNNq

**Comment by Zinkelburger** [comment]
Thank you, that is able to install with no dependency issues.
