### ISSUE TITLE
[Bug]:   Process

### ISSUE THREAD

**Issue by alabotski** [hovancik/stretchly#1424]
### Version

- [X] I'm using version 1.15.1

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

Windows

### Operating System Version

Windows 10 19045.3930

### Reproduction steps

1. Run Stretchly

### Expected Behavior

Run one process

### Actual Behavior

Four processes are launched
https://mega.nz/folder/Fs0BGZBR#-_6LsBXoWKSI_SCWtI0qgA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, that is how ElectronJS works, it creates multiple processes: for each windows, some main process etc.
