### ISSUE TITLE
[Bug]: Blocks lock screen, unresponsive, on Fedora/KDE

### ISSUE THREAD

**Issue by Zinkelburger** [hovancik/stretchly#1425]
### Version

- [X] I'm using version 1.15.1

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

Linux

### Operating System Version

Fedora 39, KDE 5.113.0

### Reproduction steps

1. Start stretchly, setting mini break to 5 mins & setting to "show on all monitors"
2. Connect computer to external monitor
3. Lock computer (Meta+L) & wait for stretchly to activate
Reproduces 100% of the time

### Expected Behavior

I expect Stretchly to not appear and block the lock screen. It is also frozen, and the "skip this break" button does not respond. The program does not respond to any key combinations, such as Alt+F2, Alt+F4, Ctrl+Q.
To be able to access the login screen, I have to disconnect the monitor.

Also, if there is no external monitor connected stretchly does not block the lock screen.

### Actual Behavior

I am blocked from logging into the computer by an unresponsive Stretchly screen

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi @Zinkelburger , are there any messages in log? Any other specific settings? 

I've been trying to replicate on my Debian KDE machine with external monitor but no issues

**Comment by Zinkelburger** [comment]
Thank you for checking it out. I really appreciate your program, it has helped me a lot.

I have the stretchly default settings:
Show breaks in window
Show exercise tips during breaks
Show breaks on all monitors
Monitor system idle time
Show breaks even in do not disturb mode

**Comment by hovancik** [comment]
Maybe related to #1420?

**Comment by Zinkelburger** [comment]
I downloaded the version in #1420, and the issue still occurs

**Comment by hovancik** [comment]
Hi @Zinkelburger , sorry for no reply, I am busy :( 

Still not able to replicate at my machine. Could you check if anything pops up in logs? (In Preferences and About, hit Ctrl+D and location of logs file will be shown)

**Comment by Zinkelburger** [comment]
I'll try to look at it later today
The stretchly logs show `window 2` by itself. At the same time, there is a core dump for OOM or something. Seems like they could be related. I put the small logs in the comment and attached the larger ones.
The logs show 2 of the same error, one at 14:11, and one at 14:38

Stretchly logs:
```
[2024-07-23 14:06:23.686] [info]  Stretchly: showing window 1 of 2
[2024-07-23 14:06:23.686] [info]  Stretchly: starting Mini Break
[2024-07-23 14:06:23.731] [info]  Stretchly: showing window 2 of 2
[2024-07-23 14:06:43.689] [info]  Stretchly: finishing Mini Break (shouldPlanNext: true)
[2024-07-23 14:11:43.934] [info]  Stretchly: showing window 2 of 2
[2024-07-23 14:13:30.426] [info]  Stretchly: finishing Mini Break (shouldPlanNext: true)
```

Bad window error at the same time as window 2 by itself
```
Jul 23 14:13:20 my-hostname kwin_x11[3200]: kwin_core: XCB error: 3 (BadWindow), sequence: 38177, resource id: 15279243, major code: 129 (SHAPE), minor code: 6 (Input)
Jul 23 14:13:30 my-hostname kwin_x11[3200]: kwin_core: XCB error: 3 (BadWindow), sequence: 43095, resource id: 60817486, major code: 129 (SHAPE), minor code: 6 (Input)
```

OOM error at the same time
```
Jul 23 14:11:43 my-hostname stretchly[45061]: [45061:0723/141143.820051:ERROR:v8_initializer.cc(789)] V8 javascript OOM (CALL_AND_RETRY_LAST).

Jul 23 14:11:43 my-hostname kernel: traps: stretchly[45061] trap int3 ip:557bd111195f sp:7ffceebeb030 error:0 in stretchly[557bd0b2c000+8009000]
░░ This usually indicates a programming error in the crashing program and
```

14:38 stretchly log:
```
[2024-07-23 14:36:16.132] [info]  Stretchly: postponing Mini Break
[2024-07-23 14:38:16.405] [info]  Stretchly: showing window 2 of 2
[2024-07-23 14:40:46.515] [info]  Stretchly: finishing Mini Break (shouldPlanNext: true)
```

[journalctl2.txt](https://github.com/user-attachments/files/16353126/journalctl2.txt)
[core_dump.txt](https://github.com/user-attachments/files/16353046/core_dump.txt)

**Comment by hovancik** [comment]
@Zinkelburger is it still the same? I wonder whether new Stretchly version with newer electron did help.

**Comment by Zinkelburger** [comment]
Seems like it went away! I'll reopen if I see it, but looks good so far.
