### ISSUE TITLE
[Bug]: RTL glitches and i18n missing strings

### ISSUE THREAD

**Issue by yarons** [hovancik/stretchly#1428]
### Version

- [x] I'm using version 1.15.1

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.2.1

### Reproduction steps

1. Switch to Hebrew or Arabic
2. Open the preferences

**Reproduces how often:** Always

### Expected Behavior

Should align neatly

### Actual Behavior

Some elements misbehave and some are not translated

The top bar is aligned to the left.
The text under the heart icon is LTR.
The words seconds and minutes are untranslated.
The speaker icon is too close to the text.

### Additional information

<img width="712" alt="Screenshot 2024-01-30 at 9 54 56" src="https://github.com/hovancik/stretchly/assets/406826/436a3ba6-1f50-482b-aa4a-425b9de0e95c">
<img width="712" alt="Screenshot 2024-01-30 at 9 55 01" src="https://github.com/hovancik/stretchly/assets/406826/048744f6-6d46-4336-81e0-aed071a00388">
<img width="712" alt="Screenshot 2024-01-30 at 9 55 06" src="https://github.com/hovancik/stretchly/assets/406826/e055cd7f-50a6-4633-afc4-20755e9ec374">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, 

translations are community effort, you can help here: https://hosted.weblate.org/projects/stretchly/

Unfortunately, I don't speak Hebrew or Arabic so not sure how it should look like. PRs would be appreciated.

**Comment by yarons** [comment]
@hovancik I am translating this project already :)
The problem is the RTL alignment and the fact that these terms are translated yet appear in the native language regardless, as you can see in the screenshots.

**Comment by hovancik** [comment]
Gotcha, the syncing process to the app is manual, so new translations appear once I make a new version.

**Comment by yarons** [comment]
Hmmm I highly doubt that, this string was translated around 2 years ago:
https://hosted.weblate.org/translate/stretchly/stretchly/he/?q=minutes&sort_by=-priority%2Cposition&checksum=#history
And it was submitted to the repository:
https://github.com/hovancik/stretchly/blob/7038e073e6048f6f55a292595fbdef01eec2e334/app/locales/he.json#L205
It looks like an i18n issue, I can't verify it with other languages but it does look like it.

**Comment by hovancik** [comment]
Seems like we have it wrong? 

```
    "minutes_one": "דקה",
    "minutes_two": "{{count}} דקות",
    "minutes_many": "{{count}} דקות",
    "minutes_other": "{{count}} דקות",
 ```

This https://jsfiddle.net/6bpxsgd4 suggests it should be `_one, _two, _other`. But not sure why extra element would be an issue.

**Comment by hovancik** [comment]
Ah, other languages have the same issue, will try to look at it. Do you remember if this was issue as well in previous versions?

**Comment by hovancik** [comment]
So it seems it's not issue with i18next but with how I am refreshing translations after changing language. Can you try hitting Cmd+R after changing the language? For me I can see correct translations then: 

![image](https://github.com/hovancik/stretchly/assets/4745859/358b823e-b7bb-4a85-9951-c922d8082820)

Or after Stretchly restarts / Preferences gets reopened

I have found the issue and made a quick fix.

**Comment by yarons** [comment]
Thank you!
What about the RTL glitches I've  mentioned?

**Comment by hovancik** [comment]
Could you please explain / show how the correct one should look like? It's hard for me to imagine what is wrong

```
The top bar is aligned to the left.
The text under the heart icon is LTR.
```

**Comment by yarons** [comment]
Settings should be rightmost, then Scheduling, Themes and About, while the support button should appear leftmost.

Regarding the text on the support button, this is the right form:
<div dir=rtl>תמיכה ב־Stretchly‏ (Starting from the right).</div>

The current wrong layout is:
‎תמיכה ב־Stretchly
It looks like Stretchly Support instead of vice versa.

Also the speaker is too close to the text in the Theme tab.

Thanks :)

**Comment by hovancik** [comment]
Thanks, regarding Support button, I guess translation should be changed? `"heart": "תמיכה ב־Stretchly",`

Others seems to fit: 
![image](https://github.com/hovancik/stretchly/assets/4745859/1eaeac4e-3810-4522-9b3c-e6234e756cd8)

**Comment by hovancik** [comment]
Ah, I think I found it. Is this correct? 

![image](https://github.com/hovancik/stretchly/assets/4745859/8da87ed2-fee0-4816-b9fc-f3ad83246859)

**Comment by yarons** [comment]
Great! It looks way better!
The "Preferred language" box has its combobox arrow aligned to the right instead of left but I think it's a small price to pay after all the great job you've been doing, thank you :)

**Comment by hovancik** [comment]
Thanks for all the feedback, I think I was able to fix the select as well :)

**Comment by yarons** [comment]
Thank you so much!

One last thing that I've noticed and I'm not sure it's possible to fix without setting the whole system to RTL:
![תמונה](https://github.com/hovancik/stretchly/assets/406826/c537a9f6-e668-4193-8917-77d0818bffa3)

The menus are left aligned on mac.

**Comment by hovancik** [comment]
This is what I see on Linux, but no idea what the correct way is:
![image](https://github.com/hovancik/stretchly/assets/4745859/eaae491c-9fb5-4c5e-88ee-2fc9ee47055c)
From what I read in Electron docs, there is no such an option in Menus :(
