### ISSUE TITLE
[Feature request]:  Customize message withou json

### ISSUE THREAD

**Issue by wilco6** [hovancik/stretchly#1440]
### Version

- [X] I'm using version 1.15.1

### Existing requests

- [X] I've checked Existing requests

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### Problem description

I find myself routinely messing up the JSON file when I try to modify messages. Possibly because Stretchly is mixing something up if I modify when it's not fully exited. I'd like a better way to change messages, either built in to software options or robustness when both editing and having app open.

### Possible solution

Please fix the JSON or whatever is causing the issue, or add a tab that allows editing of messages.

### Alternative solutions

I don't really see one. It's the 50 default messages are well though out but not for everyone. Combing through the JSON and hoping not to erase the wrong code isn't the most user-friendly.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by warrnmtl** [comment]
I've tried once more and with a fresh JSON and managed to get it to work. But it really is a pain having to check every comma and apostrophe just to modify the built-in alerts.

**Comment by hovancik** [comment]
Hi, sorry to hear about the troubles you had :( 

Unfortunately, I work on this in my free time, which is limited, so I have to carefully choose what I work on and what I don't. 
Right now, it's best to always check the formatting of JSON with some tool like https://jsonformatter.curiousconcept.com/

**Comment by wilco6** [comment]
Hi Jan,

Thank you so much! I'm sorry I know my post was rude and I wanted to delete
it. I had just worked 12 hours straight and was frustrated.

Anyway, thank you for taking the time to reach out. Your app is really
wonderful and has been a great help. I think I've supported before but at
least now I can message you that as well

Have a great day or evening,
Michael
