### ISSUE TITLE
not possible?

### ISSUE THREAD

**Issue by raptor59** [hovancik/stretchly#145]
Hello, so if i want to have a 5 min microbreak every 25 minutes and then 15 min restbreak every hour - i cannot configure it with Stretchly? Seems pretty limiting!

**Comment by hovancik** [comment]
so if I understand you want this: ? 
-> time is 0 
-> after 25 minutes -> 5 minutes break -> (time is 30 minutes)
-> after 25 minutes -> 5 minutes break  -> (time is one hour) -> start 15 minutes break

So basically you would have 5 minute break after first 25 minutes and then 20 minutes break after another 25 minutes?

**Comment by hovancik** [comment]
Closing this as a possible non-issue. Let me know if you still need help.
