### ISSUE TITLE
[Feature request]: Shortcut to Pauze breaks for a period

### ISSUE THREAD

**Issue by tomgoos** [hovancik/stretchly#1457]
### Version

- [X] I'm using version 1.15.1

### Existing requests

- [X] I've checked Existing requests

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Problem description

I would like to set a shortcut key for the Pauze breaks options. If I have a meeting or I am talking someone through something I have on screen it is convenient to Pauze the breaks for a while. It would be cool if this could be done using a keyboard shorcut
![image](https://github.com/hovancik/stretchly/assets/131454199/8949039b-7d0b-45bb-80b5-67bbbf1c5538)

### Possible solution

E.g add options
 `"pauseBreaks30mToggleShortcut": "",`
 `"pauseBreaks1hToggleShortcut": "CmdOrCtrl+P",`
 `"pauseBreaks2hToggleShortcut": "",`
 `"pauseBreaks5hToggleShortcut": "",`

or alternatively add option:
`"pauzeBreaksPostponeTime": 120000,`
(Use "" for infinite)
To use in combination with the existing
`"pauseBreaksToggleShortcut": "CmdOrCtrl+P",`

### Alternative solutions

I am now using `"pauseBreaksToggleShortcut": "CmdOrCtrl+P",`
The drawback is that I may forget to turn it on again.

### Additional information

Thanks for your consideration! Great tool!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi there and thanks for the feedback. I like the first solution you described, I think it makes more sense then to configure pause time. If anyone wants to contribute, this should be easily done.

**Comment by evgenyneu** [comment]
Hi @hovancik, can I work on this please?

**Comment by hovancik** [comment]
@evgenyneu sure thing :) how would you like to implement it? (in a sense: let's agree on solution first, then do the coding part :) )

**Comment by evgenyneu** [comment]
Sure, are you still in favor of this solution proposed by @tomgoos?

```
"pauseBreaks30mToggleShortcut": "",
"pauseBreaks1hToggleShortcut": "CmdOrCtrl+P",
"pauseBreaks2hToggleShortcut": "",
"pauseBreaks5hToggleShortcut": "",
```

**Comment by hovancik** [comment]
Yeah I think adding those to `pauseBreaksToggleShortcut` makes the most sense. Plus `untilMorning` could also be added.

**Comment by evgenyneu** [comment]
Makes sense, so it matches as the Pause Breaks menu. Ok, I'll do that then! 👍
