### ISSUE TITLE
[Bug]:   I can skip the restricted mode

### ISSUE THREAD

**Issue by gestshb** [hovancik/stretchly#1464]
### Version

- [X] I'm using version 1.15.1

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

macOS

### Operating System Version

MacOS ventura

### Reproduction steps

I appreciate the strict mode in your app as it encourages me to take necessary breaks. However, I found a way to bypass this restriction by putting my iMac to sleep using the power button and then waking it up again. This allows me to terminate the break prematurely.

### Expected Behavior

The strict mode feature in the app should enforce break periods without allowing users to bypass the restriction. Putting the iMac to sleep and waking it up again should not terminate the break prematurely. The app should maintain the break period regardless of the device's sleep status, ensuring that users take the necessary breaks as intended.

### Actual Behavior

When using the strict mode feature in the app, I discovered a way to bypass the enforced break periods. By putting my iMac to sleep using the power button and then waking it up again, the app prematurely terminates the break. This allows me to resume work without completing the required break period.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, by default, the breaks get reset when user closes the lid. You can change that behavior with [advanced preferences](https://github.com/hovancik/stretchly?tab=readme-ov-file#advanced-preferences), specifically with [Pause breaks on Suspend/Lock](https://github.com/hovancik/stretchly?tab=readme-ov-file#pause-breaks-on-suspendlock-). It is not that reliable, though.

**Comment by gestshb** [comment]
Thank you, that was really helpful!

**Comment by hovancik** [comment]
great, I will close this, then :)
