### ISSUE TITLE
[Feature request]: Allow changing to a custom background color based on user-specified HEX code like #3B3B3B for example

### ISSUE THREAD

**Issue by adrummer354** [hovancik/stretchly#1465]
### Version

- [X] I'm using version 1.15.1

### Existing requests

- [X] I've checked Existing requests

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

Linux

### Operating System Version

Linux Mint Cinnamon 21.3 Edge

### Problem description

A clear and concise description of what the problem is.
Ex. I'm always frustrated when [...]

### Possible solution

I like the application but would love to see the option to be able to change the background color to my specific color preference based on hexadecimal to match my OS theme color exactly  

### Alternative solutions

Add option under Preferences>Theme>Appearance to input my own color based on HEX value rather than just pick from the 5 options in the menu. Keep transparency with this color

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
You can do that :) https://github.com/hovancik/stretchly?tab=readme-ov-file#advanced-preferences
