### ISSUE TITLE
[Feature request]: Enable user to add screen messages during breaks

### ISSUE THREAD

**Issue by DanijelDomazet** [hovancik/stretchly#1467]
### Version

- [X] I'm using version 1.15.1

### Existing requests

- [X] I've checked Existing requests

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

Linux

### Operating System Version

22

### Problem description

Would be great to enable users to add their own messages. This could be fun, and lead to some very amusing stuff...

Great app!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, you can do that by editing advanced preferences: https://github.com/hovancik/stretchly?tab=readme-ov-file#advanced-preferences
