### ISSUE TITLE
[Bug]:   "Monitor system idle time (breaks are paused if system is idle). Prevents from taking long breaks

### ISSUE THREAD

**Issue by Karim-KM** [hovancik/stretchly#1469]
### Version

- [X] I'm using version 1.15.1

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

Windows

### Operating System Version

Windows10

### Reproduction steps

When I just Select "Monitor system idle time" feature

### Expected Behavior

It should give me long break after 4-time mini breaks. 

### Actual Behavior

It starts over from remaining 4-mini breaks again. Without giving me a full break. 
![image](https://github.com/user-attachments/assets/aa77eda8-01bf-424c-8570-d016b39300e0)

### Additional information

I selected the "Monitor system idle time" feature, which pauses breaks during inactivity. However, this option is resetting my mini-break progress. For example, after completing two mini breaks, it starts counting from three or four again. This happens all the time! So, I can't have a full-time break unless I removed this option. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi and thanks for the feedback. It is indeed how Stretchly currently works. I hope to change this, but as it will be bigger change, not sure when I will find time to do that. Please follow #1248  for updates.
