### ISSUE TITLE
[Feature request]: Run on startup  from windows apps

### ISSUE THREAD

**Issue by itszaki01** [hovancik/stretchly#1471]
### Version

- [X] I'm using version 1.15.1

### Existing requests

- [X] I've checked Existing requests

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

Windows

### Operating System Version

10

### Problem description

please add run on startup automaticly

### Possible solution

please add run on startup automaticly

### Alternative solutions

please add run on startup automaticly

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, how did you install? Regular installer has this functionality. If you installed from Windows Store, unfortunatelly there is a bug in library I use and I am waiting for fix

**Comment by itszaki01** [comment]
you are right the regular installer is working normally i saw this problem because i installed it from Windows apps

**Comment by iNgeon** [comment]
> Hi, how did you install? Regular installer has this functionality. If you installed from Windows Store, unfortunatelly there is a bug in library I use and I am waiting for fix

Currently havin this same issue (27Sep2025). Stretchly does not start even though its in the startup list
Installed via Windows 10 10 Pro 10.0.19045 Build 19045 Stretchly v1.18.0.0 via Windows Store

<img width="816" height="160" alt="Image" src="https://github.com/user-attachments/assets/d0786d21-c081-4a5a-bbd2-a53e4a732e90" />

**Comment by hovancik** [comment]
hi, I don't have Windows 10 to try, but I think this should work, part " Add a Shortcut to Your Startup Folder (For Any App) " https://www.howtogeek.com/364263/how-to-open-windows-store-apps-on-startup-in-windows-10/
