### ISSUE TITLE
[Feature request]: More legible remaining time in tray icon

### ISSUE THREAD

**Issue by Wikiwix** [hovancik/stretchly#1478]
### Version

- [X] I'm using version 1.15.1

### Existing requests

- [X] I've checked Existing requests

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2

### Problem description

I have a hard time reading the number (for the remaining time to the next pause) in the tray icon.

### Possible solution

- Offer an option that does not have the Stretchly icon in the background
- Use a more legible font (e.g. make it bolder)
- Improve contrast between icon and font

### Alternative solutions

See possible solution, I added multiple options there

### Additional information

I checked the source code (too see if there is something I can do), but I did not find any script that created the many number variation icons (I guess those where created with some automation)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, icons were added by contributor, so not sure whether done manually or by some script.

**Comment by Wikiwix** [comment]
So [the script](https://github.com/senpl/stretchly/blob/e0830cb56989f1b9b46ee715b68a83b9a43ab4df/app/utils/trayWithText.js) that created the icons seems to be available in the [PR's](https://github.com/hovancik/stretchly/pull/957/) history.

**Comment by hovancik** [comment]
@Wikiwix could you please post the screenshot? what specific color scheme combinations do you use?

**Comment by hovancik** [comment]
I've recreated images so if you could test if that is better for you, it would be nice (if you can run from source)

**Comment by Wikiwix** [comment]
> @Wikiwix could you please post the screenshot? what specific color scheme combinations do you use?

I use the dark icons (on a light Windows 11 setup), see the screenshots below

I will check whether I am able to run from source :)

![image](https://github.com/user-attachments/assets/d2bea70a-64e0-4089-91f2-dceac9063c4b)

![Screenshot 2024-10-19 202811](https://github.com/user-attachments/assets/71eb3352-817e-40d9-bdab-6ccacd80ba23)

**Comment by Chealer** [comment]
This should apparently be solved in 1.17.0, but as discussed in ticket #1194, the time seems to be missing as of 1.17.2.
