### ISSUE TITLE
Feature request | show time remaining for next break in menubar

### ISSUE THREAD

**Issue by mohamed-osama-aboelkheir** [hovancik/stretchly#148]
It would be cool, if the time remaining for the next break can be shown in the menu bar.

**Comment by hovancik** [comment]
Hi, time remaining for next break is show as tray tooltip. What platform are you on? 


![stretchly-tray-3](https://user-images.githubusercontent.com/4745859/32038306-816e15c4-ba29-11e7-9fd0-d6c7492ad747.png)


It's working on Windows and Linux, but on mac there is an [electron bug](https://github.com/electron/electron/issues/9447), so there's nothing I can do about it.

**Comment by mohamed-osama-aboelkheir** [comment]
Thanks Jan for the quick response.

I am on Mac. What i meant is that it would be cool If you can see the time
remaining without having to move the mouse to the icon. something like the
below screenshot from the "Be focused" pomodoro app.


​
Best Regards,
Mohamed AboElKheir

**Comment by hovancik** [comment]
could you please attach the screenshot from github interface? it's now shown when replying via email.

**Comment by mohamed-osama-aboelkheir** [comment]
Screenshot attached ![screen shot 2017-10-26 at 8 51 05 am](https://user-images.githubusercontent.com/7032838/32091648-5df903c0-baf5-11e7-8510-61e502c2a5e1.png)

**Comment by xim** [comment]
As onhover tooltips isn't a part of normal OS X user interactions, I'd recommend adding another way of bringing the same text up. The same for at least some Linux window managers.

On my system, Cisco Proximity, Airplay and Wi-Fi all use a disabled option as the first menu item. Screenshot of those:
![screen shot 2017-11-18 at 20 57 27](https://user-images.githubusercontent.com/169057/32984246-515268fe-cca3-11e7-9930-e236632a7df1.png)
![screen shot 2017-11-18 at 21 01 15](https://user-images.githubusercontent.com/169057/32984275-acdc668e-cca3-11e7-955d-678bbec5afb2.png)
![screen shot 2017-11-18 at 21 01 58](https://user-images.githubusercontent.com/169057/32984279-c407bbec-cca3-11e7-9f23-f2fadd19a77e.png)

**Comment by hovancik** [comment]
I'll check how would it work. Thanks for the idea!

**Comment by hovancik** [comment]
So what I would add is: 

first item in menu is and is disabled as mentioned previously: 

```
next {type of break} in {time}
paused for {time/indifinetly}
``

**Comment by BradKML** [comment]
@hovancik @mohamed-osama-aboelkheir first I would like to note that https://splode.github.io/pomotroid/ exists (for reference only)
Secondly, is it possible to do the same for Windows, except as a transparent overlay on-screen at the corner?

**Comment by hovancik** [comment]
There's a PR to add time to break to tray icon: #957 
<img width="332" alt="image" src="https://user-images.githubusercontent.com/4745859/125411551-4ec8b580-e3be-11eb-9d38-557c1ea09f47.png">
