### ISSUE TITLE
[Bug]:   

### ISSUE THREAD

**Issue by raccoonyy** [hovancik/stretchly#1480]
### Version

- [X] I'm using version 1.16

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.6.1 (23G93)

### Reproduction steps

1. On macOS Sonoma 14.6.1
2. Run Stretchly
...
**Reproduces how often:** [What percentage of the time does it reproduce?] 100%

### Expected Behavior

Works well.

### Actual Behavior

It is broken after the macOS update. :(

<img width="319" alt="image" src="https://github.com/user-attachments/assets/3b159cac-8e19-4eb5-9942-66f286e60427">

### Relevant log output

```shell
brew info stretchly
==> stretchly: 1.16.0
https://hovancik.net/stretchly/
Installed
/opt/homebrew/Caskroom/stretchly/1.16.0 (310.4MB)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/s/stretchly.rb
==> Name
Stretchly
==> Description
Break time reminder app
==> Artifacts
Stretchly.app (App)
==> Caveats
This application is not signed. For details see:

https://github.com/hovancik/stretchly#application-signing

==> Analytics
install: 506 (30 days), 955 (90 days), 3,682 (365 days)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, how did you install? As the link provided by brew states (https://github.com/hovancik/stretchly#application-signing), Stretchly is not signed and need to be installed with `brew install --cask --no-quarantine stretchly`

**Comment by raccoonyy** [comment]
@hovancik Hi. I used this command.
```
brew install --cask --no-quarantine stretchly
```

But I tried remove Stretchly and install again. It works! 

Thanks! 

I'll try to find some time to contribute to the Korean translation as well. :)
