### ISSUE TITLE
[Feature request]: Add Greek Language support

### ISSUE THREAD

**Issue by csandreas1** [hovancik/stretchly#1481]
### Version

- [X] I'm using version 1.16

### Existing requests

- [X] I've checked Existing requests

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

Windows

### Operating System Version

windows 11

### Problem description

Add support for greek language after weblate completion

### Possible solution

![image](https://github.com/user-attachments/assets/279299b5-20fc-42b9-924b-f49249d76a7b)

### Alternative solutions

Add support for greek language

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Thanks, I will add it :) It will appear in app in next release (it will take some time as 1.16 was recently)

**Comment by csandreas1** [comment]
can I make a pr to add it?
Maybe i can follow this logic: add Latvian language by darksworm · Pull Request #869 · hovancik/stretchly (github.com)<https://github.com/hovancik/stretchly/pull/869/files>
[https://avatars.githubusercontent.com/u/9987548?s=400&v=4]<https://github.com/hovancik/stretchly/pull/869/files>
add Latvian language by darksworm · Pull Request #869 · hovancik/stretchly<https://github.com/hovancik/stretchly/pull/869/files>
Issue: #868 Requirements Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers&#39; di...
github.com

________________________________

**Comment by hovancik** [comment]
Sorry just added it as more languages needed adding and fix Welcome window but feel free to check whether it's OK: #

![image](https://github.com/user-attachments/assets/4b4a5d50-89f5-4db8-b501-38af9e199f1a)

**Comment by csandreas1** [comment]
perfect! When to expect the next release?
________________________________

**Comment by hovancik** [comment]
Hi, it will take some time as 1.16 was short time ago, so probably few months. (Until I make some more changes)
