### ISSUE TITLE
[Bug]:   Support macOS Sequoia

### ISSUE THREAD

**Issue by minhdanh** [hovancik/stretchly#1484]
### Version

- [ ] I'm using version 1.16

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

macOS

### Operating System Version

macOS Sequoia 15.0

### Reproduction steps

I upgraded stretchly with latest version using:
```
brew upgrade --cask
```
Then open it. There's no icon displayed on the task bar of macOS.
This error message is displayed when it's time for the rest:
![image](https://github.com/user-attachments/assets/64b909be-ef19-4d9d-a874-bd4c8820c7a0)

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Expected Behavior

Stretchly 

### Actual Behavior

Can open stretchly and see the icon displays in task bar

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, error message suggest there should be some more info in logs, can you check? 

If I remember correctly, something like `~/Library/Logs/Stretchly/main.log`

I don't have Mac device

**Comment by minhdanh** [comment]
[main.log](https://github.com/user-attachments/files/17038018/main.log)
Here it is

**Comment by hovancik** [comment]
Did you close Stretchly before updating it? From logs it seems you did not. Can you try closing it and starting again?

**Comment by minhdanh** [comment]
I see. I closed it and started it again and it is working now. Thank you. I'm closing this issue.
