### ISSUE TITLE
[Bug]:   Outdated Microsoft Store app

### ISSUE THREAD

**Issue by fkoemep** [hovancik/stretchly#1486]
### Version

- [ ] I'm using version 1.16

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2 64 bits

### Reproduction steps

Install Stretchly from Microsoft Store https://apps.microsoft.com/detail/9pp2b76lqqbn

### Expected Behavior

The version downloaded is 1.16.0

### Actual Behavior

The version downloaded is 1.15.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Thanks! Their UI is superconfusing and I have missed some button I needed to hit to submit the new package. Done that now so hopefully in a day or two it's out!

**Comment by hovancik** [comment]
Just got message: "Good news. Your submission for the app stretchly has been processed. Access your app in the Microsoft Store."
