### ISSUE TITLE
[Feature request]: disable CTRL+X to close

### ISSUE THREAD

**Issue by Chuck-RT** [hovancik/stretchly#1487]
### Version

- [X] I'm using version 1.16

### Existing requests

- [X] I've checked Existing requests

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro

### Problem description

It would be helpful if we can disable CTRL+X shortcut that closes the Breaks
Sometimes Im still working on something important and I close the window by accident when cutting/pasting files

### Possible solution

Add an option in Preferences if possible

### Alternative solutions

With this option we can select if we want to use this shortcut or not

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, this is available in config file: 

https://github.com/hovancik/stretchly?tab=readme-ov-file#postponefinish-break-shortcut
https://github.com/hovancik/stretchly?tab=readme-ov-file#advanced-preferences

**Comment by Chuck-RT** [comment]
Hi, cahnging the Value cause a crash when the timer ends or if the break is manually skipped
![image](https://github.com/user-attachments/assets/9502a71c-4921-4386-8d08-a0e2b8545e6f)

**Comment by hovancik** [comment]
Did you stop the app before making change?

**Comment by Chuck-RT** [comment]
Yes, I attach the Log if theres something you can find
[main.log](https://github.com/user-attachments/files/17120727/main.log)

**Comment by hovancik** [comment]
Found the issue, thanks :)

**Comment by hovancik** [comment]
Until new version is out (which might take time), I would suggest changing to some valid value but something that will not bother you.

**Comment by Chuck-RT** [comment]
Ok, I have tried with Shift+X and everything works ok, thanks!!!!
