### ISSUE TITLE
[Feature request]: Remember breaks after Do Not Disturb pause

### ISSUE THREAD

**Issue by dkaszews** [hovancik/stretchly#1493]
### Version

- [X] I'm using version 1.16

### Existing requests

- [X] I've checked Existing requests

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Enterprise 10.0.22631 Build 22631

### Problem description

I like using the Do Not Disturb (DND) detection to prevent Stretchy breaks obscuring my screen during meetings, but it resets the breaks every time it unpauses. This means that if I have long breaks set to once an hour, but every 30 minutes or so enter DND for even a minute (short call, sharepoint fullscreen, etc), I will never actually get a long break. 

### Possible solution

Provide setting to remember breaks after DND ends, that is resume timers/counters from the state they were in when DND started. 

### Alternative solutions

Have DND only prevent breaks from appearing, but keep the timers running. That is, if I have 30 minutes till a long break, and enter DND for 10 minutes, then after exiting it I should be 20 minutes away from a long break. If time to long break goes below zero, it should trigger immediately after exiting DND. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi this is related to #1248. Please follow there for updates.
