### ISSUE TITLE
[Bug]:   Stretchly menu item not visible on Macos Sequoia 15.0.1 (24A348) 

### ISSUE THREAD

**Issue by duffysk** [hovancik/stretchly#1494]
### Version

- [X] I'm using version 1.16

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

macOS

### Operating System Version

MacOS Sequoia 15.0.1 (24A348)

### Reproduction steps

When I start Stretchly, it is running (invoking regular breaks) but no Menu bar icon visible, impossible to get to preferences.

### Expected Behavior

Menu bar icon visible.

### Actual Behavior

Menu bar icon not visible.

### Relevant log output

```shell
NA
```

### Preferences

```shell
NA
```

### Additional information

NA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
is this after macOS update? 

I guess apple changed something and electron is not ready for this

**Comment by duffysk** [comment]
Yes, after an update.

**Comment by joanna-kocot** [comment]
I confirm the same issue after update to Sequoia. Stretchly doesn't start with the system, when started manually it functions ok for some time, but may crash after several hours. I can check logs when it happens next time, but I don't know where to look for them - is there a way to check them from the app or I should look somewhere in the system files?

**Comment by hovancik** [comment]
Probably some change in macOS that ElectronJS needs to catch up with. 

Logs are located in sth like `~/Library/Logs/Stretchly/main.log`

**Comment by joanna-kocot** [comment]
Ok, so I've got a couple of these errors:

```
[2024-10-15 19:33:38.524] [error] TypeError: Cannot read properties of null (reading 'showInactive')
    at IpcMainImpl.<anonymous> (/Applications/Stretchly.app/Contents/Resources/app.asar/app/main.js:891:23)
    at Object.onceWrapper (node:events:634:26)
    at IpcMainImpl.emit (node:events:531:35)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:83159)
    at WebContents.emit (node:events:519:28)
```

Happening after either `Stretchly: Long Break window loaded` or `Stretchly: Mini Break window loaded`

**Comment by hovancik** [comment]
So I managerd to upgrade my old macbook with OpenCore Patcher to Sequoia, but I do not see any issues, all is fine for me. 

Have you tried reinstalling Stretchly?

**Comment by joanna-kocot** [comment]
I think the problem was fixed with one of the system updates. I have Sequoia 15.1 now, and Stretchly works correctly (I didn't reinstall it, just updated the system).

**Comment by hovancik** [comment]
Thanks, closing then :)

**Comment by duffysk** [comment]
I can confirm the same. Working well with 15.1.
