### ISSUE TITLE
[Bug]:   White flash before every break

### ISSUE THREAD

**Issue by adamshand** [hovancik/stretchly#1506]
### Version

- [X] I'm using version 1.16

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.5

### Reproduction steps

1. Manually trigger a break or wait for a break
2. Before the break screen shows, the entire screen flashes white
...
**Reproduces how often:** 100%

https://github.com/user-attachments/assets/4356a51b-c6a3-48e9-98ae-49a6cc1ef7d6

### Expected Behavior

When working at night, the white flash is quite startling and unpleasant (especially when working on a large monitor).  

I don't mind the minor delay, but would love if the temporary screen was a dark colour.

I'm not sure why, but the actual effect is more pronounced than the below video shows.  Perhaps because it fades from the white to the background colour which isn't shown in the screen capture?

Thanks for the great app!

### Actual Behavior

.

### Preferences

```shell
.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi this is issue with electron: 

https://github.com/electron/electron/issues/42523
https://github.com/electron/electron/issues/44371

I have some workarounds in place (I don't see this issue on my Linux machine for example) but obviously they are not 100% :(

**Comment by adamshand** [comment]
Thanks, will hope for the best with the upstream bugs!
