### ISSUE TITLE
An option to disable update check

### ISSUE THREAD

**Issue by Oreolek** [hovancik/stretchly#151]
*Yes, I know there was a new release 2 days ago, I don't need to be reminded every system start about it*

**Comment by hovancik** [comment]
Thanks for the feedback! 

How do you imagine that would work?

**Comment by Oreolek** [comment]
maybe "Turn the notifications off for 1 month" or "forever" checkbox?
Ideally, there's a repository so the user doesn't have to care about updates.

**Comment by hovancik** [comment]
I've decided to allow this via editing config file. I'm trying to make as less config options in "Settings" as possible and also from my point of view it makes sense to "force" users to update to the latest version. 

Upon editing config file, there will be no more notification about new version, only the option in tray menu.
