### ISSUE TITLE
[Bug]:   Unable to install on android 

### ISSUE THREAD

**Issue by Jatingehlot05** [hovancik/stretchly#1521]
### Version

- [X] I'm using version 1.16

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

Other (specify below)

### Operating System Version

Android 12

### Reproduction steps

Tried both normal .apk file and also tried arm64 apk file both are unable to install 
...
**Reproduces how often:** 100%

### Expected Behavior

I should be installed without any error 

### Actual Behavior

It says "problem while phrasing the package"
On installing 

INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed to parse /data/app/vmdl530311231.tmp/0.apk: AndroidManifest.xml
![Screenshot_2024-12-18-12-30-03-236_com xapkinstaller imod](https://github.com/user-attachments/assets/57221e04-b2c9-4c3f-b94d-a813b100a926)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi @Jatingehlot05 , the APK packages are not for Android, but for the Alpine Linux. There is no Android version.
