### ISSUE TITLE
[Bug]: Location of settingsFile reported incorrectly when installed through Microsoft Store

### ISSUE THREAD

**Issue by frankkusters** [hovancik/stretchly#1524]
### Version

- [X] I'm using version 1.16

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

Windows

### Operating System Version

Windows 11 version 23H2

### Reproduction steps

1. Install Stretchly from the Microsoft Store (https://apps.microsoft.com/store/detail/stretchly/9PP2B76LQQBN?hl=en-us&gl=us)
2. Go to Stretchly Preferences > About.
3. Hit CTRL+D, it shows the `settingsFile` location.

**Reproduces how often:** Always

### Expected Behavior

I would expect to be able to edit `config.json` using the `settingsFile` link.

### Actual Behavior

4. Observe that the reported location is `C:\Users\$USER\AppData\Roaming\Stretchly\config.json`
5. When clicking the link, the text editor reports that the file does not exist. I verified in Explorer that it indeed doesn't exist.
6. The `logsFile` has the same problem.

### Additional information

Apparently, [Windows 11 can install apps sandboxed](https://www.reddit.com/r/Windows11/comments/1b1ewl9/is_there_a_difference_installing_apps_through_the/), providing a virtual filesystem to the app. The virtual filesystem is accessible, but it takes quite some hoops to jump through: https://superuser.com/questions/1519617/windows-10-sandbox-how-do-i-access-my-files-in-the-sandboxed-environment-of-my

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi @frankkusters and thanks for the report! 

In my case, the file seems to be located here `"C:\Users\user\AppData\Local\Packages\33881JanHovancik.stretchly_24fg4m0zq65je\LocalCache\Roaming\Stretchly\config.json"`

I will try figure out this, but not sure why it points to wrong location in Preferences.

**Comment by frankkusters** [comment]
> I will try figure out this, but not sure why it points to wrong location in Preferences.

I have a hard time finding more information on the Microsoft sandbox, but if it is even remotely similar to [chroot](https://en.wikipedia.org/wiki/Chroot), then there is no way for the process to figure out the 'real' location of files. That's mostly the point of a sandbox. Although you never know, there might be an API for it.

**Comment by hovancik** [comment]
I have found this issue, which suggest Electron team won't fix this: https://github.com/electron/electron/issues/39636

**Comment by hovancik** [comment]
Note to self: 

```C:\Users\$USER\AppData\Roaming\Stretchly\config.json```
```C:\Users\$USER\AppData\Local\Packages\33881JanHovancik.stretchly_24fg4m0zq65je\LocalCache\Roaming\Stretchly\config.json```

I guess when Win Store is detected, we can just replace the string.

**Comment by hovancik** [comment]
@frankkusters you ever had Store version only? I think it behaves rather weirdly: 
- when you already have a regular installer / data in typical location, it uses that data
- when ever installed from store only, it uses that other location

**Comment by hovancik** [comment]
I could check whether the location exists but as there is that fuckery with file system, that would not work as expected. Not sure if there is a way to figure out which location it uses ;/

**Comment by hovancik** [comment]
So I am just gonna use the version of file "user never ever installed regular installer and just used Windows Store". That's probably gonna be majority.

**Comment by frankkusters** [comment]
> [@frankkusters](https://github.com/frankkusters) you ever had Store version only? I think it behaves rather weirdly:
> 
> * when you already have a regular installer / data in typical location, it uses that data
> * when ever installed from store only, it uses that other location

This was on a new laptop. Although I have been using Stretchly for a few years now. :blush: Thank you for the great tool!

> So I am just gonna use the version of file "user never ever installed regular installer and just used Windows Store". That's probably gonna be majority.

Thanks for the update. It works.
