### ISSUE TITLE
[Bug]:  Tray menu opens in Strict mode (it shouldn't)

### ISSUE THREAD

**Issue by jeregon1** [hovancik/stretchly#1527]
### Version

- [X] I'm using version 1.17

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 23H2

### Reproduction steps

1. Activate Strict Mode for both Mini and Long breaks
2. Try opening the menu from the tray icon

**Reproduces how often:** 100%

### Expected Behavior

It shouldn't open because "showTrayMenuInStrictMode" is set to false by default (I've checked it).

### Actual Behavior

It lets me open regardless of whether I'm in strict mode or not

### Preferences

```shell
{
	"microbreakDuration": 30000,
	"microbreakInterval": 1200000,
	"breakDuration": 600000,
	"breakInterval": 2,
	"breakNotification": true,
	"microbreakNotification": true,
	"breakNotificationInterval": 60000,
	"microbreakNotificationInterval": 30000,
	"microbreak": true,
	"break": true,
	"microbreakStrictMode": true,
	"breakStrictMode": true,
	"morningHour": 6,
	"microbreakPostpone": false,
	"breakPostpone": true,
	"microbreakPostponeTime": 120000,
	"breakPostponeTime": 300000,
	"microbreakPostponesLimit": 1,
	"microbreakPostponableDurationPercent": 33,
	"breakPostponesLimit": 1,
	"breakPostponableDurationPercent": 1,
	"mainColor": "#1D1F21",
	"miniBreakColor": "#1D1F21",
	"transparentMode": false,
	"blurredBackground": false,
	"opacity": 0.9,
	"audio": "crystal-glass",
	"miniBreakAudio": "crystal-glass",
	"volume": 1,
	"fullscreen": true,
	"ideas": true,
	"naturalBreaks": true,
	"naturalBreaksInactivityResetTime": 900000,
	"allScreens": true,
	"useIdeasFromSettings": false,
	"language": "en",
	"notifyNewVersion": true,
	"isFirstRun": false,
	"posLatitude": 0,
	"posLongitude": 0,
	"useMonochromeTrayIcon": false,
	"useMonochromeInvertedTrayIcon": true,
	"silentNotifications": false,
	"monitorDnd": true,
	"microbreakStartSoundPlaying": false,
	"breakStartSoundPlaying": false,
	"themeSource": "system",
	"endBreakShortcut": "CmdOrCtrl+X",
	"breakWindowWidth": 0.85,
	"breakWindowHeight": 0.85,
	"checkNewVersion": true,	
        "showBreaksAsRegularWindows": false,
	"appExclusions": [],
	"appExclusionsCheckInterval": 1000,
	"pauseForSuspendOrLock": true,
	"pauseBreaksToggleShortcut": "",
	"pauseBreaksFor30MinutesShortcut": "",
	"pauseBreaksFor1HourShortcut": "",
	"pauseBreaksFor2HoursShortcut": "",
	"pauseBreaksFor5HoursShortcut": "",
	"pauseBreaksUntilMorningShortcut": "",
	"screen": "primary",
	"timeToBreakInTray": true,
	"currentTimeInBreaks": true,
	"showTrayIcon": true,
	"skipToNextScheduledBreakShortcut": "Alt+Shift+S",
	"skipToNextMiniBreakShortcut": "",
	"skipToNextLongBreakShortcut": "",
	"resetBreaksShortcut": "",
	"showTrayMenuInStrictMode": false,
	"__internal__": {
		"migrations": {
			"version": "1.17.0"
		}
	}
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, works fine for me on Linux, will check later on Windows. 

Is this clean install or update? If update, did you turn-off Stretchly when updating? This causes troubles. I would try reinstalling and making sure Stretchly is not running.

**Comment by jeregon1** [comment]
At first it was update, but now I've tried clean install and it doesn't work either. Any logs I can provide you with?

**Comment by hovancik** [comment]
![image](https://github.com/user-attachments/assets/1c756bed-9223-4c3d-8250-21a0838674b3)
All works fine for me. Also when I try with your preferences. 

Only thing that comes to my mind, to be sure about this feature: menu disappears only *while* in break. At other times, it is available.

**Comment by jeregon1** [comment]
Omg! Sorry for the confusion, I thought it disappeared all the time hahaha, thanks for the quick response
