### ISSUE TITLE
Time between microbreaks

### ISSUE THREAD

**Issue by jt007** [hovancik/stretchly#153]
Suggestion for improvements: Would have been nice to be able to choose the length between microbreaks in the settings. Instead of the standard 10 minutes microbreaks, it would be practical to choose between 10, 15 or 20 minutes. 

Ps: I have chosen "silence" in the settings, and still there is a notification sound in addition to the visual notification. (version 0.12.0, windows 10.)

**Comment by sxmanton** [comment]
You already can adjust length between microbreaks, in 5 minute intervals, just use the buttons on either side of the length of time.

![settings_screenshot](https://user-images.githubusercontent.com/4335536/32907977-16b26eda-cad0-11e7-92cb-3f4d29fd0287.PNG)

I'm also on Windows 10, I'll look into whether I can reproduce the error with the silence mode not working.

**Comment by sxmanton** [comment]
Silence mode is working fine for me... I'm guessing that the notification sound you're talking about is not the stretchly sound, but the windows system notification sound.

https://www.isunshare.com/windows-10/turn-off-notification-sounds-on-windows-10.html

**Comment by jt007** [comment]
Thank you,  that worked:)

**Comment by hovancik** [comment]
thanks for helping @sxmanton ! 
@jt007 so this issue can be closed?

**Comment by jt007** [comment]
Yes, that solved the problem:)

**Comment by hovancik** [comment]
Ok, closing then ;]
