### ISSUE TITLE
[Bug]:  core dump on Ubuntu 24.04

### ISSUE THREAD

**Issue by mattmccormick** [hovancik/stretchly#1533]
### Version

- [X] I'm using version 1.17.1

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

Linux

### Operating System Version

Ubuntu 24.04

### Reproduction steps

1. Upgrade to 1.17.1 via package manager
2. Try to start Stretchly

...
**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Expected Behavior

Stretchly should start

### Actual Behavior

```
[6197:1226/085742.884248:FATAL:setuid_sandbox_host.cc(163)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/Stretchly/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)
```

I've verified that `chrome-sandbox` has the permissions setup as indicated in the error message:

```
-rwxr-xr-x 1 root root     38448 Dec 25 06:57 chrome-sandbox*
```

After downgrading to 1.16.0, I was able to launch Stretchly successfully again.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, seems like the error described here: https://github.com/hovancik/stretchly?tab=readme-ov-file#linux-note, part `If Stretchly is not starting, you might need to run:`

**Comment by mattmccormick** [comment]
Thanks, I ran that command and re-upgraded to 1.17.1 but I'm still getting the same error and Stretchly doesn't start.

**Comment by hovancik** [comment]
How did you install it again? I guess snap? 

Ubuntu is troublemaker :) Seems like this starting again lately and previous fix is not working: https://github.com/electron/electron/issues/17972#issuecomment-2551237520

**Comment by mattmccormick** [comment]
I'm using the `apt` repository https://apt.fury.io/hovancik/

Upgrade command
```shell
sudo apt upgrade
```

Downgrade command
```shell
sudo apt install stretchly=1.16.0
```

**Comment by hovancik** [comment]
Ok, thanks. I see some people also do `sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0`  https://github.com/toeverything/AFFiNE/blob/canary/.github/workflows/build-test.yml#L600

**Comment by mattmccormick** [comment]
Oh thank you!  That works for me.

**Comment by hovancik** [comment]
Great, I'll ad that to readme
