### ISSUE TITLE
Close windows using keyboard shortcut ({Cmd,Ctrl}+W)

### ISSUE THREAD

**Issue by xim** [hovancik/stretchly#154]
On OS X, Cmd+W is expected to close a window, this doesn't happen in any of the stretchly windows.

**Comment by sxmanton** [comment]
Stretchly uses Ctrl/Cmd + X to cancel the break window, assuming you have the options set to allow skipping breaks

**Comment by xim** [comment]
Ah, okay, it works on one window then. Would be nice if it worked on the settings / about dialogs as well.

**Comment by hovancik** [comment]
Ah, so `Cmd+W` is macOS specific shortcut? I'll check how electron deals with it.

**Comment by sxmanton** [comment]
I didn't fully understand the original issue, turns out Ctrl+W does not work to close the settings window in Windows either, so this isn't just a macOS issue.

**Comment by xim** [comment]
Just to specify, I only mentioned `Cmd+W` because I had only tested on OS X. Also, `Cmd+W` on OS X is an even more established shortcut on OS X than `Ctrl+W` is on Windows. But yes, `Cmd+W` should work on OS X and `Ctrl+W` should work on Windows / Linux.

**Comment by hovancik** [comment]
I believe `Cmd+W`in mac is the same as `Alt+F4` in windows. Linux would have something else, eg my XFCE has `Ctrl+W` to close tab and `Ctrl + Q` to close app

**Comment by hovancik** [comment]
Related: https://github.com/electron/electron/issues/5536

**Comment by sxmanton** [comment]
Alt+F4 is possibly more universal in Windows, but Ctrl+W works for most programs in windows, except in cases like where chrome overrides the shortcut to be close tab instead of close window.

**Comment by fttx** [comment]
You have to add an app menu like this to enable CMD+W, CMD+H, etc. on macOS
![image](https://user-images.githubusercontent.com/5663423/34905371-72db6cb6-f857-11e7-8a86-07d350248c92.png)

```
{
            label: app.getName(),
            submenu: [
                { role: 'about' },
                { type: 'separator' },
                { role: 'services', submenu: [] },
                { type: 'separator' },
                { role: 'hide' },
                { role: 'hideothers' },
                { role: 'unhide' },
                { type: 'separator' },
                { role: 'quit' }
            ]
        }
```

**Comment by hovancik** [comment]
Testing on Linux (Debian sid XFCE) 
 `ctrl+w` closes window
 `ctrl+q` closes app

Rebooting to macOS to test there
