### ISSUE TITLE
Stretchly app crashed. Unable to reinstall

### ISSUE THREAD

**Issue by jt007** [hovancik/stretchly#155]
I guess the app crashed because I chose to disable both the break features. I needed to do this temporarily. Then the app crashed, and I had to uninstall the whole app from the Windows 10 settings. When I try to reinstall it, I get this feedback. Please see enclosed printscreen file. 

[Stretchly printscreen.docx](https://github.com/hovancik/stretchly/files/1525032/Stretchly.printscreen.docx)

(windows 10, Stretchly 12.0)

**Comment by jt007** [comment]
Just in case you can't open the filetype, this is the text in the error message: 

[Window Title]
Error
[Main Instruction]
A JavaScript error occurred in the main process
[Content]
Uncaught Exception:
TypeError: Cannot read property 'plan' of null
    at BreaksPlanner.nextBreak (C:\Users\jontore\AppData\Local\Programs\stretchly\resources\app.asar\breaksPlanner.js:78:19)
    at App.loadSettings (C:\Users\jontore\AppData\Local\Programs\stretchly\resources\app.asar\main.js:247:16)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:194:7)
[OK]

**Comment by hovancik** [comment]
Hi, you can disable breaks for infinite time from tray menu, no need to disable both type of breaks. 

The quick fix for you would be to find `config.json` and make 
```
  microbreak: true,
  break: true,
```

Don't have any win 10, but should be in `%APPDATA%` (https://github.com/electron/electron/blob/master/docs/api/app.md#appgetpathname)

**Comment by sxmanton** [comment]
While the disable breaks is definitely the right way to accomplish the intended behavior, it would probably still be a good idea to add some null checks to safeguard against it crashing, possibly pulling in default values or something.

**Comment by hovancik** [comment]
Yeah, I'm planning to fix this, but I'm still working on translations right now. 

I guess the fix will be not allowing to disable both types of breaks.

**Comment by jt007** [comment]
Thanks, problem solved :)
