### ISSUE TITLE
Make a stretchly package for chocolatey

### ISSUE THREAD

**Issue by sxmanton** [hovancik/stretchly#156]
[Chocolatey](https://chocolatey.org/) is a package manager for windows kind of like apt on linux. It would be great if there was a package on it for Stretchly so that I don't have to manually download the installers for new ones. I'd be happy to help create the package and write some scripts to automate the process of publishing new chocolatey packages alongside new versions of Stretchly.

**Comment by hovancik** [comment]
Hi, I'm all in if it's easy to maintain. Saying that, I haven't had time to go through docs. So if you did, that would be nice to hear more ;] 

Anyway, here is how I do it now: 
I have virtual machines with Windows, and Debian where I build for linux and win. And on my macbook I build for mac. Then I upload them manually to github.

**Comment by sxmanton** [comment]
Cool, I will take a more detailed look at how to set it up sometime in the next couple weeks.

**Comment by sxmanton** [comment]
So I've been having a bit of a look at this. Trying to figure out if there's a way to automatically run this as part of the npm dist, but only on windows. Haven't really been able to figure out a way to have platform specific sets of scripts for that, are you aware of any?

If that's not possible, would you be okay with manually running an additional script when you do the windows build?

**Comment by hovancik** [comment]
No, I don't know of anything, but I am fine with running another script. I'm going from platform to platform anyway now..

Do you know about any electron-based app that is doing it? That would be easiest, I guess.

**Comment by sxmanton** [comment]
I know Atom has a package on chocolatey, but at least before, they were doing it in some weird way where it wasn't really versioning the package correctly.

If you're fine running an additional script, then that's easy enough. I'll work on writing a script soon, really the script just has to create a nuget package which contains the installer .exe and a chocolateyInstall powershell script which will be very straightforward in this case, it just has to run the .exe. I found some npm packages for nuget so it should be pretty easy, I just need to find some time to try it out.

**Comment by sxmanton** [comment]
@hovancik my apologies. I would still like to do this at some point, but haven't found any time for it. If you want to close the issue that's fine. If I ever get around to it I can just reference the closed issue in PR

**Comment by hovancik** [comment]
these guys have it, but haven't checked that  https://github.com/desktop/desktop

**Comment by sxmanton** [comment]
Hmm, looked through their build and publish scripts and couldn't find anything that is automatically making a chocolatey package. Turns out from looking at the chocolatey package page, the package is maintained by a third party package maintainer. I guess the authors themselves are just aware of the package and chose to include it in their readme.

At any rate, it appears that recently, some generous third party with more choco package maintaining experience than myself decided to take upon stretchly: https://chocolatey.org/packages/stretchly

While it would still be ideal to have it happen automatically (as the third party maintainer has some delay in releasing the updated package versions and who knows if they will remain dedicated), I think for now, this issue is sufficiently addressed.

**Comment by hovancik** [comment]
Cool! If I don't forget I'll add it to docs/website.
