### ISSUE TITLE
Settings Profiles

### ISSUE THREAD

**Issue by sxmanton** [hovancik/stretchly#157]
It would be nice if I could set up a few different saved profiles, i.e. one for working, one for gaming, rather than having to set/reset my settings every time I want to switch contexts.

**Comment by tslin306** [comment]
Nice to have different profiles. But currently you can pause for 1hr, 2hr, 5hr, or indefinitely while playing games.

**Comment by p2635** [comment]
Hi there, why was this one closed?

**Comment by hovancik** [comment]
Hi @p2635 , when I was cleaning some old issues, I've put `possible-feature` label on it, meaning I am closing now but might happen in the future. 

Unfortunately, number of features is infinity but my time is not, so progress is not super-fast and I need to be very picky about what I implement.

**Comment by p2635** [comment]
Thanks for the reply, I don't know how this project is set up, but if the person implementing is not you that is it worth keeping this ticket open? @hovancik 

If the project is set up in such a way you prefer to work on itself then I understand, just wanted to keep it visible in case any other devs want to disuss and pick it up.

**Comment by hovancik** [comment]
TBH, I was burning out and I needed to clean the slate so that was the decision I made at the time. Can't say whether it was right or wrong...

**Comment by p2635** [comment]
Hi @hovancik , no worries, I understand that you have your own responsibilities. All I am saying is whether it's worth keeping this issue open for others to work on? If it's not a feature you want then I guess it makes sense for this to stay closed.
