### ISSUE TITLE
Feature request | Custom message

### ISSUE THREAD

**Issue by Diazbesjorge** [hovancik/stretchly#163]
Hi Hovancik, congratulations for the app. After trying many others I'm sticking to this one because of it's simplicity and beauty.

One thing that doesn't work for me are predefined ideas, so I was wondering about the possibility of adding a custom message. I would appreciate being able to write something like "Take a break" or "Be here now" in a settings field.

Regards,
Jorge

**Comment by hovancik** [comment]
Hi, 
there is no "easy" way in application interface, but you can do it by editing config file as it is mentioned in readme here: https://github.com/hovancik/stretchly#editing-breakmicrobreak-ideas 

I hope this helps ;] 

I plan to add break ideas editor in future, but it will take time as there are many many features that needs to be done.

**Comment by Diazbesjorge** [comment]
Hi, I tried editing the config file as mentioned in the readme, but no matter how I do it the program keeps reloading the original ones. Is there something I am missing?

**Comment by Diazbesjorge** [comment]
Thanks, I was missing `useIdeasFromSettings": true` it works now.

**Comment by hovancik** [comment]
Awesome, glad it works. I'll enhance README.md.
