### ISSUE TITLE
Release stretchly in Microsoft Store

### ISSUE THREAD

**Issue by bramborman** [hovancik/stretchly#164]
It would be great if _stretchly_ was released in Microsoft Store (fka Windows Store). It would enable _stretchly_ to be run on Windows 10 S where only apps from Microsoft Store are allowed to run and it would also be easier to be always updated as Microsoft Store updates apps automatically.

I found [this][1] guide that may help you.

[1]: https://electronjs.org/docs/tutorial/windows-store-guide

**Comment by hovancik** [comment]
Thanks, I'll check it out.
