### ISSUE TITLE
Text is selectable

### ISSUE THREAD

**Issue by bramborman** [hovancik/stretchly#167]
I just noticed that the text in settings and even on the (micro)break page is selectable. I doesn't break anything, it just looks kinda odd.

![screenshot](https://user-images.githubusercontent.com/20975774/34384152-90bc942a-eb1a-11e7-9ae7-d750a1e39995.png)

**Comment by hovancik** [comment]
Thanks for reporting, what platform are you on?

**Comment by bramborman** [comment]
Windows 10, 16299 (Fall Creators Update)
