### ISSUE TITLE
Notifications are not working in Windows 10 Fall Creators Update

### ISSUE THREAD

**Issue by bramborman** [hovancik/stretchly#168]
While working on a czech translation I noticed that the app should show notification before (micro)break but on Windows (at least Windows 10, Fall Creators Update) it's not working. I never got any notification before any break. I have them enabled in settings.

**Comment by hovancik** [comment]
Not that familiar with windows anymore. I have them on my WIn 10 inside virtualbox. Do you get notifications from other apps? Maybe there is some config that needs to be turned on?

**Comment by bramborman** [comment]
It should work, all apps have them enabled from system by default AFAIK. What version of W10 do you have? They're releasing new version of W10 about twice a year now so in older versions notifications may be working while in newer they're broken.
I may take a look at that when I have time...

**Comment by bramborman** [comment]
So according to this issue (https://github.com/electron/electron/issues/10864) electron notifications don't work in Fall Creators Update.
There's a fix/workaround however: https://github.com/electron/electron/issues/10864#issuecomment-346229090

**Comment by hovancik** [comment]
sorry for delay but i didn't manage to upgrade my virtualbox machine so far. I have troubles with not enough space

**Comment by hovancik** [comment]
So I've just tried solutions mentioned in the issue but they are not working for stretchly. We will have to wait for upstream fix.

**Comment by hovancik** [comment]
so I've tried again and it seems to work now. weird, but I guess good ;]
