### ISSUE TITLE
Broken break view on macOS (missing all text)

### ISSUE THREAD

**Issue by anton-unity** [hovancik/stretchly#171]
Without obvious reason randomly getting broken fullscreen view (see screenshot). Can't escape it and seems only way is to kill application. It happens every second run, or once in couple of hours.

![screen shot 2018-01-02 at 18 04 49](https://user-images.githubusercontent.com/15607374/34490180-b49aeb68-efe7-11e7-8d00-b46a25fcf1d2.png)

stretchly v0.13.0 (eng locale)
macOS 10.12.6

Just started to use stretchly, so can't say if it's regression. I will try to check what it might be..

**Comment by hovancik** [comment]
Have you changed any settings?

**Comment by anton-unity** [comment]
Yep, I tuned a bit timers and changed _break view_ to fullscreen. I just nuked config and reinstall from brew. So far it's running stable in window mode, in default settings.

**Comment by hovancik** [comment]
If you remember what you changed, that would be awesome. Of if you could send me config file. I'll try running in fullscreen.

**Comment by hovancik** [comment]
So it's because of the fullscreen.

**Comment by anton-unity** [comment]
Yep. Seems to work few hours in window mode. 
Then changed to fullscreen and it worked couple of times, then became broken. 

[config.json.zip](https://github.com/hovancik/stretchly/files/1599862/config.json.zip)
