### ISSUE TITLE
Please add chinese language in locales

### ISSUE THREAD

**Issue by midpoint** [hovancik/stretchly#172]
[chinese language files.zip](https://github.com/hovancik/stretchly/files/1599081/chinese.language.files.zip)

In addition, can you add break Ideas to locales file？

**Comment by hovancik** [comment]
Thanks, should I use "‪繁體中文‬" for language selection or something else?

Break ideas will be also translatable in future, but I haven't implemented it yet.

**Comment by midpoint** [comment]
Certainly.

**Comment by hovancik** [comment]
Thanks, I've also added you to the list of the contributors as `midpoint, @midpoint` (https://github.com/hovancik/stretchly/tree/feature/cn#contributors). Is that fine or you would like to change it?

**Comment by midpoint** [comment]
It is ok. Thanks.
