### ISSUE TITLE
Please block "ctrl/cmd + tab" in break view

### ISSUE THREAD

**Issue by antnsi** [hovancik/stretchly#176]
A bit odd feature request, but still. I'm using combination of options:
- don't let me skip breaks (mini breaks)
- breaks are fullscreen

So I have fullscreen break without skip button, but I still can just do cmd+tab (on macosx) and therefore switch tabs. Stretchly break view left working in background. 

Not sure that's important, but I keep doing that automatically... 😆

**Comment by hovancik** [comment]
I see. I looked into that and seems that it might be possible with electron's "Kiosk" mode. The "Fullscreen" I am using now works as you described. 

I've tried "Kiosk" on my machine and it doesn't seems to work as I thought. I'll try and ask electron developers.

**Comment by hovancik** [comment]
So Kiosk should do what you want, but in *stretchly* case it for some reason does not. I have no idea why. I've tried some stuff and example that works elsewhere doesn't work with stretchly. Really lost here.

**Comment by anton-unity** [comment]
Thank you for investigation! And well, it's not that important, don't waste time.
I got used to window, instead of full screen 😄  (it hides half of screen and prevent normal work)

**Comment by hovancik** [comment]
Ok, I'll keep the issue open for now, and we will see.

**Comment by hovancik** [comment]
closing in favor of #437 as it's pretty much the same thing
