### ISSUE TITLE
natural breaks not counted properly

### ISSUE THREAD

**Issue by gotson** [hovancik/stretchly#178]
Hello,

just installed Stretchly v0.13.0 on Windows 7, and i have an issue with natural breaks not taken into account.
I use it on my work PC, and before leaving at night my windows session is locked.
When i come in the morning, i get a microbreak in the first minute after being logged back in. It should count 10 minutes from my login time before triggering this microbreak though.

**Comment by hovancik** [comment]
Hi, I think there is another API in play: 
electron's API for power monitoring  https://github.com/electron/electron/blob/master/docs/api/power-monitor.md 

My guess is that either it does not support windows 7, or what you are describing is not suspend/resume.

**Comment by gotson** [comment]
Looks like the API is not working properly for other platform too:
https://github.com/electron/electron/issues/8560#issuecomment-353657966
https://github.com/electron/electron/issues/1615

**Comment by hovancik** [comment]
Thanks for the links, I'll take a look.

**Comment by hovancik** [comment]
I wonder, does tray tooltip works on Win 7? If yes, what does it says when you log back in?

**Comment by gotson** [comment]
Tooltip is working fine.
Just tried a couple of times today, and i get the following:
```
10mn to microbreak
Next break following 2 more microbreaks
```

The timer seems to be correct, not sure what the second line is about though.
From what I understand i should expect 1 microbreak, then 1 break, then 2 microbreaks, whereas the coorect behavior should be 2 microbreaks, then 1 break, no ?

**Comment by hovancik** [comment]
I would say that the tooltip is OK. The fact that there is 10 minutes means, that the timer resets itself. 

The second line means that you will have 2 microbreaks, then break, which is also correct, depending on your settings. By default there are 2 microbreaks and then break.

**Comment by gotson** [comment]
Indeed i tested this morning, it works fine.
I found the tooltip text misleading because of the wording, mentioning first what would happen last.

Not sure what happened earlier on when i opened the issue, but the behavior seems to be correct for now. I will close the issue and let you know in case it happens again :)

**Comment by hovancik** [comment]
Ok, thanks ;] What wording would you use? I'm not native English speaker and I am not sure about the person who made the text as well. The text was made by another contributor.

**Comment by gotson** [comment]
I'm not a native English speaker either :)
