### ISSUE TITLE
[Ready to help] Ukrainian and Russian translation

### ISSUE THREAD

**Issue by neooleg** [hovancik/stretchly#181]
Hi @hovancik and the team,

thanks a lot for creating a health-keeping software!

A bit of contribution from my side -- I'm ready to assist with UA and RU i18n if it's required. Just give me a file with English keys -- I'll come back with UA/RU.

**Comment by hovancik** [comment]
Hi and thanks! 
the translation files are located here: https://github.com/hovancik/stretchly/tree/master/app/locales

**Comment by neooleg** [comment]
OK, I've planned to do it in near future.

Is there anybody to test the i18n? (especially layout consistency)

**Comment by hovancik** [comment]
If you make translations, I can send you app version with translations

**Comment by neooleg** [comment]
Hi, apologies me for disappearing for a long time for this initiative -- I have a lot on my plate for now.

Anyway, Ru was done already by @fizvlad -- thanks for him!

Hence, I've prepared Ua -- pls check #231

**Comment by hovancik** [comment]
Thanks! There is problem with keys starting with capitals

**Comment by neooleg** [comment]
@hovancik sure, I did the fix. Can you check?
