### ISSUE TITLE
Break reminder not centered in Windows 10 multiple monitors

### ISSUE THREAD

**Issue by alexwennerberg** [hovancik/stretchly#183]
When using Windows 10 Pro, I encountered an issue where the break reminder window is not centered when using one of the two external monitors.

![image](https://user-images.githubusercontent.com/11624958/34692761-d8fa17d8-f486-11e7-9373-5b1aa9cd85be.png)

 The setup is, laptop below two external monitors, this is the rightmost of the two monitors. When the reminder pops up on the left monitor, the window is in the upper left corner of the screen, also partially obscured.

Let me know if you need any more info. Me & my coworkers love this app, thanks!

**Comment by hovancik** [comment]
Hi, 
what version of stretchly do you have? I've made some changes in the latest one (0.14.0).

**Comment by alexwennerberg** [comment]
This is 0.14.0

**Comment by hovancik** [comment]
Was it the same in previous versions?

**Comment by alexwennerberg** [comment]
Not sure. Haven't seen older versions on windows 10

**Comment by hovancik** [comment]
Do your monitors have different DPI? I guess this is electron's issue: https://github.com/electron/electron/issues/10862

I don't have Windows machine to test older versions, could you try 0.13.0?

**Comment by alexwennerberg** [comment]
My coworker is the one having this issue (I'm on a Mac) but I'll talk to her and get back to you!

**Comment by hovancik** [comment]
Hi, is this still issue? It's been a few months and versions ;]

**Comment by alexwennerberg** [comment]
Not sure. My coworker just changed it to fullscreen mode and it worked fine.

**Comment by hovancik** [comment]
Ok, noone else reported so I'm gonna close it.
