### ISSUE TITLE
Brazilian Portuguese Translation

### ISSUE THREAD

**Issue by sergiopjf** [hovancik/stretchly#184]
I maked the brazilian portuguese translation.

Please, send me app version with brazilian portuguese for translation check.

[br.zip](https://github.com/hovancik/stretchly/files/1620518/br.zip)

**Comment by hovancik** [comment]
Hi and thanks! 
- what os do you use? 
- can I use "português brasileiro" in language selector? or should I use different name?

**Comment by sergiopjf** [comment]
I use Windows 10

"português brasileiro" is perfect.

**Comment by hovancik** [comment]
You can find the file here: https://ufile.io/i5f8t

**Comment by sergiopjf** [comment]
I made some corrections. Now it's perfect.

[br.zip](https://github.com/hovancik/stretchly/files/1627937/br.zip)

In language selector use "Português Brasileiro" and not "Português brasileiro".

Thanks for all.

**Comment by hovancik** [comment]
Thanks, do you want to send new version for another test or I can merge it?

**Comment by sergiopjf** [comment]
It's no longer necessary. You can merge it.

Thanks.

**Comment by lubianat** [comment]
I was going to open such an issue @hovancik . May I update the brazilian portugues translation of stretchly?

**Comment by hovancik** [comment]
Hi @lubianat  and thanks for your interest ;] 

 I am currently redoing UI/UX of Stretchly so there will be a lot of changes in translation files. I can't say when it will be done, but I think better to wait. There will be probably be no version meanwhile I am done. I plan to send newsletter then, asking people to help with translations.
