### ISSUE TITLE
Rails Girls Summer of Code 2018

### ISSUE THREAD

**Issue by hovancik** [hovancik/stretchly#193]
Hey folks, stretchly has been accepted as project for RGSoC. If you know about someone who might be interested in, feel free to let them know ;] 

I wrote about it in my blog: https://hovancik.net/blog/2018/02/02/stretchly-accepted-to-participate-in-rgsoc-2018/

**Comment by Anisha1234** [comment]
@hovancik I would like to work on the project. I am experienced with NodeJS, D3JS, Express framework, HTML, CSS, Javascript, Bootstrap with MongoDB and MySQL. Though I am new to ElectronJS, yet I am confident enough to develop my skills in ElectronJS. Kindly guide me through the process

**Comment by Akshitaag** [comment]
Hello @hovancik ,
I am Akshita from New Delhi ,India. I wish to apply for rgsoc 2018 along with my team-mate @rahmeen14 .We both have worked in NodeJs ,Express ,MongoDB, HTML,CSS ,JS and MYSQL. We are willing to learn electronJS too. How can we begin contributing?

**Comment by Rahmeen14** [comment]
Hello @hovancik . Would love to contribute! :)

**Comment by manaswinidas** [comment]
Hello @Anisha1234 I'll be more than happy to contribute!

**Comment by hovancik** [comment]
Thanks everyone ;] I'm really happy that you are interested in helping stretchly out ;] 

I guess you have already read this: https://railsgirlssummerofcode.org/students/application/  so for starters, you should install stretchly and start using it, so you are familiar with how it works. Then you should be able to say what features/issues you would like to work on.

**Comment by purva98** [comment]
hello @hovancik sir,
I am purva. Me and my team mate are familiar with NodeJS, Javascript , React JS, Redux , Electron js , Html and css. We read about Strechly in your blog on hovancik.net. 
We are very excited to contribute to Stretchly project. We will give our best :)

**Comment by hovancik** [comment]
Hi everyone, 
there is a https://gitter.im/stretchly/Lobby where I hang out when I'm online, if you have some fast questions ;]

**Comment by Sveijk** [comment]
Hi Jan! 

My teammate Alina and I got accepted for this Rails Girls Summer of Code. 
Stretchly is our first choice project. We're looking forward to working on Stretchly this Summer :-) 

I think it would be a good idea to get in touch with you before the project starts, what do you think / how do you feel about that? Sabine

**Comment by hovancik** [comment]
Yeah, great idea ;] I'm hanging out on https://gitter.im/stretchly/Lobby
