### ISSUE TITLE
Typo in Contributing.md

### ISSUE THREAD

**Issue by Rahmeen14** [hovancik/stretchly#194]
```Other thinks to keep in mind:```

Shouldn't it be ```things``` ?.
If it's approved, I would love to send a PR to fix it!
P.S. I am an aspiring RGSoC scholar with beginner's level proficiency in Node.js :)

**Comment by hovancik** [comment]
Feel free to make a PR and thanks! ;]

**Comment by Rahmeen14** [comment]
@hovancik  I have made the PR https://github.com/hovancik/stretchly/pull/196 
It's failing 2 checks in files i didn't even touch. Can you please help out?

**Comment by hovancik** [comment]
Yeah, that are some older issues that I haven't addressed yet. Thanks for the fix ;]

**Comment by hovancik** [comment]
I forgot to add you to Readme's Contributors part. What would you like to have there?

**Comment by Rahmeen14** [comment]
I would not want my name there until I fix some real issues! :)
Thank you for the help and the merge, that happens to be my first successful PR!

**Comment by hovancik** [comment]
I think you deserve to be there ;] Documentation is more important than people think. 

And congratz for first PR!

**Comment by Rahmeen14** [comment]
Thank you so much!
