### ISSUE TITLE
Selecting a sound more than once doubles the volume

### ISSUE THREAD

**Issue by ahallicks** [hovancik/stretchly#20]
I'm not sure if it's just a Windows (10) thing, or my system, or what. But when I select a sound, change it, and then select the first sound again it gets louder. If I do this a couple of times it gets REALLY loud!

**Comment by hovancik** [comment]
thanks for the report, I can confirm that it is happening on macos too. going to look into it.

**Comment by hovancik** [comment]
issue has been fixed, gonna release new version soon.
