### ISSUE TITLE
Welcome Page

### ISSUE THREAD

**Issue by dimi-23** [hovancik/stretchly#202]
Hi, I and my teammate @AnkitaKhurana are interested in working on this project during RGSoC 2018.

We tried installing the Stretchly app by .exe in order to understand its functioning, and we had a few suggestions which could enhance the robustness of the software. While installing the app on our PCs there was no welcome screen to introduce the user about the app has been installed, which leaves the user a bit confused. Also, if we try to open the app by double-clicking on the desktop icon, no interface is encountered.

**Comment by hovancik** [comment]
Hi, you are right. Some kind of intro screen would be nice as stretchly is tray only app.

**Comment by kavya-jain** [comment]
Hi @hovancik,
Kindly review the Welcome page and suggest changes.
![image](https://user-images.githubusercontent.com/30476096/36520658-2cdd9bfa-17b8-11e8-8c93-b7dbdab738a1.png)

**Comment by kavya-jain** [comment]
Hi @hovancik,
Kindly review the welcome page and suggest changes
![welcome_page](https://user-images.githubusercontent.com/30476096/36520747-d7b52a02-17b8-11e8-8af5-e39df55d6c4e.PNG)

**Comment by hovancik** [comment]
@kavya-jain thanks for the screenshot.  

Few things here. 

I know that we are all excited about RGSoC but let's not get ahead of ourself ;] 
The feature of welcome screen was suggested by @dimi-23 and @AnkitaKhurana so I think it would be fair to let them implemented it, if they are still interested in contributing. 

Another thing is implementation itself. First we need to think in terms of problem. 

Q: What problem are we solving? 
A: When user starts app, they do not see anything happening.  

Then we need to think about how can we solve this, while keeping in mind what stretchly does and how user interacts with it. 

So when we say "When user starts app, they do not see anything happening. ", we also mean: they probably don't know what to do and what to expect. 

This should lead us to few conclusion (and we might add few more later):
- welcome screen should tell user how stretchly works (as user probably don't know it yet)
- welcome screen should be shown only once (so user is not disturbed every time)
   - or user should be able to tick "Do not show again"
- welcome page should be in selected language and user can choose from other languages (as it's english after install)
- there should be link to website with even more detailed explanation of how stretchly works
- welcome page might need to be different for different OS, as they are some differences in functionality

After thinking about all of this, we can start to think about what we should put on the page, how it should behave and so on:  a list of functionalities (which will be very similar to our list of conclusions, but it will be final version- ie. we will decide whether welcome screen will be shown only once, or we let user tick "Do not show again"). 

And then, we can finally start to think about how we gonna implement it ;] 

But anyway, I think this would be good task to keep for the summer, as a team could learn how to work with user's problems.

**Comment by kavya-jain** [comment]
@dimi-23 Thanks for the confirmation. @hovancik  i'll create a PR for it.

**Comment by hovancik** [comment]
@kavya-jain so how about questions mentioned here? https://github.com/hovancik/stretchly/issues/202#issuecomment-368209111
