### ISSUE TITLE
Redundant Data

### ISSUE THREAD

**Issue by kavya-jain** [hovancik/stretchly#203]
Hi
My teammate @tsah20 and I are interested in working on this project during RGSoC 2018. 
Break ideas and microbreak ideas are included in defaultSettings file as well as defaultBreakIdeas and defaultMicrobreakIdeas file. It can be included in one file and redundancy can be removed.

**Comment by hovancik** [comment]
Hi, thanks for your interest! 
They are duplicated there for a reason: https://github.com/hovancik/stretchly#editing-breakmicrobreak-ideas (in case someone wants to use custom break ideas)
