### ISSUE TITLE
Update Electron dependency

### ISSUE THREAD

**Issue by jainaman224** [hovancik/stretchly#204]
Update electron dependency to 1.8.x. So, there is support for latest debian based distros for tray icon. https://github.com/hovancik/stretchly/blob/master/package.json#L40

**Comment by purva98** [comment]
Sir, 
Great to see the upgradation, I wanted to ask that, by debian based do you mean Kali Linux, Tails, Ubuntu , Grml?

**Comment by jainaman224** [comment]
I setup strechly on ubuntu 17.10 and 17.04. In both the OS, there were no tray icon initiated.

**Comment by hovancik** [comment]
Hi, I usually update deps before I make a release. Not sure if that's the best way to do it, thought. 

For tray, `libappindicator1` needs to be installed as dependency. https://github.com/hovancik/stretchly#linux-note

**Comment by jainaman224** [comment]
I tried to run after installing `libappindicator1` but it is of no use. https://github.com/electron/electron/issues/10887, See people are reporting same issue with electron 1.7.x but no one said anything about 1.8.x and moreover upgrading to 1.8.x worked for me. AppImage also doesn't produce tray icon.

**Comment by hovancik** [comment]
Ok, we'll check after I release new version.

**Comment by hovancik** [comment]
Is this still issue with new version? On my debian and xfce setup I see icon fine.

**Comment by jainaman224** [comment]
No, thanks.
