### ISSUE TITLE
Edit submenu

### ISSUE THREAD

**Issue by jainaman224** [hovancik/stretchly#205]
I don't think there is a need for edit submenu. As option like cut copy paste are of not much use.

**Comment by hovancik** [comment]
Which option do you mean? I am not sure if I understand.

**Comment by jainaman224** [comment]
![screenshot from 2018-02-15 13-43-29](https://user-images.githubusercontent.com/13117482/36246616-9f00b77e-1256-11e8-9d8e-920e48644631.png)

**Comment by hovancik** [comment]
Ah, I see. This is from electron. Not sure if I can edit this menu.

**Comment by bramborman** [comment]
Isn't it visible only when not in release mode? I have downloaded stretchly from GitHub releases and the menu is not there. It may also be Windows specific, not sure...
![image](https://user-images.githubusercontent.com/20975774/36269465-91476880-1279-11e8-9ef9-14590a84e785.png)

**Comment by jainaman224** [comment]
It is not visible on my friends Mac. I am unsure about the behavior. It is visible for me.

**Comment by hovancik** [comment]
@jainaman224 you are also on mac? 

I've tested on my Debian/XFCE and I don't have it.

**Comment by jainaman224** [comment]
@hovancik With my friends PC. I have also tested it on windows. There is no such menu. So, maybe we can close this issue. But it gives me an idea to have a menu like this. So, that we don't need to have separate about and settings page.

**Comment by hovancik** [comment]
My bad, I have it on Settings page, but I do not have it on break window. 

Anyway, I will close this as it is not big issue. Probably depends on platform...
