### ISSUE TITLE
Include gitter badge to Readme

### ISSUE THREAD

**Issue by jainaman224** [hovancik/stretchly#206]
This is the sample badge for stretchly.
[![Join the chat at https://gitter.im/stretchly/Lobby](https://badges.gitter.im/stretchly/Lobby.svg)](https://gitter.im/stretchly/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Comment by hovancik** [comment]
Feel free to make a PR. I thought that gitter would create it automatically as their bot forked the repo, but that didn't happen and I forgot about it after.

**Comment by jainaman224** [comment]
@tsah20 @kavya-jain Make a Pr.
