### ISSUE TITLE
javascript error in installation process

### ISSUE THREAD

**Issue by shloka-812** [hovancik/stretchly#214]
![error](https://user-images.githubusercontent.com/36547714/36324115-642782f8-1379-11e8-8757-d799fcb83b3b.png)

**Comment by shloka-812** [comment]
I am a windows 10 user. This electron issue is coming up and I am unable to install it.

**Comment by hovancik** [comment]
Is this when you run the app or when running installer?

What file are you using to install stretchly?

**Comment by shloka-812** [comment]
This is when I am trying to do npm start , after doing npm run dist as well as npm install

**Comment by purva98** [comment]
Hi fellow windows 10 user,
Is the error saying node_module 54 but expected 57?
I think a common solution which you can try is:
-reinstall node js from https://nodejs.org/en/  ( to upgrade to v8.9.4)
- Open windows powershell
        -Right click on the icon and select run as administrator option
- npm --add-python-to-path='true' --debug install --global window 
    (This will install Visual studio build tools,python)
    (This will take some time so be patient)  ;)
- cd into your project folder
- now follow the usual steps of npm run pack, then npm install and then npm start
- while npm install if you face any “electron” related issue then :
    - delete electron named folder from node modules and type the following
           - npm install electron --verbose
           - now say npm start :)

**Comment by shloka-812** [comment]
@purva98 thanks!
You said it will take some time , but everything was very fast as I followed the steps ;]
Thanks for solving my issue.
