### ISSUE TITLE
Add Russian translation

### ISSUE THREAD

**Issue by fizvlad** [hovancik/stretchly#219]
@hovancik 
Hello! I would like to add Russian localization.
There is already exists same issue #181 but it is now more than month old

CONTRIBUTING.md says I need to open an issue so here it is :)

At the moment I got translated _ru.json_, edited _settings3.html_, edited _README.md_, edited _CHANGELOG.md_.
I committed those [changes to fork here](https://github.com/fizvlad/stretchly/commit/5adf0a9b5be83c498a8906b976aac8f7d4726a1b)

**Comment by hovancik** [comment]
Feel free to create a pr
