### ISSUE TITLE
AppX package problems

### ISSUE THREAD

**Issue by bramborman** [hovancik/stretchly#221]
Hi, I just tried to install _stretchly_ from the AppX package from GitHub releases but it fails to install since the package is not signed with a trusted certificate. So the AppX is practically useless for now. And there are assets missing so the package uses default _electron_ icon as you can see.

![image](https://user-images.githubusercontent.com/20975774/36472747-fe665eda-16f2-11e8-9669-5773be8853e0.png)

**Comment by hovancik** [comment]
So it's not possible to install without the cert? I guess then I wont use AppX. 

The similar issue with icon is in Linux, I guess some electron-builder config has changed. One student interested in RGSoC is looking into it already.

**Comment by bramborman** [comment]
If an app is **not** distributed through Microsoft Store, AppX must be signed with a certificate and the certificate must be installed on each device in the _Trusted Root_ or _Trusted People_ certificate store [(docs.microsoft.com)](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-distribute#distribute-your-app-without-placing-it-onto-the-microsoft-store). 
However if you will distribute it through Store (#164), when submitting the app there, it will automatically be signed with trusted Store certificate. I already have a few apps in Microsoft Store, one using Desktop Bridge, so I may help you with it if you want.

Regarding the icon, from what I've read [here](https://www.electron.build/configuration/appx#appx-assets), what I believe is documentation for what you're using to generate AppX and other packages, you must create the icon assets manually and add them to `appx` folder in the `build` directory. You'll probably end up with more than 40 icons - for different places and different DPIs. It may sound horrifying, but with Visual Studio 2017 it's easy to generate them. I've already tried it with slightly modified mac tray icon and may create a PR with these icons (or another automatically generated icons if you don't have VS) if you're interested.

![Generated icons](https://user-images.githubusercontent.com/20975774/36479232-3045ab9e-1708-11e8-87b7-7f8a6530e2d8.png)

![App tile](https://user-images.githubusercontent.com/20975774/36481581-8bac7848-1710-11e8-83d8-f2089a00a02c.png)

**Comment by hovancik** [comment]
Many thanks for the research! 

If you would like to help out with #164 , that would be great. Another option is to wait until summer and give this to RGSoC students. You could mentor them with this task. 

The icon: I would rather go with colourful icon (so it's the same as in tray) ;] The black-n-white I am using only for Mac as per apples requirements. Or Microsoft wants black-n-white too?

**Comment by bramborman** [comment]
There're not many things to do to release _stretchly_ in Microsoft Store besides preparing the AppX and they all should be probably done by you:

You have to [be registered](https://developer.microsoft.com/en-us/store/register) as an app developer in Microsoft Dev Center. You'll have to pay one-time developer fee (about $19).

1. [Register new app](https://developer.microsoft.com/en-US/dashboard/apps/new) in Microsoft Dev Center.
2. Send request to allow you to release Desktop Bridge app in Store using [this form](https://developer.microsoft.com/en-us/windows/projects/campaigns/desktop-bridge). They'll contact you in about a week, test your app and if it passes, they'll enable you to publish it in Microsoft Store.
3. Submit your app to Microsoft Store using [Microsoft Dev Center](https://developer.microsoft.com/en-us/dashboard/apps/overview).

About the icon: Microsoft recommends white icons as they are visible on most tile colors (users can select a color of their choice in Windows Settings or the app can force one color to be used on its tile) but it's not required and the app can be in Store with colorful icon too. But most of the apps in Microsoft Store and apps built-in in Windows 10 use white icons (funny enough, Microsoft Store uses icon with colors). I used the white icon because I didn't find the colorful as vector :D

![Apps](https://user-images.githubusercontent.com/20975774/36489147-965eb0f2-1725-11e8-80b3-757f91f7b928.png)

![Tray](https://user-images.githubusercontent.com/20975774/36489056-55246794-1725-11e8-879b-b73741e5a61d.png)

**Comment by bramborman** [comment]
You'll also have to add some AppX configuration to be able to publish _stretchly_ in Microsoft Store. It's described in the first paragraph of [this article](https://www.electron.build/configuration/appx).

These values are used in app's Store manifest and according to [this article](https://docs.microsoft.com/en-us/windows/uwp/publish/view-app-identity-details), only three of them are really required:

 - Package/Identity/Name&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- `identityName`
 - Package/Identity/Publisher&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- `publisher`
 - Package/Properties/PublisherDisplayName&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- `publisherDisplayName`

But it would also be good to add `languages` so the Store will show the correct info.

**Comment by hovancik** [comment]
Many thanks for research! Seems that the fee is yearly. I'll try to follow the steps when I find some time.  I guess I will charge some money for app-store version. Or no.

**Comment by bramborman** [comment]
No, it definitely isn't yearly :D It was few years before, but they changed it to one-time. I'm registered as a developer for about 3 years and have never paid again.

This is on the registration page:
> Individual accounts cost approximately $19 USD, and company accounts cost approximately $99 USD (the exact amounts may vary depending on your country or region). **This is a one-time registration fee and no renewal is required.**

**Comment by hovancik** [comment]
@bramborman did you get any email when asking for Desktop Bridge app? It's been some time and I have not heard back from Microsoft. I remember I did not get any email when applying, so I am wondering that maybe my application didn't get through or something.

**Comment by hovancik** [comment]
so I resubmitted again. seems that it was not successful last time.

**Comment by bramborman** [comment]
Not sure - it was a long time ago but if I remember correctly that day I submitted the form I got email saying they'll take a look at it and the next email with instructions came about 8 days later.

**Comment by hovancik** [comment]
So I received the email. I've tried to upload app but it says and that there are some problems and points to link that does not work... oh microsoft... I'll probably try again later and then give up.

**Comment by hovancik** [comment]
So I've tried again and again some weird errors from MS. Giving up. I won't do appx.
