### ISSUE TITLE
Friendlier download page

### ISSUE THREAD

**Issue by rafpaf** [hovancik/stretchly#222]
I'd like to recommend Stretchly to my students. However, from https://hovancik.net/stretchly/ it's hard to figure out how to download the software. Most users expect a large button somewhere that says "download Stretchly". Even if you click on the "downloads" link, you're taken to a page with a lot of strange language ("assets?") and it's hard to figure out which of those links will work for your system.

**Comment by hovancik** [comment]
Yeah, that's true. I was hoping to leave this task for students from [RGSoC](https://railsgirlssummerofcode.org/), but I guess I will make a supersimple download page now and then let them enhance it. 

The "strange" assets are stretchly installers/executables for different operating systems and package managers.

**Comment by rafpaf** [comment]
Thank you!

**Comment by hovancik** [comment]
https://hovancik.net/stretchly/downloads/

**Comment by rafpaf** [comment]
Brilliant, thank you Jan!
