### ISSUE TITLE
Update is annoying

### ISSUE THREAD

**Issue by mpnieland** [hovancik/stretchly#227]
Stretchly is great, and it's updated frequently (which is good), but currently the update is pretty rudimentary.  A notification pops up that a new version is available, and it keeps doing that at least once a day until you update (which is manual).

It would be great if Settings contained a period selector for how often to check for an update, and if there was auto-updating that just did it in the background instead of interrupt your workflow by having to download and install it.  It doesn't take long to install, but because it checks so often and the branch is updated so often, I find myself having to do this 2-3 times a week just to keep the notification from popping up and further disrupting my workflow.

**Comment by hovancik** [comment]
That is strange, what release are you on? The last release before the latest 0.15.0 was 0.14.0 and was released this on Jan 7 ·

**Comment by hovancik** [comment]
Anyway, you can disable update check manually by editing config: 

https://github.com/hovancik/stretchly#new-version-notification
