### ISSUE TITLE
Tray Tooltip not shown in Plasma 5 Arch

### ISSUE THREAD

**Issue by lundibundi** [hovancik/stretchly#228]
So as stated in the title I cannot get KDE to show me the tooltip upon hovering of stretchly tray icon. It only shows me the icon and the name. 
![image](https://user-images.githubusercontent.com/9109612/37372714-730bed7a-271c-11e8-994c-465a547ff19c.png)
I expect it to show me time left until the next microbreak (break) and so on.
```
Stretchly v0.15.0

 ➔ ~ uname -a
Linux neko 4.15.8-1-ARCH #1 SMP PREEMPT Sat Mar 10 00:00:33 UTC 2018 x86_64 GNU/Linux

 ➔ ~ electron --version
v1.8.2

 ➔ ~ plasmashell --version
plasmashell 5.12.3

 ➔ ~ kf5-config --version
Qt: 5.10.1
KDE Frameworks: 5.44.0
kf5-config: 1.0
```
Thanks for the great app =)

**Comment by hovancik** [comment]
I don't have KDE env on my Linux, but: does the click on icon work? 

I think that probably KDE does not support tooltips. Will research it...

**Comment by hovancik** [comment]
this is electron issue, I've reported it https://github.com/electron/electron/issues/12321

**Comment by hovancik** [comment]
This should be now fixed on Electron's side, only took few years :) Stretchly 1.13 has this.
