### ISSUE TITLE
upper limit of microbreak duration set to 5 minutes

### ISSUE THREAD

**Issue by hovancik** [hovancik/stretchly#237]
In the beginning, limit was set to 30 seconds max. In the latest version we changed it to 1 minute. 

After talking to some people, I think we should go even higher and set it to max 5 minutes. 

If anyone wants to contribute, this one is easy one ;]

**Comment by immonika** [comment]
I would like to contribute @hovancik , but can we make this option in settings , so that users can change it according to their comfort . And as you mentioned it should be set to 5 minutes , by default.

**Comment by hovancik** [comment]
Feel free to create a PR ;]

not sure what you mean by making this option in settings. this is already in options: user can microbreak duration time up to one minute. what I would like to do is to allow this to be set up to 5 minutes.
