### ISSUE TITLE
Making it more Interactive

### ISSUE THREAD

**Issue by immonika** [hovancik/stretchly#238]
Can we make stretchly  more interactive by asking users their basic details like name , age , country and according to age and country suggest the idea's in the window . And instead of writing the idea like "Look up and down " , it can show use username , like " Jan , Look up and down". 
While going through the settings , i noticed there are only 4 audio schemes , can we modify it so that it can sync with user's playlist and play music during breaks what user enjoys. As we all know music is a great therapy , it will help the user a lot . Hope to hear soon @hovancik , so that we can start working on it.

**Comment by hovancik** [comment]
Hi, thanks for the idea but right now I'm not interesting in implementing this. As user, I would personally prefer not to share any of my private info with this app. 

The changes would be also huge for codebase size (thus hard to maintain) and it would go against stretchly's philosophy: be as simple as possible.

Using name would be also hard: in English it's easy but in Slovak it's totally different and it would sound awkward as we need to think about gender and so on when making sentence. I guess other languages have specifics as well.
