### ISSUE TITLE
It stops timing sometimes? Is there a solution to fix it?

### ISSUE THREAD

**Issue by CYC777** [hovancik/stretchly#239]
### Prerequisites

- [x] I'm using latest version: v0.16.0 

### Description
The app often stops timing and won't go into breaks. 

Operating system: 
MacOS High Sierra 10.13.3
### Steps to Reproduce

1. Not sure what triggers it, but it happens a lot on my computer. 

**Expected behavior:** remind me to take a break on time

**Actual behavior:** Stop reminding me to break. 
**Reproduces how often:** high

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by hovancik** [comment]
- how did you install it? 
- did you change any settings? 
- when you feel like it does not show any breaks, could you go to About window and do `Cmd+D` and write here what `breakPlanner:` shows?

**Comment by CYC777** [comment]
- how did you install it?
I use the .app file in the release for mac.

- did you change any settings?
Yes, I changed some time intervals, but just those settings. 

- when you feel like it does not show any breaks, could you go to About window and do Cmd+D and write here what breakPlanner: shows?
OK. I can see the remaining time, I will keep an eye on it. And right now, it says, 
![image](https://user-images.githubusercontent.com/32247119/38424458-1f5de51e-397f-11e8-8d90-d7bfba376723.png)

Thanks for the quick reply.

**Comment by CYC777** [comment]
I checked it when I feel it it's stopped, the "timeleft" did roll back.

**Comment by hovancik** [comment]
Hi, so what you mean is that time left goes not to lower numbers but to higher numbers? 

Could you please paste the content of settingsFile from screenshot? I will try on my mac with your settings, the problem is probably there somewhere.

**Comment by CYC777** [comment]
I think the time left was set to the default countdown number while it stops timing, like reset. It's not like it goes up minute by minute. 
The json is below. The problem happens before I add those few Chinese comments, it probably won't cause the problem. Also, I have tried some other rest reminder app on my computer, they also lost timing from time to time. I feel like they stop running in the background, but they exist in the Activity Monitor. 
![image](https://user-images.githubusercontent.com/32247119/38459020-84bd1c9c-3a72-11e8-8daf-1afecf74d9fc.png)

**Comment by hovancik** [comment]
so I'm not sure if I understand correctly, but I see that you have naturalBreaks on, so stretchly will reset timer every time you go idle for 5 minutes. Maybe that's what happening?

**Comment by CYC777** [comment]
The plist is not the solution. Are you suggesting to turn the naturalBreaks off?

**Comment by hovancik** [comment]
Yeah, if you do not want time to reset after 5 minutes of idle time, turn it off ;]

**Comment by CYC777** [comment]
I think it works! Thank you so much!!
