### ISSUE TITLE
Stretchly not paused automatically during DND/presentation mode on OSX

### ISSUE THREAD

**Issue by leneux** [hovancik/stretchly#240]
### Prerequisites

I'm using latest version: v0.16.0. I am also running stretchly in full screen mode.

### Description

When enabling do not disturb mode (or when done automatically during presentation mode) stretchly still works. I've had the messages  pop up when I am trying to present things to other people which is really annoying.

I could switch it off, but I forget, and worst still the DND mode turns off the stretchly notifications (as expected) which let you know it will happen shortly.

Operating system: OSX high sierra 10.13.2

### Steps to Reproduce

1. Go to notification centre and turn DND on
2. Wait for microbreak or break and stretchly will start

**Expected behaviour:** When in DND stretchly should pause for the duration of DND

**Actual behaviour:** Stretchly interrupts presentations and causes some bother.

**Reproduces how often:** 100% of the time

Many thanks for reading.

**Comment by hovancik** [comment]
Sorry for late reply, I was on holidays. What do you mean by: "Go to notification centre and turn DND on" ?

**Comment by leneux** [comment]
That's OK, thank you for replying.

On OSX, if you press the icon on the very top right of the screen this notification tray opens, there is an option to turn on do not disturb there.

<img width="1440" alt="screen shot 2018-04-30 at 10 23 57" src="https://user-images.githubusercontent.com/38141548/39421715-358e5ba2-4c62-11e8-9835-cfa830938ab8.png">

**Comment by hovancik** [comment]
Ah, thanks, I didn't know about this, will research it
