### ISSUE TITLE
Overlapping of reminders with 1 second remaining

### ISSUE THREAD

**Issue by unholyHub** [hovancik/stretchly#241]
### Prerequisites

- [ ] I'm using latest version: v0.16.0
### Description

[Description of the issue]

Operating system: Windows 8.1

### Steps to Reproduce

1. Wait until **microbreak** reminder appears
2. While the **microbreak** timer is decreasing go to the tray and **skip to next break**
3. After the **break** finishes the **microbreak** stays at **1 second remaining** 

**Expected behavior:** If there is a present microbreak/break whatever I skip to it should close all reminders.

**Actual behavior:** The reminder stays on 1 second remaining always and does not close

**Reproduces how often:** 100%

### Additional Information

I have test it with skipping with two consecutive microbreaks. It shows only one but stops/freezes at 1 second remaining.

**Comment by hovancik** [comment]
Many thanks for the report, I was on holidays so sorry for late reply. 

Right now I'm lost in tasks, but I will try to fix it as soon as I find some time. More options here: 

- do not allow to skip to other breaks while some type of break is going on 
- allow to skip to other break but cancel actual one 

I am for option 2 (the same you said) and unless someone comes with great argument, I will fix it that way.
