### ISSUE TITLE
At every reboot, Node.dll was not found (ffmpeg.dll too)

### ISSUE THREAD

**Issue by auanasgheps** [hovancik/stretchly#245]
### Prerequisites

- [x] I'm using latest version: v 0.16.0

### Description

When I install Stretchly works fine. However every time I reboot the system I get two error messages:
- node.dll was not found
- ffmpeg.dll was not found

![2018-04-30 10_00-stretchly exe - system error](https://user-images.githubusercontent.com/20586878/39420717-b119a088-4c5d-11e8-95f1-13bb09de55cf.jpg)
![2018-04-30 09_58-stretchly exe - system error](https://user-images.githubusercontent.com/20586878/39420718-b134d1c8-4c5d-11e8-9a84-23e8a7eacd6f.jpg)

As the errors suggests, the problem gets fixed if I reinstall the program... Until the next reboot.

Operating system: Windows 10 - 1709

### Steps to Reproduce

1. Install Stretchly
2. Reboot
3. Stretchly does not automatically start
4. When I open it manually, errors appear

**Expected behavior:** Stretchly should open

**Actual behavior:** Stretchly does not open

**Reproduces how often:** At every reboot

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by auanasgheps** [comment]
Little update:
The worst antivirus ever made (McAfee, for Enterprise) thinks that Stretchly is a malware.
![2018-04-30 10_09-mcafee endpoint security](https://user-images.githubusercontent.com/20586878/39420958-db342de2-4c5e-11e8-92cc-c3629be2e130.jpg)

I would love to get rid of it, but I'm using Stretchly on an enterprise PC.
McAfee thinks Stretchly **installer** is a malware, but I can't see any evidence in the logs that removed Strecthly files.

**Comment by auanasgheps** [comment]
2nd update:
Looks like I have resolved the problem by reinstalling Stretchly in **Program Files** and not in **AppData** as was previously done. I have done a reboot and looks fine.

**Comment by hovancik** [comment]
Hi and thanks for reporting, 

antivirus: they really don't like electron based apps ;/ many of them ;/ I haven't seen any solution for this, yet

missing files: glad you worked it out, I guess that's some windows thingy going on there
