### ISSUE TITLE
not working on high sierra...

### ISSUE THREAD

**Issue by fKing** [hovancik/stretchly#250]
### Prerequisites

- [ ] I'm using latest version: v  0.17.0

### Description

[Description of the issue]  nothing is happening (app is open in the menu bar)...

Operating system:  mac os 10.13.4

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by fKing** [comment]
it does seem to work (but perhaps the windows appear underneath whatever i am doing? will check further, and report back

**Comment by fKing** [comment]
fine after a reboot!

**Comment by hovancik** [comment]
glad it works ;]
