### ISSUE TITLE
Monochrome icons for all platforms

### ISSUE THREAD

**Issue by itay-grudev** [hovancik/stretchly#253]
Can you enable the monochrome icons for all platforms (not just OS X). For example both KDE and Windows 10 use white monochrome icons.

**Comment by hovancik** [comment]
What do other people think?

**Comment by itay-grudev** [comment]
It could be an option to switch it on or off, couldn't it?

**Comment by hovancik** [comment]
Yeah, that's the best solution ;]

**Comment by jancborchardt** [comment]
Best would be to check the operating system and use the defaults. :) Then people don't have to fiddle with settings. Ubuntu and GNOME for example use monochrome icons, and there the colored one is quite out of place ;)
![screenshot from 2018-07-29 13-47-37](https://user-images.githubusercontent.com/925062/43365994-157bef76-9336-11e8-9186-6298277d84ab.png)

**Comment by itay-grudev** [comment]
Can you propose an automatic solution for checking the _Desktop Environment_ defaults?

**Comment by jancborchardt** [comment]
Am not a programmer, but some searching showed that it might be possible via process.platform or [require('os').release()](https://nodejs.org/api/os.html#os_os_release). [Blog post](https://ourcodeworld.com/articles/read/108/how-to-get-operative-system-and-hardware-information-with-electron-framework) with more info.

There's also the library [electron-is](https://www.npmjs.com/package/electron-is) which offers `is.macOS()`, `is.windows()` and `is.linux()`, but might be too much overhead including it only for that.

**Comment by jancborchardt** [comment]
Oh and: On macOS the default is monochrome, as is on Ubuntu/GNOME. Since you mention that both Windows and KDE _also_ use monochrome icons, there probably does not need to be any checking anyway and the app should simply use monochrome icons by default? :)

**Comment by itay-grudev** [comment]
It's not as easy as that. For example windows 10 uses monochrome icons. Previous versions don't. MacOS does, but not every **Desktop Environment** on Linux (Gnome and KDE do, some of the others don't). And AFAIK there is no API to check for that. So the simplest solution is a toggle in the settings of the app or the context menu of the tray icon. Though for compatibility with new system trays app settings is the best.

**Comment by jancborchardt** [comment]
Sure, but it’s all about defaults and making it look nice for the majority initially. :)

Windows 10, macOS, Gnome and KDE all use monochrome icons, and that covers a _lot_. And for all others it’s not really bad if it’s monochrome.

_But_ it does really look out of place when it’s colored in a monochrome environment. Hence a simple change to use a monochrome icon would fix it for most environments. (Sure a setting to use a colored icon might be possible, but since the app is about relaxing, people should not need to fiddle with more settings. ;)
