### ISSUE TITLE
Asymmetric breaks

### ISSUE THREAD

**Issue by mbbmbbmm** [hovancik/stretchly#254]
Hi!
Very nice app :) 
Is it possible to configure asymmetric breaks? so for instance after 10 minutes take a micro break, after another 20 minutes take a full break? 
Thank you!

**Comment by hovancik** [comment]
Hi and thanks for feedback. 

Right now it's not possible and I don't think it will change anytime soon as it would require a big changes in internal app logic ;/

**Comment by mbbmbbmm** [comment]
I see, thanks
