### ISSUE TITLE
Reset the break timer after screensaver kicks in

### ISSUE THREAD

**Issue by jerzydziewierz** [hovancik/stretchly#255]
### Prerequisites

- [ X ] I'm using latest version: v0.17.0

### Description

Stretchly appears to not notice that I am not at my keyboard (e.g. not moving my mouse) -- I frequently get breaks right after coming back to my machine after being on a break

Operating system: macOS High Sierra 10.13.5

### Steps to Reproduce

1. Set your break schedule to e.g. every 15 minutes
2. Work for 5 minutes, then go away for 9 minutes, 
3. Come back, move the mouse to disable the screensaver

**Expected behaviour:**  The break timer starts ticking to give me a break after full new 15 minutes

**Actual behaviour:** I am getting a break nag after 1 minute

**Reproduces how often:** every time

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.
Installed from the official website
I am using a bluetooth moouse

**Comment by hovancik** [comment]
Hi, so I set up breaks to come after 15 minutes and my screensaver to start after 1 minute. I waited 10 minutes with screensaver and when I come back the tooltip was saying that next microbreak is in 15 minutes. So it works ok for me. 

Do you have monitoring of idle time turned on?

**Comment by hovancik** [comment]
If this is still issue, please let me know, I'm closing for now.
