### ISSUE TITLE
When use the block mode, not all workspaces are blocked in Mac OS X

### ISSUE THREAD

**Issue by mhewedy** [hovancik/stretchly#256]
### Prerequisites

- [x] I'm using latest version: v installed using homebrew

### Description

[Description of the issue]

Operating system: Mac OS X

### Steps to Reproduce

1. Change the setting to "Breaks are fullscreen" to on
2. Wait for the break to come

**Expected behavior:** Block happened on all workspaces

**Actual behavior:** Block happened on single workspace which make it easy to skip the break and continue working

**Reproduces how often:** alaways

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by hovancik** [comment]
Hi, on my mac 10.13.2  and one external monitor it works fine and I see break window on all screens.
  
How many external monitors do you have? 
Do you have option "breaks are show on all screens" checked? It's on last settings page.

<img width="416" alt="screen shot 2018-06-26 at 12 59 02" src="https://user-images.githubusercontent.com/4745859/41907330-cc5b1e52-7940-11e8-886f-240e826ad722.png">

**Comment by mhewedy** [comment]
Yes, I have this option "breaks are shown on all screens" checked. I think it comes checked by default.

Note, I am not talking about all monitors, I am talking about all workspaces within my mac book bro monitor. ( I am not attaching external monitor in this case)

**Comment by hovancik** [comment]
Gotcha. I have found API for this so I will take a look whether it works.  

https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winsetvisibleonallworkspacesvisible

**Comment by mhewedy** [comment]
Note, the same function works fine on windows 10 

This is what I mean by workspace (but since I don't have mac in my work, I screenshotted my windows workspaces)

![stretchly](https://user-images.githubusercontent.com/1086049/41909009-86890ba6-794e-11e8-9907-005bf1ec07f7.png)

**Comment by mhewedy** [comment]
@hovancik , it is working as expected on windows, the issue only occurs on mac. Shall I open this issue on electron instead?

**Comment by hovancik** [comment]
@mhewedy The API I mentioned is not used right now in stretchly, so no need to open issue with electron, yet. I will test turning it _on_ and we shall see. Electron's docs don't mention whether it's on or off by default.

**Comment by mhewedy** [comment]
@hovancik I tried the function you mentioned but didn't manage to get the issue solved.

**Comment by hovancik** [comment]
how did you do it? I haven't had time yet...

**Comment by mhewedy** [comment]
I called the method setVisibleOnAllWorkspaces(true) in two places, once for the BrowserWindow object at initialization time (exactly after the constructor, after this line https://github.com/hovancik/stretchly/blob/master/app/main.js#L317)

And called the same method on the same object in the 'ready-to-show' event after this line: https://github.com/hovancik/stretchly/blob/master/app/main.js#L320

And in both cases, the issue still exists.

**Comment by mhewedy** [comment]
It seems we have a complex issue:

Call to `BrowserWindow.setFullScreen` should be avoided, because it sends stretchly to a new workspace itself (i.e. as if you click the mac maximize button without click on the alt button). Instead we can resize the BrowserWindow to fill the screen.

Still One issue remaining is to hide mac menubar and dockbar

here's diffs

```
Index: app/main.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- app/main.js	(revision c9d960eeb801921820ad36435717e7c4cc204936)
+++ app/main.js	(date 1530212152000)
@@ -302,9 +302,11 @@
   if (settings.get('ideas')) {
     idea = breakIdeas.randomElement
   }
+  const electron = require('electron');
 
   for (let displayIdx = 0; displayIdx < numberOfDisplays(); displayIdx++) {
-    let breakWinLocal = new BrowserWindow({
+
+    const options = {
       icon: `${__dirname}/images/stretchly_18x18.png`,
       x: displaysX(displayIdx),
       y: displaysY(displayIdx),
@@ -314,17 +316,26 @@
       skipTaskbar: true,
       focusable: false,
       title: 'stretchly'
-    })
+    }
+
+    if (settings.get('fullscreen')) {
+      const displaySize = electron.screen.getAllDisplays()[displayIdx].size
+      options.width = displaySize.width
+      options.height = displaySize.height
+    }
+
+    let breakWinLocal = new BrowserWindow(options)
+
     // breakWinLocal.webContents.openDevTools()
     breakWinLocal.once('ready-to-show', () => {
       breakWinLocal.show()
-      breakWinLocal.setFullScreen(settings.get('fullscreen'))
       if (displayIdx === 0) {
         breakPlanner.emit('breakStarted', true)
       }
       breakWinLocal.webContents.send('breakIdea', idea, settings.get('breakStrictMode'))
       breakWinLocal.webContents.send('progress', Date.now(), settings.get('breakDuration'))
       breakWinLocal.setAlwaysOnTop(true)
+      breakWinLocal.setVisibleOnAllWorkspaces(true)
     })
     breakWinLocal.loadURL(modalPath)
     breakWins.push(breakWinLocal)

```

**Comment by hovancik** [comment]
I see. Could you push your code and make a pr so I can play with it as well?   

And have you tried it on electron-quick-start? Does it behave the same?

**Comment by mhewedy** [comment]
Mac contains two types of workspaces:

* Application-created:
![application-created](https://user-images.githubusercontent.com/1086049/42091982-fb5d6f18-7baf-11e8-92ee-0d1a24b75220.png)
* vs User-created:
![user-created](https://user-images.githubusercontent.com/1086049/42091988-00a2eda4-7bb0-11e8-8841-a24778b5687e.png)

The following table illustrates the diff between stretchly and electron-quick-start regarding specific features:

| Feature   |      stretchly      |  electron-quick-start |
|----------|:-------------:|------:|
| `setFullScreen` create a application-created ws|  yes | yes |
| `setVisibleOnAllWorkspaces` make the app visiable on user-created workspaces|    yes   |   yes |
| `setVisibleOnAllWorkspaces` make the app visiable on other application-created workspaces | yes |    no |

**Comment by mhewedy** [comment]
Any updates on this from your side?

**Comment by mhewedy** [comment]
Good luck for your interview 👍 👍

**Comment by hovancik** [comment]
Thanks,  I have moved interview for tomorrow, probably :D

Anyway, I have tried your PR and it seems that we can not put window over whole screen in that way ;[ At least I haven't found one ;[ 

there is also 
```
      breakWinLocal.setSimpleFullScreen(true)
      breakWinLocal.setVisibleOnAllWorkspaces(true)
```
that is a bit better but the titlebar is still visible and skipping break text often gets hidden by bar ;[ 

So I guess what we can try is to open issue in electron and ask them to make  `setVisibleOnAllWorkspaces` and `setFullscreen` both turned on behave in such a way that there is no escape from app that is fullscreen.

**Comment by hovancik** [comment]
Or maybe there is hope

I'm just trying ` breakWinLocal.setKiosk(true)` and it seems to work. 

I remember it not doing anything long time ago, so maybe they fixed it?

**Comment by mhewedy** [comment]
Woooow!
`setKiosk(true)` looks like it is the one!

**Comment by hovancik** [comment]
Would you like to update PR so that we only update `setFullscreen` to `setKiosk` ? 

I've tested on linux and it's broken, but the fullscreen is as well (https://github.com/electron/electron/issues/11632) 

I have to test on Windows

**Comment by mhewedy** [comment]
@hovancik I noticed that the `setKiosk(true)` works as expected only in the electron-starter, not in stretchly, I am trying to find out why!

**Comment by hovancik** [comment]
It seemed to work from me. What I did was to replace `setFullscreen` with `setKiosk`. But not with your changes,  I did it  in master.

**Comment by mhewedy** [comment]
Have you tried to press ALT+TAB?

**Comment by hovancik** [comment]
Yes, that is able to workaround fullscreen break ;[ Unless electron devs come up with some mode where fullscreen is always fullscreen and on top, I don't think we can fix that ;/

**Comment by hovancik** [comment]
@mhewedy will you update your PR to use kiosk mode as I mentioned so we can have you as contributor? 

I think the most we can do now is to keep behavior as it was before but use Kiosk, not Fullscreen. Will still need to check on Windows and Linux...

**Comment by mhewedy** [comment]
@hovancik Sorry for being late, currently I am too busy, in one or two days I should be resume working on this issue.

**Comment by hovancik** [comment]
No problem ;] take your time

**Comment by pjebs** [comment]
I think there is a setting in the app mac app bundle plist that helps but  I can't remember what it was.
