### ISSUE TITLE
start using querySystemIdleTime upon update to electron@3.0.0

### ISSUE THREAD

**Issue by lundibundi** [hovancik/stretchly#258]
New electron version added chromium bindings for [system idle time](https://github.com/electron/electron/pull/11807) so consider using them upon update to the new Electron. ([Electron release notes](https://github.com/electron/electron/releases/tag/v3.0.0-beta.1))

Also, I tried updating electron in stretchly to beta version and it seemed to work just fine, though I couldn't get paulcbetts/node-system-idle-time to work properly, so I just disabled natural breaks in configuration. Other than that I haven't noticed any issues, though I didn't thoroughly checked it.

**Comment by hovancik** [comment]
Small update: there is a bug with electron 3: https://github.com/electron/electron/issues/15161 so I am still using version 2 for now.
