### ISSUE TITLE
resumes from manual pause upon system resume

### ISSUE THREAD

**Issue by lundibundi** [hovancik/stretchly#259]
### Prerequisites

- [x] I'm using version: master at c9d960eeb801921820ad36435717e7c4cc204936 with https://github.com/hovancik/stretchly/pull/233 merged in.
- [x] I'm using version: master at c9d960eeb801921820ad36435717e7c4cc204936.

### Description

Stretchly resumes manual pause upon resume from suspend.

Operating system: Arch linux

### Steps to Reproduce

1. Start app
2. Select pause for 1 hour in menu
3. Suspend the pc
4. Resume from suspend

**Expected behavior:** Stretchly should stay paused

**Actual behavior:** Stretchly is no longer paused

**Reproduces how often:** always

Based on code inspection and in particular `keepAfterPowerResume` this seems to be the intented behavior but this seems wrong to me, so I suggest to change it to preserve any user breakand not only indefinite break. What do you think?

Also as there is currently no way to correct break time after resume from suspend (for example user start 1 hour pause, then suspends the pc for 2 hours and if not for the aforementioned behavior stretchly would still be paused) I suggest to add such correction mechanism to power-state listemers and breakPlanner. This may be done with simple system suspend time logging and then computing passed time upon resume to use for correction.

**Comment by hovancik** [comment]
I'm not absolutely sure, but I believe that I only used it for indefinite break because when in suspend/sleep the timer is not changed. So ie. when user pauses for 2 hours and after 1 hour suspends for 3 hours, when he come back the timer is at 1 hour. 

So yeah, if I understand you correctly: 

```
This may be done with simple system suspend time logging and then computing passed time upon resume to use for correction.
```
you would: 
on suspend - remember time
on resume - calculate suspended time and recalculate timer for break restart

Do I understand correctly?

**Comment by lundibundi** [comment]
@hovancik yes, that's correct.
Though this may be a problem for mac os/windows as the power monitor in electron still doesn't seem to work correctly on those platforms (based on electron issues), so we may have to leave the previous behavior for them or use something like [this](https://blog.alexmaccaw.com/javascript-wake-event) to detect suspend/wake.

**Comment by hovancik** [comment]
I will test but it might take time ;[ Also I will check code. I'm slowly getting to close/merge all remaining PRs but time is time :D
