### ISSUE TITLE
Dutch translation

### ISSUE THREAD

**Issue by Sveijk** [hovancik/stretchly#261]
### Prerequisites

- [x] I'm using latest version: v 

### Description

translating Stretchly for Dutch language

Operating system: MacOS High Sierra version 10.13.3

**Comment by hovancik** [comment]
👍 go for it

**Comment by Sveijk** [comment]
Thank you :-)

2018-07-04 14:10 GMT+02:00 Jan Hovancik <notifications@github.com>:
