### ISSUE TITLE
Minimization of window of mac is not working

### ISSUE THREAD

**Issue by aleuca** [hovancik/stretchly#264]
### Prerequisites

- [x] I'm using latest version: v 

### Description

When you maximize a Stretchly window on mac there is no obvious way to minimize it again aside from quitting the app.

Operating system: 

### Steps to Reproduce

1. Open an About window
2. Maximize window
3. Try to minimize window

**Expected behavior:** When mouse is hovered on top the toolbar should appear. Shortcuts like command+M and command+option+H should minimize the window.

**Actual behavior:** The toolbar does not appear on top of the screen if you hover the mouse. Shortcuts like command+M and command+option+H also don't minimize the window.

**Reproduces how often:** 100% observed

**Comment by hovancik** [comment]
What window do you mean?

**Comment by hovancik** [comment]
This is more complicated task. It relates to #154 . We would need to research how electron and system shortcuts works. 

Anyway, what I have noticed on Linux is that there is no maximize on About window.
