### ISSUE TITLE
Hard to click checkbox in settings

### ISSUE THREAD

**Issue by fizvlad** [hovancik/stretchly#272]
### Prerequisites

- [x] I'm using latest version: v 0.17.0

### Description

One of checkbox is hard to click because it covered with "Back" button

Operating system: Win8.1

### Steps to Reproduce

1. Choose Russian language
2. Go to 3rd step of Settings ("Настройки")

**Expected behavior:** User is able to click checkbox on screenshot

**Actual behavior:** Hard to click because of "Back" button

**Reproduces how often:** Always (100%)

### Additional Information

Screenshot:
![stretchly](https://user-images.githubusercontent.com/26169149/42733374-26c90258-8839-11e8-8cde-c6214fa3fd2e.png)

### Possible ways to fix

* Change CSS parameters (Add left and right padding probably?)

**Comment by hovancik** [comment]
Thanks for the report ;] As you said, we can easily fix this with css.

**Comment by hovancik** [comment]
@sm-g to be honest, no idea. should they be? Not sure if there is recommended way to do this but default way of how HTML behaves is that only checkbox is clickable

**Comment by sm-g** [comment]
Of course they should! You must be using checkboxes in every OS or website (github ie). Every ui ecosystem has guidelines, you may check any.

**Comment by sm-g** [comment]
Also, please do not make list of checkboxes inline
