### ISSUE TITLE
Tray icon sizing issue on GNOME/Ubuntu

### ISSUE THREAD

**Issue by jancborchardt** [hovancik/stretchly#279]
### Prerequisites

- [x] I'm using latest version: v0.17.0

### Description

The tray icon seems to be too small and shows repeated on the right of it:
![screenshot from 2018-07-29 13-47-37](https://user-images.githubusercontent.com/925062/43366021-71a23a62-9336-11e8-8baf-6752c226e51c.png)

Operating system: Ubuntu 18.04 with GNOME 3.28.1

### Steps to Reproduce

Happens always. Found no workaround yet.

**Comment by hovancik** [comment]
Hi this a know electron issue unfortunately. https://github.com/electron/electron/issues/12791

**Comment by ErroneousBosch** [comment]
My icon is completely missing in Gnome. I tried removing the .config/stretchly dir, but it didn't seem to fix anything. Running vanilla gnome in X on Ubuntu 18.04.

**Comment by hovancik** [comment]
@ErroneousBosch https://github.com/hovancik/stretchly#linux-note try this

**Comment by ErroneousBosch** [comment]
Unfortunately, already installed in latest version

**Comment by ErroneousBosch** [comment]
Just an update:

I found a solution for my issue (at least for Ubuntu 18.04, Gnome 3.28.2), with a caveat. 

1. Don't use the AppIndicator plugin from the Gnome Extensions site. Go to the github and [Download the release appropriate to your version of Ubuntu](https://github.com/ubuntu/gnome-shell-extension-appindicator/releases) and extract to:
`~/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com`
Then enable it. You may need to restart Gnome.

2. Edit the `/usr/share/applications/stretchly.desktop` file. Change:
`Exec="/opt/stretchly/stretchly" %U`
to
`Exec=/usr/bin/env XDG_CURRENT_DESKTOP=Unity "/opt/stretchly/stretchly" %U` 

I now get the icon, which I thought was not working at first, but (caveat) in actual fact is rendering as black on black in my theme. Would love to get the option to either switch colors in the app, or switch back to the old rainbow icon in the app.

**Comment by ErroneousBosch** [comment]
And I just now found the option to use the rainbow Icon in settings. Everything working perfectly for me!

**Comment by hovancik** [comment]
Awesome ;] 

I'm using XFCE and icon is also now correctly sized for me, but no idea what package upgrade caused it.
