### ISSUE TITLE
Blur effect on window for nicer integration

### ISSUE THREAD

**Issue by jancborchardt** [hovancik/stretchly#280]
### Prerequisites

- [x] I'm using latest version: v0.17.0

### Description

Currently the popover is a very stark contrast to the work environment and looks quite out of place, no matter the theme.

What might be cool is a blur effect on the overlay window which nicely puts it on top of your current work. There is a package called [electron-vibrancy](https://www.npmjs.com/package/electron-vibrancy) which does just that:
![](https://i.imgur.com/42jOnRV.png)

Currently supports Windows and macOS, an issue for Linux support is open at https://github.com/arkenthera/electron-vibrancy/issues/12

**Comment by hovancik** [comment]
I'll try it and add screenshot here to see what people say.

**Comment by hovancik** [comment]
I'm trying from readme: 

`  electronVibrancy.SetVibrancy(mainWindow, 0);` and it exists whole app without error

`electronVibrancy.SetVibrancy(true,browserWindowInstance.getNativeWindowHandle());` gives error `window.getSize is not a function`

If anyone has more success let me know here

**Comment by Sveijk** [comment]
Maybe we could add this issue to RGSoC project @hovancik ? Suggestion of @aleuca since we're now also looking into the custom changing of break background issue which is in the project.

**Comment by hovancik** [comment]
:+1:

**Comment by hovancik** [comment]
It is now supported in electron (for mac) but I would prefer it being the same on all platforms

https://electronjs.org/docs/api/browser-window#winsetvibrancytype-macos

**Comment by hovancik** [comment]
I don't think this will get implemented so closing.

**Comment by Korb** [comment]
> a blur effect on the overlay window which nicely puts it on top of your current work

Am I correct in understanding that you suggested applying a blur effect to the entire image outside the main rest notification window? That is, all currently open windows and notifications during the rest period will no longer be readable, but will be guessed. If so, that's a great suggestion.

I'll supplement it with a suggestion to add a setting to reduce the brightness of windows and the desktop outside the window notifying about the current rest.

**Comment by SophiaSaiada** [comment]
I found a simple solution to implement it on MacOS (I don't know if it'll work on windows).
Is it OK to open a PR for that?
