### ISSUE TITLE
Afk recognision.

### ISSUE THREAD

**Issue by Matsku12** [hovancik/stretchly#282]
Program should have option to recognise if watching vlc player or netflix and not counting that in so it wouldnt start breaks while watching something. It could work propably best if it detects that mouse and keyboard or controllers havent been used for couple of minutes.

**Comment by hovancik** [comment]
Hi, stretchly already takes idle time into account (mouse and keyboard activity). But as your example with VLC says, for some reason OS does not count that as idle time... So there is nothing I can do about it... 

With new release of electron, we will have new way of detecting idle time, so maybe something will change then (https://github.com/hovancik/stretchly/issues/258)

**Comment by douglasg14b** [comment]
A simple idea:

Use mouse & keyboard hooks (At least in windows). And record the amount of mouse and keyboard activity with some thresholds that denote active vs inactive.

There is a lot that could go into that, but some simple things like infrequent and short mouse movements, or the use of the spacebar only on the keyboard might indicate that the user is doing something idle.

**Comment by Matsku12** [comment]
If you are going to add that would be super cool if you could also add at least xbox one controller to that list. I love this program and I play much so would be nice that those gaming sessions would also have breaks. 

Also I dont know is it possible that program would notice afk time and instead of resetting whole counter the clock would just stop. I am using computer very much, but I would want that watching movies and videos would not count that time, but other things would have breaks. Thats mostly, because I keep natural breaks when watching something, but doing other things its easy to forget.

**Comment by hovancik** [comment]
I'll wait for the new way of watching idle time with new electron release and we will see how it behaves

**Comment by hovancik** [comment]
Hi all, I am closing this in favor of #389 where possible functionality is being discussed.
