### ISSUE TITLE
Request-password protect, prevent closing?

### ISSUE THREAD

**Issue by p520504** [hovancik/stretchly#286]
Using stretchly v0.17.0 + Windows 7/10.

I want to setup stretchly in a way that user can not quit/change setting in strict mode.

I hope a password feature can be added in, such that when one clicked on the stretchly icon, a password needed to be entered before proceeding any further.

Also, if possible, I hope there is a way to prevent a standard user from terminating stretchly in task manager.

Thank you

**Comment by p520504** [comment]
yes, for sys admin ...to force standard user to take a rest

**Comment by hovancik** [comment]
added in #476

**Comment by hovancik** [comment]
Hi, I am closing this as there is pretty much zero chance I will ever get back to this. Sorry :(

I am marking with label if I ever have never ending amount of free time.
