### ISSUE TITLE
Change the tray icon when Stretchly is paused

### ISSUE THREAD

**Issue by p-himik** [hovancik/stretchly#287]
### Prerequisites

- [x] I'm using the latest version: v0.17.0

### Description

Right now, if you pause Stretchly the icon stays the same even if the pause if indefinite. This say, it's really easy to forget about the pause.
I think, changing the icon in some way (e.g. graying or striking it out like Workrave does) during the pause would be helpful.

**Comment by hovancik** [comment]
yeah, I was thinking about this from beginning, but to be honest, I am not capable of creating icons :D not good with graphics 

stretchly RGSoC students will try to look into this how many icons we need and if they can create them

**Comment by FanciestW** [comment]
I would like to help, I see that this issue a good first issue and being that I am still new to open source contribution I would love to start with this issue. I think I can get some work done to:

* Mock up possible "paused" tray icons 
(I'm not a designer but I work with a team of very talented designers)
* Add in the code needed to change the tray icon when Stretchly is paused
* And finally submit it for review

What do you think? May I work on this issue? Are there any deadlines?

**Comment by hovancik** [comment]
Hi @FanciestW and thanks for your interest! What you wrote makes sense ;] I would be very happy to help you! 

There is no deadline, so if you can post some mockups of icons, that would be great. 

Only one thing comes to my mind: the colorfull icon that we use right now is not done very well (it's not svg, and there are some problems with borders and so.) Maybe you could start with that? Not sure how hard that would be, but you could ask the designers if you have access to some ;]

**Comment by FanciestW** [comment]
@hovancik You got it! I am taking the colorful icon from the root directory of the project and editing it to fix the borders and also convert it into an SVG. I removed the shadow of the colorful icon and also cleaned up the border. Here is a mockup (PNG) before I convert it to a SVG.
![stretchly_128x128_edit2](https://user-images.githubusercontent.com/9480166/47922586-cadc7280-de8d-11e8-8725-9cee31c5a0f7.png)

**Comment by hovancik** [comment]
Looks nice!

**Comment by FanciestW** [comment]
What do you thinks of these paused SVG icons for Stretchly? I can't upload a SVG but below are the two SVGs converted into PNGs. 
I took Stretchly tray icons and just added a pause icon on top. I followed the design pattern of Microsoft OneDrive on how they overlay a pause icon when you pause syncing on OneDrive.
Let me know which one of the two paused icons you like better. 😄 
<img width="26" alt="screen shot 2018-11-05 at 11 32 03 pm" src="https://user-images.githubusercontent.com/9480166/48043138-11aebe80-e153-11e8-90b5-68a1ce5d87f7.png">
![stretchly 2](https://user-images.githubusercontent.com/9480166/48043037-6b62b900-e152-11e8-97b6-a50e8fd56d70.png)
![stretchly_v2](https://user-images.githubusercontent.com/9480166/48043038-6b62b900-e152-11e8-9adf-91510e83419c.png)

**Comment by FanciestW** [comment]
Will the colorful icon be updated when the Stretchly is paused? My understanding was that only the tray icon will be updated to show the paused status.

**Comment by hovancik** [comment]
default icon is the monochrome, but users can choose to use colorful one (they look better on Windows and Linux)

**Comment by FanciestW** [comment]
Ignore the above un-finished garbage, here is the finished versions:
(Without Shadow)
<img width="735" alt="screen shot 2018-11-11 at 11 04 25 pm" src="https://user-images.githubusercontent.com/9480166/48326246-3ea51a80-e606-11e8-9771-e5a83b5ed3a9.png">
(With Shadow)
<img width="735" alt="screen shot 2018-11-11 at 11 08 44 pm" src="https://user-images.githubusercontent.com/9480166/48326336-cee35f80-e606-11e8-9a1b-980d0a00ff21.png">

**Comment by hovancik** [comment]
@FanciestW wow, this is amazing! I really appreciate your work!  

I like the one with shadow more ;] the change from S to colors seems more natural to me ;]

**Comment by FanciestW** [comment]
@hovancik Okay I will export both version into a PNG and SVG. However, I have run into an issue when I export as an SVG. The exported SVG gets all messed up. I'm not sure if it is an issue with Sketch or just the way I made the icon. But I will send it to some graphic designers to diagnose the issue. I'll keep you updated. Thank you!

**Comment by FanciestW** [comment]
Thanks to my more creative friend was able to get it working and has exported it as an SVG. Sorry it took a while but I will open a PR with the new colorful icon as SVG.

**Comment by hovancik** [comment]
That sounds great!

**Comment by hovancik** [comment]
Looks great ;] 

The only think I am not sure is whether we should use the same "pause" style for monochrome as in colorful one. What do you think? 

I am leaning toward using the same style (meaning reuse pause style from monochrome)

**Comment by FanciestW** [comment]
Does this look okay? It was harder to design it this way because of all the colors so I didn't know what colors to use for the background color of the pause symbol. Let me know if there is anything I can change for you :)

![asset 1_v1](https://user-images.githubusercontent.com/9480166/49890025-09f8ce80-fe11-11e8-89bf-85ce28d61cc4.png)

**Comment by FanciestW** [comment]
![asset 1_done](https://user-images.githubusercontent.com/9480166/49890053-1aa94480-fe11-11e8-92cd-11c64df98996.png)

**Comment by FanciestW** [comment]
I was thinking what you were thinking, I went ahead and made a transparent pause button version. I can make it more or less transparent. Right now it has a 50% opacity. I think it looks good and the icon will be made much smaller when it is in the task bar.

![asset 1_transparent](https://user-images.githubusercontent.com/9480166/49953762-d4b1b680-fecc-11e8-9c21-4f6312f3a360.png)

**Comment by hovancik** [comment]
Looks good to me as well ;] We'll see when we test it ;]

**Comment by hovancik** [comment]
Implemented in #474
