### ISSUE TITLE
Can't find Stretchly settings menu

### ISSUE THREAD

**Issue by gordon556** [hovancik/stretchly#289]
I just had my IT support help me install Stretchly today on my work computer (Windows 10), using his administrative login. It seems to be running with default settings now but I don't know how to access the settings menus I see on the Stretchly screenshots to customize it (like setting time between breaks, or pausing the app). Can someone point me in the right direction? Thank you!

**Comment by hovancik** [comment]
hi, you should see stretchly icon in tray menu and when you click on it, you will get menu

**Comment by gordon556** [comment]
Now I see it! I can get to it by right-clicking on the icon down in the system tray. Thank you!

**Comment by hovancik** [comment]
great !
