### ISSUE TITLE
Logo spacing

### ISSUE THREAD

**Issue by Hum4n01d** [hovancik/stretchly#294]
### Description

I opened up [stretchly.svg](https://github.com/hovancik/stretchly/blob/master/stretchly.svg) and found a strange space around the logo path.

**Expected behavior:** [What you expect to happen]

![screen shot 2018-09-08 at 3 37 59 pm](https://user-images.githubusercontent.com/17228477/45259259-2d792c80-b37d-11e8-9e47-f11b35dfa4e8.png)

**Actual behavior:** [What actually happens]

![screen shot 2018-09-08 at 3 38 15 pm](https://user-images.githubusercontent.com/17228477/45259261-37029480-b37d-11e8-86ee-1cc4c5480d81.png)

### Additional Information

This may cause many problems, including #293

**Comment by hovancik** [comment]
Thanks! Feel free to create a PR

**Comment by Hum4n01d** [comment]
Will do when I get a chance :smile:

**Comment by Hum4n01d** [comment]
Will do when I get a chance :smile:
