### ISSUE TITLE
Prevent closing screen

### ISSUE THREAD

**Issue by pjebs** [hovancik/stretchly#296]
I was wondering how you managed to prevent the user from pressing `Cmd-W` to close the screen without using Kiosk mode?

**Comment by hovancik** [comment]
I bet it's some weird electron thing. `cmd+q` closes the window for me (macOS).

**Comment by pjebs** [comment]
How come you aren't using kioskmode?

**Comment by hovancik** [comment]
I wanted to use it for fullscreen, but I had some issue with it, not working correctly with some option I needed or Operating System, don't remember 

 But I might start using it, see #256

**Comment by hovancik** [comment]
I'm using kiosk mode now for fullscreen
