### ISSUE TITLE
Countdown display on the interval notification

### ISSUE THREAD

**Issue by GHNalk2016** [hovancik/stretchly#301]
### Prerequisites

- [ ] I'm using latest version: v0.17.0

### Description

Either as a system tray notification like now, or as a separate message it would be great to have a countdown before a break. When you're in the middle of a important work that would help to handle the situation more smoothly. I previously used "Eyes Relax" which had this functionally: https://themech.net/eyesrelax/

Operating system: Windows 10 Pro 1703

**Comment by hovancik** [comment]
Hi, new feature is coming soon, where in tray menu you will see time of the next break ;] hope that it fixes your issue

**Comment by GHNalk2016** [comment]
Hi  hovancik,

Do you mean in the task bar area of the system tray (like how windows shows time and date)? That would be great if possible.

**Comment by hovancik** [comment]
That's not possible with electron ;/ 

What was added is message containing time and type of next break when you click on tray icon.

**Comment by GHNalk2016** [comment]
Can a countdown be added on the system tray popup?

**Comment by hovancik** [comment]
Can you explain how you mean it? I'm not sure

**Comment by GHNalk2016** [comment]
Currently, stretchly shows a small popup message to notify before a break (like it shows in the image here: https://github.com/hovancik/stretchly/issues/111). So can it counts down the number of seconds inside that message, like "Microbreak in 30 seconds", "Microbreak in 29 seconds", 28, 27, etc.?

**Comment by hovancik** [comment]
I gotcha, I checked the [docs](https://electronjs.org/docs/tutorial/notifications) and it does not seem to be possible ;/

**Comment by GHNalk2016** [comment]
OK, thanks for the time anyway 👍
