### ISSUE TITLE
Option to automatically postpone break when typing

### ISSUE THREAD

**Issue by nicolae-stroncea** [hovancik/stretchly#302]
A lot of the time, it's very frustrating to be coding something, and have stretchly block the screen offering a break. An option for stretchly to initiate the break later, once there's some sort of typing break(let's say 5 seconds), would be appreciated.

**Comment by hovancik** [comment]
Hi, we are thinking about implementing something like that in #189, feel free to subscribe there to get updates, but it's not coming any time soon (might be months or more)
