### ISSUE TITLE
Didnt work on Fedora 29

### ISSUE THREAD

**Issue by tim77** [hovancik/stretchly#303]
### Prerequisites

- [x] I'm using latest version: 0.17.0 

### Description

Segmentation fault.

Operating system: Fedora 29 x64

**Comment by hovancik** [comment]
HI, can you show some screenshot? Or segmentation fault is everything you see? 

How did you install?

**Comment by tim77** [comment]
Hi! I installed Stretchly RPM package:
`sudo dnf install ./stretchly-0.17.0.x86_64.rpm`

Then when i run Stretchly:
`stretchly`

I got this:
`Segmentation fault`

![Screenshot](https://user-images.githubusercontent.com/5614476/46914923-14cbea00-cfad-11e8-876f-7896d4fe5061.PNG)

**Comment by hovancik** [comment]
I don't have a Fedora but will try to create some VM when I have a time

**Comment by hovancik** [comment]
@tim77 can you try with new version? 0.18.0

**Comment by hovancik** [comment]
great to hear that!
