### ISSUE TITLE
Minimalist Mode

### ISSUE THREAD

**Issue by CristianAven** [hovancik/stretchly#305]
It will be very useful to have a minimalist mode, wich shows only a small message and not a almost-full screen message. This because in my work, people keep asking me why I'm watching the big green message and not working.
Also, it must lock the user actions, because it won't hide the active text or window.
I think this can be done with a transparent full screen object and a small message on the middle.

Thanks :)

**Comment by hovancik** [comment]
I'll try to look into this, but with my free time available, not gonna happen any time soon ;/

**Comment by hovancik** [comment]
Hi, I am closing this as there is pretty much zero chance I will ever get back to this. Sorry :( 

I am marking with label if I ever have never ending amount of free time.
