### ISSUE TITLE
Create longer breaks

### ISSUE THREAD

**Issue by 183amir** [hovancik/stretchly#31]
Hi, thank you for this great app. I was using workrave but that is really showing its age.

How hard would be to implement longer breaks?

Thanks.

**Comment by hovancik** [comment]
Hi, how you like to longer breaks to work? I can image few systems how it could work...

**Comment by 183amir** [comment]
Ideally I want what http://www.workrave.org/ does. It has two breaks: microbreaks, and longbreaks.
Every 10 minutes gives 20 seconds microbreaks by default (which I disable).
Every 45 minutes gives 10 minutes breaks which I use all the time.

**Comment by hovancik** [comment]
I will think about mechanism and how to implement it and try to do it ASAP. I will probably write here for more feedback.

**Comment by hovancik** [comment]
So this is still WIP because I am making some changes about how stuff works internally. If you wanna, checkout to `topic` branch and try it out. It's my playground, so i am force pushing there, so hard reset might be needed when I update the branch. 

Feedback welcome ;]
