### ISSUE TITLE
Add possibility to translate breaks/microbreaks

### ISSUE THREAD

**Issue by pwolaq** [hovancik/stretchly#310]
AFAIK there is no possibility to translate the default ideas for brake/microbreak. It would be nice to have this feature.

**Comment by hovancik** [comment]
Hi, you can't translate them in app itself, but can do that via editing config file: https://github.com/hovancik/stretchly#editing-breakmicrobreak-ideas

**Comment by dbtek** [comment]
Hi @hovancik, thanks for the stretchly and all the good work. I'm very happy with it.

How about implementing translation of ideas with [object & array translations](https://www.i18next.com/translation-function/objects-and-arrays)?

Something like this could work I guess:

```json
// en.json
{
  "microbreakIdeas": [
      "Go grab a glass of water.",
      "Slowly look all the way left, then right."
   ],
   "breakIdeas": [{
      "title": "Not alone",
      "content": "Do you find it hard to take a break alone? Try to do it with a co-worker. Aside from making it easier to stick to breaks, you will have a chance to get to know them better/. Taking breaks together increases productivity."
   }]
}
```

```js
// main.js
microbreakIdeas = i18next.t('microbreakIdeas', { returnObjects: true })
breakIdeas = i18next.t('breakIdeas', { returnObjects: true })
```

**Comment by hovancik** [comment]
Hi and thanks for the idea ;] 

My plan is first to find some way to work with translations via some online service... Working with PRs kinda sucks: translations are hard to track and easy to get outdated ;/ 

After I solve this I wanna add translations for Break ideas. (Also I would like to stabilize break ideas first, they will need some work to make them better)

**Comment by dbtek** [comment]
I see. Absolutely agree with you on difficulty of tracking updates for all
locales.

**Comment by Kadilov** [comment]
I have had a look at some comparison charts and it seems that [POEditor](https://poeditor.com) has a useful free plan for "1000 strings". Currently Stretchly needs 44*22=968 strings for breaks/microbreaks ideas for potential translations in all existing localizations (this calculation works if theirs "string" can be long enough for 1 break idea).

**Comment by hovancik** [comment]
I've tried few online services (POEditor as well) but I did not like any of them. Can't really tell why, but they all seemed kind of clunky and difficult to work with.  

But I think I know how I want to solve "the ability to translate break ideas": 

Stretchly users will be able to choose "sources" of break ideas
- probably github repos urls 
- there could be break ideas in different languages
- break ideas for usage in schools, wherever
- funny break ideas... 

This will solve few usecases that people asked for with custom break ideas for their company or whatever. 

Will need a lot of thoughts, first ;] This is rough idea

**Comment by Yoneo** [comment]
Here are a lot of ideas. In my eyes, the most important and easiest task would be to show the break ideas depending on the selected language in settings.

![image](https://user-images.githubusercontent.com/26109315/99901965-ac3ab580-2cba-11eb-8d77-7432074b311b.png)
If you need help with the german translation, let me know!

**Comment by hovancik** [comment]
Yeah that would be ideal. The problem is that with every release I add new breaks and then everything is outdated very fast ;/ 

I am trying some online services to make translating easier so let's see.

**Comment by fspade** [comment]
I've translated the Microbreaks to German with MS Visual Studio and saved it. I then restarted Strechly, but my translations are not shown. What am I missing?
To handle the issue with updates, would it be an option to offer a subfile, where local translations are stored and when a new release with new breaktypes comes, check the breaks in the subfile by name if it is defined include those virtually. That way both can coexist and the user can see, where local translations are needed.

**Comment by hovancik** [comment]
Hi @fspade , I replied to your email. 

With translations, I am still not sure how to handle it. The biggest issue is that translations get out of date very fast ;/ Translators get interested and then never come back :) I still probably think the best would be to add external sources of break ideas (as some poeple wanted to separate "funny" ideas, "excercices", "mental breaks" etc)

**Comment by AssafKatz3** [comment]
Hi,
1. This isn't only matter of translation, Hebrew for example require RTL support
2. Since the message address the user, they must be gender depended for some languages (e.g. Hebrew)
3. This requested support won't replace the customization of ideas, only just replace the default
Thanks

**Comment by Chealer** [comment]
I do not see break ideas in Stretchly 1.7.0. Which is a shame, since I've been wishing for something like that for years. Was this feature removed?

**Comment by AssafKatz3** [comment]
> . Which

Hi,
I see them (at Windows), check useIdeasFromSettings at your config.json.
Regards

**Comment by Chealer** [comment]
> 
> Hi,
> I see them (at Windows), check useIdeasFromSettings at your config.json.
> Regards

That option was set to `false`, but setting it to `true` has no effect that I can see.

Are break ideas supposed to be disabled by default?

**Comment by hovancik** [comment]
No, break ideas are enabled by default. Please open new issue if you have problems not related to this issue.

**Comment by sr258** [comment]
@hovancik Do you have any thoughts on the break ideas "sources" you wrote about [here](https://github.com/hovancik/stretchly/issues/310#issuecomment-557877850)?

**Comment by hovancik** [comment]
Hi @sr258 , I am currently working on prototype "Stretchly for Web" aka simple running version from Browser and I wanna test the idea of break ideas from url/repo there. When it's in likeable form, I will copy it to regular Stretchly as well.

**Comment by hovancik** [comment]
So I decided to add this via regular translations for now. Let's see how it will go.
