### ISSUE TITLE
Ubuntu 18.04 Only half break screen is shown

### ISSUE THREAD

**Issue by RaghavendhraK** [hovancik/stretchly#311]
Hi,
OS: Ubuntu 18.04 LTS.
Stretchly version: 0.18.0

In this system, whenever a break screen appears, that too on multiple monitor, only the first half of the break screen is shown in the screenshot.
![screenshot from 2018-10-22 18-42-45](https://user-images.githubusercontent.com/2741110/47294688-6d455c00-d62b-11e8-9ad4-d28dea70b172.png)

But If we click on any other screen, like about, settings of the stretchly page, then the break screen corrects itself and shows nicely on both monitor. 
![screenshot from 2018-10-22 18-43-52](https://user-images.githubusercontent.com/2741110/47294653-59015f00-d62b-11e8-8afe-9a4e6e3d5843.png)

Please have a look at this one also, along with upcoming nice features :-)

Thanks,
Raghu

**Comment by hovancik** [comment]
Hi, do you have stretchly setup to be on fullscreen? (#186)

There is a issue with electron https://github.com/electron/electron/issues/11632
