### ISSUE TITLE
Libappindicator not provided on openSUSE LEAP 15

### ISSUE THREAD

**Issue by richardstevenhack** [hovancik/stretchly#315]
### Prerequisites

Stretchly 0.17.0 currently installed. Trying to install Stretchly 0.18.0

### Description

When attempting to install Stretchly 0.18.0 on openSUSE LEAP 15, I get the following response from the YAST Installer:

nothing provides libappindicator.so.1 needed by libappindicator-12.10.1+bzr20141110-lp150.3.1.noarch

    [ ] do not install stretchly-0.18.0-1.x86_64

    [ ] break libappindicator-12.10.1+bzr20141110-lp150.3.1.noarch by ignoring some of its dependencies

Operating system:  openSUSE LEAP 15.0

### Steps to Reproduce

1. Download stretchly-0.18.0.x86_64.rpm
2. Open with "Install/Remove Software"
3. Go through YAST installation process as normal.

**Expected behavior:**

Installs normally like Stretchly 0.17.0 did.

**Actual behavior:**

Yast reports the following: 

nothing provides libappindicator.so.1 needed by libappindicator-12.10.1+bzr20141110-lp150.3.1.noarch

    [ ] do not install stretchly-0.18.0-1.x86_64

    [ ] break libappindicator-12.10.1+bzr20141110-lp150.3.1.noarch by ignoring some of its dependencies

**Reproduces how often:**

Always.

### Additional Information

I have the following libappindicator related software installed on this system:

libappindicator1  12.10.1+bzr20170215-lp150.3.1  88.7 KiB from Vendor openSUSE
libappindicator3-1 12.10.1+bzr20170215-lp150.3.1  88.7 KiB from Vendor openSUSE

The file it is complaining about is present in:   /usr/lib64/libappindicator.so.1

**Comment by hovancik** [comment]
Hi, sorry for that. To be honest, I have no idea why it's like that. It might be problem with electron-builder, which I use to create packages, or might be something else. I did not find any issue in electron-builder related to this. 

I've googled around and found https://github.com/Foundry376/Mailspring/issues/459#issuecomment-353335619 and https://github.com/jgraph/drawio-desktop/issues/51 so it seems that more electron-based apps have this problem. 

Seems that it is ok to go with "break libappindicator", if you are willing to try.

**Comment by richardstevenhack** [comment]
OK, I will go ahead and break the dependency and see if it works well
enough. I'll let you know if it does. Worst that can happen is that I
revert to 17. Thanks for your response.

**Comment by richardstevenhack** [comment]
Oh, one more note. After I told it to break the dependency, I got this
message as well:

Error: INVALID:stretchly-0.18.0-1.x86_64 (file-59bfa0bd): Signature
verification failed [6-File is unsigned]
Header SHA1 digest: OK
MD5 digest: OK
Package is not signed!

Might want to check that out.

**Comment by richardstevenhack** [comment]
OK, it seems to run all right.  It installed a different earlier version of
libappindicator to resolve the dependency issue apparently.

Installing libappindicator-12.10.1+bzr20141110-lp150.3.1.noarch.rpm
(installed size 0 B)
Installing stretchly-0.18.0.x86_64.rpm (installed size 132.99 MiB)

I only had these two libs installed:  libappindicator1
12.10.1+bzr20170215-lp150.3.1 and libappindicator3-1
12.10.1+bzr20170215-lp150.3.1
The other one was available in the repository, but I don't know why it
didn't go ahead and install that one if it needed it the first time. Weird.

**Comment by hovancik** [comment]
Glad it worked out in the end. 

Packages are not signed, not sure if electron-builder supports that. I remember I could sign for Mac OS build but I don't have spare money to spend on some fancy certs ;]  

Seems github is not signing atom as well https://github.com/atom/atom/issues/7635
