### ISSUE TITLE
Russian translation for v0.18.0

### ISSUE THREAD

**Issue by fizvlad** [hovancik/stretchly#316]
### Prerequisites

- [x] I'm using latest version: v0.18.0

### Description

No Russian translation for latest features

**Comment by fizvlad** [comment]
I have already done some work on it, so I'll create PR soon

**Comment by fizvlad** [comment]
Btw, is there nay way to open 'Welcome' page manually?

**Comment by hovancik** [comment]
Hi and thanks for working on the update! ;] 

Currently you can do it by editing config file and change the `isFirstRun` to false.
