### ISSUE TITLE
Next break time format does not match OS

### ISSUE THREAD

**Issue by afonseca08** [hovancik/stretchly#318]
I'm using latest version: v0.18.0

### Description

The menu icon Next break time displays in 24 hour format despite my operating system setting display format being set to 12 hour format.

Operating system: macOS Mojave Version 10.14

### Steps to Reproduce

1. Click on stretchly menu icon 
2. Observe next break time is displayed in 24 hour format
3. Compare to time format displayed in menu clock

**Expected behavior:** 
stretchly time format should match system 12 hour format

**Actual behavior:**
stretchly time format is 24 hour format

**Reproduces how often:** 
100%

![screenshot 2018-10-26 23 13 44](https://user-images.githubusercontent.com/863419/47600357-da7f2700-d974-11e8-9da4-c8e30d0e80e1.png)

**Comment by curreta** [comment]
I did some debugging, I think the fix is:

On this [line](https://github.com/hovancik/stretchly/blob/ce016f9cd5cffcd63a0e4d0c977574f19dc94404/app/main.js#L55):

- Include momentJS
- Use the "[Formatting](https://www.i18next.com/translation-function/formatting)" section of i18next. Example formatting from link below:

`i18next.init({
    interpolation: {
        format: function(value, format, lng) {
            if (format === 'uppercase') return value.toUpperCase();
            if(value instanceof Date) return moment(value).format(format);
            return value;
        }
    }
});`

**Comment by hovancik** [comment]
Right now we got 2 numbers HH and MM that we present as HH:MM.

**Comment by hovancik** [comment]
I've changed this in new upcoming version, so closing. 

![image](https://user-images.githubusercontent.com/4745859/82055423-bf901700-96c0-11ea-8c64-12ce05e8dddf.png)
