### ISSUE TITLE
Inconsistent monochrome tray icon color on Ubuntu

### ISSUE THREAD

**Issue by dotchev** [hovancik/stretchly#322]
Thanks for the nice app. I recently switched to it from another one.

### Prerequisites

- [x] I'm using latest version: v0.18.0 

### Description

Tray icons in Ubuntu are monochrome too, but they use a light color while Stretchly icon uses a dark color. This also leads to poor contrast when a window is maximized. See screenshots.

Operating system: Ubuntu 18.04.1 LTS

### Steps to Reproduce

1. Install Stretchly on Ubuntu 18.04

**Expected behavior:** Stretchly monochrome tray icon uses a similar color as the default icons in Ubuntu.

**Actual behavior:** See screenshots

**Reproduces how often:** 100%

### Additional Information

Screenshots

![stretchly-tray-icon](https://user-images.githubusercontent.com/4962228/47613037-ec092180-da8f-11e8-8729-dd13efdddae1.png)
![stretchly-tray-icon-2](https://user-images.githubusercontent.com/4962228/47613038-ec092180-da8f-11e8-80b2-22450b6f0ad5.png)

**Comment by hovancik** [comment]
Hard to say, but I think this is problem with Ubuntu. Kinda. 

This is what MacOS does, and the icon is the same as in Ubuntu: 

![stretchly-tray-3](https://user-images.githubusercontent.com/4745859/47613866-c0d60080-da96-11e8-844e-6771d676b942.png)

Meaning it somehow changes color of the icon  depending on color scheme of interface. I don't think I can fix icon for Ubuntu as from nodejs I only get that I am on Linux and for another distros/DE, I guess, black icon might be just fine.

I would recommend going to 3th settings page and using not monochrome icon.

**Comment by et2010** [comment]
I have the same issue on Manjaro. Besides, the size of the icon is not right either. Here is what I got when switching to non monochrome icon:

![image](https://user-images.githubusercontent.com/11584902/48308948-cf014200-e5a9-11e8-847d-a51ddf875499.png)

**Comment by hovancik** [comment]
@et2010 yeah, that is know issue with electron, we will have to wait for their fix ;/ https://github.com/electron/electron/issues/12791

**Comment by novalis111** [comment]
There is a workaround at least for XFCE mentioned in that thread. Change starter command to

`/usr/bin/env XDG_CURRENT_DESKTOP=Unity /opt/stretchly/stretchly %U`

Thanks for stretchly! Will give it a try now.

**Comment by hovancik** [comment]
There is another fix: to make icon bigger (https://github.com/electron/electron/issues/12791#issuecomment-442797497). I haven't tested yet, but with new icon being done in https://github.com/hovancik/stretchly/pull/347 we will have this done
