### ISSUE TITLE
[request] Sound alert before or at start of a break

### ISSUE THREAD

**Issue by Nirose** [hovancik/stretchly#326]
### Prerequisites

- [x] I'm using latest version: v0.18.0 

### Description

Most of the time i do not notice the notification on the bottom bar and the large box starts up abruptly blocking what i was doing. A sound or a count down could help? with an option to toggle it.

Operating system: Windows 10 (Version 10.0.17134.345)

### Steps to Reproduce

No sound played at the beginning of the break

**Expected behavior:** [What you expect to happen]
A sound to play

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information
This could be used as an example:
https://www.audioblocks.com/stock-audio/metal-singing-bowl-5-inch-tap-wood-mallet-muted.html
Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by hovancik** [comment]
Hi and thanks for the feedback. 

I don't have windows machine, but doesn't the notification play sound?

**Comment by Nirose** [comment]
i don't think it does. Stretchly only plays sound at the end of the break. for me at least

**Comment by Nirose** [comment]
your answer got me thinking if it was because Windows Sound settings were set to "no sounds". And seems like it was it. I set a sound to just for Notification and it's working now.

Thanks

**Comment by hovancik** [comment]
Glad it worked out!
