### ISSUE TITLE
[Request] Disable notification sound before alert

### ISSUE THREAD

**Issue by asterite** [hovancik/stretchly#327]
### Prerequisites

- [x] I'm using latest version: v0.18.0

### Description

[Description of the issue]

Operating system: macOS High Sierra 10.13.6

### Steps to Reproduce

1. Click on the tray icon
2. Click on "Settings"
3. Click on the right arrow to advance to the next page
4. In "audio scheme" choose "silence"

**Expected behavior:** If I choose "silence" I expect no sounds at all coming from the application

**Actual behavior:** A notification sound appears before break and microbreak, when the notification pops up (for example the one that says "next microbreak in 10 seconds".

**Reproduces how often:** All the time

### Additional Information

I guess the "audio scheme" refers to the sound that appears when stretchly becomes active or deactive?

I personally use stretchly without sounds and just the notification that appears on screen 10~30 seconds before the break is enough for me, but the sound alert is too much and I can't turn it off.

**Comment by hovancik** [comment]
Hi there and thanks for the feedback. 

Yeah, the sound scheme is sound at the end of break. 

It's not possible to disable notification sound from app, AFAIK. To get rid of sound you can disable whole notifications at 3th settings page ;/ 

There might be some setting in MacOS to turn off notifications sound, don't know. (There is such a option in WIndows)

**Comment by asterite** [comment]
@hovancik Thank you! Don't worry, I will send a PR for this so you have an initial codebase :-)

**Comment by hovancik** [comment]
closing ;] thanks for PR
