### ISSUE TITLE
Support for multiple monitors

### ISSUE THREAD

**Issue by stribny** [hovancik/stretchly#33]
Currently I see notifications displayed across my two monitors, centered as they were one.

Would it be possible that the notification is centered on one (primary) monitor?

**Comment by hovancik** [comment]
What's your setup? I have 2 monitors and I get message only at primary monitor (macOS).

**Comment by stribny** [comment]
Fedora 24, Gnome 3, one external and one internal monitor (laptop).

**Comment by hovancik** [comment]
https://github.com/electron/electron/blob/master/docs/api/screen.md

I believe I found API for it, will implemented hopefully over weekend. Thanks for the feedback!

**Comment by hovancik** [comment]
@stribny btw, do Settings and About windows work the same?

**Comment by hovancik** [comment]
Would you be willing to try running whether https://github.com/electron/electron-quick-start works fine? I mean whether the window it creates is in the middle of primary screen? 

If not, I believe it's electron bug, or some weird Gnome 3 thing. According to docs that I have found, the way I create those windows is correct.

**Comment by 183amir** [comment]
Both stretchly and electron both open in my secondary monitor (which is my laptop's).

**Comment by hovancik** [comment]
What's your OS?

**Comment by 183amir** [comment]
Arch Linux gnome 3.22

**Comment by hovancik** [comment]
@stribny would you be willing to try https://github.com/electron/electron-quick-start ?

I have macOS and Windows OS confirmed to work correctly, so this appears to be electron, not stretchly bug. 

Could you guys report it to electron? I have no linux machine myself.

**Comment by stribny** [comment]
@hovancik Yes, I am going to try the electron example.

**Comment by stribny** [comment]
Ok, so I am attaching two screenshots, they are taken from my left monitor. On one of them you can see Electron demo aligned to the right. This is also the place where stretchly Settings and About windows are displayed. On the other one you can see stretchly in action - only half of the window is displayed on this screen.
![electron-2-screens](https://cloud.githubusercontent.com/assets/313952/19678357/b78fcd7a-9a9d-11e6-95e4-0b289c064e4f.png)
![stretchly-2-screens](https://cloud.githubusercontent.com/assets/313952/19678356/b78e4aea-9a9d-11e6-8f09-bc9db2272527.png)

**Comment by hovancik** [comment]
@stribny  so this is obviously electron linux issue. On mac and windows this works correctly. Would like to report issue to electron? Or I can do it. 

I don't have Linux machine right now.

**Comment by 183amir** [comment]
Arch Linux, gnome 3.22

**Comment by hovancik** [comment]
so one more idea from good people on electron slack: could you try different VM?

**Comment by 183amir** [comment]
What do you mean by VM? Do you mean Window Manager?

**Comment by hovancik** [comment]
Yep, KDE, e17, XFCE or that stuff. I still don't have inux machine, so... But people said there is problem with Linux in general that different VMs take ideas about multiple displays differently.

**Comment by 183amir** [comment]
They are not VMs they are WMs. and you can install Linux using virtual machines (VMs) if you have time. I am not going to install KDE or anything on my machine to test this. Maybe @stribny can try it.

**Comment by hovancik** [comment]
Ah, ok. I have virtual machine but I don't know how to have more displays with it.

**Comment by hovancik** [comment]
so virtualbox suports it, going to download it now. ;] thanks for the idea

**Comment by 183amir** [comment]
You can also try Linux with a live USB.

**Comment by stribny** [comment]
Once I find some time I will try the KDE. @hovancik If you talked to Electron guys, can you post a link here to the discussion?

**Comment by hovancik** [comment]
It was on slack channel with some people that also make cross platform apps

**Comment by Pierre-lbt** [comment]
Same issue for me : LinuxMint 17.3 with Cinnamon 2.8.8

**Comment by hovancik** [comment]
Thanks, I'll open an issue on electron repo.

**Comment by hovancik** [comment]
Here is the issue I've opened: https://github.com/electron/electron/issues/7991

**Comment by stribny** [comment]
@hovancik Thanks for looking into it! Seems like we just need to wait for a fix in Electron. Pasting the link to the bug issue: https://github.com/electron/electron/issues/3490

**Comment by hovancik** [comment]
@stribny would you like to try https://github.com/hovancik/stretchly/tree/fix/dual-linux ?
I am trying to workaround the issue there. Would be nice if you could try with one and then 2 displays. Seems to work OK on VirtualBox, but real hardware test would be better.

**Comment by stribny** [comment]
@hovancik Yes, I can. I will try to find the time for it this week. Thanks!

**Comment by stribny** [comment]
@hovancik  The fix works for me!

**Comment by hovancik** [comment]
Awesome, will try to release soon.
