### ISSUE TITLE
Hide tray icon

### ISSUE THREAD

**Issue by xWee** [hovancik/stretchly#336]
Hi! Thanks for Stretchly.
Please add possibility to hide tray icon for more control, because I can skip breaks sometimes, but I really don't want it.

**Comment by hovancik** [comment]
Hi, I am not sure if I understand. How would hiding stretchly icon help? We would not be able to control/change/quit/see info anymore... 

You probably want to enable "strict mode" in settings which wont let you skip breaks

**Comment by xWee** [comment]
> Hi, I am not sure if I understand. How would hiding stretchly icon help? We would not be able to control/change/quit/see info anymore...
> 
> You probably want to enable "strict mode" in settings which wont let you skip breaks

It's enabled, but when I press Start button (or alt+tab) and then right mouse button on tray icon I can close the programm.  Like this:
![1231](https://user-images.githubusercontent.com/19345719/49461008-c3e5ae80-f803-11e8-9ac0-2add1f60f4a1.jpg)

**Comment by hovancik** [comment]
Sorry but help here ;/ Even if I close remove the icon tray, one can always run some sort of process manager and quit stretchly... There is no way to prevent user from closing app 

I was looking into preventing alt-tab some time ago but never found any solution for electron apps
