### ISSUE TITLE
SettingsFiles path is not displayed with correct slashes on Windows.

### ISSUE THREAD

**Issue by xinxuzhang** [hovancik/stretchly#337]
### Prerequisites

- [x] I'm using latest version: v0.18.0 

### Description

[Description of the issue]

Operating system: Windows 10.0.17134 Build 17134

### Steps to Reproduce

1. Open About dialog.

**Expected behavior:** 
The settings file path should be like C:\Users\XXX\AppData\Roaming\stretchly\config.json

**Actual behavior:** 
settingsFile: C:\Users\XXX\AppData\Roaming\stretchly/config.json
The last separator should be a backslash on Windows, however, it is a forward slash.

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by hovancik** [comment]
Thanks for the report ;] 

Would you like to create a PR to fix this? It's an easy fix..

**Comment by xinxuzhang** [comment]
> Thanks for the report ;]
> 
> Would you like to create a PR to fix this? It's an easy fix..

Cool, I'll do it later.

**Comment by hovancik** [comment]
Great ;] I might be wrong, but using `path.join` should take care of differences in OSes.
