### ISSUE TITLE
Displaying on the primary monitor

### ISSUE THREAD

**Issue by whiver** [hovancik/stretchly#339]
### Prerequisites

- Running v0.18.0
- OS: Windows 10

### Description

I have 3 monitors and the primary one isn't the one displaying the reminders. Though, #61 seems to say that it's the expected behavior.
In fact the reminders are always are always displayed on the 3rd monitor, the one at the right. I tried to unplug the monitor and skip to the next break, and the reminder was then displayed on the 1st monitor (the one at the left), so still not my primary one! And when I plugged back the 3rd monitor the reminders started to show again on this one.
I didn't find a way to choose the target monitor in the settings file btw.

### Steps to Reproduce

1. Have multiple monitors
2. Use stretchly

**Expected behavior:** The reminders are displayed on the primary monitor

**Actual behavior:** The reminders are displayed on another monitor

**Reproduces how often:** Always

**Comment by whiver** [comment]
Hi :)
The second one:
![image](https://user-images.githubusercontent.com/394565/49588381-d75d5a80-f966-11e8-810f-447cefada83d.png)

And the reminders are showing on the 3rd one (on the right) or on the 1st one (on the left) when I unplug the 3rd.

**Comment by hovancik** [comment]
I'll have to think about it as I have no way to test it.

**Comment by hovancik** [comment]
Ah, it does take time for anything ;/ 

Anyway, I was checking code and by default behaviour was like this: run on active screen. I will change it so that's it configurable: follow active screen or show on primary.

**Comment by stefankip** [comment]
I used stretchly a year ago with two monitors in landscape mode and I remember that the pause screen was shown on both monitors.
Now I use the 1st monitor in portrait mode and the 2nd in landscape mode, the pause screen is only shown on the 1st monitor.

**Comment by hovancik** [comment]
@stefankip sorry for no reply, I get busy sometimes. Now I am ill at home so going through the issues ;] 

is it still happening? What OS? my guess would be that it's electron bug, they are not good with monitors' stuff

**Comment by stefankip** [comment]
No problem, I know what it's like ;-)
Dunno if it's still happening; I quit using stretchly because I'm used to taking short breaks now.
I'm running Windows 10 (latest version).

**Comment by rasmusmk** [comment]
I have similar issue. One laptop with 2 additional monitors. Stretchly always pop ups on laptop unless chose all monitors :-(.
Monitor configurations is: Monitor 2 (set as main monitor), monitor 3, monitor 1(laptop).
So solution could be either manual choose from availbe monitors or be able to display on the main display choosen in windows 10 display settings.

**Comment by dplatte** [comment]
I am using a desktop with Windows 10 and  two monitors and seeing this same issue. Monitor 1 is configured as the main display, but the break notification always pops up on Monitor 2. I've also tried switching the main display to Monitor 2 and the break notification continues to pop up on Monitor 2. 

If I have Monitor 2 set as the main display when a break notification pops up and then change the main display to Monitor 1 while the break notification is still on the screen, the break notification will briefly appear on Monitor 1 but then switches back to Monitor 2 after a second.

Please let me know if there is any other information I could provide that would be helpful. Thanks!

**Comment by hovancik** [comment]
It would be interesting to see whether another electron-based app has the same problem. With so many hacks I did to get things working as much as possible with different platforms, it's hard to tell if it's electron or some hack.

**Comment by michael714** [comment]
I'm having the same issue.  Monitor 1 on left is primary, monitor 2 on right is not primary.    Break notice shows up on Monitor 2.   I will admit, though, that everything was working fine until I bought new monitor cables and switch where each monitor was  plugged into the graphics card.   I haven't even tried restarting the system yet, so here goes...
