### ISSUE TITLE
Support for Gnome 3

### ISSUE THREAD

**Issue by stribny** [hovancik/stretchly#34]
I don't see the app icon in my Gnome 3 tray.

**Comment by 183amir** [comment]
Have you installed `libappindicator-1`?

**Comment by stribny** [comment]
It seems installed, getting `Package libappindicator-12.10.0-11.fc24.x86_64 is already installed, skipping.`

**Comment by 183amir** [comment]
Your tray is in bottom left of your screen. Have you checked there?

**Comment by stribny** [comment]
Oh, I expected it on the top bar, sorry! Closing, the icon is in the tray.

**Comment by 183amir** [comment]
You can use this: https://extensions.gnome.org/extension/1031/topicons/ to bring it up.
