### ISSUE TITLE
Stretchly stops working on my PC. I have to reinstall it over and over. Please help.

### ISSUE THREAD

**Issue by three-foldsecret** [hovancik/stretchly#341]
### Prerequisites

- [x] I'm using latest version: v 

### Description

[Description of the issue]

Operating system: 

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by hovancik** [comment]
Hi, could you please fill the data in template?  

I can't figure out what might be the problem without more info ;/

**Comment by three-foldsecret** [comment]
Hi, Jan.

I am sorry to be of so little use to you. I do not even know what template
to which you are referring, and all I can say is that I install your
product, it works a couple of times, and then I have to reinstall it. That
happens over and over again. It is the same with my wife's computer. We are
both using Chrome Windows 10.

**Comment by hovancik** [comment]
Hi, due to inactivity, I am closing this issue. Feel free to open new issue if this is still problem.
