### ISSUE TITLE
Ability to add/edit/enable/disable breaks and microbreaks

### ISSUE THREAD

**Issue by nicdesjardins** [hovancik/stretchly#345]
### Prerequisites

[x] I'm using latest version: v0.18.0

### Description

Feature request: The ability to add/edit/enable/disable breaks and microbreaks.

I would like to implement two new pages ("Edit Breaks", "Edit Microbreaks") in "Settings" that would allow the end user to "Add/Edit/Enable/Disable" breaks and microbreaks as well as enable/disable/delete existing ones.

Does it make sense that I code that up myself and push it through pull requests, or is such a feature already being worked on / planned? I'm happy to do it, but I don't want to work on this if something is already on its way.

Operating system: Windows 10

### Steps to Reproduce

If implemented:
Go to Settings
Navigate past existing settings pages
New page "Edit Breaks"
- On this page you could edit existing breaks, enable/disable/delete them.
- On this page you'd have the ability to add new breaks.
Navigate one more Settings page
New page "Edit Microbreaks"
- On this page you could edit existing microbreaks, enable/disable/delete them.
- On this page you'd have the ability to add new microbreaks.

**Comment by hovancik** [comment]
Hi, what do you mean by enable/disable/delete? In current settings, you have ability to disable breaks and microbreaks

**Comment by nicdesjardins** [comment]
Oh, I mean the ability to modify the list of text strings that come default
w/ the app.

For example, following two files contain the defaults:

   - app/utils/defaultBreakIdeas.js
   - app/utils/defaultMicrobreakIdeas.js

I'd like to be able to modify the strings in those files so that I can add
other breaks/microbreaks (e.g. "Get moving... Do one body squat.")

**Comment by nicdesjardins** [comment]
I think you are misunderstanding me.

I am suggesting that I could contribute code such that it can be modified
within the settings, rather than by editing configuration files.

I filled out a feature request so that it's clear someone has had the idea
and that someone is working on it.

**Comment by hovancik** [comment]
Sorry for miscommunication. I understand that you would like to contribute, but I was not very clear about it. 

What I am trying to say is: 
- I am doing some fixes and refactors right now, so I am not sure if it's good idea to do it now (to prevent merge conflicts and so on). But it might be OK, as it's quite separate code.
- I have on TODO adding ability to also translate break ideas, so I am not sure if that should be done first, or it doesn't matter or if these 2 features should be done together. Maybe it doesn't matter..
- I believe we should translate break ideas in config file. defaultBreakIdeas.js are defaults if something goes very wrong. stretchly allows to use ideas from settings in config. 

What do you think? 

Also more things to think about: 
- break ideas in settings file are probably outdated (I would have to check but I think they are break ideas from first installed version). So I think user should get some warning that what she edits might be outdated with possibility to "rewrite them with current ones"
- can we track difference between custom added and defaults? Do we want to? 
- what should happen when new release comes with new or updated break ideas?
- should we check for length of ideas? I would say yes.
- we probably need "backup" functionality - save custom break ideas to file

**Comment by hovancik** [comment]
Closing this one. If future this will be implemented in a way where user can add repositories with custom break ideas and manage them.
