### ISSUE TITLE
Do not disturb is enabled and cannot be disabled

### ISSUE THREAD

**Issue by vitlib** [hovancik/stretchly#348]
### Prerequisites

- [x] I'm using latest version: v 0.18.0 

### Description

Do not disturb is enabled and cannot be disabled

Operating system: Win 7 64 bit

### Steps to Reproduce

1. Open app
2. Right click on its icon on tray. 
3. Click on "On do not disturb mode"

**Expected behavior:** 
Do not disturb is disabled and the app can work

**Actual behavior:** 
Do not disturb mode stays enabled. 

**Reproduces how often:** 
100%

### Additional Information
I tried with the win release and with npm, same result. I can change settings, view about pages and all, but notifications never appear.

**Comment by hovancik** [comment]
Hi there,

the text in tray menu is only informational, saying that your Windows OS is in do not disturb mode (or however Micorsoft calls it).

stretchly does not edit do not disturb mode, you have to do it from Windows settings. No idea where it is in Windows 7, I use Linux and MacOS...

Hope that helps

**Comment by vitlib** [comment]
Hi, thanks for answering, happy holidays!

I looked it up and it doesn't seem to exist a do not disturb mode or equivalent under Windows 7.
Is there a chance to use a manual switch to select the do not disturb mode?
Or maybe modify the code so its defaults behavior is not to check the OS do not disturb mode?

Thanks

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by hovancik** [comment]
Did you upgrade to 10 and then downgrade to 7 by any chance? https://techcommunity.microsoft.com/t5/Microsoft-Teams/Windows-7-quot-Windows-Quiet-Hours-is-enabled-quot/td-p/236732 

If there is no DnD in Win 7, it should work fine...I am downloading Win7 image to test

**Comment by vitlib** [comment]
I did not complete a fully upgrade, I just started it then decided to stop it. Maybe that's the case. But I can't find out how to turn it off..

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by hovancik** [comment]
I guess that is the issue then. I have tried on Windows 7 image and it worked fine for me.

I will add option to disable taking DnD into consideration, hopefully before Feb I will make a release.

**Comment by vitlib** [comment]
thanks! I guess I'll have to re-install the OS to use it in the meantime. Or switch to Linux ;)

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by hovancik** [comment]
you should also be fine with previous version https://github.com/hovancik/stretchly/releases/tag/v0.17.0

**Comment by vitlib** [comment]
It works! Thank you, it's a wonderful app. If I keep using in a couple weeks I'll definetly patreon.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by hovancik** [comment]
Thanks a lot ;]  I am working on fix but as always I have found another problem connected to this, so hopefully it goes well ;]

**Comment by red-uk** [comment]
Great app, thanks Hovancik.  Just to confirm I'm seeing the same with Windows 10 Pro 1803

**Comment by hovancik** [comment]
@red-uk Thanks ;] 

Did you also update from previous version? I have tried on clean Windows 10 install and it worked fine for me.

**Comment by red-uk** [comment]
I would have done, yes. I'll try uninstalling and reinstalling.

**Comment by hovancik** [comment]
Sorry for confusion, I mean Windows update, not stretchly. I've tried on clean install of Windows 10 and do not disturb mode was working fine for me.

**Comment by red-uk** [comment]
Hi, this build was most likely win7>win10 upgrade.

I have, however found a possible workaround from: https://community.getstation.com/t/station-cannot-detect-turned-off-do-not-disturb-mode-on-windows-focus-assist-is-always-on/3445/12

The problem
Station most certainly uses ‘windows-quiet-hours’ module to check if the user is using or not quiet hours. Module Here 8
This module is not checking the correct registry key in windows. Thus never knowing if it’s on or off.

Partial Solution
Go to Registry Editor and put the value that it erroneously checks to 1:
Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Notifications\Settings
Put NOC_GLOBAL_SETTING_TOASTS_ENABLED to 1

exit and restart stretchly.

**Comment by firefancy** [comment]
Hi! I'm running **stretchly version 0.18.0** on **Windows 10 home edition 1803,** and I have the same exact problem as this. The stretchly program is stuck in _"Do Not Disturb"_ mode and clicking on the setting in the tray menu does nothing.

There is now _"Do Not Disturb"_ setting on my computer, just a windows settings function called **_"Focus Assist."_** I have the setting turn "off" in the windows settings and in the Action Center icon on the task bar. It's still won't work.

I've uninstalled and reinstalled the app, i've restarted my laptop several times, I've checked the settings config, and nothing is working.

I didn't even get to try the app out, because it was like this automatically the first time I downloaded it and installed it.
![screenshot 264](https://user-images.githubusercontent.com/46469395/50807292-34219d00-12a6-11e9-942b-8d082d3d9f6a.png)
![screenshot 266](https://user-images.githubusercontent.com/46469395/50807297-3a177e00-12a6-11e9-82e4-2fac40dde0b5.png)

I dunno if this helps, but i'm also on an **Acer Aspire E5-575 Signature Edition** laptop, and already came with **Windows 10 Pre-installed.** I didn't upgrade from an older version of windows.

Very disappointed so far. :(

**Comment by red-uk** [comment]
I’m sure Hovancik will fix it when he can. In the meantime have you tried the workaround I posted - setting that registry entry to 1 has resolved the issue for me.

**Comment by hovancik** [comment]
yes, the best workaround is to use v0.17.0. Sorry for troubles but I have limited free time. Fix/ability to not care about DND is on way, but I have found another issue in my implementation.

**Comment by hovancik** [comment]
New release is up, you can now disable DND monitoring on 3th page of Settings.

**Comment by DaniBuoy** [comment]
> 
> 
> Hi! I'm running **stretchly version 0.18.0** on **Windows 10 home edition 1803,** and I have the same exact problem as this. The stretchly program is stuck in _"Do Not Disturb"_ mode and clicking on the setting in the tray menu does nothing.
> 
> There is now _"Do Not Disturb"_ setting on my computer, just a windows settings function called **_"Focus Assist."_** I have the setting turn "off" in the windows settings and in the Action Center icon on the task bar. It's still won't work.
> 
> I've uninstalled and reinstalled the app, i've restarted my laptop several times, I've checked the settings config, and nothing is working.
> 
> I didn't even get to try the app out, because it was like this automatically the first time I downloaded it and installed it. ![screenshot 264](https://user-images.githubusercontent.com/46469395/50807292-34219d00-12a6-11e9-942b-8d082d3d9f6a.png) ![screenshot 266](https://user-images.githubusercontent.com/46469395/50807297-3a177e00-12a6-11e9-82e4-2fac40dde0b5.png)
> 
> I dunno if this helps, but i'm also on an **Acer Aspire E5-575 Signature Edition** laptop, and already came with **Windows 10 Pre-installed.** I didn't upgrade from an older version of windows.
> 
> Very disappointed so far. :(



> 
> 
> Hi! I'm running **stretchly version 0.18.0** on **Windows 10 home edition 1803,** and I have the same exact problem as this. The stretchly program is stuck in _"Do Not Disturb"_ mode and clicking on the setting in the tray menu does nothing.
> 
> There is now _"Do Not Disturb"_ setting on my computer, just a windows settings function called **_"Focus Assist."_** I have the setting turn "off" in the windows settings and in the Action Center icon on the task bar. It's still won't work.
> 
> I've uninstalled and reinstalled the app, i've restarted my laptop several times, I've checked the settings config, and nothing is working.
> 
> I didn't even get to try the app out, because it was like this automatically the first time I downloaded it and installed it. ![screenshot 264](https://user-images.githubusercontent.com/46469395/50807292-34219d00-12a6-11e9-942b-8d082d3d9f6a.png) ![screenshot 266](https://user-images.githubusercontent.com/46469395/50807297-3a177e00-12a6-11e9-82e4-2fac40dde0b5.png)
> 
> I dunno if this helps, but i'm also on an **Acer Aspire E5-575 Signature Edition** laptop, and already came with **Windows 10 Pre-installed.** I didn't upgrade from an older version of windows.
> 
> Very disappointed so far. :(


Yeah, turning off Focus Assist in Windows 10 resolved the issue for me.
Thanks.


![Stretchly and Win 10 Do Not Disturb Mode](https://user-images.githubusercontent.com/93712968/140362707-c886584a-280a-4504-9b46-f877485001c1.png)

**Comment by DaniBuoy** [comment]
> 
> 
> New release is up, you can now disable DND monitoring on 3th page of Settings.

Good job Jan!
Seems to work.
cheers


![Untitled](https://user-images.githubusercontent.com/93712968/140367410-1a3c2720-9c9d-4b6f-abe9-48dbfd9607b3.png)

**Comment by DaniBuoy** [comment]
By the way, Jan should not have needed to program this functionality into his app.
The "Focus Assist" feature in Windows 10 allows you to add exception rules for apps that you do want to allow to send notifications even with "Do Not Disturb" mode enabled / active.

But this feature [as usual Microsoft] is half-assed and does not work for this case because for some reason you only have a choice of a few apps to allow to interrupt Do Not Disturb mode - i.e. you don't have a full list of the apps on your computer to choose from, and programs are not available at all either.

cheers

![Untitled II](https://user-images.githubusercontent.com/93712968/140386164-bc8e1b43-62b1-478d-a2d6-54039aeba796.png)

**Comment by yAnn1ck-B** [comment]
i fixed this by going to my windows 10 System/Notifications. It said my Do not disturb was off, but i turned it on and off again and that fixed it. All the features got enabled again

**Comment by ctlombardo** [comment]
I came across this same issue and found that the Do Not Disturb was locked due to my windows notification settings being set to "Alarms Only"

Hope that helps anyone having issues.

![image](https://github.com/hovancik/stretchly/assets/399513/a2c62024-f260-405f-8606-4cbe89ab5039)
