### ISSUE TITLE
Tray Menu Organization

### ISSUE THREAD

**Issue by Hum4n01d** [hovancik/stretchly#350]
### Prerequisites

- [x] I'm using latest version: v0.18.0

### Description

It would be nice to have a more semantic context menu on the tray, right now it isn't following common patterns for organization and capitalization.

Operating system: macOS 10.14.2 (Mojave)

**Expected behavior:** [What you expect to happen]

![image](https://user-images.githubusercontent.com/17228477/50491840-3a239e00-09c9-11e9-9f8c-1e102d7d9892.png)

**Actual behavior:** [What actually happens]

![image](https://user-images.githubusercontent.com/17228477/50491746-b23d9400-09c8-11e9-95fc-953a35ddd080.png)

### Additional Information

* I also removed the "Start at Login" option, shouldn't that be in the settings?
* If the "Your stretchly" feature isn't built yet, it probably shouldn't be in the menu
* Capitalization would have to be changed across the different language localizations
* I'm modeling after macOS system tray menus like the Bluetooth one:

![image](https://user-images.githubusercontent.com/17228477/50491816-152f2b00-09c9-11e9-8301-74746e2ee6f3.png)

* This would be different on other platforms

**Comment by hovancik** [comment]
Ah, I am superbusy with your stretchly right now ;] MVP is done except of styling and should go out with next release ;] 

If that's how mac does it, we should do it that way... Any chance you know how other OSes do it? I would prefer having it all same to keep it simple..

I've put start at login because I've seen other apps using the same

**Comment by decadent** [comment]
I'd propose putting ‘Start a break‘ on the top level, and disposing of the ‘start a microbreak’ item. The microbreak seems too ephemeral to me to spend time running it manually.

**Comment by mfyz** [comment]
Also, as a common UX approach seen on other apps, with a custom menu model, some of these can be more prominent buttons (start break at the top) or less prominent stuff like settings, about, quit to be minimal icons in a single row (like dropbox app).

**Comment by hovancik** [comment]
I am making some changes in new redesigned version, so I will close this issue.  

![image](https://user-images.githubusercontent.com/4745859/82055191-6de78c80-96c0-11ea-8567-f9d0547ca602.png)
