### ISSUE TITLE
Reset break interval if system is idle after break period is finished

### ISSUE THREAD

**Issue by alinberce** [hovancik/stretchly#351]
### Prerequisites

- [x] I'm using latest version: v 0.18

### Description

I saw that there were some issues related to this but I don't know if it was fixed or not.
My suggestion is `stop` the counting if the user takes a longer break than the app requires

Operating system: Windows 10

### Steps to Reproduce

1. Set a microbreak of 300 seconds every 25 minutes
2. When break window pops in, for the 5 minutes, leave the computer and return after 8 minutes
3. When return back, the next break interval will be 22 minutes, so basically have the break faster than needed
4. I have checked `monitor system idle time for natural breaks` but I don't know what it's suppose to do

**Expected behavior:** 
I'd like the app to start with a new microbreak interval of 25 minutes after returning from a natural break

**Actual behavior:** 
App continues to count, after the 5 minutes break is over

**Comment by hovancik** [comment]
Hi and thanks for the feedback ;]

This is how it works (monitor system idle time for natural breaks): 
- if you are on natural break for longer than 5 minutes and then come back, stretchly resets breaks

So in theory, it should work as you said. Idle time monitoring is not perfect though... I noticed in some cases (for example watching movie) it does not take that as idle time...

I am on Linux and I did test this happened: 
- idle time got reset on break end 

So the idle time checker for some reason is not working as one would expect... Newer versions of electron has different idle time checker so maybe it will be fixed there... I didn't upgrade yet as there are some bugs in features that I use in stretchly.

**Comment by hovancik** [comment]
Hi, due to inactivity, I am closing this issue. Feel free to open new issue if this is still problem.
