### ISSUE TITLE
Feature Request:  Align end of break with :00 and :30

### ISSUE THREAD

**Issue by adambirnbaum** [hovancik/stretchly#352]
### Description

I work with other people and our meetings start at the beginning of the hour (e.g. 2:00pm) or half hour (2:30pm).  It would be great to have breaks end at :00 or :30 (and microbreaks align at :10, :20, :40, and :50) when using the default settings.  That way when the break ends, if I have a meeting I'd be all set to go to the meeting.

### Prerequisites

- [ ] I'm using latest version: v 0.18

Operating system: 10.13.6

### Steps to Reproduce

N/A

**Expected behavior:** N/A

**Actual behavior:** N/A

**Reproduces how often:** N/A

### Additional Information

N/A

**Comment by hovancik** [comment]
Hi there and thanks for the feedback. 

Unfortunately this is not possible with how stretchly works ;/ 

With default settings, if you would start breaks at x:00:00, you would get first microbreak around x:10:00 (as javascript timers are not exact). Seconds microbreak would come around x:20:20 and then break would start at x:30:40. Then microbreak at x:45:40 and so on. 

I don't plan to create another algorithm for breaks. Not sure if that would be even possible in feasible time. The more features are in stretchly, the harder to make changes to how it works, unfortunately...
