### ISSUE TITLE
Feature Request | Add custom pre-break notification time

### ISSUE THREAD

**Issue by afonseca08** [hovancik/stretchly#353]
### Prerequisites

- [x] I'm using latest version: v 0.18.0

### Description

[Description of the issue]
I'm finding the default 30 second notification prior to a break to be a bit jarring, giving me just barely enough time to get to a place where I can stop working. I use a time tracking app that I need to stop before the break screen takes over, files I'd like to be sure I save just in case, etc.

I'm proposing adding a custom time notification setting where I would be able to say define a 5 minute warning before the break so that I can prepare to stop working if I'm in the middle of something involved before the default 30 second notification comes up.

Operating system: Mac OS X Mojave

**Comment by hovancik** [comment]
Hi there, 

you can edit break notification time by editing config file: https://github.com/hovancik/stretchly#editing-breakmicrobreak-notification-interval

I hope this helps, I do not plan to add multiple notifications before breaks.

**Comment by afonseca08** [comment]
Thanks, I forgot there was a config file for this. I agree there probably isn't a need for multiple notifications so I'll try a 1 minute notification to give me more heads up.

**Comment by hovancik** [comment]
Ok, great ;]
