### ISSUE TITLE
Feature Request - Disable during PowerPoint Presentations

### ISSUE THREAD

**Issue by PonyoStar** [hovancik/stretchly#356]
### Prerequisites

- I'm using latest version: v0.18.0 

### Description

Thanks for such a useful program, I've been using it for a week and am loving it. I did find myself in a bit of an embarrassing situation though, I was presenting to 250 people at my work and forgot to pause Stretchly so I popped up over my presentation.

There's some info here about detecting this https://stackoverflow.com/questions/27943255/determine-whether-powerpoint-is-in-presentation-mode-or-not

I think this would be useful for may users.

Operating system: Windows 10

**Comment by hovancik** [comment]
Hi there, 

stretchly uses ElectronJS/NodeJS where the function to detect whether another app is in fullscreen is not available ;/
