### ISSUE TITLE
Fullscreen mode broken in v0.19.0

### ISSUE THREAD

**Issue by Quitch** [hovancik/stretchly#359]
### Prerequisites

- [x] I'm using latest version: v0.19.0

### Description

"breaks are fullscreen" no longer causes breaks to display in fullscreen mode

Operating system: Windows 10 Pro x64 1803

### Steps to Reproduce

1. Enable "breaks are fullscreen" in settings
2. Force a break

**Expected behavior:** Break window will display fullscreen

**Actual behavior:** Break window displays in top left of monitor

**Reproduces how often:** 100%

### Additional Information

Only started occurring after upgrade to 0.19.0

**Comment by hovancik** [comment]
Thanks for the report. Is your setup one monitor or more?

**Comment by Quitch** [comment]
It is a single monitor.

**Comment by vitlib** [comment]
same issue. single monitor (but it's the same if I hook another monitor to the laptop)

**Comment by ohsospoko** [comment]
Same issue.

Windows 10 Enterprise x64. Dual monitors - 1200x1920 and 1920x1200. Worked perfectly in 0.18.

**Comment by mbrodala** [comment]
I also see this issue using 3 monitors (1920x1080), the overlay pops up at each of them in the top left corner. Downgrading to version 0.18 fixes the issue.

(BTW I also noticed that the tray icon is squished in 0.19 compared to the previous versions.)

**Comment by ohsospoko** [comment]
> (BTW I also noticed that the tray icon is squished in 0.19 compared to the previous versions.)

I noticed that too, but only the monochrome icon. Switching to full-color fixed it. But like you, I've also now reverted to 0.18

**Comment by hovancik** [comment]
The fullscreen not working is a problem with electron. I have filled issue here: https://github.com/electron/electron/issues/16907 so let's see. I can do workaround meanwhile. 

@mbrodala 
What do you mean by squished?

**Comment by mbrodala** [comment]
@hovancik I've created #362 for this.
