### ISSUE TITLE
Monochrome tray icon squished since 0.19

### ISSUE THREAD

**Issue by mbrodala** [hovancik/stretchly#362]
### Prerequisites

- [x] I'm using latest version: v0.19

### Description

The monochrome tray icon is squished.

Operating system: Windows 10

### Steps to Reproduce

1. Run stretchly
2. Check tray icon

**Expected behavior:**
The tray icon should look like this (v0.18):

![2019-02-13 09_08_44-](https://user-images.githubusercontent.com/5037116/52696561-950c5700-2f6f-11e9-8a7a-2281322e54f8.png)

**Actual behavior:**
The tray icon looks like this (v0.19):

![2019-02-13 09_10_03-](https://user-images.githubusercontent.com/5037116/52696583-9e95bf00-2f6f-11e9-9b38-c78e120fc02b.png)

**Reproduces how often:**
100%

**Comment by ohsospoko** [comment]
Only monochrome icon seems to be affected. Full-color icon is normal, on my machine.

**Comment by Esildor** [comment]
Issue still exists on _v0.19.1_

**Comment by hovancik** [comment]
I fixed this in #386, will be in next release ;]

**Comment by mbrodala** [comment]
Thanks!
