### ISSUE TITLE
Cut text shortcut collision on MacOS

### ISSUE THREAD

**Issue by xhw1** [hovancik/stretchly#363]
### Prerequisites

- [x] I'm using latest version: v0.19.0

### Description

Operating system: 
MacOS Mojave 10.14.3 

### Steps to Reproduce

1. Open stretchly
2. Select any text, in another application
3. Press ⌘ + x

**Expected behavior:** 
Text is cut to clipboard.

**Actual behavior:**
Stretchly prompt an error message, as shown below
<img width="488" alt="screen shot 2019-02-12 at 4 11 25 pm" src="https://user-images.githubusercontent.com/23283447/52700571-1c84a680-2f2d-11e9-9f81-c8e27facea9e.png">
**Reproduces how often:** 
60% of the time

**Comment by hovancik** [comment]
Interesting. Do you have one or more displays? Is that when you are on Break/Microbreak or when outside of Break?  

`cmd+x` should be available only when break/microbreak is on. Looks like shortcut is not removed correctly on break end.

**Comment by bsnresearcher** [comment]
I was bothered to have met similar problem.

Open stretchly
Select any text, in another application
Press ⌘ + c

Env: MacOS and stretchly is newest now.

<img width="420" alt="スクリーンショット 2019-09-11 6 56 31" src="https://user-images.githubusercontent.com/34906909/64659647-d3bbae80-d477-11e9-8145-c206b0068dbf.png">

**Comment by hovancik** [comment]
Thanks, this should be fixed in #459
