### ISSUE TITLE
'Show Break Ideas' Broken in v0.19.0

### ISSUE THREAD

**Issue by spgross** [hovancik/stretchly#364]
### Prerequisites

- [x] I'm using latest version: v0.19.0 

### Description

Break ideas appear, even though "show break ideas" is disabled.

Operating system: Windows 10 Enterprise, v. 1607

### Steps to Reproduce

1. Disable "show break ideas"
2.  Force a break

**Expected behavior:** No break ideas will be displayed

**Actual behavior:** Break ideas are displayed

**Reproduces how often:** 100%

### Additional Information
Experiencing issue #359 at the same time, only since upgrading to latest version. Experienced on triple-monitor work set up *and* personal laptop

**Comment by hovancik** [comment]
Ou well, seems like I've introduced a lot of new bugs in 0.19.0 ;]  Thanks for reporting
