### ISSUE TITLE
Fullscreen mode no longer works in the latest version

### ISSUE THREAD

**Issue by MohamadZeina** [hovancik/stretchly#368]
### Prerequisites

- [] I'm using latest version: v 0.19.0

### Description

The latest version, fullscreen mode does not work correctly. Instead, I get a small box in the top left corner of the screen.

Operating system: Windows 10

### Steps to Reproduce

1. Ensure latest version
2. Tick "breaks are fullscreen" in the settings
3. Wait for next break

**Expected behavior:** the break screen takes up the whole screen

**Actual behavior:** the break screen only takes up a small portion of the screen in the top left corner

**Reproduces how often:**100% of the time

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

![img_6692](https://user-images.githubusercontent.com/29977055/52733109-ce69b480-2fb9-11e9-83f2-332e27941660.jpg)

**Comment by hovancik** [comment]
Thanks for reporting. This has been already fixed in master and hopefully over weekend I will release fix version ;]
