### ISSUE TITLE
Full screen not working

### ISSUE THREAD

**Issue by albert-cb** [hovancik/stretchly#369]
I just installend Stretchly and like it a lot. But the fullscreen option (breaks are fullscreen) does not work: the popup is not fullscreen but fills only about 1/4 part of my screen.

Is that how it suposed to work?

**Comment by hovancik** [comment]
Hi there,  

this is a bug, which I have already fixed. I am gonna release new version during weekend ;]

**Comment by albert-cb** [comment]
Hi, sounds great. Thank you :)

**Comment by mrdimaan** [comment]
Hi. Does not work for me and it's not fullscreen. The content looks like it is fullscreen but the container is normal size so the content is cropped! @hovancik

**Comment by hovancik** [comment]
@mrdimaan are you on Linux? If yes, there is a known bug in electron ;[

**Comment by illright** [comment]
@hovancik is there a way to perhaps pass the initial window size through the command line on Linux? This bug is nasty

**Comment by hovancik** [comment]
@illright not sure, what do you mean?

**Comment by illright** [comment]
Well, currently, when the break comes up in non-fullscreen mode, the window is of certain size. I was thinking that if this size could be changed by the Electron config or command-line parameters, maybe we could use it as a temporary workaround
