### ISSUE TITLE
double notifications

### ISSUE THREAD

**Issue by Jake331** [hovancik/stretchly#371]
### Prerequisites

- [ ] I'm using latest version: v 0.19.0

### Description

I just installed the new version this morning. I downloaded the .dmg and copied Stretchly to my Applications folder, replacing the version already there. (I quit the program first.) Since then, I'm getting double breaks--I have it set for a microbreak every 30 minutes, so I'll get one at say 10:50 but then another one at 10:52; next at 11:20 and then again at 11:22; and so on. I have reset the breaks, but it's persistent.

Operating system: MacOS High Sierra 10.13.6

### Steps to Reproduce

It happens on its own

**Expected behavior:** One microbreak each half hour

**Actual behavior:** Two breaks, separated by 2 minutes

**Reproduces how often:** every time, as far as I can tell

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by hovancik** [comment]
Hi and thanks for the report. Can you go to the About window and push `Cmd+d`? You will see some debug info, which will include location of config file. Could you paste the content of that file?

Any chance that you close the break early? In 0.19.0 I have introduced functionality that allows you to postpone microbreak for 2 minutes (and break for 5 minutes)

**Comment by nicoguaro** [comment]
I have the same problem and this is the debug info in my system

```bash
breakPlanner: {reference: startMicrobreak, timeleft: 26 minutes left, breakNumber: 5, postponesNumber: 0, Do Not Disturb: false} 
settingsFile: /home/nguarinz/.config/stretchly/config.json 
Node.js: 8.9.3, Chromium: 61.0.3163.100, Electron: 2.0.17
```

I have Linux Mint 18.3 with Cinnamon for 64 bits.

**Comment by Slinky1nky** [comment]
Also using the latest version and having this problem. Running the newest version on Windows 10.

**Comment by hovancik** [comment]
Did you guys change any settings? Could you paste debug info before first break and then before second break? Also `config.json` could help if you changed settings. 

Any chance that you close the break early? In 0.19.0 I have introduced functionality that allows you to postpone microbreak for 2 minutes (and break for 5 minutes)

**Comment by Slinky1nky** [comment]
Hi, Jan. I believe I initially misunderstood the postpone break function. I've tested it out, and it seems this "problem" I am having goes away once I uncheck "allow to postpone." Oops! ;)

**Comment by hovancik** [comment]
No worries ;]

**Comment by lex3001** [comment]
I'm having the same problem. The first version if I ever installed was 18 on Windows 10. I did change the break time to 15 minutes I think (from 10 or 12). I installed version 19. I am getting a second notification 2 minutes after the first. I'm not sure if it is every time or just when I skip the break. FYI I also tried uninstalling and reinstalled. Here is my debug info:

breakPlanner: {reference: startMicrobreakNotification, timeleft: 9 minutes left, breakNumber: 2, postponesNumber: 0, Do Not Disturb: false} 
settingsFile: C:\Users\[removed]\AppData\Roaming\stretchly\config.json 
Node.js: 8.9.3, Chromium: 61.0.3163.100, Electron: 2.0.17

**Comment by lex3001** [comment]
I closed Stretchly, deleted everything from the folder C:\Users[removed]\AppData\Roaming\stretchly\, and then restarted. My settings are gone, but so is this problem of duplicate notifications.

**Comment by lex3001** [comment]
I think I spoke too soon. I am still getting double notifications, the second comes about 2 minutes after the first. I've noticed this is when I dismiss a notification, not sure if it also when I don't dismiss one.

How many background processes should be in Task Manager? I notice three. One with the new black logo and two with the old colorful logo. This is after a reboot of Windows.

I also notice there is only one Stretchly in the Startup section of Task Manager (I thought maybe there were two now, and that could be causing the issue).

Debug:

breakPlanner: {reference: startMicrobreakNotification, timeleft: 7 minutes left, breakNumber: 1, postponesNumber: 0, Do Not Disturb: false} 
settingsFile: C:\Users\luther.miller\AppData\Roaming\stretchly\config.json 
Node.js: 8.9.3, Chromium: 61.0.3163.100, Electron: 2.0.17

**Comment by Slinky1nky** [comment]
If you want this to stop, select "Settings" and then uncheck the boxes that say "Allow to Postpone." What you're experiencing is a "snooze" function that was released with the most recent update. To clarify: when you dismiss the Stretchly notification, you have "snoozed" it, and a second attempt to remind you to stretch will occur again ~2 minutes later.

**Comment by lex3001** [comment]
Noted - Thank you!

> If you want this to stop, select "Settings" and then uncheck the boxes that say "Allow to Postpone." What you're experiencing is a "snooze" function that was released with the most recent update. To clarify: when you dismiss the Stretchly notification, you have "snoozed" it, and a second attempt to remind you to stretch will occur again ~2 minutes later.

**Comment by hovancik** [comment]
Closing, seems that all cases are because of new "postpone" feature.
