### ISSUE TITLE
breaking change: recent version doesn't cover all monitors

### ISSUE THREAD

**Issue by pjebs** [hovancik/stretchly#375]
The recent version's break screen doesn't cover all the monitors. It use to cover all.

The setting is set to cover all screens.

**Comment by hovancik** [comment]
Hi @pjebs , what OS are you using?

**Comment by pjebs** [comment]
ios

**Comment by hovancik** [comment]
Ah yeah, having the same. Probably introduced with #365. I'm not sure if I will be able to fix this unless electron team fixes underlying issue, but let's see...

**Comment by pjebs** [comment]
what seems to be the problem. What part of electron API caused the regression?

**Comment by pjebs** [comment]
Can't you create different code for Windows and Mac so that Mac uses old code. https://github.com/electron/electron/issues/16907

The issue you were trying to fix is only for Windows.

**Comment by mbrodala** [comment]
Notice that the latest version (0.19.1) also only covers the primary monitor on Windows 10 now. All other monitors are left unchanged.

**Comment by hovancik** [comment]
@pjebs 
Yep I will add check for OS but  Windows will be still broken. I would prefer not to have OS-specific workarounds, but that's life I guess ;]

**Comment by hovancik** [comment]
@mbrodala without fullscreen as well? should be fine when fullscreen is off

**Comment by mbrodala** [comment]
Yes, in non-fullscreen mode the message appears on every screen.

**Comment by pjebs** [comment]
Can we have full screen for 1 monitor on windows?

**Comment by automattack** [comment]
Can confirm - full screen mode is only on the primary monitor. Non-full screen mode is on both. 

Windows 10 Enterprise
Version 1709
Build 16299.967

**Comment by kingweee** [comment]
Also can confirm full screen only on primary monitor.

Version v0.19.1
Windows 10 pro
Build 10.0.17763

**Comment by lenaburkett** [comment]
Same here, on Windows 10.
Previous version of Stretchly displayed full screen on both monitors on this computer. Newest update only displays full screen breaks on 1 monitor. 

If this worked in earlier versions, what is the issue that causes this not to work in the current version?

**Comment by hovancik** [comment]
It's problem with electron. I've tried building with version of electron that worked previously but the same results. TBH I have no idea why it's not working with previous version of electron. Maybe something with packaging.

**Comment by hovancik** [comment]
I'm closing this, adding to known issues.
