### ISSUE TITLE
Stop break with task manager

### ISSUE THREAD

**Issue by albert-cb** [hovancik/stretchly#376]
I have enabled the option "don't let me skip" and disabled the option "allow to postpone".

When a break starts (fullscreen) I still have the option to open my task manager (ctrl+alt+del) and then end the stretchly processes. 

So I can simply bypass the break this way, by cheeting using the task manager (windows 10).

Is this how Stretchly suposed to work? When I really want to be forced to take a break (and not being able to cheat)  a need other software?

Thank you for your help :)

**Comment by hovancik** [comment]
Hi and thanks for feedback ;] 

Task manager operates at OS level (it's basic part of os that can kill pretty much everything), so there's no way stretchly to override it somehow ;/
