### ISSUE TITLE
Can't disable break ideas

### ISSUE THREAD

**Issue by Tomas-XC** [hovancik/stretchly#377]
Using the latest version I can't disable break ideas. Even if I unselect the ,,show break ideas" they still occur.

**Comment by hovancik** [comment]
Hi ;] What version are you using? Over weekend I released 0.19.1 where this should be fixed. 

If it's 0.19.1, what OS are you using?

**Comment by Tomas-XC** [comment]
Oh, right, I didn't saw 0.19.1.  sorry. Since problem occured on 0.19.0 I used older version, and  didn't noticed that there already is 0.19.1. 
Yea the problem was fixed in 0.19.1, thank you!

**Comment by hovancik** [comment]
Awesome ;] Glad it works now!
