### ISSUE TITLE
The stretchly.Setup.0.19.1.exe is quarantined by Symantec (Malware / WS.Reputation.1)

### ISSUE THREAD

**Issue by vinczu** [hovancik/stretchly#378]
Hi,

New version's installer (stretchly.Setup.0.19.1.exe) is blocked by Symantec.

Operating system: Windows 10 Enterprise, 64-bit, version 1709, OS Build 16229.904
Symantec Endpoint Protection: version 14 (14.0 RU1 MP1) build 3876 (14.0.3876.1100) with latest definition files

See attached pics.
Please check.

Thanks,
vinczu

![screenshot 1](https://user-images.githubusercontent.com/22315084/53017571-98f91700-3450-11e9-925e-23eb2dcdd68b.jpg)
![screenshot 3](https://user-images.githubusercontent.com/22315084/53017572-98f91700-3450-11e9-9da3-c917f7cf143a.jpg)

**Comment by hovancik** [comment]
Seems that Symantec quarantined it because it has only seen this file by less than 5 user. TBH: weird, no idea what they are trying to say...

**Comment by vinczu** [comment]
I've submitted a dispute form at Symantec, let's see

**Comment by hovancik** [comment]
great :+1: in general, there used to be problems with false positives for electron-based apps in past

**Comment by vinczu** [comment]
good news: issue is now solved, I could install the 0.19.1 version
Reply from Symantec:

> Upon further analysis and investigation we have verified your submission and, as such, the detection(s) for the following file(s) will be removed from our products:
> 
>     File name: stretchly.Setup.0.19.1.exe
>     MD5: B10C2BAA408A7584A3A9E659521084EE
>     SHA256: 1AFA54BAFDBE2C19EBD5DC41C8235CA086200577BB737AB9D7CF0B984C136563
>     Note: Whitelisting may take up to 24 hours to take effect via Live Update

**Comment by hovancik** [comment]
Great! Thanks for your help!
