### ISSUE TITLE
Feature request: In-app Update

### ISSUE THREAD

**Issue by afonseca08** [hovancik/stretchly#379]
### Prerequisites

- [X] I'm using latest version: v 0.19.1

### Description

I've been enjoying Stretchly so far but find it cumbersome to have to manually download and install updates. I'd like to see support for updating to the latest version from within Stretchly. A stretch goal would be an option to allow for auto-updates in the background.

Operating system: OS X Mojave

### Steps to Reproduce

1. Observe notification that an update to Stretchly is available
2. Manually go to the website, download the update
3. Close running instance of app, install the new version
4. Find the installed app in the Applications folder and give it permissions to run as you'll otherwise be unable to open it
5. Finally, you are able to use the latest version normally

**Expected behavior:** 
Within the Stretchly app, I am given the option to update to the latest version with one click.

**Actual behavior:**
You have to update manually.

**Reproduces how often:** 
Always

**Comment by zuoliang0** [comment]
or maybe can setting to disable update.

**Comment by hovancik** [comment]
It's on my todo list but it's not highest priority. I've been checking it lately and seems it's easier to implement that it used to be year ago ;]

**Comment by diegosom** [comment]
+1, this would let me recommend the app to my non-technical savvy friends

**Comment by yo1995** [comment]
May be worth looking at 

- https://github.com/electron/electron/blob/main/docs/api/auto-updater.md
- https://github.com/electron/electron/issues/29057
- https://github.com/sparkle-project/Sparkle/issues/648

It would be ideal if the auto-update is triggered by an GitHub release event. The default updater *[Squirrel](https://github.com/Squirrel/)* of Electron seems to require a backend (I'm not familiar with Electron so correct me if I'm wrong), which is a hassle for a lightweight project. Using *[Sparkle](https://sparkle-project.org/)* might be a better way to go on macOS, though not sure if it's doable for a JS app.

**Comment by hovancik** [comment]
I'm closing this issue. Reasoning: although it would be nice, it would be adding more places where things go wrong when I want to make new release for Stretchly. Unfortunate truth is, that with Electron, almost every time when I want to make new release, there are multiple things that has changed or are not working anymore and I spend a lot of time trying to make a release.
