### ISSUE TITLE
Feature request: reset when unlocking Windows

### ISSUE THREAD

**Issue by lex3001** [hovancik/stretchly#380]
It would be a neat feature that when you return to your computer and Unlock it, Stretchly sees that and reset the clock on the "big" 5 minute break as well as the next small break. E.g. if I get back and unlock I was probably walking around and don't need a break again right away.
There is probably an equivalent to "unlocking windows" on the Mac etc. Waking from Sleep would be similar.

**Comment by hovancik** [comment]
We already have sleep functionality: unless very specific case, I reset the breaks on wake-up. 

There is a new API for lock/unlock for Mac/Windows, so I will add that as well: https://electronjs.org/docs/api/power-monitor#event-lock-screen-macos-windows

**Comment by ohsospoko** [comment]
What does Stretchly consider "sleep"? If I'm away from my computer for, say, 30 minutes, and the computer locks but doesn't go to sleep (because my power settings have it sleep at 1 hour), will Stretchly reset the breaks when I unlock the computer?

**Comment by hovancik** [comment]
@ohsospoko right now stretchly checks for this event: https://electronjs.org/docs/api/power-monitor#event-suspend 

In MacOS that is "Sleep". No idea how it's called in Windows. 

stretchly also checks for idle time (which unfortunately also is not same on every platform): 
- if idle time is longer than 5 minutes and user has came back from idle time, then reset breaks

**Comment by ohsospoko** [comment]
The 5-minute idle should take care of most situations, I would think. Certainly answers my question.

**Comment by hovancik** [comment]
fixed in #448
