### ISSUE TITLE
Configurable time-of-day for "pause until morning"

### ISSUE THREAD

**Issue by andydonzelli** [hovancik/stretchly#381]
A nice enhancement would be to have the "tomorrow morning" time be configurable. This is currently fixed at 6am.

This would be useful for me, and I think others, because I don't usually start work at 6am. Being reminded to take breaks while having breakfast or doing other light computer-use work can be quite irritating.

**Comment by hovancik** [comment]
Hi, you can edit this via editing a config file: https://github.com/hovancik/stretchly#editing-sunrise-time-to-pause-breaks-until-morning

There is also MVP version of "Your stretchly", where Patreon supporters of stretchly can edit the hour via UI. (https://www.patreon.com/hovancik)
