### ISSUE TITLE
Please explain "Your Stretchly" settings

### ISSUE THREAD

**Issue by JoeSchr** [hovancik/stretchly#382]
Hi,

I'm curious which are the additional settings you can configure by becoming a patreon? Do you have a feature list or explanation posted somewhere?

Thanks

**Comment by hovancik** [comment]
Hi there ;] 

I've added few settings that are described in here: https://github.com/hovancik/stretchly#advanced-settings 

So basically you can still edit everything via config file. "Your stretchly" is just little something for people who support the app. It looks like this right now: 

![image](https://user-images.githubusercontent.com/4745859/53814387-d20cad80-3f5f-11e9-9d09-631f81353967.png)

![image](https://user-images.githubusercontent.com/4745859/53814448-eb155e80-3f5f-11e9-941b-3178be575a90.png)

I believe the regular user wont need to go for those settings, but I wanted to do something extra for my supporters.

**Comment by JoeSchr** [comment]
Seems great, thanks!
