### ISSUE TITLE
Can‘t use in multiscreen in mac os

### ISSUE THREAD

**Issue by ZZK-AJ** [hovancik/stretchly#383]
### Prerequisites

- [+] I'm using latest version: v 

### Description

[Description of the issue]

Operating system: 
mac os high sierra 10.13.6 

### Steps to Reproduce

when i used the latest version v0.19.1,i founded when time to rest
it only can used in my main screen,and my sceond screen can not jump to the rest picture
i think it can be used in the previous version.

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by itsdani** [comment]
This happens to me too. It actually appears if the fullscreen mode is turned off, but will not appear on both monitors in fullscreen.

Operating system: 
mac os mojave 10.14.3

Stretchly: v0.19.1

**Comment by itsdani** [comment]
I've just noticed that this issue is already discussed in #375
