### ISSUE TITLE
v0.19.1 Sends daily notifications to update, even though it is literally the current version

### ISSUE THREAD

**Issue by winterdrake** [hovancik/stretchly#384]
### Prerequisites

- [ ] I'm using latest version: v0.19.1 

### Description

Every single day on startup, stretchly reminds me that there is an update available. I've tried re-installing what's listed as the most recent version a couple of times, but it doesn't fix it. Even though I'm on the newest version, I'm constantly reminded to update.

Operating system:  Windows 10

### Steps to Reproduce

1. Download Stretchly
2. Open stretchly
3. Notification reminding me to update appears

**Expected behavior:** No notifications, I already updated.

**Actual behavior:** Annoying notification

**Reproduces how often:** 100%

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by hovancik** [comment]
Hi, sorry to hear that. What do you see as title in "About" window? I don't have Windows machine right now to test...

**Comment by winterdrake** [comment]
Weird, that window is showing 0.18.0 even though I just ran the 0.19 installer today

**Comment by winterdrake** [comment]
Okay cool, that fixed it! Looks like the installer on https://hovancik.net/stretchly/downloads/ was outdated or didn't ask me to replace old files or something. Thank you though!!

**Comment by hovancik** [comment]
Awesome,  glad to hear that!
