### ISSUE TITLE
Cannot increase microbreak interval past 30 minutes via settings UI

### ISSUE THREAD

**Issue by Naphier** [hovancik/stretchly#387]
### Prerequisites

- [X] I'm using latest version: v 0.19.1
- [X] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description

Cannot increase microbreak interval beyond 30 minutes in the UI. Setting it manually in the config.json to 45 minutes (2,700,000) works, but not sure why the user limit. If you want to recommend max of 30 minutes, then maybe just a warning message instead of a hard limit?
Interestingly, if you change the config.json to, say, microBreakInterval = 2700000, then the UI lets you continue to increment up.

Operating system: Windows 10 Pro (1809)

### Steps to Reproduce

1. Open settings
2. Press '-' button on microbreak interval until it's below 30 minutes.
3. Press '+' button on microbreak interval and observe it will not go above 30 minutes.

**Expected behavior:** Microbreak interval not limited to 30 minutes,

**Actual behavior:** Microbreak interval is limited to 30 minutes (UI only). 

**Reproduces how often:** Always

**Comment by hovancik** [comment]
Hi ;] 

Do you use 45 minutes for microbreaks? I thought no-one would go for more than 10-15 minutes so checks there are rather simple.

**Comment by hovancik** [comment]
Hi, I am going through the old issues and as there is no plan right now to change how stretchly works, I am closing this issue. Thanks for your input!
