### ISSUE TITLE
Not displaying on all monitors fullscreen Win10

### ISSUE THREAD

**Issue by Zeit08** [hovancik/stretchly#388]
### Prerequisites

- [ ] I'm using latest version: v0.19.1
- [ ] I've checked [issue#375 on macos](https://github.com/hovancik/stretchly/issues/375)

### Description

Does not work fullscreen with multiple monitors on Windows 10. My settings are: fullscreen, display on all monitors. It was working flawlessly on previous version. **If I disable Fullscreen, it does work on both monitors.**

Operating system: Windows 10 build 17763.379

### Steps to Reproduce

1. Set at least 2 monitors;
2. Use fullscreen settings and apply on all monitors;
3. Both type of breaks are affected.

**Expected behavior:** Stretchly should work fullscreen on both monitors I have.

**Actual behavior:** It works only on primary screen.

**Reproduces how often:** Always, since last Strechly update.

**Comment by hovancik** [comment]
Hi, this is a known issue in electron: https://github.com/electron/electron/issues/16907 

Unfortunately my experience is that they hardly fix them, because they have hundreds of them ;/

**Comment by mbrodala** [comment]
But I still don't understand why it works with version 0.18.0. For now I'm stuck with this version infinitely because of this issue.

**Comment by hovancik** [comment]
Old version of electron was working fine, but newer does not ;/ That version is not supported anymore unfortunately.
