### ISSUE TITLE
Dutch Translations issues and their correct ones.

### ISSUE THREAD

**Issue by iAmRenzo** [hovancik/stretchly#390]
Hi there, I am sorry but I do not know how to work with git, if I even can change it. But there are some issues with the Dutch locale:

Line "english" > "dutch"

6 Next {{reference}} at {{hours}}:{{minutes}} > Volgende {} om {}
7 break > pauze
8 microbreak > micro pauze
9 Resuming breaks at > Hervat pauzes om
45 wait for a bit > wacht nog even
69 don't let me skip > laat me niet overslaan
70 allow to postpone > laat me uitstellen
106 silent notifications > stille berichtgeving | stille meldingen

Do Not Disturb is called "Niet Storen" in macOS (line 104)

**Comment by hovancik** [comment]
Hi ;] 

as this is only one file, you can use Github's editor: 

- navigate to the files location and you will see the edit icon
![image](https://user-images.githubusercontent.com/4745859/55933985-78b72e80-5c2f-11e9-832c-88b92b099f5a.png)

It should be easy to go forward from there ;] (And we can keep you as the contributor)

**Comment by iAmRenzo** [comment]
Ok thanks. Will look into it.
I also saw the big 'hints' in the pause screens are English. These are not present in the translation files.
Where can I edit those?

**Comment by hovancik** [comment]
which hint do you mean? I am not sure. Could be that I forgot to put something into translations...

**Comment by iAmRenzo** [comment]
If there is a break-screen there are hints like "close your eyes and take a few deep breaths". I couldn't find these in the locale files.

**Comment by hovancik** [comment]
Gotcha, those are not translatable, yet.

**Comment by hovancik** [comment]
@iAmRenzo Hi there, do you still plan to fix the translations?

**Comment by hovancik** [comment]
@sheriallis feel free to do it ;] I was just planning to release new version of stretchly today/tomorrow so it would be nice to have updated translations ;]  I will wait for you

**Comment by sheriallis** [comment]
👍 I'll work on it right now.
