### ISSUE TITLE
Enhancement: Option to set breaks at top of the hour or (top/mid hour)

### ISSUE THREAD

**Issue by haniobaid** [hovancik/stretchly#392]
The structure for setting break intervals is too complex and the breaks are based on the mini breaks. I worked around that by disabling minibreaks, and setting breaks every 30 mins but I prefer to have the breaks start at the top and bottom of the hour.

Right now to have breaks start every 30 mins at top and bottom of the hour (i.e. 9AM, 9:30AM, 10AM, etc....) I have to take care to start the app at a specific time and sometimes I spent two hours waiting to hit the top or bottom of the hour and still remember to do it. Other times it would round off to the next minute.

**Comment by hovancik** [comment]
Hi, there have been a person already asking for the same, but unfortunately I don't see this very possible to happen ;/ 

Considering how system works right now, and that I take other things into consideration (idle time, Do Not Disturb, pausing) it would be very complicated to add another system to do breaks ;/ 

Sorry about it

**Comment by hovancik** [comment]
Thinking about it more, one more think that might help a little: stretchly does not consider break time,  so 30 minutes  starts after break. If you would want 2 minute break every 30 minutes, not after 30 minutes, you could:

start break at X:02, set break time for 2 minutes and interval for 28 minutes
