### ISSUE TITLE
Enhancement: Set default tray icon to color (or add option for light tray icon)

### ISSUE THREAD

**Issue by pedlino** [hovancik/stretchly#393]
### Prerequisites

- [x] I'm using latest version: v  0.19.1
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues): Yes

### Description

[Description of the issue]
If the user has a transparent tray (default on Ubuntu 18.04) the black monochrome tray icon can become invisible (depending on the color of the background image)

An easy way to test this is setting the background to single Color = Black

Operating system: Ubuntu 18.04 x64

**Expected behavior:** Tray icon is visible

**Actual behavior:** Tray icon is invisible (black icon on black background)

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

My suggestion is to set the color tray icon as default (switching to monochrome can be easily done in the Settings). This solves the problem with same color background.
Another additional suggestion is to have three icon tray options: light, dark and color (which would also be a workaround for Bug #322 )

**Comment by hovancik** [comment]
Hi,  

you can set to "colorful icon" is settings on 3th page

![image](https://user-images.githubusercontent.com/4745859/56303551-7297e500-613c-11e9-96e0-d097a2e92042.png)

I'm using it on my debian sid ;] 

![image](https://user-images.githubusercontent.com/4745859/56303514-5c8a2480-613c-11e9-8061-616b08deaac6.png)

there are too many DEs on Linux and too many tray implementations. The best way forward would be to report issues on different DEs and ask them to support what macOS is doing: I give it monochrome icon and it changes to the best color for tray auto-magically.

**Comment by pedlino** [comment]
> you can set to "colorful icon" is settings on 3th page

Yes, I had already done that.
My suggestion was that to set the color icon as Default and the user could manually switch to either a dark or light monochrome icon if he/she didn't like the colored icon.

> there are too many DEs on Linux and too many tray implementations. The best way forward would be to report issues on different DEs and ask them to support what macOS is doing: I give it monochrome icon and it changes to the best color for tray auto-magically.

I agree. That is one of the main advantages of Apple hardware+software solutions.
Could you add a manual option for those who don't have auto-magic? ;)

**Comment by hovancik** [comment]
I have not done any of the graphics, so I will need help with this, but yeah, why not allow user to choose from more icons.

**Comment by hovancik** [comment]
Added in #476

**Comment by pedlino** [comment]
Tested in 0.21. It works perfectly!
Thank you for listening and for adding the option!
Best regards from Faro, Portugal

**Comment by hovancik** [comment]
Awesome, glad it works ;] And thanks!
