### ISSUE TITLE
Windows Settings UI? 

### ISSUE THREAD

**Issue by JSP314** [hovancik/stretchly#394]
### Prerequisites

- [ ] I'm using latest version: v 0.19.1.0
- [ ] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues) and don't see anything about this.

### Description

No Settings UI displays. 
No ability to see countdown to the next break.

The beaks appear as expected, but I really would like to modify their frequency and the sounds but that does not display.

Operating system Win 10 Enterprise

### Steps to Reproduce

1. Launch stretchly.exe

**Expected behavior:**
Program launches with a UI, settings menu exists somewhere. 

**Actual behavior:** 
Nothing loads. 
Also there is no system tray icon. 
There are no notifications prior to a break.

**Reproduces how often:**
100% of the time.

### Additional Information
Just installed, only installed for my user (not admin.) 
Hopefully this is just something I'm missing.

**Comment by hovancik** [comment]
Hi, that's indeed very weird. What file and where did you download it from?

**Comment by JSP314** [comment]
I downloaded the Web installer on https://hovancik.net/stretchly/downloads/
I have now deleted and can reinstall in whatever manner is recommended.

**Comment by BlythMeister** [comment]
Are you using a machine which has been provided by your company?

I had issues with our group policy blocking the app (as it does with all electron apps) because they run from the appdata/roaming folder.

**Comment by JSP314** [comment]
I am .
Interesting.

Thanks for letting me know

**Comment by BlythMeister** [comment]
If you look in event viewer when you start the app, it will log a group policy block.  This was you can contact your sysadmin and beg 😂

**Comment by hovancik** [comment]
You could try self-contained app with https://github.com/hovancik/stretchly/releases/download/v0.19.1/stretchly-0.19.1-win.zip. But no idea whether that could help. It does not install the app but you can run it from folder.

**Comment by batquis** [comment]
I use a computer with Windows 10 Home Single Language. I downloaded the app from both sources and could not see the system tray icon. The same problem as JSP314 except I can see the notifications. I ran the app both normally and as administrator but it does not show any system tray. I should change the time settings because 10 minutes is too short to concentrate. What would you recommend?

**Comment by hovancik** [comment]
@batquis

Can you show the screenshot of your tray? The default icon is the black-and-white, so maybe that's confusing?

**Comment by stefankip** [comment]
I had the same issue, at least I thought. My task bar is black-ish and the icon is also black without any background.
Then I found out there was a task bar icon because I accidentaly hovered over it :-) Now I set the icon to be in color.

**Comment by hovancik** [comment]
There is also possibility (not yet released but coming soon) to set icon to white! 

Anyway, closing this issue.
