### ISSUE TITLE
Custom break ideas

### ISSUE THREAD

**Issue by XperioR** [hovancik/stretchly#395]
### Prerequisites

- [ ] I'm using latest version: v0.19.1
- [ ] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description

Hey, I was thinking about adding option to make custom ideas on the break screen, just like typing and using your own ideas, in text file for example.

...or there is already option like this? I searched for file with ideas in installation folder, but I didn't found anything like this.

Operating system: Windows 10 Home 64-bit

**Comment by hovancik** [comment]
Hi there,

you can edit config file: https://github.com/hovancik/stretchly/blob/master/README.md#editing-breakmicrobreak-ideas

Hope this helps :) Im closing issue but let me know if you need more help
