### ISSUE TITLE
Feature Request: unlimited postpone

### ISSUE THREAD

**Issue by kofifus** [hovancik/stretchly#397]
Switching from Workrave to Stretchly

I'm overall impressed however there is one thing which is a no go for me - in Workrave I could postpone the break unlimited times and I would regularly postpone 2-3 times until I could take the break, in Stretchly unless I'm missing something I can only postpone the break once ?

I end up having to cancel the break because I just can't take it at that time, then ending up not taking a break for another 40 minutes because there is no reminder :(

Can we please have the option to keep allowing the possibility to postpone the break endlessly ?

Thanks !

**Comment by hovancik** [comment]
Hi there,  

you can do that by editing a config file:  https://github.com/hovancik/stretchly#editing-postpone-functionality

here's how to find the file: https://github.com/hovancik/stretchly#advanced-settings
