### ISSUE TITLE
Overlay is d

### ISSUE THREAD

**Issue by jfml** [hovancik/stretchly#399]
### Prerequisites

- [x] I'm using latest version: v0.19.1 
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description

When the break starts the window (with tips etc.) is shown between my main and external monitor:

![Screenshot from 2019-05-12 16-27-43](https://user-images.githubusercontent.com/4312909/57584713-59cde580-74d6-11e9-996e-0524d95a793c.png)
![Screenshot from 2019-05-12 16-28-24](https://user-images.githubusercontent.com/4312909/57584715-605c5d00-74d6-11e9-9904-4adcadd453e9.png)

Operating system: Ubuntu Budgie 19.09, but it's the same on Gnome. 

### Steps to Reproduce

1. Install Stretchly
2. Skip to next brake.

**Expected behavior:** 

Overlay should either be displayed on primary or both primary and secondary display

**Actual behavior:**
Overlay is shown between the displays.

**Reproduces how often:** 
Always

### Additional Information

Thanks for this amazing piece of software, been using it without problems on MacOS and Windows, so I'm super sad that it's not working for me on Linux +___+ I'm happy to supply more info if I can!

**Comment by jfml** [comment]
Lol, sorry! I did NOT check the known issues, very carefully!

**Comment by jfml** [comment]
Or is this something different from https://github.com/electron/electron/issues/11632 ?

**Comment by hovancik** [comment]
Hi @jfml . So it's 2 screen setup, right? Also, are you fullscreen in settings?

There used to be problem with wrong position of window on Linux, but it was fixed some time ago. 

I am on Linux, but on one screen only. I will try with 2 screens. It is possible that problem came back.

**Comment by jfml** [comment]
Hello and thanks for the quick reply! I just double-checked, and indeed when I'm not in fullscreen the overlay is displayed nicely on both monitors. I'm happy with not having the overlay fullscreen so that works for me but I'm happy to do more tests/provide more info.
