### ISSUE TITLE
I want to help in translating this product to Hindi and Marathi languages.

### ISSUE THREAD

**Issue by sunn-e** [hovancik/stretchly#401]
### Prerequisites

- [x] I'm using latest version:  v0.17.0

### Description

[There are nearly 54% users in India who speak Hindi as opposed to 12% English speakers. It would be a great opportunity to increase reach of this software. Also, I genuinely want this to be in Hindi so that elderly,office workers who I have noticed keep seating from 10am to 6 am makes me worried about their health. Also, I want this software to be used more often so that I do not look like an idiot being the only user where I use it. I'm ready to contribute, waiting for @everyone's input. Thanks.]

Operating system: 

**Expected behavior:** [It should have an option to show instructions in Hindi and Marathis]

**Actual behavior:** [Currently I could not find an option to do so]

### Additional Information

I'm a native speaker of both the languages and have helped other open source softwares in translation.

**Comment by sunn-e** [comment]
for reference  <https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers_in_India>

**Comment by hovancik** [comment]
Hi ;] 

There is no way right now to translate break ideas, only the interface. There is a translation for Hindi (https://github.com/hovancik/stretchly/blob/master/app/locales/hi.json) which could use an update. There is no version for Marathi, yet, so feel free to add it. 

Latest version is v0.19.1 btw ;]

**Comment by sunn-e** [comment]
> 
> 
> Hi ;]
> 
> There is no way right now to translate break ideas, only the interface. There is a translation for Hindi (https://github.com/hovancik/stretchly/blob/master/app/locales/hi.json) which could use an update. There is no version for Marathi, yet, so feel free to add it.
> 
> Latest version is v0.19.1 btw ;]

Yes,I updated the app. And to be honest the hindi translation seems like done by someone who just simply used google translate, did not care about actual words that are used on daily basis. I will send a pr soon.

**Comment by sunn-e** [comment]
checkout #402
