### ISSUE TITLE
It is not full screen when giving notification

### ISSUE THREAD

**Issue by cursedchico** [hovancik/stretchly#405]
I downloaded stretchly-0.19.1-win.zip and run from .exe.

Everything is fine. But it is not going fullscreen.

I have dual monitor on windows. But without monitor, also it is not going fullscreen.

I am attaching screenshot

![image](https://user-images.githubusercontent.com/6413453/58457191-bcf28580-812e-11e9-992c-760a3cac0782.png)

This is settings

![image](https://user-images.githubusercontent.com/6413453/58457212-c67bed80-812e-11e9-9bd9-d4306fbb6123.png)

This is specs

![image](https://user-images.githubusercontent.com/6413453/58457247-de537180-812e-11e9-8ed9-4a030b12fe1f.png)

I looked for issues but did not see same issue. So please forgive if there is similar and solved issues.

**Comment by hovancik** [comment]
Hi, this is a known issue in electron: https://github.com/electron/electron/issues/16907

I would recommend not using "breaks are fullscreen". We will have to wait for electron fix ;/
