### ISSUE TITLE
Uncaught javascript exception found.

### ISSUE THREAD

**Issue by sunn-e** [hovancik/stretchly#406]
### Prerequisites

- [x] I'm using latest version: v 
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description

[Description of the issue]

Operating system: win 10 home in test mode

### Steps to Reproduce

1. open stretchly
2. click on reset to defaults(a dialogue windows will appear)
3. close the main stretchly settings window
4. Click yes in the dialogue box

**Expected behavior:** Either shift focus on the popup/dialogue window or handle the exception

**Actual behavior:** Default windows javascript error pops up. 

**Reproduces how often:** 100%

### Additional Information

https://i.imgur.com/u8PTCEN.png here link in case you dont have a windows machine to try this.

**Comment by hovancik** [comment]
Thanks for the report! I was able to reproduce on Linux as well. 

I am working on upgrade of electron to v5 and then I will fix this.

**Comment by sunn-e** [comment]
No problem. :)
