### ISSUE TITLE
Feature request: We can add Anuloma pranayama message along with how to do it.

### ISSUE THREAD

**Issue by sunn-e** [hovancik/stretchly#408]
So as you know i'm using stretchly daily, It has become monotonous for me. I'm clicking on "nyahh..I want to keep going" more often. So I want to  change few things, what about adding some small yoga activities. Like this one < https://en.wikipedia.org/wiki/Anuloma_pranayama> or <https://en.wikipedia.org/wiki/Kapalabhati>. See if that would be possible. I can help in finding some similar acivities if this gets ahead.

**Comment by sunn-e** [comment]
@hovancik

**Comment by hovancik** [comment]
@sunn-e can you write an examples? I am not familiar with it...

I guess you have idea about length, but just in case https://github.com/hovancik/stretchly/blob/master/app/utils/defaultBreakIdeas.js and https://github.com/hovancik/stretchly/blob/master/app/utils/defaultMicrobreakIdeas.js

**Comment by sunn-e** [comment]
First you update the project to latest electron, then we will discuss about it later.

**Comment by sunn-e** [comment]
closing #408
