### ISSUE TITLE
Breaks don't display on all monitors Win7

### ISSUE THREAD

**Issue by RobFreundlich** [hovancik/stretchly#409]
### Prerequisites

- [x ] I'm using latest version: v0.19.1 
- [x ] I've checked [Not displaying on all monitors Win10](https://github.com/hovancik/stretchly/issues/388)

### Description

With **breaks are shown on all monitors** checked, my breaks only show on my primary monitor. This may be different from [Not displaying on all monitors Win10](https://github.com/hovancik/stretchly/issues/388) because I'm running Windows 7, not Windows 10.

Operating system: 
Windows 7 Enterprise
Service Pack 1

### Steps to Reproduce

1. Have a Windows 7 Enterprise system with two monitors, set to **Extend these displays**
2. In Stretchly, check the **breaks are shown on all monitors** checkbox
3. Wait for a break or microbreak to occur

**Expected behavior:**

Break or microbreak information should be shown on both monitors.

**Actual behavior:**

Break or microbreak information is shown only on primary monitor.
**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

Display settings:

- Display 1: Resolution: 1920 x 1200, Orientation: Landscape
- Display 2: Resolution: 1920 x 1200, Orientation: Landscape
- Multiple displays : Extend these displays

**Comment by BlythMeister** [comment]
This is a duplicate of #388 which was closed as this is an electron bug found here https://github.com/electron/electron/issues/16907

**Comment by RobFreundlich** [comment]
[#388](https://github.com/hovancik/stretchly/issues/388) specifically mentions Windows 10, and I'm on Windows 7. Do we know for sure that it also applies to 7? If so, I'm happy to close this.

**Comment by BlythMeister** [comment]
As far as I can tell from electron...yes.

**Comment by RobFreundlich** [comment]
:-) <----- Me happily closing the issue.

**Comment by hovancik** [comment]
Yeah, sorry about it ;/
