### ISSUE TITLE
Can escape the long break lock

### ISSUE THREAD

**Issue by puraminy** [hovancik/stretchly#411]
### Prerequisites

- [x] I'm using latest version: v 
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description

[Description of the issue]
In long break lock, sometime I can hit Windows Key or Alt +Tab (or combination o them) and the Task bar appears when I can pause or quit the break. It doesn't happen always, but sometimes it happens. I wish I can't escape the lock mode in anyway
Operating system: 
Windows 8.1
### Steps to Reproduce

1. [First Step] let a long break starts
2. [Second Step] try hitting Windows key (the one between Alt and Ctrl), or Alt +Tab, ... until the task bar apears 
3. [and so on...]

**Expected behavior:** [What you expect to happen]
Never can escape the lock
**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]
40%
### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by hovancik** [comment]
Last time I checked that was not possible because Alt-Tab is basic OS function and electron can not steal shortcuts from another programs/os. 

I will try to find some time to check again... But anyway I conflicted about it: should we try to steal OS level keyboard shortcuts?

**Comment by puraminy** [comment]
I should add I don't know when it happens. Sometimes, however I try, I can't break the lock and sometime I succeed. Anyway, I do that with hitting Alt Tab, and windows key.... I remember once just hitting windows key caused the Task bar pops up.......

About OS level shortcuts, you are right. Or it could be an option for user. In my opinion, the best program in this field is the one which is unbreakable in any way.

**Comment by tupio** [comment]
My taskbar is configured to auto-hide. When the lock appears all I have to do is to press the windows key, look for the tray icon and quit the app from there. I know it's me doing it, I would prefer to disable the taskbar icon in the settings during an ongoing lock to prevent the closing of the app.

**Comment by hovancik** [comment]
Yeah, stretchly is regular window, so you can close it in numbers of ways if you want to

**Comment by hovancik** [comment]
Hi, I will close this as I don't think it's possible to get over ctr+tab and similar OS functions. I tried to refocus to stretchly every 100ms when on break but nothing changed.
