### ISSUE TITLE
Feature Request: Can we have an auto launch option?

### ISSUE THREAD

**Issue by sunn-e** [hovancik/stretchly#414]
So, as you can see, I need the app to launch when I boot up. 
Refer this : https://www.npmjs.com/package/auto-launch

**Comment by hovancik** [comment]
Are you on Linux? There is auto-launch implemented, but only macOS and Windows  https://electronjs.org/docs/api/app#appsetloginitemsettingssettings-macos-windows

**Comment by hovancik** [comment]
The package seems abandoned ;/  https://github.com/Teamwork/node-auto-launch/issues/64

**Comment by sunn-e** [comment]
I'm on windows 10. And I cant find option to auto start on boot.

**Comment by hovancik** [comment]
Should be "start at login"

![image](https://user-images.githubusercontent.com/4745859/59495036-c6018780-8e8e-11e9-864e-239079d32824.png)

**Comment by sunn-e** [comment]
@hovancik Yes. I found it. So naive of me. Thanks. Also I was wondering whether you have completed your updatation to Electron 5? If that is the case, I may send you a translation or two around this weekend. What say?

**Comment by sunn-e** [comment]
Also, You can close this issue if you want to. I want it to be open for someone like me in future who cant find start at login. :p

**Comment by sunn-e** [comment]
One more thing, is this going to be on your private account forever or it will be made into an organization like stretchly's own organization github account or something like that. :)

**Comment by hovancik** [comment]
Hi, 

if you could send PR with translations that would be awesome, because I was planning to have a new release over weekend :) I've fixed some issues with electron 5 , hopefully that's all 

Right now I am not planning to create "stretchly" org.

**Comment by sunn-e** [comment]
> Right now I am not planning to create "stretchly" org.
That is okay. In that case, I may not be helping you much. This is your personal project and I respect your choices. Ping me if you make it into an org.

**Comment by NandaKishorJeripothula** [comment]
@hovancik  I tried your app. Its awesome. But as mentioned above am also getting the same issue ( am using **linux**) . There is no button called  **start on login** in menu. 
To fix that I manually added `/opt/stretchly/stretchly` to startup setting.
Do provide fix for linux as well.

**Comment by hovancik** [comment]
hi @NandaKishorJeripothula , this is unfortunately supported only for macOS and Windows ;/ My guess is that it's because different distros do that differently

https://electronjs.org/docs/api/app#appsetloginitemsettingssettings-macos-windows
