### ISSUE TITLE
taskbar icon is too dark for black taskbar

### ISSUE THREAD

**Issue by yxd0018** [hovancik/stretchly#415]
The icon on the black taskbar at right bottom corner is too dark to see. How can I revert to previous version's icon? Is there a way to add that in the setting?

**Comment by hovancik** [comment]
I guess you are on Linux or WIndows? MacOS takes care of that automatically. 

Anyway you can change to colourful icon in 3th page of settings: 

![image](https://user-images.githubusercontent.com/4745859/59771064-53871200-92a9-11e9-974d-b63c7acfcc77.png)

just uncheck "use monochrome tray icon"

**Comment by yxd0018** [comment]
Thank you very much

**Comment by hovancik** [comment]
:+1: Welcome!
