### ISSUE TITLE
Minor UX Issues

### ISSUE THREAD

**Issue by morinted** [hovancik/stretchly#420]
### Prerequisites

- [x] I'm using latest version: v0.19.1
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description

The UI has very thin font and the color schemes are low contrast, leading to some usability issues. This is exacerbated by Mac display scaling on an external 4K monitor.

Additionally, in the settings, the buttons don't really look like buttons, and the radio buttons for the audio and color schemes are not following conventions, making them hard to use.

I get the sense that a lot of the design decisions are aimed towards creating a Zen aesthetic or personality, but I fear that the user experience isn't the best.

Operating system: Retina macOS

### Proposed adjustments

- Use an easier to read body font—either a different font or a heavier weight.
- Adjust the controls on the schemes settings page so that the radio buttons look more like radio buttons (highlighting the selected option with a glow, add a smaller box to indicate selection, hover states when your mouse is over them)
- Make a more consistent button styling (+, -, reset to defaults, skip this break) where it's clear to the user that these are buttons (hopefully without sacrificing aesthetic.)
- Increase font color contrast. The `coffee kisses` theme should probably use a black font. If this is implemented, adding a lighter theme would also be possible.

I'd be willing to assist in implementing some of these changes as I really like the work that's gone into this application.

**Comment by hovancik** [comment]
With new redesigned version coming soon, I am closing this :)
