### ISSUE TITLE
Looking for help with ui/ux/design

### ISSUE THREAD

**Issue by hovancik** [hovancik/stretchly#421]
Hi all, 

**I am looking for help with design/ux/ui of *stretchly*.**

*stretchly* was always the app I made for myself, and while I tried to make it look nice and all, there's a lot of room for improvement. 

### Problems:
 
1. due to different bugs in electron, tray hover behaves differently on different platforms, and right now correctly works only in windows
<img width="233" alt="Screen Shot 2019-06-30 at 11 57 18" src="https://user-images.githubusercontent.com/4745859/60395078-50ecae00-9b2e-11e9-968d-57cd157a907c.png">

2. tray menu could use some reorganisation (probably)
<img width="209" alt="Screen Shot 2019-06-30 at 11 58 35" src="https://user-images.githubusercontent.com/4745859/60395089-77aae480-9b2e-11e9-883f-ca04c715ae5e.png">

3. a lot of people don't understand how break settings work 
<img width="797" alt="Screen Shot 2019-06-30 at 12 01 07" src="https://user-images.githubusercontent.com/4745859/60395115-da9c7b80-9b2e-11e9-979c-4e9fe7265979.png">

4. in fact all 3 sections of settings could use a reorganisation to make them more understandable 

5. differenced between high and low dpi screens

6. Elements like buttons, links etc doesn't look like they should 

7. and more probably

### Solution

I think *stretchly* needs overall redesign and some deep thought about what should be where and how to communicate settings and so on.  

For example for tray, I was thinking it could be redesigned to use window instead of menu, similar how other apps do it (to use instead of tray hover and tray menu): 
<img width="398" alt="Screen Shot 2019-06-30 at 12 14 49" src="https://user-images.githubusercontent.com/4745859/60395224-c78aab00-9b30-11e9-961c-21bae2d702b0.png">
<img width="278" alt="Screen Shot 2019-06-30 at 12 16 31" src="https://user-images.githubusercontent.com/4745859/60395239-f6a11c80-9b30-11e9-8f2b-19dd1df13a82.png">

All screens would need to be redesign, and some special thought given to organisation of settings

There's a lot of functionalities on tray and on settings and I'm not good with design so if anyone is willing to help, that would be awesome. This could lead to *stretchly* version 1.0 

If you are a ui/ux person or know someone who is and is using stretchly, let them know. 

related: 
- https://github.com/hovancik/stretchly/issues/420
- https://github.com/hovancik/stretchly/issues/350
- https://github.com/hovancik/stretchly/issues/318

**Comment by decadent** [comment]
For the ‘next break’ indication, one option on Mac that I personally like is to put it in the dock icon. AntiRSI does that superbly. The two arcs indicate time to the break and the microbreak:

![bild-803](https://user-images.githubusercontent.com/240699/60417287-b3a28000-9be8-11e9-862b-6e2df70da29d.jpg)

Since icons in the Mac dock are rather compact compared to Windows' taskbar panels, this doesn't take too much space—but is still legible.

Drawing the dock icon is pretty easy in Electron, and I can share a very similar piece of code from another app of mine. However, such animations in Electron do use some CPU—a handful of percents on lower-end machines but still noticeable.

**Comment by cpshanley** [comment]
Happy to help out. I've run a design practice in central London for donkey's years. Not sure how to get in direct touch without publishing contact details. Cheers, Colin.

**Comment by mfyz** [comment]
Hi @hovancik @cpshanley what's the status of your engagement? We are also a small team that we already internally put dozen of tweaks, some visual tweaks. I'm in the process to create each one of these tweaks as PRs coming your way @hovancik.

On the design side, we also love to contribute together aside with @cpshanley or if it's stalled, we can take over as well.

**Comment by hovancik** [comment]
Hi @mfyz we are slowly making progress through the screens! I was on holidays but I am now back.

**Comment by mfyz** [comment]
Awesome @hovancik, let us know if you guys need any help. My team is enthusiastic to help you on the design front.

**Comment by balazsnasz** [comment]
#537 will "solve" this issue. It's not relevant anymore and should be closed now. @hovancik

**Comment by hovancik** [comment]
good point, will link so it will get closed when `redesign` is merged to master.
