### ISSUE TITLE
Tray Icon

### ISSUE THREAD

**Issue by alabotski** [hovancik/stretchly#423]
Linux Mint 19.1 Cinnamon
So icon is displayed in the tray

![image](https://user-images.githubusercontent.com/439337/60593231-fc099b80-9daa-11e9-9d71-493da2c1d5ac.png)

**Comment by hovancik** [comment]
hi, what version of stretchly? this issue was fixed for me with 0.20.0 on debian and xfce

**Comment by alabotski** [comment]
Latest - 0.20.0
But once again check in the evening

**Comment by alabotski** [comment]
It's my error - 0.20.0
All work fine
