### ISSUE TITLE
"The SUID sandbox helper binary was found, but is not configured correctly" error

### ISSUE THREAD

**Issue by sispus** [hovancik/stretchly#424]
### Prerequisites

- [x ] I'm using latest version: v 20
- [ x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description

I'm using appimage version. I just remove version 19, make ver.20 executable (by 'preferences'window of file manager), and it won't start. When I tried to start it from terminal, it says:

```
[11434:0704/123647.928167:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_stretcu9oS05/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)
```

Operating system: 

Manjaro 18 XFCE 4.13

### Steps to Reproduce

1. Remove old version appimage file
2. MAke new version executable
3. error message:

```
[11434:0704/123647.928167:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_stretcu9oS05/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)
```
4. remove old config files under `~/.config/stretchly` the same output.

**Expected behavior:** [What you expect to happen]
Just start.

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

I tried to clean up eveything about stretchly, no change.

**Comment by hovancik** [comment]
Hi,  this is because of changes in chromium which then means changes for electron which then means changes for stretchly. 

I wont pretend that I know what's going on, but check the last paragraph here: https://github.com/hovancik/stretchly#linux-note

From what I understand, the most of distros do that by default, but not all of them. I had to do that in Debian, but not in Ubuntu...

**Comment by sispus** [comment]
Adding "`kernel.unprivileged_userns_clone=1` to `/etc/sysctl.d/00-local-userns.conf` and reboot" worked. Thanks.
By the way, this little program is my only simple cure for my chronic conjunctivitis. A short break after 20 minutes of work, as my doctor adviced, really helps me. 
Best thing about it is its focusing on, not to "productivity", but some breathing.
Thank you, again :)

**Comment by hovancik** [comment]
Awesome and thanks for feedback! Hope it will keep helping you!
