### ISSUE TITLE
The break window not always shown on top of other windows

### ISSUE THREAD

**Issue by jkocot** [hovancik/stretchly#425]
### Prerequisites

- [x] I'm using latest version: v0.20.0
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description

The break window doesn't always show on top of other windows. It does with e.g. the browser, but it doesn't with e.g. Eclipse IDE. Therefore, when working for some time with the IDE I miss all the breaks.
Toggling full screen mode doesn't change anything - when fullscreen, only the edge parts of the break window is are visibile (unless other app windows are displayed fullscreen).

Operating system: Windows 10. Only one monitor.
Worked fine before updating to 0.20.0

**Comment by hovancik** [comment]
Hi there and thanks for report. 

I haven't changed anything regarding that functionality so I guess it's bug in electron. Will have to check when I have time. 

Version of eclipse has not changed?

**Comment by jkocot** [comment]
> Version of eclipse has not changed?

It has, but I upgraded a couple of days before updating Stretchly and didn't observe this behaviour in between.

**Comment by joboj** [comment]
I've also noticed this behaviour in Windows 10.
I'm not using Eclipse but I haven't noticed which programmes are active when it happens.

**Comment by hovancik** [comment]
I was able to replicate. I'll try to reproduce with basic electron app.

**Comment by hovancik** [comment]
can you guys try this version? https://we.tl/t-yfTrO9nbbu

**Comment by joboj** [comment]
Thank you, installing now.  I'll try it over the next few (work) days and let you know if I notice it happening again.

**Comment by joboj** [comment]
Ok, been using this version for the rest of the day and it's been working as normal with the break reminder appearing always on top on all displays.

**Comment by zhangchenkai** [comment]
I have same problem.
When I'm using chrome and Pycharm, the break window not always prompt properly, but I still could receive the notification.
OS: Windows 10 1903

**Comment by hovancik** [comment]
@zhangchenkai can you also try build from https://we.tl/t-yfTrO9nbbu?

**Comment by zhangchenkai** [comment]
> @zhangchenkai can you also try build from https://we.tl/t-yfTrO9nbbu?

@hovancik Yes, it works better. At least for now, nothing has went wrong.
Thank you, and your software.

**Comment by hovancik** [comment]
Awesome, thanks guys for testing! I will try to make new release asap.

**Comment by jkocot** [comment]
I also tried the new version for a few hours on Friday and it seems to work ok, thanks!

**Comment by hovancik** [comment]
I've released new version today with the fix. I hope it works because this was really weird fix :D

**Comment by joboj** [comment]
Thanks, quick work!
