### ISSUE TITLE
change break postpone time

### ISSUE THREAD

**Issue by kofifus** [hovancik/stretchly#426]
Which settings control how much time between pressing postpone and the next break ?

**Comment by hovancik** [comment]
Hi, you would have to edit config file as described here: https://github.com/hovancik/stretchly#advanced-settings and https://github.com/hovancik/stretchly#editing-postpone-functionality

**Comment by kofifus** [comment]
Thanks! I saw that but as far as I can tell there is no setting for the amount of time between postpones ??

**Comment by hovancik** [comment]
Hi there, it's `microbreakPostponeTime` and `breakPostponeTime` to change postopone time in milliseconds.
