### ISSUE TITLE
Feature request: open config file from tray

### ISSUE THREAD

**Issue by kofifus** [hovancik/stretchly#427]
I find it hard to find and open the config file - ie on my computer it's in c:\users\kofifus\AppData\Roaming\stretchly\config.json

I suggest having an option in the tray right click menu to open/edit the config file

Thanks!

Micha

**Comment by hovancik** [comment]
Hi there, you can go to About windows and press `Cmd+d`/`Ctrl+d` and the location of file will be shown. It's not clickable yet, but I will try to make it clickable. Should be possible on all platforms, I guess.
