### ISSUE TITLE
Electron Menu Bar Shown in Settings

### ISSUE THREAD

**Issue by joboj** [hovancik/stretchly#430]
- [ y] I'm using latest version: v0.20.0
- [y ] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description

When I open any windows such as About, the default Electron menu bar is visible, this wasn't the case in the previous version.

Operating system: Windows 10

### Steps to Reproduce

1. Open About

![image](https://user-images.githubusercontent.com/18419438/60985817-1a850f00-a336-11e9-80d6-9fae8cdb0f0c.png)

**Comment by hovancik** [comment]
Thanks, I'm probably not setting `autoHideMenuBar: true`everywhere
