### ISSUE TITLE
Feature request: auto-pause video while taking a break

### ISSUE THREAD

**Issue by istar0me** [hovancik/stretchly#433]
### Prerequisites

- [x] I'm using latest version: v0.20.0 
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description

I've been using stretchly for a while, and the overall experience was excellent! But there's one thing that bothers me often: Every time the break window popped up when I was watching YouTube videos, I had to manually pause the video playback. Is it possible to auto-pause/resume the video while the break window pops up/disappear?

Operating system: macOS Mojave 10.14.5

### Additional Information

It's my first time to request a feature. If there's something doing wrong, please let me know.😓

**Comment by hovancik** [comment]
I agree that it's good idea, but I was not able to find a way how to do that ;/ 

I'll keep this issue opened for some time, maybe someone knows a way to do it...

**Comment by cpshanley** [comment]
Have a look at Dejal Time Out on the App Store. Free to download. It allows you to configure what will auto pause. I think it is a 'big ear' that listens for apps running. So that would take care of things like VLC, Sky Go, Quick Time, etc. It also has a pause dropdown (e.g. pause for 2 hours).

**Comment by Luukgr** [comment]
It's a bit hacky... But in principle, a space bar press, should be enough right? Not sure if node.js can do this. Plus this has consequences if you're coding/typing etc... Maybe someone has a solution for all this?

**Comment by hovancik** [comment]
I've merged PR yesterday that keeps focus on active window before break started so that should help a bit with pressing space bar.

**Comment by hovancik** [comment]
There is no progress on this, and I don't see a way how to do this, so closing.
