### ISSUE TITLE
it can escap from long break if you lock mac then return

### ISSUE THREAD

**Issue by cattrace** [hovancik/stretchly#436]
### enviroment
mac pro 2017 touchbar 
stretchly version 0.20.0

### decription
i have many time that when i unlock(the shotcut key at touchbar top right) my mac , the long break gone (switch to other desktop).

**Comment by cattrace** [comment]
![image](https://user-images.githubusercontent.com/4670343/61198459-b767f380-a70c-11e9-9923-05a8ae18c6ff.png)
like this , it's very easy to  reproduce

**Comment by hovancik** [comment]
your breaks are fullscreen, right? 

I think it's how macos works: when app is fullscreen, it actually goes to new Desktop. When you lock your screen, and unlock, you are at your default desktop, not the new one created for fullscreen stretchly.

**Comment by cattrace** [comment]
> your breaks are fullscreen, right?
> 
> I think it's how macos works: when app is fullscreen, it actually goes to new Desktop. When you lock your screen, and unlock, you are at your default desktop, not the new one created for fullscreen stretchly.

you are right

**Comment by hovancik** [comment]
Hi, the new stretchly behavior is that it will finish the break when user locks the computer.
