### ISSUE TITLE
stretchly should refocus to itself if someone escapes to different app with ctrl/cmd+tab or with another way

### ISSUE THREAD

**Issue by cattrace** [hovancik/stretchly#437]
## enviroment
mac 2017 pro touchbar
stretchly 0.20.0  fullscreen mode

## description
![image](https://user-images.githubusercontent.com/4670343/61203786-fc485600-a71d-11e9-8316-ab6141512b93.png)

when you use Alfred with shotcut   , and then type another application(like chrome) , mac will switch that application (at another desktop) ,then you escaped.

**Comment by hovancik** [comment]
Yeah ;/ 

Stretchly is a regular window, so there will be always a way to get out of break

**Comment by cattrace** [comment]
> always

On Windows,There is a breaktime program name "eyefoo", when you are breaking, the program will force the system swtich to it and show it on top (it repeat this action per second), so you cant do anything(it will switch back immediatly), i think the "loop action" is the key @

**Comment by hovancik** [comment]
That's interesting approach! I'll try that

**Comment by hovancik** [comment]
So I have tried to `show()` window when I am in break every few milliseconds but that does not work ;/ 

it should work as I was able to do that with `electron-quick-start` application. No idea what it makes not to work with stretchly, could not find it.

**Comment by smaheshs** [comment]
RSI guard blocks keyboard and mouse inputs once the break starts. Could something similar be done?

**Comment by MM-John** [comment]
I came here to ask for an option the break window to NOT be "always on top". I take my breaks ON the computer, most of the time. They are playful, mentally refreshing, inspirational, motivational breaks, but they require me to click on things and look at windows and type. Example: journaling.

My workaround is to set break window size to 0.5 and it's transparency to 50%. Then I can work behind it. Not perfect, but doable.

EDIT2: another workaround I found is a free, portable utility called [GUIPropView](https://www.nirsoft.net/utils/gui_prop_view.html) by nirsoft (I use dozens of his utilities). With that, I can find the Stretchly window, and turn off "Top Most" and then move around my windows normally. However, at that point the Stretchly window doesnt appear in the Windows 10 Alt+Tab list, nor is there an entry for it in the Windows 10 taskbar. To get the Stretchly window back, I have to use GUIPropView Switch To. Not perfect, but it works.

I'm on Windows 10. v1.4.0.

I'm not sure if I should submit this as its own request.

(Great program, by the way. I wouldn't spend the time to come here and ask if so many features weren't terrific already.)

EDIT: asking for "an option" not to change default behavior

**Comment by hovancik** [comment]
@MM-John so you mean that the window will come on top first, but let's say you click away, it will disappear/go under another window?

**Comment by MM-John** [comment]
@hovancik correct. As in a regular old window. An option for it to behave that way. I have sound on so that I will hear when the break ends, even if the window isn't on top when it ends.

**Comment by darksworm** [comment]
> @MM-John so you mean that the window will come on top first, but let's say you click away, it will disappear/go under another window?

> @hovancik correct. As in a regular old window. An option for it to behave that way. I have sound on so that I will hear when the break ends, even if the window isn't on top when it ends.

So basically, an option in the contributor settings which turns the (pseudo)kiosk mode (fullscreen, always on top, not movable, etc) on/off. 

Happy to implement this some time later this week.

**Comment by MM-John** [comment]
@darksworm sounds right to me. I didnt know the term "kiosk mode" but it makes sense and the description is right.

**Comment by hovancik** [comment]
@darksworm I think it should be only `alwayOnTop`but I guess you'll be able to test. If somebody uses Fullscreen they can't really click on another Window :) 

https://github.com/hovancik/stretchly/blob/082329aa09a9f6a4c381b21dbfa03974459e395a/app/main.js#L432

Note that there is also this hack so it's in more than one place: https://github.com/hovancik/stretchly/blob/082329aa09a9f6a4c381b21dbfa03974459e395a/app/main.js#L475

**Comment by MM-John** [comment]
Browsing your code for the first time, naively, what about in the non-mini break code?

https://github.com/hovancik/stretchly/blob/082329aa09a9f6a4c381b21dbfa03974459e395a/app/main.js#L546

and then

https://github.com/hovancik/stretchly/blob/082329aa09a9f6a4c381b21dbfa03974459e395a/app/main.js#L588

Also, at least on my Windows 10 v1903 when the window's not alwaysOnTop it disappears from the ALT+Tab sequence. And it's not in the task bar.

I'm guessing that one or more of

      show: false,
      skipTaskbar: true,
      focusable: false,

should change but I'm just guessing.

Thanks for considering this. I will make a great tool even better for a sub-set of users (like me!)

**Comment by darksworm** [comment]
@hovancik disabling `alwaysOnTop` would solve the issue, but I feel that a more proper solution would be to allow the users to minimize and move the window around as well. (To me, this seems to fit the use-case of using other applications during breaks better)

@MM-John your guess is largely correct. 

I think we can call this option "Make Stretchly act as a regular window" and It seems that it (when turned on) should either override the fullscreen option or handle it such that the taskbar is visible while the break window is open (so that you aren't forced to alt-tab to switch applications). If you have a preference of either - let me know.

**Comment by MM-John** [comment]
Not sure. I haven't used fullscreen. But if people turn that on, they might not be interested in this new option.

I suppose a fullscreen window can still be "regular", eg, like a youtube or browser full screen window? Hit ESC to return to regular window? I don't know, seems like a lot of details to sift through there.

I am in favor of taskbar, especially if the option is called "Make Stretchly act as a regular window". Seems to neatly tie it in a bow.

**Comment by hovancik** [comment]
can you create PR so we don't discuss here? this issue is about different thing.

**Comment by hovancik** [comment]
This is pretty old, so closing.
