### ISSUE TITLE
Postpone new version notification until next version

### ISSUE THREAD

**Issue by furioness** [hovancik/stretchly#439]
As the title says, it just repeatedly shows me a notification about the availability of new version that (in this specific case) seems for me useless and I don't want to update right now.
What a pity to have this kind of notification instead of just having it in some kind of repository.
OS: Linux (.deb)

**Comment by hovancik** [comment]
Hi there,  
you can disable new version notification in settings file: https://github.com/hovancik/stretchly#new-version-notification and https://github.com/hovancik/stretchly#advanced-settings
There is no repo as I don't know how to do that and unfortunately have no time to research it as there are many packages with different architectures for repos

**Comment by furioness** [comment]
Wait, don't close. You said only about disabling notifications at all, but my request about postponing notification, so I can skip one single update but for next updates, I would get a notification.
I understand about time, so at least would be nice to see that in the to-do list.

**Comment by hovancik** [comment]
Ok 👍

**Comment by hovancik** [comment]
Hi, it's been few years and I don't see this happening, so closing. Sorry.
