### ISSUE TITLE
Menubar mouse click (minor UX issue)

### ISSUE THREAD

**Issue by yacsaw** [hovancik/stretchly#440]
### Prerequisites

- [X] I'm using latest version: v 0.20.1
- [X] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description

Expected menubar behavior is to show the menu as soon as the mouse button is depressed.  Stretchly is the only icon in my menubar that does not show the menu until the button is released.  For short menus, the slickest behavior is to show the menu only as long as the button is held down, so that no second click is required to hide it.  To select a menu item, drag the cursor onto it, then release the button.

Operating system: I'm not sure whether this behavior manifests in Mohave since I am using El Capitan (10.11.6).

**Comment by hovancik** [comment]
Hi there. I'm testing on my mac 10.14.5 and it's the same. Some apps are the same, some are as you say it should be. 

Unfortunately, this is how electron works and I can't change that ;/
