### ISSUE TITLE
Allow changing settings numbers using text input

### ISSUE THREAD

**Issue by jbkkd** [hovancik/stretchly#442]
This feature proposal, which I will be working on, will allow changing intervals for breaks and microbreaks using an HTML input tag in addition to the "-" or "+" buttons.

Numbers on the first settings pages can only be changed using the "-" or "+" buttons. These jump in pre-set intervals (skipping by intervals 5 for the first the first three settings). This is limiting in case a user (myself ;) prefers breaks with non round numbers in them.

I'm suggesting an addition to the existing buttons. When clicking on the numbers, they will change to an HTML input, and allow the user to change them to whichever number he pleases.

**Comment by hovancik** [comment]
Hi! 

There is a plan to rewrite whole UI, so not sure if this is good time to make changes in current UI: https://github.com/hovancik/stretchly/issues/421

**Comment by hovancik** [comment]
New version coming soon, so closing this.
