### ISSUE TITLE
seems multiple instances are running

### ISSUE THREAD

**Issue by yxd0018** [hovancik/stretchly#443]
I use zip format on win 10 64bit. After I upgraded for the first time, I find the timing is off. It seems there are 2 instances are running. 5 min break after 2 mini-breaks seems only 10min apart. I checked the startup list and there is only 1 Net.hovancik.stretchly there. How do I trouble shoot? Thanks.

**Comment by hovancik** [comment]
Thanks for the report!

Do you have 2 or one icons in tray? There is check in code to check for only one instance running.

**Comment by yxd0018** [comment]
one icon

**Comment by hovancik** [comment]
From what version were you upgrading? 

There is a new feature in 0.19.0 that allows you to postpone microbreaks (for 2 minutes) and break for 5 minutes. Maybe it was it? (You can disable ability to postpone in settings)

check for one instance looks like this: 

```
const gotTheLock = app.requestSingleInstanceLock()

if (!gotTheLock) {
  console.log('stretchly is already running.')
  app.quit()
  return
}
```

**Comment by yxd0018** [comment]
I think the problem starts with version 0.19.1.
Is that "allow to postpone" in microbreak and break? They are checked by default.  When the screen shows up, the prompt is the same "skip" as before and there is no separate postpone button.

**Comment by yxd0018** [comment]
seem cancelled postpone solved the problem. App either need 2nd button on the screen for postpone or uncheck the postpone by default.

**Comment by hovancik** [comment]
The postpone button is the same location as skip button. By default (when allowed to postpone), it's there for 30 percent of break/microbreak time and then it's replaced by skip button.

**Comment by yxd0018** [comment]
I still feel skip is skip, postpone is postpone, they are different. There should be a drop down choice let user choose how long to postpone.

**Comment by noloader** [comment]
"multiple instances are running" still seems to be a problem for some users: https://www.reddit.com/r/Fedora/comments/13aezos/bug_repeated_app_entry_in_the_background_apps/.
