### ISSUE TITLE
Feature Requests - Options for Window Size & Balloon Notifications

### ISSUE THREAD

**Issue by pan-jeffhochberg** [hovancik/stretchly#445]
Hello!

I installed your application only a few minutes ago and I'm in love with the simplicity and elegance.

I do a lot of web meetings where I share out my desktop. While I can appreciate the need to get my attention, it would be nice to have more choices than just the default window size or full-screen.

Additionally, it would be great if you could implement some sort of balloon messages similar to the older Windows notifications above the systray. Definitely NOT the Windows 10 Notification Center which is medieval and looks awful. Your UI is crisp and eye-pleasing. If you were to implement notifications similar to what the most recent version of Slack can do, that would be incredible!

They would still catch your attention and have a unique appearance, but not overly intrusive to the point where people watching you give a presentation are interrupted because you are supposed to take a break. :-)

Keep up the AMAZING work!

**Comment by hovancik** [comment]
Do you have a screenshot/image of what you mean? I am not Windows user ;]

**Comment by hovancik** [comment]
Closing as no reply. I'm adding ability to set Break Window in #666
