### ISSUE TITLE
npm bugs macos-notification-state

### ISSUE THREAD

**Issue by RekaH** [hovancik/stretchly#446]
I'm trying to install Stretchly on Ubuntu 16.04 with `sudo npm install stretchly` and I receive the following error:
```
Exit status 1
Failed at the macos-notification-state@1.3.1 install script 'node-gyp rebuild'.
Make sure you have the latest version of node.js and npm installed.
```
`npm -v` returns  5.3.0 and `node -v ` returns  v8.6.0.

**Comment by hovancik** [comment]
Hi there, 

What you do looks wrong. You should use `.deb` package to install stretchly from https://github.com/hovancik/stretchly/releases/tag/v0.20.1

**Comment by RekaH** [comment]
Hi!

Thank you for your quick reply! I've installed the .deb package and it works like a charm! I love the feature to customise break and microbreak messages!

**Comment by hovancik** [comment]
Awesome, glad that helped!
