### ISSUE TITLE
libX11-xcb.so.1: cannot open shared object file:

### ISSUE THREAD

**Issue by RJDan** [hovancik/stretchly#449]
### Prerequisites

- [x ] I'm using latest version: v  0.20.1
- [ x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description

[Description of the issue]

Stretchly won't start up.
opening stretchly from application list does nothing. running from the terminal with "stretchly" returns an error.

Operating system: <! Ubuntu 18.04 Bionic>

### Steps to Reproduce
Either entering "stretchly" in the terminal or pressing 'super' key and searching for stretchly. I would expect the app should start up instead nothing happens when opening via application list or an error is produced when using the terminal terminal (as below).

`stretchly: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory`

Running 
`sudo apt-get install libx11-xcb1`  in the terminal produces
`libx11-xcb1 is already the newest version (2:1.6.4-3ubuntu0.2).`

running `sudo find / -name "libX11-xcb.so.1" -print `
shows the libX11-xcb.so.1 in a number of /snap/ subdirectories and in /usr/lib/x86_64-linux-gnu/

Repeated 8 times after 3 computer restarts and 5 or so "sudo apt-get update"
The deb file was installed using gdebi v. 0.9.5.7+nmu2

**Comment by hovancik** [comment]
Hi @RJDan but no idea ;/  
Are other packages up to date? Maybe reinstall stretchly?  

Also, is this your first time installing stretchly? or it's after update?

**Comment by RJDan** [comment]
Hi @hovancik 
Thanks for the reply. I had a previous install which I removed. I jumped the gun and installed the new version before removing the old version. I had to back track and uninstall both. 
I think all other packages are up-to-date. I've tried re-installing several times.

**Comment by hovancik** [comment]
can you try installing dev version of package? something like libx11-xcb-dev

**Comment by RJDan** [comment]
I got it working. I had been trying to install the 32bit instead of the 64. 64 installed without a problem.
