### ISSUE TITLE
German translation: Improve and Continue

### ISSUE THREAD

**Issue by robot-5** [hovancik/stretchly#450]
### Prerequisites

- [x] I'm using latest version: v0.20.1
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description

The German translation is incomplete with the English default showing up in some screens (e.g. all of the tutorial). I would like to translate those parts and make some light stylistic changes in a few already translated sentences. I'm aware that the break ideas cannot be translated at the moment.

Operating system: Windows 10.0.18362 Build 18362 (64 bit)

### Steps to Reproduce

1. Start the app and just look around e.g. in the tutorial or the settings.

**Expected behavior:** Everything being in German.

**Actual behavior:** Parts are in English.

**Comment by hovancik** [comment]
Hi there, feel free to go ahead and thanks!
