### ISSUE TITLE
Allow stretchly operations to be issued via commandline

### ISSUE THREAD

**Issue by lkrms** [hovancik/stretchly#458]
### Prerequisites

- [x] I'm using latest version: v0.20.1
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description

There is currently no way to "Reset Breaks" (for example) via command line. This would be helpful in multi-platform or multi-system environments (I use Linux and macOS side-by-side via Synergy), to enable automatic syncing of multiple stretchly instances.

### Steps to Reproduce

n/a

### Additional Information

n/a

**Comment by hovancik** [comment]
Can you tell me specifically how you imagine that look/work like?

**Comment by lkrms** [comment]
Apologies for the delay in replying.

At present, if a stretchly process already exists, running `stretchly` from the commandline outputs `stretchly is already running.` and some i18next output, before terminating.

It would be great if it were possible for a running stretchly process to be sent a signal from the commandline. This would allow for all sorts of automation, although for my particular use case, it would be to run a command simultaneously on two systems, to synchronise stretchly on both after I log in to one (running the command on the remote computer would be via SSH).

For me, as a starting point, being able to run:

```
stretchly --reset-breaks
```

and have this achieve the equivalent of clicking "Reset breaks" in the tray menu of stretchly, would be perfect. For other automation purposes, other signals would also be helpful, e.g. `--skip-to-next-break`, `--skip-to-next-microbreak`, `--pause-until-morning`.

**Comment by hovancik** [comment]
I've asked on their forum, no idea if that's even possible: https://discuss.atom.io/t/passing-command-line-arguments-to-running-electron-app/68161

**Comment by lkrms** [comment]
This documentation seems to indicate it's possible via the `second-instance` event:

https://electronjs.org/docs/api/app#apprequestsingleinstancelock

Am experimenting... will try to get a PR ready in coming days.

**Comment by lkrms** [comment]
Ok, it's not ready for a PR just yet (still need to check on edge cases, e.g. when stretchly is paused), but I've got the `--reset-breaks` signal working. It would be great if you could check out the commit referenced above and let me know what you think of the way I've approached it.

(Disclaimer: it's not my first JS, but it is my first dive into Electron.)

**Comment by hovancik** [comment]
:+1:  

I've added some comments

**Comment by SeabassHeyneman** [comment]
HI @lkrms, can I help out here?

**Comment by hovancik** [comment]
@SeabassHeyneman I think if you're still interested, you could start the work. 

How do you imagine the interface and what commands would you add?

**Comment by SeabassHeyneman** [comment]
I'd love to be able to customize the length of time during the Stretches. Here's a product story: Users start their work sessions at inconsistent times. They go up for a walk or for a meeting and they find time where they can. They can work faster with a quick terminal command. 

Does that sound right to you?

**Comment by hovancik** [comment]
So you mean user can start a break and specify for how long they want it to be via command line?

**Comment by SeabassHeyneman** [comment]
Yes!

**Comment by hovancik** [comment]
I see. That's not possible right now (and I mean `easily`, as one would have to change settings, then start break, and then probably change settings back?). Solution for this would be to allow this in general, as in to change how breaks work. My guess is it's rather big change. 

Here's the things I imagine would be possible via command line argument: 
- pause breaks (indefinitely)
- resume breaks
- reset breaks
- skip to mini break
- skip to (regular) break

That would be good MVP. Later we would add pausing for hour, 2 hours, custom; starting custom timed break and such.

MVP would allow you to set 2 different times (one for mini and one for regular break) and then be able to skip to those.

**Comment by KingOfSpades** [comment]
I would also like this functionality (controlling Strechtly from the command line) My use case is to combine it with RescueTime and some custom scripting. I would like to use the RescueTime app to schedule my breaks. For example, every 20 minutes I spent on productive time do a micro brake. This allows for more customization and custom scripting. I would be able to schedule more breaks in the afternoon, automatically pause schedules if I’m in a meeting or away from my computer.

**Comment by SeabassHeyneman** [comment]
@hovancik, love this! How can I be helpful for this MVP?

**Comment by hovancik** [comment]
@SeabassHeyneman if you feel like coding, I would say go ahead ;] I am here to answer any questions.

**Comment by SeabassHeyneman** [comment]
Great! Can you please point me to the file that I should work with? Would love to have a general outline for what I should be adding! 😃

**Comment by hovancik** [comment]
Hmm, looks like the previous PR is gone, can't see it anymore. Anyway, here is the code from it: https://github.com/lkrms/stretchly/commit/030965087b4a0014fb709f6cc05a3293be09e12d 

You could take a inspiration from there. 

Basically you need to work in `main.js`, maybe extract a class outside. Are you familiar with nodejs? You can run Stretchly locally with `npm`. 

I would recommend to start inside of `redesign` branch, as that is the most recent one.

**Comment by lkrms** [comment]
Unfortunately I've not had time to continue with this, and yes, the original PR was "cleaned up" after I mistakenly used the same branch for an unrelated fix and PR (back when I was more of a GitHub n00b). My original use case (syncing Stretchly across two systems) no longer applies, but being able to schedule breaks at precise times is something I've been meaning to add regardless (e.g. to align breaks with change of hour and/or vary my schedule around particular routines). I'd also like to be able to set the next message, so that particular breaks can have particular reminders. Being able to make a one-off change to the next break to prevent it from being postponed or cancelled would be excellent, too.

Perhaps this could all be consolidated into one command like "set-next-break", with flags like:

- `-type <break|microbreak>`
- `-time <HHMMSS>`
- `-interval <seconds>` (alternative to `-time`, i.e. seconds from now)
- `-duration <seconds>` (override the default just for this break)
- `-message <text>`
- `-allowpostpone <yes|no>`
- `-allowskip <yes|no>`

Some of these would be easier to implement than others, of course. Glad you were able to find that commit as a starting point, @hovancik. Apologies I've been unable to do this work myself in the meantime.

**Comment by SeabassHeyneman** [comment]
Love this! @lkrms , would you be open to spend thirty minutes and pair program at least to start?

**Comment by lkrms** [comment]
I may have gone a little further down the rabbit hole than planned. Please see the PR I just opened (https://github.com/hovancik/stretchly/pull/567). If you have a running instance, you can now call the `stretchly` command with any of the following arguments to take fairly self-evident actions:

- `reset-breaks`
- `skip-to-microbreak`
- `skip-to-break`
- `pause-breaks [indefinitely|until-morning|<seconds>]` (Default: indefinitely)
- `resume-breaks`

I think that covers most of the features requested so far -- except for the extras I added earlier today.

Some improvements are needed (e.g. changing the `stretchly is already running.` output), not to mention another command or two, but it's a start.

**Comment by decadent** [comment]
Note that there's an option to implement external commands as an API, with an http server running in Stretchly's process. Node.js makes that pretty simple. The command-line client could be implemented as a separate script or a binary, if Electron allows that.

This way, some inter-process interaction issues would be obviated: since the code would handle this communication, instead of Electron's mechanisms, you wouldn't need to worry about it passing command-line arguments of the control process into the main process. The API could use a serialized format, like JSON, so no extra parsing is necessary.

Additionally, if third-party programs are used to automate calls to Stretchly (e.g. Alfred or Hammerspoon)—then these automation scripts could make requests directly to the API and receive responses also in a serialized format, instead of going through text conversion with the command line.

**Comment by hovancik** [comment]
Well, from what I remember reading about similar things in past, it's not really recommended to have running server in Electron (security and such). Might have changed meanwhile :) 

But yeah, allowing others programs interacting with Stretchly would be definitely interesting. 

I think, for starters, trying to stretch electron's possibilities is good enough and we will see.

**Comment by decadent** [comment]
> security and such

Ah, that might be related to things like the recent findings of JS in browsers connecting to local servers, and the possibility of that in the first place. I'm not 100% sure but unix domain sockets should be immune to that, and are generally a better choice for local connections than ports (what with the limitation on the number of ports, and the guessing of which ones aren't occupied).

Of course, Windows throws in a wrench with the long-standing absence of UDS or a close alternative (afaik)—although they finally did add the AF_UNIX socket types in 2018, but that's too recent to be relied on here, and not sure if there are or aren't any problems with it. Names pipes, that I suggested earlier, actually also can't properly process multiple clients (again, on Unix and dunno about Windows, but should be similar here), so file locks or something needs to be utilized. Basically, if HTTP can't work smoothly on Windows somehow, it would be better to pick a thought-out cross-platform IPC library for Node.js that abstracts all of that away and avoids using tcp/udp ports if possible.

That's just an update to my proposal, in case it's decided in the future that this sort of thing is needed. Of course, Electron does about the same thing for us with both second-instance handling and the page-background communication, so all-in-all it's a case of weighing the annoyance of handling `second-instance` detail vs the hassle of rigging up a separate IPC.

**Comment by hovancik** [comment]
To be honest, this is a bit above what I am knowledgeable about. The `second-instance` implementation is almost done so we will see how the real usage and use-cases develop. 

I am pretty sure people already tried different alternatives.

**Comment by papey** [comment]
@decadent The HTTP API was one of the idea I have at the beggining. It's quite an amount of work to since you have to test client side, server side on 3 plateforms as well as the security aspects you mention.

**Comment by decadent** [comment]
@papey Dunno, as a web-dev I see the client side as basically off-the-shelf, especially since it can be tested in isolation. Whereas after I fiddled with Stretchly itself,  I keep being tempted to replace the logic with an FSM.

In fact, if you treat the API server part as an emitter of state-changing events, you can also test it in isolation by simply matching API calls to emitted events. Isolated tests are less thorough than integrated ones, but they are way more feasible.
