### ISSUE TITLE
Stretchly and gaming?

### ISSUE THREAD

**Issue by Matsku12** [hovancik/stretchly#461]
I havent used this for longtime, because of problems with games, but wanted to make suggestion/questions could there be ability to program notice when windows is in game mode? I would only like break reminder to work while I am gaming. 

If I red correctly dnd is disabling alarms, but is there possibility to have it working other round around meaning it would only work when computer is in do not disturb mode like while gaming?

This type of programs usually does not work well on computers which are used for watching movies etc. because it stops the movie and only thing I would like to use this is while gaming.

**Comment by hovancik** [comment]
I think this should be solved after #389.  I'll close this issue, please track the progress there.
