### ISSUE TITLE
Cmd + Tab make possible to skip the break

### ISSUE THREAD

**Issue by giannigdev** [hovancik/stretchly#468]
Hi, i have found on macos Mojave that pressing Cmd + Tab provide the ability to skip the break making the tool useless. Thank you for your time and interest.

**Comment by hovancik** [comment]
Hi, please follow #176 for updates. Not sure if it can be fixed, thought.

**Comment by ghost** [comment]
this works :
https://github.com/hovancik/stretchly/issues/1232#issuecomment-1543447627
