### ISSUE TITLE
Provide a bright monochrome icon for dark dekstop themes.

### ISSUE THREAD

**Issue by vladipus** [hovancik/stretchly#475]
I'm currently on Linux Mint and the tray icon is almost invisible.
![image](https://user-images.githubusercontent.com/468323/66105122-3873b000-e5c3-11e9-8e58-0205a0802248.png)

**Comment by hovancik** [comment]
it would be nice if linux would do it the same as mac (it automagically invert colours). 

![image](https://user-images.githubusercontent.com/4745859/66121080-9fea2980-e5dc-11e9-92c8-bd87348b7efe.png)

**Comment by hovancik** [comment]
you can also use "colourful" icon, from settings page 3

**Comment by vladipus** [comment]
I know I can, but it's too colorful ; )

Great job on the app, amigo!
