### ISSUE TITLE
Memory issues

### ISSUE THREAD

**Issue by joydashy** [hovancik/stretchly#484]
- [x] I'm using latest version: v0.20.1
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

Operating system: Windows 10, 1903

### Description

I have noticed Stretchly using several GB of memory on my laptop. At this point the machine gets incredibly slow. Killing Stretchly immediately resolved this issue. Restarting Stretchly does not immediately cause problems, so I assume it's in the line of a memory leak.

I love Stretchly otherwise, so I hope there's some solution to this issue.

**Comment by hovancik** [comment]
Sorry to hear that ;/ 

I don't have Windows machine, but will try watching on Linux. 

Here's what I get at OS start
![Screenshot_2019-10-11_15-06-53](https://user-images.githubusercontent.com/4745859/66653714-f092ff80-ec38-11e9-8166-82e21517d321.png)

**Comment by joydashy** [comment]
Thanks for the quick reply! Frustratingly it does not appear to show up in the Windows task manager as using GB's of memory. But the moment I killed it, memory usage dropped several GB's and the slowness disappeared...

**Comment by hovancik** [comment]
@joydashy some questions: 
- how long does it take to eat GBs? 
- is it continual use or you put your PC to sleep or so? 
- do you have any other electron based app? ie slack etc. How do they behave? 

Can you filter in Task manager by string? Electron apps have more processes, as you can see in my screenshot.

**Comment by joydashy** [comment]
Will keep an eye to see how long it takes to start eating memory. My laptop is almost never rebooted, but frequently use sleep mode.

I use Visual Studio Code, have not had issues with that.

I see this only for Stretchly atm: https://i.imgur.com/7zx8R1r.png

**Comment by hovancik** [comment]
This one's pretty old, I think new versions don't have this issue anymore :) If it persists, please open new issue.
