### ISSUE TITLE
setting options in below can not display separately

### ISSUE THREAD

**Issue by talentldk** [hovancik/stretchly#489]
### Prerequisites

- [x] I'm using latest version: v 
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description

[Description of the issue]

Operating system: Win10 enterprise 17763.737

### Steps to Reproduce

1. [First Step] set stretchly working in Chinese 
2. [Second Step]right click icon and select setting 

**Expected behavior: setting option show correct place

**Actual behavior: options in below can not display separately

**Reproduces how often:permanent

###screenshot:
![2019-10-23 15 47 27](https://user-images.githubusercontent.com/46208028/67370225-e19f3c00-f5ac-11e9-8564-3350adc48ce2.png)

**Comment by talentldk** [comment]
![2019-10-23 15 47 27](https://user-images.githubusercontent.com/46208028/67370358-1612f800-f5ad-11e9-9df6-3b5e1d3bb2fb.png)

**Comment by hovancik** [comment]
Hi there and thanks for the report! I don't have the Windows machine but will try to fix it

**Comment by talentldk** [comment]
> Hi there and thanks for the report! I don't have the Windows machine but will try to fix it

Thanks in advance for your quick response :)

**Comment by talentldk** [comment]
update 25.10.2019
this error occurs on an expand monitor.
after restart my computer and check again, it doesn't happen again on both screen.

**Comment by hovancik** [comment]
hi @talentldk , you're right. TBH I am not sure how to fix this, rather complicated issue with CSS that I am not so familiar with. 

I will be reworking whole UI of app soon, so it will be fixed there, as whole settings will change.
