### ISSUE TITLE
Feature request: Options to automatically pause when on certain apps or when apps are fullscreen

### ISSUE THREAD

**Issue by e-t-l** [hovancik/stretchly#491]
### Prerequisites

- [X ] I'm using latest version: v0.21.0 
- [ X] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description

Please add an option to pause while computer is in fullscreen and/or while certain apps are running. It would be great to have functionality similar to f.lux, which allows users to whitelist certain apps (e.g. VLC Media Player) as well as pause whenever an app goes into fullscreen mode. That way, the Stretchly pop-up wouldn't interfere with things like Netflix, Powerpoint presentations, etc.

Operating system:  Windows 10 Home

**Comment by hovancik** [comment]
Hi there and thanks for the feedback. 

I am closing this in favor of #389 where this is discussed
