### ISSUE TITLE
Make the plus and minus icons dim, its confusing

### ISSUE THREAD

**Issue by vjpr** [hovancik/stretchly#492]
First user impression was confusing. I read it as "minus 20 seconds break"...took me a bit to figure out they are used for adjustment.

**Comment by hovancik** [comment]
Hi and thanks for feedback. 

You are totally right, it is confusing. Good news is that I am working with designer to wholly rework stretchly ;] 

Someone already started to work on improving current version here: #488 . Can you comment there what you think?

**Comment by balazsnasz** [comment]
Should be closed, as with the new redesigned interface doesn't have such icons. @hovancik
