### ISSUE TITLE
Suggestion: display clock during breaks

### ISSUE THREAD

**Issue by Maartijs** [hovancik/stretchly#496]
Thanks for building this application! I can be very chaotic at times, and stretchly really helps me to have some time to reflect on what I'm doing and pay attention to what time it is.

I got a feature request that's kind of connected to this. I think it might be nice to have an option to display the current time during the pause screens (when stretchly is on fullscreen, I mean). It could possibly help me and others with challenges similar to mine keep track of the time. I think just a text clock would suffice for that. 

Let me know what you think of it, and thanks again for a great application!

**Comment by hovancik** [comment]
Hi there and thanks for your feedback ;] really glad stretchly helps you. 

With clock, do you mean to show it instead of break ideas or with them?

**Comment by harshPPatel** [comment]
Yeah, it will be great if we can see current time at the right bottom corner on windows and on top right (I guess) on Mac. It will be helpful during long breaks.

**Comment by Maartijs** [comment]
Thanks for you reply hovancik! Personally I was thinking about showing the time together with the break ideas.

**Comment by yj2303** [comment]
Would you like to assign this issue to me.

**Comment by hovancik** [comment]
Hi @yj2303 and thanks for the interest ;]

How do you imagine this would work?  

FYI, as part of whole app restyle, I already restyled breaks, so they look like this: 
![image](https://user-images.githubusercontent.com/4745859/77529712-6e1d9580-6e90-11ea-8cb5-f489aac3724f.png)

**Comment by hovancik** [comment]
This has been already added, so closing :)
