### ISSUE TITLE
why dose this happen?

### ISSUE THREAD

**Issue by st-rain** [hovancik/stretchly#498]
![微信截图_20191125094339](https://user-images.githubusercontent.com/46990336/69506208-87591880-0f68-11ea-8c41-e8bd35384b03.png)

**Comment by st-rain** [comment]
After installation，it showed that

**Comment by hovancik** [comment]
@st-rain what OS are you at?  

My guess is windows 7 upgraded to Windows 10. There is a bug in such a case. To fix that, you should go to "Settings" and then go ">" to the last page and uncheck "monitor system idle time for natural breaks". This tries to check if you are in DND mode...

This is some weird Windows OS quirk/bug  ;/

**Comment by hovancik** [comment]
It's been few months, so I am closing this. Let me know if you still need help ;]
