### ISSUE TITLE
App not running

### ISSUE THREAD

**Issue by FOOLIG** [hovancik/stretchly#502]
I have downloaded on my window 10 laptop, but I could not open the app or change its setting.

**Comment by hovancik** [comment]
hi @FOOLIG , 
you should be able to see icon in tray: 

![image](https://user-images.githubusercontent.com/4745859/70426767-d9736100-1a73-11ea-94bf-eb3b5be12d87.png)

**Comment by hovancik** [comment]
It's been more than a month, so closing this. Let me know if you still need help ;]
