### ISSUE TITLE
Portable version

### ISSUE THREAD

**Issue by diegosom** [hovancik/stretchly#505]
Any portable version is available for download?

**Comment by hovancik** [comment]
Hi @diegosom , portable version can be downloaded from https://github.com/hovancik/stretchly/releases

ie
stretchly-0.21.0-ia32-win.zip for 32 bit windows or  stretchly-0.21.0-win.zip for 64 bit windows

**Comment by diegosom** [comment]
Thanks, haven't noticed "stretchly-0.21.0-win.zip" before :)

**Comment by gundamhyl** [comment]
> Hi @diegosom , portable version can be downloaded from https://github.com/hovancik/stretchly/releases
> 
> ie
> stretchly-0.21.0-ia32-win.zip for 32 bit windows or stretchly-0.21.0-win.zip for 64 bit windows

The configuration file is still in "C:\Users\Admin\AppData\Roaming\stretchly\config.json". A portable software means that the configuration file is in its installation directory, so how does stretchly turn on portable mode?

**Comment by hovancik** [comment]
@gundamhyl hmm, I see. it's not portable then in that sense. `config.json` is just the file that I use for storing my settings, but there are many different things that electron creates in app data folder
