### ISSUE TITLE
cannot start in debian 10?

### ISSUE THREAD

**Issue by lazebird** [hovancik/stretchly#506]
is there anyone who can use stretchly in debian 10?
i download the deb, install it with root account, run it either with root account in terminal or common user account double click, nothing happens

**Comment by hovancik** [comment]
Hi, not sure how it's done these days but I install it with

```
sudo apt-get update
sudo dkpk -i stretchly_package.deb
```
if it gives some missing libs, this should solve it: 

```
sudo apt-get install -f
```
For debian, you might need to do what's mentioned here https://github.com/hovancik/stretchly#linux-note in last paragraph:

> If stretchly is not starting, you might need to run sudo sysctl kernel.unprivileged_userns_clone=1. Read more here. Depending on your distro, you probably want to do something similar to this, so the settings are kept after reboot: Add kernel.unprivileged_userns_clone=1 to /etc/sysctl.d/00-local-userns.conf and reboot.

**Comment by hovancik** [comment]
It's been a month, so closing. Let me know if you still need help ;]
