### ISSUE TITLE
When a break is skipped, wait the full time to next one

### ISSUE THREAD

**Issue by danielb2** [hovancik/stretchly#509]
### Prerequisites

- [x] I'm using latest version: v0.21.0
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues) ( but god ((and all other deities)) know(s) I'm bad I'm finding stuff )

### Description

This issue is about microbreaks only. I don't use regular breaks.

Skipping a break doesn't wait the full time until next one. The next break is far too quick once one has been skipped. If I am skipping a break, I _really_ meant counting it as skipped, not snoozing it.

IOW, either give an option to properly skip a break, or snooze one.

Operating system: macOS mojave

### Steps to Reproduce

1.  skip a break

**Expected behavior:** skipping a microbreak means next microbreak should be in 10 minutes

**Actual behavior:** break is _snoozed_ for 2 minutes.

**Reproduces how often:** 33% (?) of the time.

### Additional Information

The ctrl/command+x needs to be prominently documented.

**Comment by hovancik** [comment]
Hi @danielb2 , thanks for the report! 
By default, first 30% of break , the `Cmd+X` will only postpone/snooze it (for 2 minutes). 

So I think that's what happens there, as you mention it is snoozed for 2 minutes. You can disable this behavior by unchecking "allow to postpone" in first settings page. 

Does this help?

**Comment by danielb2** [comment]
That helps! thank you :)
