### ISSUE TITLE
New install, can't turn off Do Not Disturb

### ISSUE THREAD

**Issue by wendiriggens** [hovancik/stretchly#514]
I downloaded and installed Stretchly this morning to try out, but it won't work. It says Do Not Disturb is on, but I'm unable to disable it. I'm running Win7 on a PC. Thank you!

**Comment by wendiriggens** [comment]
Nevermind, figured it out! Thank you!

**Comment by hovancik** [comment]
@wendiriggens glad you figured it out ;] 

Unfortunately the technology I use to create stretchly has glitches on specific OSes ;/
