### ISSUE TITLE
Hangs on resume from sleep

### ISSUE THREAD

**Issue by Quitch** [hovancik/stretchly#516]
### Prerequisites

- [X] I'm using latest version: v0.21.0 
- [X] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description

Sometimes, after the system resumes from sleep, the Stretchly application fails to resume. The system tray icon cannot be interacted with and breaks do not trigger. Task Manager must be used to terminate the application and then it must be relaunched.

Operating system: Windows 10 Pro x64 1909

### Steps to Reproduce

1. Sleep system
2. Resume from sleep

**Expected behavior:** Stretchly system tray icon will display a context menu on right-click and breaks occur according to schedule

**Actual behavior:** Stretchly system tray icon does not respond and breaks do not occur

**Reproduces how often:** 10-20% of the time

**Comment by hovancik** [comment]
hi @Quitch  and thanks for the report. What is the OS? 

Can you check what's the RAM/Processor usage when this happens? I have seen stretchly being kinda slow to response when my Linux is overloaded. 

Is task manager showing anything helpful?

**Comment by Quitch** [comment]
Both CPU and RAM usage are normal, and no other applications are displaying unusual behaviour. I am using ~8GB RAM of my 32GB available.

**Comment by hovancik** [comment]
I don't have a windows machine but I will try to repro in virtualbox. Will also try search in  electron issues

**Comment by AntonOfTheWoods** [comment]
I also have Stretchly crash on resume after hibernate on Ubuntu 20.04/22.04. If memory serves it only did this with the snap version on 20.04 but also does it with a manually installed (deb) on 22.04.

**Comment by hovancik** [comment]
@AntonOfTheWoods any error messages or messages in log?

**Comment by AntonOfTheWoods** [comment]
@hovancik , nothing suspicious, and it *just* happened...

```
...
[2022-07-22 20:31:18.798] [info]  Stretchly: resuming breaks after idle time
[2022-07-22 20:36:35.111] [info]  Stretchly: pausing breaks because of idle time
<-- crashed here
[2022-07-22 20:52:38.214] [info]  Stretchly: initializing...
...
```

And actually there wasn't a resume here either. I'll turn off the pausing breaks on idle. Maybe it was that that was different on 20.04 that meant it stopped doing it with the deb.

**Comment by AntonOfTheWoods** [comment]
It makes no difference. It always disappears when coming back from a `systemctl hibernate`.

**Comment by hovancik** [comment]
I'm trying to download the ubuntu virtualbox machine, but  looks like it does not support hibernmation. Same for Windows :(

**Comment by AntonOfTheWoods** [comment]
If there is any kind of extra logging we can add to electron that could be put in, I'd be more than happy to run a dev version to get to the bottom of this... I've never used electron so wouldn't know where to start.

**Comment by hovancik** [comment]
maybe try running `gdb stretchly` ?

**Comment by hovancik** [comment]
Hi, this is pretty old issue with v0.21.0  so I will close this. If it still persists, please open a new isssue so we can get up to date details.
