### ISSUE TITLE
On Windows 10 break window doesn't overlay fullscreen applications anymore in 0.21.1

### ISSUE THREAD

**Issue by Gerqus** [hovancik/stretchly#524]
### Prerequisites

- [x] I'm using latest version: v0.21.1
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description

After update to Stretchly 0.21.1 break window doesn't show on top of fullscreen applications. Namely seen this with a game and full screen movies watched from browser and Netflix application. Suppose it applies to all full screen applications.

In previous version I was using (0.21.0) Stretchly break window was always shown on top of any other application I was/am using.

Operating system: Windows 10

### Steps to Reproduce

1. Open a full screen movie on main screen (the one that Stretchly should open it's break window)
2. Wait until Stretchly break window should appear (time has passed)

**Expected behavior:** Stretchly break window is visible on top of any application

**Actual behavior:** Stretchly break window is not visible, even after minification of full-screen video (although signal for break end is played after given time)

**Reproduces how often:** 100%

### Additional Information

Seems like window may not be opened at all. Maybe some exception is thrown?

**Comment by Quitch** [comment]
I'm not sure if it's tied to fullscreen applications. I just had this same issue, but all I had open was a maximised Chrome window. It wasn't even playing a fullscreen video. Break window did not appear, but eventually I heard the chimes indicating the break had completed.

**Comment by hovancik** [comment]
Thanks guys, I am trying in Virtualbox and can confirm. I find it rather strange as I was not changing this behavior, so it might be bug with new version of electron (I went from 6 to 7)

**Comment by hovancik** [comment]
The windows is there.

**Comment by hovancik** [comment]
So I've just tested and it is the problem with electron version, v7 is not working correctly.

**Comment by hovancik** [comment]
This bug has been reported already: https://github.com/electron/electron/issues/20933

**Comment by hovancik** [comment]
Hey folks, I've made a build with electron 6 and put it into release files as `stretchly.Setup.0.21.1.electron.6.exe` . As this is older version, some other things might be broken ;/ 

Unfortunatelly my experience with electron is that issues get hardly fixed, but let's hope for the best.

**Comment by jkocot** [comment]
I don't know how you fixed this last time, but it seems the same issue as #425 (at least the symptoms are the same)

**Comment by hovancik** [comment]
@jkocot well, there are more and more issues with electron ;/ I hope someone will look into the issue that I reported.

**Comment by hovancik** [comment]
Looks like they are removing this option altogether ;[ https://github.com/electron/electron/pull/21732

**Comment by smith558** [comment]
Confirming that `stretchly.Setup.0.21.1.electron.6.exe` works just fine 👍

**Comment by hovancik** [comment]
Too bad electron 6 is not supported anymore ;/ https://www.electronjs.org/blog/electron-9-0#end-of-support-for-6xy

Even worse because it's a regression bug ;/

**Comment by hovancik** [comment]
Is this still happening in 1.0?

**Comment by Quitch** [comment]
My experience has been that it does, yes.

**Comment by jkocot** [comment]
I haven't seen this issue in 1.0 for **non-full screen** windows (I don't use full screen much), and it used to happen to me often for not even maximised Chrome or IntelliJ/Eclipse. I had a few cases when I had just opened a context menu and the break window opened out in the background of it instead at the top, but that's generally a non-issue.

**Comment by jkocot** [comment]
> I haven't seen this issue in 1.0 for **non-full screen** windows (I don't use full screen much), and it used to happen to me often for not even maximised Chrome or IntelliJ/Eclipse. Now, I had a few cases when I had just opened a context menu and the break window opened out in the background of it instead at the top, but that's generally a non-issue for me.

After some more time using v1.0 I did notice the problem several times even with for non-full screen apps, hovewer, these are rare cases (~1 in 20 times the popup should show), whereas, earlier this happened more frequently.
