### ISSUE TITLE
Support Snap Packages

### ISSUE THREAD

**Issue by jwillikers** [hovancik/stretchly#525]
Would it be possible to support building Stretchly as a [Snap](https://snapcraft.io/)?

If Stretchly is added to the [Snap Store](https://snapcraft.io/store), I will automatically receive updates and not have to download and install a release manually each time.

**Comment by hovancik** [comment]
Looks like it is possible: https://www.electron.build/configuration/linux#LinuxConfiguration-target 

Will try with next release

**Comment by hovancik** [comment]
Hey, so I've tried and failed ;[ There is some error `electron-builder ` which there is no solution to, yet ;[

**Comment by mwoz123** [comment]
link issue ticket: https://github.com/electron-userland/electron-builder/issues/4940

**Comment by hovancik** [comment]
So I published in SnapStore, I guess. I don't really agree with all that snap things so I am not a user and can't test :)

**Comment by mwoz123** [comment]
Works thanks :)

**Comment by jwillikers** [comment]
Thanks @hovancik!
