### ISSUE TITLE
Intermittent Hang State

### ISSUE THREAD

**Issue by s-ahuja** [hovancik/stretchly#528]
### Prerequisites

- [x] I'm using latest version: v 
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description

When stretchly microbreak appears - it has no text just empty window. It takes 1-2 seconds (the whole system is in a hung state for that brief 2-3 seconds), subsequently the text on the window appears. 

Operating system: Mac OS Mojave

### Steps to Reproduce

1. Each microbreak

**Expected behavior:** The earlier version of the app, wasnt hanging and was smooth.

**Actual behavior:** Each microbreak the window hangs briefly until the text on the microbreak appears.

**Reproduces how often:** 100%

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by hovancik** [comment]
Thanks for the report @s-ahuja ! 

Could you check the RAM around that time? In my experience, Stretchly hangs when there's not a lot of RAM available ... 

Let's be hones, Stretchly is Electron app, so not very good in those terms ;/

**Comment by s-ahuja** [comment]
Lots of Ram. Its on MacBook Pro 16GB / i7 with not much running.

**Comment by hovancik** [comment]
Interesting... Must be then electron version change.. Not much has changed between versions of stretchly. Will try in macOS when I get chance. Didn't notice anything in Linux.

**Comment by mohakshah** [comment]
For me this issue started with `v0.21.1`. Since then, I have tried downgrading to `v0.21.0` and `v0.20.0` and yet faced the same issue. And I'm certain I did not used face this issue with those earlier versions. This makes me think that the crux of the issue could be an update to macOS itself. I'm currently running macOS 10.14.6.

**Comment by hovancik** [comment]
Hi, this is pretty old, so will close the issue. If it still persist, please open a new one so we can get up to date info.
