### ISSUE TITLE
Where do I find settings so I can customize breaks, etc?

### ISSUE THREAD

**Issue by cbuschur** [hovancik/stretchly#529]
### Prerequisites

- [x] I'm using latest version: v 
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description

I have tried right-clicking on the Stretchly icon in my system tray and in the start menu and on the desktop, but there is nothing other than "Stretchly" and "Open" as options that might allow me to change break durations, types, etc. When I right click either of those, nothing happens. Reminders do appear every few minutes, but I would love to customize them a little. :-) I have v21.1 or similar (not v20 ish) and am using Windows 7 on a laptop. Can you help me?

Operating system: 

### Steps to Reproduce

I have tried right-clicking on the Stretchly icon in my system tray and in the start menu and on the desktop, but there is nothing other than "Stretchly" and "Open" as options that might allow me to change break durations, types, etc. When I right click either of those, nothing happens. Reminders do appear every few minutes, but I would love to customize them a little. :-) I have v21.1 or similar (not v20 ish) and am using Windows 7 on a laptop. Can you help me?

**Expected behavior:** [What you expect to happe]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by cbuschur** [comment]
I have tried right-clicking on the Stretchly icon in my system tray and in the start menu and on the desktop, but there is nothing other than "Stretchly" and "Open" as options that might allow me to change break durations, types, etc. When I right click either of those, nothing happens. Reminders do appear every few minutes, but I would love to customize them a little.  :-) I have v21.1 or similar (not v20 ish). Can you help me?

**Comment by hovancik** [comment]
Hi, you should look for the Stretchly icon in your tray area. Then, depending on your platform you can right/left-click to open Menu: 


![image](https://user-images.githubusercontent.com/4745859/73933754-6f453400-48dd-11ea-8fe3-68b19419aead.png)

Then click on "Settings"

**Comment by cbuschur** [comment]
OHHHHHHH!! I tried to do that on every icon EXCEPT the one in that darn system tray before! Thank you for your help and your quick reply!! I found the system tray icon and got to the settings by right-clicking on THAT one! YAY!

**Comment by hovancik** [comment]
Awesome, glad that helped :)
