### ISSUE TITLE
Stretchly is intercepting some hotkeys in Ubuntu

### ISSUE THREAD

**Issue by tjiagoM** [hovancik/stretchly#530]
### Prerequisites

- [X ] I'm using latest version: v 0.21.1
- [ X] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description

Sometimes stretchly intercepts some hotkeys I use in Ubuntu. More specifically, they are used as media hotkeys for play/pause and others. The ones that I use are `CTRL+ALT+P`, `CTRL+ALT+ +`, and `CTRL+ALT+O`. What happens is that I hit these keys and the media behaviour does not happen. I have to quit stretchly and the hotkeys work again, even if I open stretchly again.

Unfortunately, I was not able to find what is the issue that produces this error (eg suspension/hibernation/specific break), because this error just happens out of nowhere. However, it is clear at least that the issue comes from stretchly

Operating system: Ubuntu 18.04.4

**Comment by hovancik** [comment]
Interesting. Is that all the time or when in break? 

Stretchly only takes `Ctrl+X` when starting break and then release it when break is over.

**Comment by tjiagoM** [comment]
I was also surprised given I thought it was a problem with my computer, but after closing programs one by one, stretchly was the one.

The problem is everytime. I'm trying to figure out what conditions exactly lead to such behaviour to try to help debugging, but so far I have no clue (most of the times it's just working normally).

**Comment by hovancik** [comment]
Have you been using previous versions of Stretchly? Did you have the same problem? 

If previous versions were fine, then it's probably some electron thingy...

**Comment by tjiagoM** [comment]
No, I've used for the first time stretchly a couple of weeks ago, so I think the only version I've ever used was the last one.

I wasn't able to reproduce the problem again. I've tried suspending, hibernating, but the problem hasn't appeared ever since. 

I'll keep some attention and update this issue if I suspect of what might have lead to this problem. I've reported the bug anyway already in case you'd have some ideas of where the bug could be.

**Comment by hovancik** [comment]
:+1: 

I am on Debian but I never really use shortcuts, so haven't noticed anything, yet

**Comment by tjiagoM** [comment]
@hovancik Strangely, the problem never happened again... Maybe it's better to close this issue and then if this happens again I'll try to find more information about what sequence of events lead to it, and reopen the issue?

**Comment by hovancik** [comment]
Okay, I'm closing for now, thanks for your efforts!

**Comment by tjiagoM** [comment]
@hovancik I think I found the issue after all this time (after happening with another app going to the system tray). It seems is an old issue with Electron app: https://askubuntu.com/questions/925732/keyboard-shortcuts-stop-working-intermittently


At a certain point it is mentioned that the bug was solved (eg https://github.com/parro-it/electron-localshortcut/issues/16), but as I've never used Electron I don't know whether it is some feature you still use and which you could use differently. I leave it here in case you see a way to solve this from your side. Otherwise, well, thanks anyway!

**Comment by hovancik** [comment]
Hi @tjiagoM and thanks for the update. The issue you link to is only a package (`electron-localshortcut`), not electron itself. I am not using that package thought, so it must be something else, then ;/ 

Is it still happening to you, or only sometimes?

**Comment by tjiagoM** [comment]
What a mind blowing problem! :o In my case it only happens sometimes, thus the difficulty task to isolate the problem... Well, I guess next time I update my ubuntu that will stop being an issue :) 

Thanks for the time anyway!
