### ISSUE TITLE
update to latest version and keeps reverting to previous version

### ISSUE THREAD

**Issue by dmikester1** [hovancik/stretchly#531]
### Prerequisites

- [x] I'm using latest version: v 
- [ ] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description

[Description of the issue]

Operating system: 
I'm using Windows 10.  I have 0.21.0 running and it tells me there is an update.  I click on update to latest version and it takes me to the website.  I click the web installer and run through the install.  It closes my running version correctly and starts up correctly and I can verify I am now running 0.21.1.  However after a period of time, maybe it's after a Windows restart, I get notifications that an update is available and I notice I'm back to running 0.21.0 again.  I think I've installed 0.21.1 3 times now.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by hovancik** [comment]
Hi @dmikester1 ,thanks for the report!

How do you verify the version? From "About"  window? 
Maybe try going to Windows settings and see if there are multiple versions installed?

**Comment by hovancik** [comment]
No reply and pretty old issue, so closing.
