### ISSUE TITLE
not working under debian 10

### ISSUE THREAD

**Issue by nor500** [hovancik/stretchly#532]
Hello,
I tryid this app and it was awesome under ubuntu 18.04. I also installed it under debian 10( with gnome 3) . The installation went without error message. The app isntalled, whenever I click on it, it is starting. According to the terminal the strechly is already running, but it is not showing up in the upper bar of the the desktop as it did under ubuntu. What shall I do?

**Comment by hovancik** [comment]
Hi @nor500 , do you have the same desktop environments in ubuntu and debian? It might be missing some package under debian. 

I have Debian Sid with XFCE. I also have these packages installed: `libappindicator1`, `libappindicator3`

**Comment by nor500** [comment]
I have debian 10 with gnome 3. I checked those libappindicator1, it exist. However the other package is missing: E: Unable to locate package libappindicator3 How can I install that?

**Comment by nor500** [comment]
I have found that, the correct name: libappindicator3-1. Though stretchly is not working.

**Comment by hovancik** [comment]
@nor500 not sure ;/ I do not use Gnome so not sure how to proceed

do you have any other electron-based app that also have tray icon? do they work? I know for example skype is electron based nowadays

**Comment by nor500** [comment]
Sorry. In the meantime it started working. Great software. Congratulation! I have one suggestion for you  if you can can put the remaining time always visible on the tray it would be even better.

**Comment by hovancik** [comment]
Thanks :)

Stretchly has a tray tooltip, but unfortunatelly it's not working under Linux.

It used to work, but not anymore :/ bug in electron
