### ISSUE TITLE
Cannot install on Window10 in many ways

### ISSUE THREAD

**Issue by drtritm** [hovancik/stretchly#534]
### Prerequisites

-  I'm using latest version: 0.21.1
-  I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description

cannot install Stretchly after uninstall it one time. tried to install using execute file,not work, it keeps saying Installation aborted.
tried to use npm install, work but after reboot, everything is back to before installing.
 tried to install using chocolate install strectch with both new version and old version (0.20.1).still not work, it keeps saying users cancel installation.

Operating system: Win10 version 1903 

Sorry, Im not a super user and English is not my first language

**Comment by hovancik** [comment]
Hi there, 

maybe try deleting stretchly folder in app data? Something like `\Users\me\AppData\Roaming\stretchly`

**Comment by drtritm** [comment]
It's still not worked

**Comment by drtritm** [comment]
ok it's worked. Thanks a lot

**Comment by hovancik** [comment]
Awesome, glad to help ;]
