### ISSUE TITLE
Displays incorrectly

### ISSUE THREAD

**Issue by vchealy** [hovancik/stretchly#535]
### Prerequisites

- [ ] I'm using latest version: v 0.2.1
- [ ] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description

On the initial install of the software, the action of the software did not give similar presentation as to that of the previous version.

Operating system: Windows 10

### Steps to Reproduce

1. Uninstall previous version
2. Install latest version

**Expected behavior:** The screen blocker to appear on each screen and a top of all other windows

**Actual behavior:** Screen blocker appears only on the main screen and behind windows currently in use.

**Reproduces how often:**I only did this once, as I found a workaround to the issue

### Additional Information

The work around to this issue, resolves issue permanently. 
1. Select the option to go full screen.
    This then presents the screen blocker on the main screen blocking the full screen.
2. Unselect the Full Screen option
The screen blocker then presents as the previous version, on all screens and on top of any window that was being worked on.

**Comment by hovancik** [comment]
Hi, this is bug with `electron`, the technology I use under the hood. Please follow this issue for updates https://github.com/hovancik/stretchly/issues/524
