### ISSUE TITLE
macOS "stretchly cannot be opened because the developer cannot be verified"

### ISSUE THREAD

**Issue by mikicho** [hovancik/stretchly#541]
### Prerequisites

- [x] I'm using latest version: v 
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description
![image](https://user-images.githubusercontent.com/11459632/76736173-fe602a00-676e-11ea-8f2c-2bf59693585e.png)

Operating system: macOS Catalina 10.15.2 (19C57)

### Steps to Reproduce

1. install strechly

**Expected behavior:** open the app

**Actual behavior:** warning popup

**Reproduces how often:** 100%

### Additional Information

There is a known workaround for this but it would be nice that we won't need that

**Comment by hovancik** [comment]
Hi @mikicho , the only solution to this is me buying account from Apple and then me buying certificate, which I do not plan to do ;/ Sorry for trouble ;/

**Comment by mikicho** [comment]
As I thought, I hate them!
@hovancik  Great app, thanks :)

**Comment by hovancik** [comment]
@subesokun sorry to hear that but it doesn't make sense for me to pay 99 USD to Apple every year ;/

**Comment by sampart** [comment]
In case anyone else, like me, found this issue and was wondering what the workaround was:

* In the Finder folder, find the Stretchly icon.
* Control-click (or right-click) the app icon, then choose Open from the shortcut menu.
* Click Open.

The app is saved as an exception to your security settings, and you can open normally in the future just as you could any authorised app.

**Comment by hovancik** [comment]
There is also mention of this in readme/website with link to the official macOS documentation https://github.com/hovancik/stretchly#macos
