### ISSUE TITLE
mid sound in microbreaks

### ISSUE THREAD

**Issue by mikicho** [hovancik/stretchly#542]
### Prerequisites

- [x] I'm using latest version: v 
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description

A lot of the microbreaks contain "tasks" that require 10 seconds on one side and 10 on the other.
A small beep sound in the mid which tells us to switch the side would be great.
Thanks

**Comment by hovancik** [comment]
Hi @mikicho and thanks for the idea

This would be huge task, I'll keep it open and we shall see ;]

**Comment by Chealer** [comment]
I imagine this ticket's title is supposed to read "mid sound in microbreaks".

**Comment by hovancik** [comment]
I'll close this as I don't see this realistically to happen. Sorry.
