### ISSUE TITLE
Debugging instructions not sufficient in readme

### ISSUE THREAD

**Issue by Tlazypanda** [hovancik/stretchly#547]
### Prerequisites

- [x] I'm using latest version: v 
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description

Operating system: Ubuntu 16.04

### Additional Information
In linux ctrl+shift+i opens the developer tools in the background and does not help with debugging. One workaround is to specify in the docs to uncomment openDevTools(). For example the debugging instructions should clearly specify that 
For opening the developer tools for Microbreak:-
- Uncomment line 363 in `app/main.js`
For opening the developer tools for Break:-
- Uncomment line 459 in `app/main.js`
For opening the developer tools for Settings:-
- Uncomment line 676 in `app/main.js`

**Comment by Tlazypanda** [comment]
@hovancik can you kindly approve this issue?Thanks :v:

**Comment by hovancik** [comment]
Hi @Tlazypanda , best way to debug is to edit https://github.com/hovancik/stretchly/tree/redesign#development and mention then there is a `npm run dev` which let's you debug via browser on `http://localhost:9222`

Feel free to check it out and create PR with better README

**Comment by hovancik** [comment]
closing as #602 was merged
