### ISSUE TITLE
Possible Fork for Distancing Computer in the Evening

### ISSUE THREAD

**Issue by SeabassHeyneman** [hovancik/stretchly#550]
### Prerequisites

- [X] I'm using latest version: v0.21.1

### Description

I'd like to use stretchly to make my computer unavailable in the evenings. I'd like to schedule it to go on break at 9PM and last for at least a couple of hours. 

Operating system: Mac OS

### Additional Information

I'm curious to find out how I can do this.

Here's one idea-- 

Can I write a script that starts a break and sets a custom length? 
And then set a cron job to tell that script to run at 9PM nightly? 

Let me know!

**Comment by hovancik** [comment]
Hi @SeabassHeyneman , right now it would be hard to do... 

You could write a script that changes the length of break but there is no way to "start a break" outside of stretchly. There is related issue here: https://github.com/hovancik/stretchly/issues/458 

I will close this in favor of that one, please follow there ;]
