### ISSUE TITLE
Added Difficulty to Skip Breaks

### ISSUE THREAD

**Issue by SeabassHeyneman** [hovancik/stretchly#551]
### Prerequisites

- [X ] I'm using latest version: v 0.21.1

### Description

I'd like to make it more difficult to skip a break. I can click cmd + q and get out of it. :/ 

I tried to use "App Shortcuts" in system preferences to re-map cmd + q to reset breaks.

Can I prevent CMD+Q from closing the break from stretchly?

Operating system: MacOS

**Comment by SeabassHeyneman** [comment]
<img width="635" alt="Screen Shot 2020-03-26 at 11 12 48 PM" src="https://user-images.githubusercontent.com/52939487/77727426-863c0480-6fb7-11ea-8c29-382cade1e1bb.png">

**Comment by hovancik** [comment]
Hi @SeabassHeyneman , 
if you uncheck "allow to postpone" and check "don't let me skip" you won't be able to cancel break ;] 
![image](https://user-images.githubusercontent.com/4745859/77746666-938bda00-701d-11ea-8e5b-6953ce344135.png)

Please close the issue if this helps ;]

**Comment by SeabassHeyneman** [comment]
Hi @hovancik! It looks like you can click command + Q to end a break after it starts.

**Comment by hovancik** [comment]
Ah, @SeabassHeyneman , sorry, I didn't notice that you wrote `Cmd+Q`... I was thinking `Cmd+X`, which is shortcut created by Stretchly... 

Not sure if I can change `Cmd+Q`, as that's the shortcut on OS level. For example on Linux it closes whole app (Any app, not just Stretchly). I guess on macOS it closes any windows as well.  

https://www.quora.com/How-do-I-disable-Command-q-in-OSX suggests that your solution should work, though

**Comment by SeabassHeyneman** [comment]
Sweet, I'll close this
