### ISSUE TITLE
Cannot run on catalina

### ISSUE THREAD

**Issue by ruben-aghayan** [hovancik/stretchly#556]
### Prerequisites

- [x] I'm using latest version: v 
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description

“stretchly” cannot be opened because the developer cannot be verified.

Operating system:
macOS Catalina

### Steps to Reproduce

1. Download from dmg from havancik.net
2. Install
3. Go to apps and run

**Expected behavior:** Stretchly should start

**Actual behavior:** Stretchly does not start.

**Reproduces how often:** Always

### Additional Information

see https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac for a workaround.

**Comment by hovancik** [comment]
Hi @ruben-aghayan , to be able to open Stretchly without "the workaround", I would need to buy Apple Developer account and then buy certificate, which I do not plan to do, as it's not cheap thing to do ;/

Sorry about it.
