### ISSUE TITLE
Change time units to singular on Settings Page 1

### ISSUE THREAD

**Issue by trisapeace** [hovancik/stretchly#563]
Hi everyone,

I just downloaded your application for the first time and am excited about using it. I opened it up to customize my settings the way that I want them and noticed this grammatical error. Seeing as how this project is open-source, I thought I'd provide a quick fix. Hope it helps!

:-)
Theresa

### Prerequisites

- [x] I'm using latest version: v0.21.1
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description

In English, when you use a length of time as an adjective to describe a noun, you will use a hyphen and the singular form of the time unit (ref: https://data.grammarbook.com/blog/numbers/numbers-as-adjectives/). For example: "I'm going to take a 5-minute break."

This is as opposed to the adverbial expression to describe the same thing which doesn't use a hyphen and uses the plural form of the time unit. For example: "I'm going to take a break for 5 minutes."

Looking at this setting in the UI, I feel like it would look weird to have the hyphen because it would look like a minus sign right beside the plus sign. So I don't think that change needs to be made. However, when you read this setting out loud, it sounded weird in English to have the plural form of the units.

Operating system: Windows 10 Pro Version 1903

### Steps to Reproduce

1. Right-mouse click on Stretchly in the taskbar
2. Click "Settings"

**Expected behavior:**
It should say "- 10 + second break every - 20 + minutes" and "- 2 + minute break every - 2 + microbreaks"

**Actual behavior:** 
It says "- 10 + seconds break every - 20 + minutes" and "- 2 + minutes break every - 2 + microbreaks"
![image](https://user-images.githubusercontent.com/1490437/79608996-cd934d80-80aa-11ea-8ef3-c2fe207216e3.png)

**Reproduces how often:** Every time

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by hovancik** [comment]
@trisapeace cheers and thanks for writing! 
I am actually working on whole new version ;] Could you check it for me? 

![image](https://user-images.githubusercontent.com/4745859/79685358-92bf2000-8238-11ea-903d-2f8ad7aba2b2.png)

**Comment by trisapeace** [comment]
Hi @hovancik . Those look great! Thanks. I think that your new version looks much cleaner. Feel free to close this Issue :-)

**Comment by hovancik** [comment]
Awesome :)
