### ISSUE TITLE
Help wanted: Translations for 1.0 

### ISSUE THREAD

**Issue by hovancik** [hovancik/stretchly#584]
Hi everyone, I am tagging you because in past, you had translated Stretchly into your language.  There will soon be new version, 1.0, and I am in need to update translations as a lot has changed. 

![image](https://user-images.githubusercontent.com/4745859/82037577-9f515f80-96a2-11ea-9a5e-3c12ed7d2cf0.png)

Please read on if you would like to help. 

1. The latest code with redesign is here: https://github.com/hovancik/stretchly/tree/redesign. 
2. If you wanna make a translation, please fork that branch and create PR to that branch so that we don't have more people working on same translation. 
3. Link your PR to this Issue by writing `#584` in PR so other people can see you work on it and comment.  
4. If you have any questions please ask me in your PR so that we don't spam people in this thread. 
5. You only need to update your translation file. 

Some things that has changed:
- stretchly -> Stretchly
- Microbreak -> Mini Break
- Break -> Long Break

Plurals: 
Each language handles plurals differently, thus you might see things such as `translation`, `translation_plural` and `translation_0` or `translation_1`. Go ahead to https://jsfiddle.net/sm9wgLze, input your language code and you will see examples to help you translate correctly.  

I've tried to copy texts that has not changed but please check those as well. There might be some further changes in translations but I hope there won't be any ;)

Thanks so much! 

@unholyHub @Jackymancs4 @aleuca @Sveijk @fizvlad @fdalvi @asterite @kavya-jain @p-bo @bramborman @ValarMarkhulis @stothew @robot-5 @manueljaguilera @whiver @laem @FWDekker @sunn-e @purva98 @cgand @dnjstlr555 @troyanas @sheriallis @rzadp @jony0008 @mfyz @dbtek @neooleg @Gowee @wilicw @pan93412

**Comment by Gowee** [comment]
The Simplified Chinese locale file seems to miss some fields, such as `main.toBreak`. Could you please take a look?

**Comment by hovancik** [comment]
@Gowee thanks for noticing, should be fixed now :)

**Comment by mcakira** [comment]
Hello Dear Hocanik,
I can help you on Turkish translations.

**Comment by nicolasdij** [comment]
You can sign me up on Spanish (Latin America) translations if you like

**Comment by Gab1Riel** [comment]
Hi,
I would like to help with the Romanian translation.

**Comment by hovancik** [comment]
Thanks everyone, feel free to open PRs :)

**Comment by hovancik** [comment]
Hi there, if anyone would like to contribute with translations for 1.0, please try to do it ASAP. I am gonna make the release soon...

**Comment by sheriallis** [comment]
I'm working on the Dutch translations right now and I should be done with them in about an hour.

**Comment by Gab1Riel** [comment]
Hi,
I am sorry, I could not work on this as I wanted.
Is there someone else that could translate into romanian?
If not, I will try as soon as possible.

Gabriel

**Comment by hovancik** [comment]
No worries, I've released 1.0 but you can update the translation when you have time ;]

**Comment by pramit-marattha** [comment]
Hi ! Hovancik 
Is it ok if I work on Nepali translation.
