### ISSUE TITLE
visibleOnFullScreen

### ISSUE THREAD

**Issue by pjebs** [hovancik/stretchly#587]
` breakWinLocal.setVisibleOnAllWorkspaces(true, { visibleOnFullScreen: true })`

visibleOnFullScreen is currently deprecated. Once it's removed, what will be the effects?

**Comment by hovancik** [comment]
As I understand it, on macOS, when users have multiple workspaces, Stretchly won't be visible on those workspaces that have app in fullscreen mode ;/

**Comment by hovancik** [comment]
But it looks like it might have never worked anyway: https://github.com/electron/electron/issues/19674
