### ISSUE TITLE
Micro breaks should recommend on 20ft. looking

### ISSUE THREAD

**Issue by Tiksagol** [hovancik/stretchly#588]
Hi,

Thanks for the great app.
AFAIK, the 20-20-20 micro-break rule says one should focus every 20 minutes for 20 seconds on an object that is 20 feet distance (~6 meter), rather than 20 meters as the micro-break screen suggest.

**Comment by hovancik** [comment]
Thanks ;] 

There are many different recommendations, the one I have found was to look as far as possible, at least 20 meters. I'll add yours as well ;]
