### ISSUE TITLE
Windows 10 Shortcuts

### ISSUE THREAD

**Issue by KiGniark** [hovancik/stretchly#594]
Hello! 

Thanks for the app ! I'm using it daily and I appreciate the breaks, the breeze feeling and the ease of use and set up.

I'm using Ctrl+X to cut a lot when I'm typing texts on editors. It has happens sometimes just when the popup comes up and well it postponed the break.

I'd like to have a way to disable the shortcut or edit it to be in a less used/accessible shortcut.

Thanks for your attention and have a nice day !

**Comment by hovancik** [comment]
Hi @KiGniark , thanks for the feedback ;]

What you could do right now, would be to disable ability to Postpone and Skip altogether. But you would not be able to postpone in case you want to ;/ 

Adding configuration for shortcuts is definitely good idea :)

**Comment by hovancik** [comment]
Closing as this was added :)
