### ISSUE TITLE
Support for Monochrome icon on OS X

### ISSUE THREAD

**Issue by itay-grudev** [hovancik/stretchly#60]
Could you add support for monochrome icons on OS X so the icon doesn't look ugly in the menu bar. Also a HighDPI (2x) icon would be appreciated, as it looks quite pixelated on Retina displays.

**Comment by hovancik** [comment]
Thanks for feedback, I'll try.

**Comment by itay-grudev** [comment]
I just downloaded the new version. Thanks!
