### ISSUE TITLE
FR: start breaks at specific times

### ISSUE THREAD

**Issue by despagito** [hovancik/stretchly#606]
### Prerequisites

- [x] I'm using latest version: v 0.21.1
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description

Add starting time for circles. E.g. starts at every hour.

**Comment by hovancik** [comment]
This is not in TODO, because I think it would require huge changes, but I'll keep it here.

**Comment by hovancik** [comment]
I will close this as I do not plan to implement this any time soon. My other app has this option, but it's a bit different than Stretchly. It's called LaterOn and it allows you to specify custom notifications/reminders on custom schedule: https://lateron.app
