### ISSUE TITLE
Tray icon to show the time until the next break

### ISSUE THREAD

**Issue by Alexsey** [hovancik/stretchly#607]
- [x] I'm using latest version: v 
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description

It would be really nice if the tray icon would show the time until next break in a similar way as [Time Out - Break Reminder](https://www.dejal.com/timeout/images/) (see *Status item popover* screenshots):
 * if there is more than one hour - show the number of full hours
 * if there is less than one hour but more than a minute - show the number of full minutes
 * if there are less then one minute - show the number of seconds (or just *45s* -> *30s* -> *15s* for not blinking too often :) )

**Comment by hovancik** [comment]
Hi, this will be similar in version 1.0 of Stretchly, which is coming soon-ish ;]

**Comment by Alexsey** [comment]
Cool, thank you!

**Comment by balazsnasz** [comment]
@Alexsey did you mean the tray tooltip or the tray icon itself?
Because in the upcoming version only the tooltip will change. In the current dev version of the upcoming new version the icon doesn't show the remaining time left.

**Comment by Alexsey** [comment]
Definitely not a tooltip

In Time Out they show it next to the tray icon in tray bar (I think technically it's a part of the icon). It can be done in the same way, or it can be a part of the tray icon (e.g. on top of it) - more a choice of design

The idea is that the remaining time should always be visible

**Comment by balazsnasz** [comment]
I thought so. For macOS it's possible to add text near the icons, but for other platforms (like Windows and most Linux distros) it's not possible.
I think we should generate all of the icon files (like 30m...1m, 50s...10s, <10s) and change them dynamically. So we should write the remaining texts inside the icon.
Also, we should make this optional because not all users like to get distracted by a countdown, so we should make it possible to turn on/off this feature.

What do you think guys? @hovancik @Alexsey

**Comment by Alexsey** [comment]
👍

**Comment by hovancik** [comment]
TBH I don't wanna do it, I don't think it will be nice and considering different languages have different shortcuts it's too much work (plus new icons when new language is added, and I have no skill in graphics). There is reason why almost no app uses tray icons to show extra information...

**Comment by hovancik** [comment]
can't really imagine let's say 25m fitting in here, mac icon size is **16x16px**

![image](https://user-images.githubusercontent.com/4745859/85048060-0c20b380-b193-11ea-808c-a7ab94064868.png)

**Comment by Alexsey** [comment]
This is how Time Out looks:
![Screenshot 2020-06-18 at 19 51 52](https://user-images.githubusercontent.com/6392013/85049770-d1704880-b19d-11ea-99cf-9ef9b23d6a48.png)

Yes, of course, to show time the icon width need to be extended

I absolutely agree with you that the localization of this feature could be a headache. And at the same time from a user perspective, it's just *s*, *m* and *h*... so maybe the timer feature can go separately from it's localization?

**Comment by balazsnasz** [comment]
What if we add nicely designed icons where there is only a number written in a circle?
So something like this: (1) or (2) or (30).
That could eliminate the translation problems while solving the proper display of the remaining time left until the next break.

**Comment by Alexsey** [comment]
good idea. Until it's more than an hour it could look like `2:34`, when there are only minutes it could be just number like `22` and when there are less than a minute it could be again like `0:30`

**Comment by balazsnasz** [comment]
In my opinion, having breaks longer than 60 minutes is not a good idea.
I thought the following:

- For 1-59 minutes: (1) .... (59)
- For less than 1 minute: (<1)
and that's all.

**Comment by hovancik** [comment]
Hi, I guess I will disappoint you but I don't think we need 2 same functionalities: clicking on icon or hovering on OS where it is supported is not that of a complication I think :)

**Comment by Alexsey** [comment]
@hovancik yes, if you are using the mouse all the time. I'm not :(

**Comment by balazsnasz** [comment]
I also agree with @Alexsey. It's a distraction if I have to work to hover/click the Stretchly icon during work. However, if I could just take a half second look at the icon to tell how much time is left until the next break, it would be much easier.
