### ISSUE TITLE
Multiple monitors

### ISSUE THREAD

**Issue by niladam** [hovancik/stretchly#61]
I just started using this and for some reason -- i'm using multiple monitors -- it doesn't show the break on both monitors ?

I think you could try and tie the break notification to where the mouse is ? (this way you'd get a better reading what's the current 'selected' monitor);

I also think it would be great to have the notification full screen.

**Comment by hovancik** [comment]
Thanks for the feedback ;] 

Right now the break should be shown only on 'primary' monitor. Working with more monitor sucks a bit, especially with Linux. I like the idea of showing notification where the mouse is, I'll try to implement it. 

Fullscreen could be added to options, too.

**Comment by hovancik** [comment]
@niladam would you like to test it from source? 
I've pushed changes to `feature/multiple-monitor-enhance`

**Comment by ptitvert** [comment]
Would like to have also full support of all monitor instead of only the main one.
Even as an option.

**Comment by hovancik** [comment]
@ptitvert it's implemented but buggy in latest release... it's actually a bug with technology that I use so a bit harder to fix, if possible
