### ISSUE TITLE
Unable to install pacman package because of a broken dependency (workaround inside)

### ISSUE THREAD

**Issue by Elbino** [hovancik/stretchly#616]
### Description

Installing the .pacman package with Pacman fails because of a broken dependency.

`warning: cannot resolve "libappindicator-sharp", a dependency of "stretchly"
:: The following package cannot be upgraded due to unresolvable dependencies:
      stretchly
`

Operating system:
```
OS: Manjaro Linux x86_64 
Kernel: 5.6.16-1-MANJARO 
Shell: zsh 5.8 
Resolution: 2560x1440, 2560x1440 
DE: GNOME
Terminal: terminator 
CPU: AMD Ryzen 7 3700X (16) @ 3.600GHz 
GPU: AMD ATI Radeon RX 5700 XT 
Memory:  15988MiB
``` 

### Steps to Reproduce

1. Download https://github.com/hovancik/stretchly/releases/download/v0.21.1/stretchly-0.21.1.pacman
2. Run` pacman -U stretchly-0.21.1.pacman`

**Expected behavior:** [What you expect to happen]
I expect to successfully install the package without dependency errors.

**Actual behavior:** [What actually happens]
An error is thrown

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Additional Information
I've found a workaround by using `sudo pacman -U stretchly-0.21.1.pacman --assume-installed  libappindicator-sharp`

**Comment by hovancik** [comment]
Hi and thanks for the report ;]

Does the package `libappindicator-sharp` exists in Manjaro? 

I am not familiar with pacman or Manjaro but for example in Debian, dependencies of single `.deb` needs to be installed by user. So when I do `dpkg -i stretchly.deb`, I then need to run `apt-get install -f` to install missing dependences.

**Comment by Elbino** [comment]
Hi @hovancik. Pacman will try to install dependencies automatically (after approval of course). It will scan the the Arch User Repo (after enabling) and Manjaro Repo (basically curated AUR packages) to resolve and install dependencies of a package. Besides the order it looks similar to how Debian does it.

I had a look and I did find Manjaro / Arch does not distribute the "obsoleted" libappindicator-sharp package anymore. https://lists.archlinux.org/pipermail/arch-commits/2020-March/722392.html

I think removing libappindicator-sharp from pacman dependency list should solve it the installation issue. (The app runs just fine)

**Comment by hovancik** [comment]
Seems the issue is solved with newer version so next Stretchly release should be fine.

**Comment by Elbino** [comment]
Perfect, thanks for the quick response and following up.

**Comment by eMUQI** [comment]
> Seems the issue is solved with newer version so next Stretchly release should be fine.

when will the next version release ?
looking forward to the next release !

**Comment by hovancik** [comment]
Hopefully this weekend ;]
