### ISSUE TITLE
Set volume more than 100%

### ISSUE THREAD

**Issue by ClassicDarkChocolate** [hovancik/stretchly#619]
### Prerequisites

- [x] I'm using latest version: v 
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description

Thanks for creating this app. Is it possible to set volume more than 1. The sound is much lower than the other apps and I can barely notice it. Currently, setting volume to 1 or 1000 have no difference.

**Comment by hovancik** [comment]
Hi @ClassicDarkChocolate,

according to docs here,https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/volume, it's not possible :( 

>  A double values must fall between 0 and 1, where 0 is effectively muted and 1 is the loudest possible value.

Depending on OS, some systems have specific controls for applications, which might be changing the value. If yours have it, you could try previewing the sound from settings (or when break is ending) to see what's the volume. 

On my Debian Linux with KDE, stretchly appears as "Chromium" and is on 100%. 

![image](https://user-images.githubusercontent.com/4745859/86106299-adc3d100-bac0-11ea-857c-33b9d3cca105.png)

I hope this helps!

(But as it's not possible to change this in code, I am closing the issue)

**Comment by ClassicDarkChocolate** [comment]
Hi, if so, is it possible to change the base volume louder?

**Comment by hovancik** [comment]
What do you mean by base volume? The one from 0..1 is the only one I can set. Did you manage to find whether OS changes volume for Stretchly? I guess that's the issue. Never had any issue with this, only people asking to make it less volume, so I added the volume option.

**Comment by ClassicDarkChocolate** [comment]
@hovancik The notification sound is comparatively lower than other applications. That's why I hope there's a way to make it louder.

**Comment by hovancik** [comment]
@ClassicDarkChocolate maybe try this?  https://www.howtogeek.com/352787/how-to-set-per-app-sound-outputs-in-windows-10/

**Comment by ClassicDarkChocolate** [comment]
@hovancik With this method, I have to set the volume of every new application lower.
