### ISSUE TITLE
Break screen not showing

### ISSUE THREAD

**Issue by easpro** [hovancik/stretchly#620]
If a break begins while using my PC's mouse, the break screen does not appear on top of other windows. Rather, it appears behind other windows, making it impossible to know if a break has started. I'm running Windows 10 Home, version 1909 and Stretchly 0.21.1

**Comment by claire181129** [comment]
same problem, Win 10 education 1903, Stretchly 0.21.1

**Comment by rob-stewart** [comment]
Stretchly windows appear at the bottom of the Z order for me, too, but I suspect it is because I enable the _Activate a windows by hovering over it with the mouse_ option in the **Ease of Access Center**'s **Make the mouse easier to use** control panel. IOW, I have _focus follows mouse_ enabled.

**Comment by easpro** [comment]
> Stretchly windows appear at the bottom of the Z order for me, too, but I suspect it is because I enable the _Activate a windows by hovering over it with the mouse_ option in the **Ease of Access Center**'s **Make the mouse easier to use** control panel. IOW, I have _focus follows mouse_ enabled.

Mouse hover over feature is not turned on for me, so must be another issue causing the problem.

**Comment by hovancik** [comment]
is this with fullscreen windows?

**Comment by rob-stewart** [comment]
No. I rarely maximize windows.

On July 2, 2020 2:00:11 PM EDT, Jan Hovancik <notifications@github.com> wrote:
> is this with fullscreen windows? 
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/hovancik/stretchly/issues/620#issuecomment-653146907

--
Rob

(Sent from my portable computation device.)

**Comment by easpro** [comment]
No, I too rarely maximize windows.

**Comment by hovancik** [comment]
I Stretchly window is fullscreen or not?

**Comment by easpro** [comment]
> I Stretchly window is fullscreen or not?

The Stretchly window appears fullscreen, but behind other windows that are open.

**Comment by hovancik** [comment]
Well, quick fix right now is to not use Stretchly in fullscreen (maybe). Fullscreen is pretty much broken in Electron on Windows... 

I have a workaround for fullscreen on Win coming soon-ish in Stretchly 1.0 but no idea whether it will fix this specific combination...

**Comment by rob-stewart** [comment]
I tried it both ways. BTW, it sometimes appears on top many times in a row, but it more often appears behind other windows.

On July 3, 2020 4:09:57 AM EDT, Jan Hovancik <notifications@github.com> wrote:
> I Stretchly window is fullscreen or not? 
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/hovancik/stretchly/issues/620#issuecomment-653414788

--
Rob

(Sent from my portable computation device.)

**Comment by hovancik** [comment]
Interesting, must be some problem with Electron, I am not doing anything special here, only calling Electron's APIs. Let's see how it is in upcoming 1.0 version of Stretchly. I don't have a  windows machine.

**Comment by anantakrishna** [comment]
> If a break begins while using my PC's mouse, the break screen does not appear on top of other windows. Rather, it appears behind other windows, making it impossible to know if a break has started. I'm running Windows 10 Home, version 1909 and Stretchly 0.21.1

For me the same symptoms, the same version.

**Comment by anantakrishna** [comment]
Happened just now. You see, the Stretchly window is behind my working window and the task panel, the break time is past.
![Screenshot_30](https://user-images.githubusercontent.com/6065071/86515429-feca2100-be42-11ea-9ede-667618fbb6ea.png)

**Comment by hovancik** [comment]
I forgot but there is an issue open in Electron about this:  https://github.com/electron/electron/issues/20933

**Comment by anantakrishna** [comment]
In version 1.0.0 this bug has disappeared, however when I recently updated to 1.1.0, the bug again takes place.
