### ISSUE TITLE
Skipping breaks bug

### ISSUE THREAD

**Issue by Nibzen** [hovancik/stretchly#621]
### Prerequisites

- [x] I'm using latest version: v 0.21.1
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description

[Description of the issue]
When running breaks on full-screen with the 'don't let me skip breaks' option enabled, it is extremely simple to escape the break screen by pressing command +tab twice

Operating system: MacOS High Sierra 10.13.6

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** Cannot skip break

**Actual behavior:** Can skip break

**Reproduces how often:** 100%

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by hovancik** [comment]
Hi, this is how macOS behaves, I mean on OS-level. I can't change that ;/ I tried in past some ideas how to workaround it, but it never worked...

**Comment by Nibzen** [comment]
Dang, yours is such a nifty minimalistic tool otherwise. Thanks so much for what you've created. 

Just a thought, have you checked Dejal's Time Out app. It is a screen timer but with many many features that can get quite confusing. However, its plus point is that the breaks come in as a screen overlay and while the comment + tab can switch to other apps (which can be seen if the break screen is set to semi-transparent) but the overlay remains. 

This is an idea, which if you would try would make Stretchly just simple awesome.

**Comment by hovancik** [comment]
Yeah I've seen that app, many many summers ago. He is using native code, so his app can do more powerful stuff. I am using Electron as aiming to be able to use app on more platforms, but Electron's APIs are less powerful ;/
