### ISSUE TITLE
我尝试更改了配置文件的编码为 utf-8 ，以便于它更好的支持中文显示。

### ISSUE THREAD

**Issue by GoGoogle** [hovancik/stretchly#622]
### Prerequisites

- [x] I'm using latest version: v 0.21.1
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description
Operating system:  Windows 7 

### 出于对中文提示的需求，我更改了以下配置文件：
`%AppData%\stretchly\config.json`

### 改动如下：
编码转为 UTF-8
配置：`useIdeasFromSettings: true`
并对提示信息进行了简单的翻译：
[config.json.txt](https://github.com/hovancik/stretchly/files/4870558/config.json.txt)

希望对中文有需求的人有所帮助。

**Comment by hovancik** [comment]
Hi, sorry, but I only speak English and Slovak.

**Comment by GoGoogle** [comment]
> Hi, sorry, but I only speak English and Slovak.

I am sorry too.

my english is very poor.
but i'm used google translate

the `%AppData%\stretchly\config.json` file default encoding is ANSI
i'am converted , now is UTF-8 , Chinese is normal display now.

**Comment by hovancik** [comment]
Ah, I think I understand. I guess that's something that Windows OS is doing, as on my Linux machine it's UTF-8 already. 

Not sure if I can do anything here.

**Comment by GoGoogle** [comment]
> Ah, I think I understand. I guess that's something that Windows OS is doing, as on my Linux machine it's UTF-8 already.
> 
> Not sure if I can do anything here.

OK
Thx

**Comment by wangrui1573** [comment]
{
	"microbreakDuration": 20000,
	"microbreakInterval": 1200000,
	"breakDuration": 300000,
	"breakInterval": 2,
	"breakNotification": true,
	"microbreakNotification": true,
	"breakNotificationInterval": 30000,
	"microbreakNotificationInterval": 10000,
	"microbreak": true,
	"break": true,
	"microbreakStrictMode": false,
	"breakStrictMode": false,
	"morningHour": 6,
	"microbreakPostpone": true,
	"breakPostpone": true,
	"microbreakPostponeTime": 120000,
	"breakPostponeTime": 300000,
	"microbreakPostponesLimit": 1,
	"microbreakPostponableDurationPercent": 30,
	"breakPostponesLimit": 1,
	"breakPostponableDurationPercent": 30,
	"mainColor": "#478484",
	"miniBreakColor": "#478484",
	"transparentMode": false,
	"opacity": 0.9,
	"audio": "crystal-glass",
	"miniBreakAudio": "crystal-glass",
	"volume": 1,
	"fullscreen": true,
	"ideas": true,
	"naturalBreaks": true,
	"naturalBreaksInactivityResetTime": 300000,
	"allScreens": true,
	"useIdeasFromSettings": true,
	"language": "zh-CN",
	"notifyNewVersion": true,
	"isFirstRun": false,
	"posLatitude": 0,
	"posLongitude": 0,
	"useMonochromeTrayIcon": false,
	"useMonochromeInvertedTrayIcon": false,
	"silentNotifications": false,
	"monitorDnd": false,
	"microbreakStartSoundPlaying": false,
	"breakStartSoundPlaying": false,
	"themeSource": "system",
	"endBreakShortcut": "CmdOrCtrl+X",
	"breakWindowWidth": 0.85,
	"breakWindowHeight": 0.85,
	"checkNewVersion": true,
	"breakIdeas": [
		{
			"data": [
				"不要一个人休息",
				"你是否发现一个人休息很难？试着与同事一起休息吧。除了更容易坚持休息，你还有机会更好地了解他们。一起休息会增加工作效率。"
			],
			"enabled": true
		},
		{
			"data": [
				"远离",
				"你是否注意到你的大脑可以独立解决问题？只需离开电脑并休息一下，思考完全无关的事情。"
			],
			"enabled": true
		},
		{
			"data": [
				"微小休息",
				"休息是确保肌肉骨骼系统工作性能的关键组成部分。频繁休息可以缩短任务持续时间，降低人体对人体工程学伤害风险的暴露。"
			],
			"enabled": true
		},
		{
			"data": [
				"冥想",
				"研究表明，基于正念的练习有助于减少焦虑、抑郁、压力和疼痛，有助于改善整体健康、心理健康和生活质量。不确定如何开始？有很多应用程序可以帮助你。"
			],
			"enabled": true
		},
		{
			"data": [
				"眨眼",
				"长时间盯着屏幕会导致你不频繁眨眼，从而使眼睛暴露在空气中。快速地眨几秒钟来刷新泪膜并清除眼表的灰尘。"
			],
			"enabled": true
		},
		{
			"data": [
				"人体工程学",
				"键盘、鼠标、显示器或工作表的高度和角度不当可能导致健康问题。花些时间了解一下桌面人体工程学知识。"
			],
			"enabled": true
		},
		{
			"data": [
				"动起来",
				"你可以在办公室内通过很多方式锻炼。尝试原地踏步或做桌上俯卧撑。"
			],
			"enabled": true
		},
		{
			"data": [
				"改变",
				"你有一个稳定球或站立式工作桌吗？考虑暂时用它们取代你的办公椅。"
			],
			"enabled": true
		},
		{
			"data": [
				"留意",
				"你是否在发呆或注意力不集中？这是你需要休息的信号。"
			],
			"enabled": true
		},
		{
			"data": [
				"无技术走走",
				"何不来一次没有技术的散步？"
			],
			"enabled": true
		},
		{
			"data": [
				"新陈代谢",
				"新兴研究表明，长时间坐着会增加代谢综合征、心脏病发作和中风等风险，甚至可能增加整体死亡风险。定期的散步休息有助于改善循环系统，从而抵消一些问题。"
			],
			"enabled": true
		},
		{
			"data": [
				"活跃会议",
				"考虑将会议从会议室移到大厅？步行不仅可以消耗热量，还可能促进合作感。"
			],
			"enabled": true
		},
		{
			"data": [
				"吃水果",
				"花点时间慢慢地吃一些水果。注意它的味道、口感和新鲜度。"
			],
			"enabled": true
		},
		{
			"data": [
				"厕所",
				"去卫生间时，走到工作场所设施最远的卫生间。"
			],
			"enabled": true
		},
		{
			"data": [
				"喝咖啡休息",
				"喝咖啡休息时，每次都考虑走个5分钟的步。"
			],
			"enabled": true
		},
		{
			"data": [
				"同事",
				"不要通过电子邮件或消息与办公室同事交流，走到他们的办公桌与他们沟通。"
			],
			"enabled": true
		},
		{
			"data": [
				"学习",
				"在对健康志愿者进行的研究中，美国国立卫生研究院的研究人员发现，频繁且早期地休息可能有助于我们的大脑学习新技能。"
			],
			"enabled": true
		},
		{
			"data": [
				"锻炼",
				"有证据表明，小量定期锻炼可以带来显著的健康益处，包括明显减少压力。"
			],
			"enabled": true
		},
		{
			"data": [
				"重复",
				"找到适合你的伸展-伸展计划了吗？不要忘记多次重复，以更好地抵抗长时间坐着的影响。"
			],
			"enabled": true
		},
		{
			"data": [
				"手腕和前臂",
				"将手臂伸直，手掌向内，然后缓慢地顺时针旋转手四次，然后逆时针旋转四次。"
			],
			"enabled": true
		},
		{
			"data": [
				"背部伸展",
				"双手握在头后面，然后将它们一起抬起，直到手掌向上。"
			],
			"enabled": true
		},
		{
			"data": [
				"动起来",
				"每30分钟的静坐时间，你应该有至少1分钟的活动。"
			],
			"enabled": true
		},
		{
			"data": [
				"7分钟锻炼",
				"这种锻炼可以在短时间内完成全身锻炼。但与任何锻炼一样，要小心。有很多应用程序可以帮助你开始。"
			],
			"enabled": true
		},
		{
			"data": [
				"脉搏",
				"将你的脉搏率提高到每分钟120次，持续20分钟，每周四到五次，通过做你喜欢的任何活动。定期提高心率有助于改善心血管健康。"
			],
			"enabled": true
		},
		{
			"data": [
				"走楼梯",
				"研究表明，爬楼梯，被认为是剧烈强度的体育锻炼，每分钟燃烧的卡路里比慢跑还要多。"
			],
			"enabled": true
		},
		{
			"data": [
				"创作艺术",
				"艺术疗法在压力管理方面有很大的心理健康益处。何不写一首简短的诗、拍一张照片或画一些小东西？"
			],
			"enabled": true
		},
		{
			"data": [
				"整理",
				"干净的空间有助于你在工作时集中注意力，并常常与幸福等积极情绪相关联。"
			],
			"enabled": true
		},
		{
			"data": [
				"户外午餐",
				"大自然与积极情绪、减轻压力和焦虑相关。只要有可能，尽量在户外吃午餐，身边绿色环绕。"
			],
			"enabled": true
		},
		{
			"data": [
				"乘坐公共交通",
				"如果你经常乘坐公共交通工具，可以站立而不是坐着。如果可能的话，尽量用步行或骑自行车代替日常出行。"
			],
			"enabled": true
		},
		{
			"data": [
				"打哈欠",
				"打哈欠真的很有帮助，因为它会产生眼泪，帮助润湿和润滑眼睛。"
			],
			"enabled": true
		},
		{
			"data": [
				"注意转换",
				"将一根手指放在眼前，专注于它。缓慢地将手指远离，集中注意力远处，然后再回到手指。把手指拿回来，然后注意远处的某物。"
			],
			"enabled": true
		},
		{
			"data": [
				"手掌遮眼",
				"坐着时，将手肘支撑在桌子上并紧贴桌子边缘。让身体向前倾，并用手掌遮住眼睛。闭上眼睛，通过鼻子缓慢地吸气，并保持几秒钟。继续深呼吸。"
			],
			"enabled": true
		},
		{
			"data": [
				"握手",
				"握住一双揉成团的袜子或软橡胶球，握住5秒钟。重复几次整个过程。"
			],
			"enabled": true
		},
		{
			"data": [
				"缓慢呼吸",
				"新兴研究表明，通过控制缓慢的呼吸技巧，可能有助于优化与健康和长寿相关的生理参数。"
			],
			"enabled": true
		}
	],
	"microbreakIdeas": [
		{
			"data": "去倒杯水。",
			"enabled": true
		},
		{
			"data": "缓慢地看向左边，然后右边。",
			"enabled": true
		},
		{
			"data": "缓慢地看向上方，然后向下方。",
			"enabled": true
		},
		{
			"data": "闭上眼睛，深呼吸几次。",
			"enabled": true
		},
		{
			"data": "闭上眼睛，放松一下。",
			"enabled": true
		},
		{
			"data": "伸展一下腿。",
			"enabled": true
		},
		{
			"data": "伸展一下胳膊。",
			"enabled": true
		},
		{
			"data": "你的坐姿正确吗？",
			"enabled": true
		},
		{
			"data": "缓慢地将头转向一侧，保持10秒。",
			"enabled": true
		},
		{
			"data": "缓慢地将头倾斜到一侧，保持5-10秒。",
			"enabled": true
		},
		{
			"data": "站起来，伸展一下。",
			"enabled": true
		},
		{
			"data": "将视线集中在至少20米外的物体上。",
			"enabled": true
		},
		{
			"data": "花点时间想一下你欣赏的事物。",
			"enabled": true
		},
		{
			"data": "微笑一下，为自己活着而微笑。",
			"enabled": true
		},
		{
			"data": "一个真正符合人体工程学的工作站是你经常远离的那一个。",
			"enabled": true
		},
		{
			"data": "闭上眼睛，数数你的呼吸。",
			"enabled": true
		},
		{
			"data": "闭上眼睛，说出你听到的声音。",
			"enabled": true
		},
		{
			"data": "把指尖放在肩膀上。将肩膀向前旋转10秒，然后向后旋转。",
			"enabled": true
		},
		{
			"data": "举起右臂，将它伸向左边头顶，保持10秒。然后换另一侧。",
			"enabled": true
		},
		{
			"data": "用右手抓住左手的每个手指，然后握住。然后换另一侧。",
			"enabled": true
		},
		{
			"data": "站起来做一个弓箭步。保持10秒，然后换腿。",
			"enabled": true
		},
		{
			"data": "闭上眼睛，简单地观察当前的一切，不加评判。",
			"enabled": true
		},
		{
			"data": "每隔20分钟，集中注意力观察20英尺远的物体20秒。",
			"enabled": true
		},
		{
			"data": "如果你需要帮助，就请别人帮忙。",
			"enabled": true
		},
		{
			"data": "一次只做一件事。",
			"enabled": true
		},
		{
			"data": "你的注意力是否明智地使用？",
			"enabled": true
		},
		{
			"data": "改变你的坐姿。",
			"enabled": true
		},
		{
			"data": "让你的眼睛暴露在自然光下。",
			"enabled": true
		},
		{
			"data": "闭上眼睛，缓慢而温柔地抬起你的眼睛看天花板，然后回到地板。",
			"enabled": true
		},
		{
			"data": "闭上眼睛，缓慢地向左边移动你的眼睛，然后再缓慢地向右边移动。",
			"enabled": true
		},
		{
			"data": "摇摇你的手，得到一些缓解。",
			"enabled": true
		},
		{
			"data": "一次一个手指，将每个手指的指尖与拇指的指尖接触，使它们形成O形。",
			"enabled": true
		},
		{
			"data": "握拳，然后将手指向上，直到它们指向天花板，就像告诉别人停下来一样。",
			"enabled": true
		},
		{
			"data": "握拳，然后将手指展开并尽可能地伸展。",
			"enabled": true
		},
		{
			"data": "坐直，双臂垂直在身体两侧，缓慢地在一个方向上旋转颈部形成一个大圈。",
			"enabled": true
		},
		{
			"data": "站直，缓慢地用同一只手将头倾斜到肩膀，直到感到伸展。",
			"enabled": true
		},
		{
			"data": "站直，胳膊垂在身体两侧，缓慢地将肩胛骨挤压在一起并保持。",
			"enabled": true
		},
		{
			"data": "站直，双臂平伸在肩膀两侧。将双手稍微放在背后，保持一秒钟，然后回来。",
			"enabled": true
		}
	],
	"showBreaksAsRegularWindows": false,
	"appExclusions": [],
	"appExclusionsCheckInterval": 1000,
	"pauseForSuspendOrLock": true,
	"pauseBreaksToggleShortcut": "",
	"screen": "primary",
	"timeToBreakInTray": false,
	"currentTimeInBreaks": false,
	"showTrayIcon": true,
	"pauseBreaksShortcut": "",
	"resumeBreaksShortcut": "",
	"__internal__": {
		"migrations": {
			"version": "1.14.1"
		}
	}
}

**Comment by wangrui1573** [comment]
https://gist.githubusercontent.com/wangrui1573/ce549f9453b144157b8ad6bdae4ceee0/raw/config.json

1.14.1可用的中文翻译
