### ISSUE TITLE
Add Window Size Config

### ISSUE THREAD

**Issue by pro-logic** [hovancik/stretchly#627]
Wouild it be possible to add additional parameters into the config.json for width / height of break window?

This will allow users to set a much larger window that blocks a bigger portion of the screen. 

This will also help while there is an issue with "full screen" on "all monitors" on windows in upstream elektron.

**Comment by hovancik** [comment]
Hi, new version, 1.0 will hopefully fix issues on Windows. At least I didn't noticed any issues (thought I am not using it daily). 

I plan to change window size to percentage of screen. Problem with pixel is that different DEs interpret it differently on different screens. Which would be hard to set for multiple screens. 

I hope to have 1.0 over weekend.

**Comment by pro-logic** [comment]
I like the idea of windows size based on configurable %. 

Having tested 1.0 there is still some issues with "full screen" on Windows. I will create a new issue for that.
