### ISSUE TITLE
Feature request: Alarm

### ISSUE THREAD

**Issue by nitinjs** [hovancik/stretchly#629]
hi,

can you add Alarm feature into the app?

I mean at 3pm daily I need to switch to another project so I need a alarm notification covering the whole screen to notify me to switch to doing another task
also I need to take tea break at 4pm so there needs to be an alarm set which reminds me to take tea break daily
so on...

thanks,
nitin

**Comment by hovancik** [comment]
Hi @nitinjs ,

thanks for the feature request, but right now that's out of the scope for Stretchly. There are a lot of apps for creating alarms, so it should not be hard to find one that will suit your need ;]
