### ISSUE TITLE
Time remaining in icon

### ISSUE THREAD

**Issue by pmontepagano** [hovancik/stretchly#63]
It would be nice if there was an option to make the icon represent how much time there is left until next break. I was thinking in a circle that fills/empties, similar to MacOS progress icon. 
![240_degrees_filled1600](https://cloud.githubusercontent.com/assets/1820549/23510086/f0c1677c-ff36-11e6-9cd5-2e0db16b3677.png)

**Comment by hovancik** [comment]
Thanks, I like the idea. Will check if that's possible with electron

**Comment by hovancik** [comment]
So this is possible, but I will need help with creating images  (of tray icon) in different stage of the animation for this. This might take some time.

**Comment by sxmanton** [comment]
I don't think you need to create a ton of images. It seems feasible to me that you could use a similar approach as in this project: https://github.com/asheb/timer
It appears to create a hidden window where it can use a canvas to programatically draw the arcs, which is then retrieved via nativeImage.createFromDataURL

I think you could just set the current icon in the background of the canvas, then draw the arcs on top with some transparency to achieve the desired effect.

Personally though, while nice and pretty, I don't think the circular timer visualization would be as useful to me as just the minutes remaining being displayed in the tooltip when hovering over the icon.

**Comment by hovancik** [comment]
I think we can close this with https://github.com/hovancik/stretchly/pull/92 ?

**Comment by sxmanton** [comment]
I'd still like to give the animated icon a shot at some point, but I do think the tooltip is sufficient

**Comment by hovancik** [comment]
I am closing it. Thinking about it now, after some time, I think it would probably be obtrusive to always have animated icon in tray. I would not like it, personally. I like your solution the best.
