### ISSUE TITLE
AppImage build of 1.0.0 reports error loading FUSE

### ISSUE THREAD

**Issue by raphinesse** [hovancik/stretchly#634]
### Prerequisites

- [x] I'm using latest version: v1.0.0
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

AppImage build reports error loading FUSE

Operating system: Ubuntu 19.10

### Steps to Reproduce

1. Download `Stretchly-1.0.0-i386.AppImage`
2. Open Terminal in containing folder
3. Make AppImage executable
4. Run AppImage `./Stretchly-1.0.0-i386.AppImage`

**Expected behavior:** Stretchly UI shows up

**Actual behavior:** Error in console:
```
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
```

**Reproduces how often:** Always

### Additional Information

- `stretchly-0.21.1-x86_64.AppImage` works for me on the same system
- AppImages should be self-contained, so I did not try to install any system dependencies.

**Comment by hovancik** [comment]
Hi,

can you try downloading Stretchly-1.0.0.AppImage? From your comment about `stretchly-0.21.1-x86_64.AppImage` I think you downloaded for another architecture.

**Comment by raphinesse** [comment]
You're right. I completely missed the architecture suffix. It works with the non-suffixed version. My bad, sorry for the inconvenience and thanks for the quick response time! :bowing_man:
