### ISSUE TITLE
No preferences or settings on Windows 10

### ISSUE THREAD

**Issue by fdahlberg** [hovancik/stretchly#635]
I can't seem to access any preferences for stretchy. 
When i right click the icon in toolbar all I see is this:
![image](https://user-images.githubusercontent.com/9571179/88051591-29adb800-cb59-11ea-8662-ae0954b25086.png)

Kind Regards
Fredrik Dahlberg

**Comment by hovancik** [comment]
Hi, 

you should see Preferences under Reset Breaks, which is not visible in your screenshot. 

Here's how I see it: 

<img width="156" alt="Screenshot 2020-07-21 at 19 15 08" src="https://user-images.githubusercontent.com/4745859/88086237-52e53d00-cb87-11ea-9368-a388875f27f2.png">

**Comment by fdahlberg** [comment]
The problem is that sometimes half the popup is hidden. Seems to depend on where the icon ends up in the system tray. When i tried it a bit later the stretchly icon was in a different location and all of a sudden it worked. 
Not sure if you can control the location of that pop up menu and make sure it's never outside the screen.

**Comment by hovancik** [comment]
Yeah, that's something I do not control. Not sure if it's OS-level thingy or it's electron...
