### ISSUE TITLE
Windows 10 installation issue

### ISSUE THREAD

**Issue by illright** [hovancik/stretchly#636]
### Prerequisites

- [x] I'm using latest version: v 
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

I am facing an issue similar to #534 on Windows. I've previously had v0.20.1 installed, and carelessly deleted the folder without running the uninstaller first. Now I have the entry of stretchly v0.20.1 in my Apps list, but the uninstall button doesn't work because the uninstaller isn't there.

Any other versions fail to install with some unknown error. How can I resolve this issue?

Also, as a further suggestion, maybe have the installers a little more verbose in what the problem is? :p
I tried running the installer through the command line, tried `winget`, but it was just silently aborting without any helpful info as to what's wrong.

Operating system: Windows 10 2004

**Comment by hovancik** [comment]
Hi, sorry to hear that you have issues. 

Have you tried installing version  v0.20.1? 

Re installer: I am using `electron-builder` to build installers, which is in turn using something else, I think NSIS. They might be able to help.

**Comment by hovancik** [comment]
This is the config I set for `electron-builder`
```
    "win": {
      "target": [
        "nsis",
        "nsis-web",
        "7z",
        "zip"
      ]
    },
    "nsis": {
      "oneClick": false,
      "allowToChangeInstallationDirectory": true
    },
    "nsisWeb": {
      "oneClick": false,
      "allowToChangeInstallationDirectory": true
    }
```

**Comment by illright** [comment]
> Have you tried installing version v0.20.1?

Just tried, also aborting

**Comment by hovancik** [comment]
So there is no error message? Which folder/files did you delete?

**Comment by illright** [comment]
No error message. I wish I remembered which folder did I delete, but I'm pretty sure it was the main folder of the application, where the exe and the installer reside. Then I also deleted the program files as was suggested in the issue I've linked above. That's about it

**Comment by hovancik** [comment]
Sorry but no idea how to help. Maybe somebody from NSIS team might know what to do. 

Otherwise I would try some cleaning apps, maybe they could make windows OS think that old Stretchly version is not installed.

**Comment by illright** [comment]
Is there a way to obtain the uninstall exe?

**Comment by hovancik** [comment]
Well, actually, not bad idea. You could try installing the version in VirtualBox and then copy the deleted files from that machine to your machine. Virtualbox has ability to do that. Microsoft have free virtualbox images (or other VM of your choice) to use here: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by illright** [comment]
Yep, copying over the `\Users\<user>\AppData\Local\Programs\stretchly` and running the uninstaller allowed me to cleanly uninstall the previous version of Stretchly and install the new one. Thanks!

P.S. I've read up on the recent issue that links to this one, scary stuff. Scary because I myself remember installing a program from Wondershare, but maybe I took care of it before it could do harm because I don't have such a process and the link wasn't hijacked
