### ISSUE TITLE
Full-screen break shows under current window 2nd monitor 

### ISSUE THREAD

**Issue by pro-logic** [hovancik/stretchly#639]
I'm using version 1.0.0 
Windows 10 x64. Dual monitor. 
In Stretchly I have "Show breaks in Full Screen" set and "Show on all monitors" 

On the primary screen, stetchly correctly draws on top of other windows. 
On the secondary screen, stretchly draws underneath other windows. See attached screenshot.  
![image](https://user-images.githubusercontent.com/552851/88127891-20375500-cc18-11ea-8a0a-3f61222950d8.png)

**Comment by XuShenLZ** [comment]
Agree. Just want to post this. Experience the same thing here. 
Win 10 2004, Dual Monitor in Extend Mode
Stretchly 1.0

**Comment by hovancik** [comment]
Thanks for the report! How is it behaving when you show breaks not fullscreen? Is it also behind the other apps? 

My workaround for 1.0 was to basically don't use fullscreen functionality (as it was broken) but to basically show normal window but make it as big as the screen. So I wonder if the "Show breaks in Window" works the same.

**Comment by XuShenLZ** [comment]
The window mode works well. But how to change the size of it? I tried dragging the edges or corners and it doesn't work. (still prefer fullscreen btw)

**Comment by pro-logic** [comment]
It works fine in "window" mode, where the window draws over the top of other windows.  Maybe a work around would be to set the size of the "window" mode to like 95% :D

**Comment by hovancik** [comment]
@pro-logic in next release, I plan to make break "window" to be 70-80% of the screen-size

@XuShenLZ size of the break window can't be changed. What I meant was workaround in the code, for the fullscreen, is that I make regular window the size of the screen, thus pretending that it's fullscreen. That's why I am surprised why it does not work, as regular window works. Will have to check the code to see if there's another difference.

**Comment by XuShenLZ** [comment]
Thanks! I am actually confused by the bug's pattern. During my use these days (fullscreen, extend on 2nd monitor), sometimes it will not be hidden (have saw it on top of Matlab when that window is not the focus), but sometimes it will be covered (when using Edge browser, Scretchly will normally be covered no matter Edge is my current focus or not). Haven't found any clear clue, but the message is that the behavior is "unstable"...

**Comment by hovancik** [comment]
Yeah, with electron the message is always "it's unstable" :smile:

**Comment by hovancik** [comment]
Maybe this will be interesting to test: https://github.com/electron/electron/issues/20933#issuecomment-685136742

**Comment by Yekmaz** [comment]
Hi. thanks for your great app. I recently installed V1.1.0 on MS win10. there is no problem in "Window" mode . but when choose "Fullscreen" , if a window is open , breaks is not shown.I tried to minimize all windows and then every thing works well.
As you said, I changed window size and see that break is running behind  the all windows in first monitor.
Interestingly, this problem does not exist in the second monitor and breaks display at top of all open windows

**Comment by hovancik** [comment]
Hey guys, I can't build on Windows for some reason, but I created branch with simple fix mentioned in Electron https://github.com/electron/electron/issues/20933#issuecomment-685136742. If anyone is running Stretchly from source on Windows, could you try branch `fix/win-fullscreen`?
