### ISSUE TITLE
Preferences window showing broken images

### ISSUE THREAD

**Issue by cameronsstone** [hovancik/stretchly#640]
# Prerequisite

- [x] I'm using latest version: v1.0.0
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

Images are broken in Preferences window
1. Sound buttons on theme tab (play?)
1. About tab
1. Love Stretchly tab

Operating system: Mac 10.15.6

### Steps to Reproduce

1. Open prefs
1. Click on Theme (etc)

### Additional Information

See attached:
![Screen Shot 2020-07-22 at 10 59 06 AM](https://user-images.githubusercontent.com/218188/88219164-0c8aef00-cc16-11ea-9962-67cf88b9f643.png)

**Comment by hovancik** [comment]
Oh man, I guess there is an older build on Releases page ;/ 

Can you try changing to light mode to see if images are fine?

**Comment by hovancik** [comment]
What did you use to install this version? I a trying .dmg file and I can't reproduce

**Comment by cameronsstone** [comment]
I got images in light mode. I upgraded using brew cask.

**Comment by cameronsstone** [comment]
Looking in /stretchly.app/Contents/Info.plist for build identifiers that might help:
1. Bundle version: 1.0.0.1931
1. DTXcode: 1110
1. DTXcodeBuild: 11A1027

`brew cask upgrade stretchly` returns `No casks to upgrade`

**Comment by cameronsstone** [comment]
Oh, just found debug display:
```

            breakPlanner: {reference: startMicrobreak,
            timeleft: 16 seconds remaining,
            breakNumber: 1,
            postponesNumber: 1,
            Do Not Disturb: false}
            
            settingsFile: /Users/csstone/Library/Application Support/Stretchly/config.json
            Node.js: 12.14.1
            Chromium: 83.0.4103.122,
            Electron: 9.1.0
```

**Comment by hovancik** [comment]
I'll check what bundle version is on my mac. I had issue with missing images but I fixed it before releasing 1.0. 

Can you try `Cmd+Shift+I` in Prefs window? It will open regular chrome inspect element. What is the missing image path?

**Comment by hovancik** [comment]
I seems to have 1.0.0.1933, not 1.0.0.1931. I guess you need to download the `dmg` file. 

I am updating cask so that DMG is used (https://github.com/Homebrew/homebrew-cask/pull/86560), there seems to be problem with zipped apps anyway (https://github.com/electron-userland/electron-builder/issues/4299)

**Comment by hovancik** [comment]
My update in `brew cask` was merge so you can reinstall Stretchly to try. I am not seeing any issue

**Comment by cameronsstone** [comment]
`brew cask update` is not showing it. :-(

Trying remove/install...

Yeah, now I have 1.0.0.1933 and the images are there in both light and dark mode. Thanks!

BTW - when you uninstall with stretchly open it doesn't close it, and leaves it in a bad state. Want me to create a separate feature request for that? I don't think it's a high priority, but worth fixing if it's easy.

**Comment by hovancik** [comment]
Yeah, it's the same version so it wouldn't show it as update. 

Regarding reinstall: not sure if that's possible for me to do for macOS (as there is basically no installer), I guess that would be task to update `brew cask` package. There seems to be a way to quit app on uninstall: https://github.com/Homebrew/homebrew-cask/blob/57abdba4eb1a3549b963105b7030906bdabd8ff3/Casks/xampp.rb

I think Windows installer closes the app.
