### ISSUE TITLE
Stretchly doesn't respect Focus assist setting on Windows 10 (aka how to enable do-not-disturb on Windows)

### ISSUE THREAD

**Issue by Merlin2001** [hovancik/stretchly#645]
### Prerequisites

- [x] I'm using latest version: v1.0.0
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

Currently, no matter what option is set for _Focus assist_, Stretchly will still show its reminders.  
So it seems there is no way to temporarily disable the overlays during a presentation, video call, or similar.

Maybe this is only a documentation issue, but I could not find any instructions on how to enable do-not-disturb on Windows 10 so Stretchly recognizes it.

Operating system: Windows 10 v1909 build 18363.959

### Steps to Reproduce

1. Set the shortest possible schedule for mini breaks
2. Enable Focus assist:  
![image](https://user-images.githubusercontent.com/13134791/88648900-b7445700-d0c7-11ea-84d6-c2a27e84b3db.png)
3. Wait for scheduled break

**Expected behavior:**
Stretchly doesn't interrupt when one of the focus modes is selected.

**Actual behavior:**
Stretchly doesn't care 😄 

**Reproduces how often:**
100%

**Comment by hovancik** [comment]
Seems like that's not supported by library I use :( https://github.com/felixrieseberg/windows-quiet-hours/issues/1

**Comment by Aziks0** [comment]
There is this library: https://github.com/bitdisaster/windows-focus-assist that can be used to get the current mode set by Focus assist.

**Comment by hovancik** [comment]
Nice :)

**Comment by Aziks0** [comment]
I've tried the library and it works as expected on Windows 10 v1903 build 18362.592.
I can implement the feature if you want.

**Comment by Merlin2001** [comment]
Thank you all for looking into the issue! 🙏

Once implemented I'll happily provide feedback if the API still works on the most recent Windows builds!  
(I'm now on Windows 10 v2004 build 19041.388)

**Comment by Aziks0** [comment]
I'm waiting for @hovancik approval before making a PR

**Comment by hovancik** [comment]
@Aziks0 feel free to go ahead :) 

I started new job so I am basically tired to check emails every day but I hope to find time over weekend :)
