### ISSUE TITLE
stretchly github auth asking for way too much

### ISSUE THREAD

**Issue by jsjoeio** [hovancik/stretchly#647]
### Prerequisites

- [x] I'm using latest version: v 1.0.0
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

Signing in with GitHub under preferences > Love Stretchly > "I am a contributor" > Sign-in with GitHub leads to an auth request with way too many privileges. 

I am not sure I understand why you need full access to all my personal data + organization access. If you're just verifying that I have a PR merged into stretchly, which is a public repository, then you should only be asking for that.

<img width="584" alt="too-much-access" src="https://user-images.githubusercontent.com/3806031/88814495-08f3ec80-d16f-11ea-9fb0-151235599279.png">

Operating system: macOS Mojave v10.14.6 (18G5033)

### Steps to Reproduce

1. Open Preferences
2. Navigate to Love Stretchly
3. Click "I am a contributor"
4. Click GitHub
5. Sign in
6. Observe permissions and access being requested

**Expected behavior:** 

Stretchly access for some profile data (email, handle, etc) and public repo data (merged PRs)

**Actual behavior:** Stretchly asks for way too much

**Reproduces how often:** 100%

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by hovancik** [comment]
Hi @jsjoeio ,

this is related code: https://github.com/hovancik/stretchly_server/blob/master/config/initializers/omniauth.rb 

Right now, I am using `user` scope and I am using ID in app. 

From here it looks like I could change to `read:user`, if that returns ID:  

https://docs.github.com/cn/developers/apps/scopes-for-oauth-apps

**Comment by jsjoeio** [comment]
Thanks for fixing that so quickly @hovancik ! Really appreciate it
