### ISSUE TITLE
Negative wait time

### ISSUE THREAD

**Issue by ClassicDarkChocolate** [hovancik/stretchly#648]
### Prerequisites

- [x] I'm using latest version: v1.0.0
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

Stretchly might not get into break mode & the wait time is negative.

Operating system: Windows 10 Version 2004

### Steps to Reproduce

1. (Probably) Idling while Stretchly is about to going to break.
2. Stretchly might not get into break mode & the wait time is negative.

**Expected behavior:** Works normally.

**Actual behavior:** Not get into break mode and the wait time is negative. Then the app no longer works. You will need to manually reset breaks.

**Reproduces how often:** Sometimes

### Additional Information

None.

**Comment by hovancik** [comment]
Hi @ClassicDarkChocolate , can you please copy the debug info? By pressing `Ctrl/Cmd + D` in the About section of Preferences.

**Comment by ClassicDarkChocolate** [comment]
```

            breakPlanner: {reference: startMicrobreak,
            timeleft: -372 seconds remaining,
            breakNumber: 2,
            postponesNumber: 0,
            Do Not Disturb: false}
            
            settingsFile: C:\Users\ClassicDarkChocolate\AppData\Roaming\Stretchly\config.json
            Node.js: 12.14.1
            Chromium: 83.0.4103.122,
            Electron: 9.1.0
          
```

I think pausing breaks might be one of the reason. I'm not sure.

**Comment by hovancik** [comment]
Thanks! 

Do you have default settings or you made some changes? 

> (Probably) Idling while Stretchly is about to going to break. 

Do you mean your computer is idle? (you are away from it?)

**Comment by ClassicDarkChocolate** [comment]
I only changed "show breaks in fullscreen", "enable long breaks for 2 minutes" and "sounds: tic toc".

Close the issue because I can no longer reproduce the bug since re-installation.
