### ISSUE TITLE
Stretchly not opening preferences

### ISSUE THREAD

**Issue by chai3524** [hovancik/stretchly#651]
### Prerequisites

- [x] I'm using latest version: v 1.0.0.
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

Hi there, 

I've had stretchly installed for over a year and it never had any issues for me. A few months back I disabled it because I needed to use my laptop for a display, and now I tried opening it to re-enable it in the settings but when I right click the tray icon it doesn't do anything. When I run as administrator nothing happens. Since it was an old version, 0.21.0, I uninstalled it, since I figured it might have something to do with that. It uninstalled, I downloaded version 1.0.0. and installed it. It's installed and listed among my apps, but again when I open the program nothing happens. When I right click the tray icon nothing happens. I can't access the preferences at all. When I hover my mouse over the tray icon it does say "Next mini break in about x minutes" and the pop up does show with the break reminder, but I can't change the settings. 

What should I do? I'm unfortunately not very experienced with programming so I apologise if I'm not using the correct technical terms.

Thank you so much for helping me out!

Operating system: Windows 10, 64-bit

### Steps to Reproduce

1. Open start menu and click on Stretchly
Nothing happens
2. Open tray and hover mouse over stretchly icon
"Next break time in about x minutes" shows (and the break reminder does pop up)
3. Click on stretchly tray icon
Nothing happens
4. Right click on stretchly tray icon
Nothing happens

**Expected behavior:** 
Either by clicking or right-clicking on the tray icon, the menu opens to access preferences.

**Actual behavior:** 
Literally nothing happens

**Reproduces how often:** 
Every time

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by hovancik** [comment]
Hi @chai3524 , sorry to hear about your issues. I am not sure what could be wrong, clicking on icon in tray should bring the menu with Preferences item in it. 

The fact that you can see popups means that apps run. 

Do you have tray in bottom left part of screen or somewhere else? There was an issue when user did not see the whole menu on specific occasions  https://github.com/hovancik/stretchly/issues/635

**Comment by chai3524** [comment]
Hi, my apologies for the late reply, I forgot to check github.

I have uninstalled the software again and installed it again, and the preferences are now opening as normal. I'm not sure what went wrong with the first install, but at least it is working now.

**Comment by hovancik** [comment]
Awesome, glad to hear it works ;]
