### ISSUE TITLE
A label of a checkbox for "idle time" option seems to be inaccurate

### ISSUE THREAD

**Issue by Kadilov** [hovancik/stretchly#654]
### Prerequisites

- [x] I'm using latest version: v 1.0.0
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

As far as I understand, v. 1.0.0 changed a wording for one of the options, while related functionality did not changed fundamentally.
In 0.21.1 it was: "Monitor system idle time for natural breaks."
In 1.0.0: "Monitor system idle time (countdown is paused if system is idle)."

A default behaviour from docs:
> "Stretchly is monitoring your idle time, so when you are idle for 5 minutes, breaks will be reset until you return."

Also this period can be tweaked if you are a contributor:
> "In the preferences file, set naturalBreaksInactivityResetTime to your preferred value (in milliseconds greater than than 20000ms). This is an idle time length, after which Stretchly timers will be cleared and will stay at 0 until the user resumes activity."

Previously it defaulted to the (shortest?) break period, but that are nuances.
If these quotes fully describe how the option works, then the checkbox description should not use words "countdown is paused if system is idle", because it can be understood as "a timer is frozen", and it is not the case. For example, the option can be described as: "timers are reset if system was idle".

**Comment by hovancik** [comment]
Yeah, in Stretchly's language paused = reset (pretty much). 

How about "Monitor system idle time (breaks are paused if system is idle)." 

And use term "pausing breaks" elsewhere. We don't use term "timers" a lot and now it seems to me that it confusing things as it's rather technical/code term.

**Comment by Kadilov** [comment]
> How about "Monitor system idle time (breaks are paused if system is idle)."
I think it is better. As a variant - theoretically it can be just "Pause breaks if system is idle", without "Monitor system idle time".
