### ISSUE TITLE
Add an option to change the opacity of the breaks windows

### ISSUE THREAD

**Issue by Aziks0** [hovancik/stretchly#657]
### Prerequisites

- [x] I'm using latest version
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues) (and [Closed issues](https://github.com/hovancik/stretchly/issues?q=is%3Aissue+is%3Aclosed))

### Description

Sometimes a break start while I'm writing, and since the window is not transparent, I cannot finish writing down my sentence/line of code before I take my break because I cannot see what I'm writing. In this case, I don't really want to postpone my break because I only need a few seconds to finish writing.

So it could be really nice to have an option to add transparency, with the possibility to change the opacity percentage (maybe a Contributor Preferences only ?).

I already tried changing the opacity and it looks like this with an opacity at 0.5 (with Green Clouds theme):
![Opacity with Windows background](https://user-images.githubusercontent.com/36425380/90304986-bbd97f80-debd-11ea-8849-eaa7b7c0546a.png)

However, depending on the background, it may be hard to read due to the white font color:
![Opacity with black and white background](https://user-images.githubusercontent.com/36425380/90305076-df50fa00-debe-11ea-9611-f3274414763e.png)

**Comment by hovancik** [comment]
Looks nice! Is it supported in all OSes?

**Comment by Kadilov** [comment]
Looks like something that will tempt me to continue working. What about gradually changing opacity, for example: start with 40%, than increase linearly to 100% in, say, 30 seconds.

**Comment by Aziks0** [comment]
> Looks nice! Is it supported in all OSes?

@hovancik I tried on Windows 10 and on Linux (Ubuntu 16.04) and it works on both OS. I guess it should be supported by all OS, at least there is nothing in the [documentation](https://www.electronjs.org/docs/api/browser-window#new-browserwindowoptions) (see `transparent` and `BackgroundColor` ) that says otherwise.

> Looks like something that will tempt me to continue working. What about gradually changing opacity, for example: start with 40%, than increase linearly to 100% in, say, 30 seconds.

@Kadilov That's a nice idea, but I don't think we can do something like that with Electron. I will do some research tho.

**Comment by Aziks0** [comment]
> > Looks nice! Is it supported in all OSes?
> 
> @hovancik I tried on Windows 10 and on Linux (Ubuntu 16.04) and it works on both OS. I guess it should be supported by all OS, at least there is nothing in the [documentation](https://www.electronjs.org/docs/api/browser-window#new-browserwindowoptions) (see `transparent` and `BackgroundColor` ) that says otherwise.

I forgot something: 
- Using `transparent: true` + `opacity: number` is the easiest solution, but it doesn't work on Linux.
- Using `transparent: true` + `backgroundColor: #AARRGGBB` works on every OS, but it's a more tricky solution because we need to set the alpha of backgroundColor

Altough I already have a function that can calculate the right backgroundColor:
```javascript
function calculateBackgroundColor () {
  const opacity = settings.get('opacityPercent') / 100
  const themeColor = settings.get('mainColor').substr(1) // remove #
  return '#' + Math.round(opacity * 255).toString(16) + themeColor
}
```

**Comment by hovancik** [comment]
So I think there are 2 possible stories here: 
- break window opacity is going down as break is progressing; user is able to turn it on/off
- break window has opacity; user is able to set numeric value that represents it

My gut feeling is that it's not good idea to combine those 2. Everybody likes something else, so it would be
- either too many options to set (resulting in noone using it) 
- less options, but then people would be asking me to change how it works all the time

Maybe I am wrong, but I would go with simple opacity for now :) 

There is a big dream of mine, that in the future people will be able to write/script their own themes (there are few issues opened around that), so I would then outsource those things (like changing opacity with time) there

**Comment by Aziks0** [comment]
Yeah I agree, there would be too many options, so we can simply go with letting the user choose the opacity of the window.
And in case you would want to implement the fading in in the futur, there shouldn't be any need to refactor anything.

As for the properties for changing the opacity, easy solution with the `opacity` property (but doesn't work on Linux) or 'trickier' solution with the `backgroundColor` property (working on every OS) ?

**Comment by hovancik** [comment]
Let's go with version that works everywhere :) 

Could you also use `settings.get('opacity')` instead of `settings.get('opacityPercent')` so we could have standard `opacity` from `0` to `1`?

**Comment by Aziks0** [comment]
> Could you also use `settings.get('opacity')` instead of `settings.get('opacityPercent')` so we could have standard `opacity` from `0` to `1`?

Yes of course, I was thinking that percentage could have been easier for the users to understand, but at the end of the day, it's probably the same.
