### ISSUE TITLE
Wind chime sound distorted on Linux

### ISSUE THREAD

**Issue by nicolae-stroncea** [hovancik/stretchly#669]
### Prerequisites

- [x] I'm using latest version: v 
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

The wind chime sound is extremely distorted on linux compared to Windows version

### Operating system: 

Fedora 32, Gnome 3.36, Xorg

### Steps to Reproduce

1. Play the wind chime in the Stretchly Preferences. It sounds like electric static. Crystal glass and Tic Toc sounds both sound fine in comparison
2. Done

**Expected behavior:** [What you expect to happen]

I use the Wind Chime sound when I'm booted in Windows. So I was quite surprised when I was hearing a very weird distorted noise when my break was done on Linux. Turns out that's the Wind Chime sound.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% of the time

### Additional Information

This is the package I used: *Stretchly-1.0.0.x86_64.rpm*, from the github releases page.

**Comment by hovancik** [comment]
Hi @nicolae-stroncea , is it also corrupted when you preview it in preferences? 

Have you tried downloading the installer again and installing again? Seems like it's corrupted.

**Comment by nicolae-stroncea** [comment]
It was corrupted on previewing the preferences too.

I re-downloaded and reinstalled, and that fixed the issue. Strange that it got corrupted

**Comment by hovancik** [comment]
Awesome, glad that worked :)
