### ISSUE TITLE
Start strechly on login (Ubuntu)

### ISSUE THREAD

**Issue by gabriellovate** [hovancik/stretchly#670]
In Windows there is a nice checkbox for configuring strechly to start on login. How can I replicate this behaviour on Ubuntu?

**Comment by hovancik** [comment]
Hi @gabriellovate , on Linux, different OSes use different ways how to deal with autostart so there is no common one. Therefore there is no API for it in electron.

 I have Debian with KDE and I need to do it manually, by going to Settings / Startup / Autostart. 

According to [this](https://askubuntu.com/questions/48321/how-do-i-start-applications-automatically-on-login) Ubuntu has "Startup Applications" app where you will be able to add Stretchly

**Comment by nicolae-stroncea** [comment]
If that doesn't work, you could also try the  Tweaks app, where you can choose "Startup Applications"

**Comment by hovancik** [comment]
I'll close this, then :)
