### ISSUE TITLE
Authentication problem

### ISSUE THREAD

**Issue by Neiromaster** [hovancik/stretchly#674]
### Prerequisites

- [x] I'm using latest version: v 1.0.0
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

You can't login with Patreon with a Google account.

Operating system: MacOS 10.15.6

### Steps to Reproduce

1. Clicked on the Love Stretchy button
2. Clicked on Patreon
3. Agreed to the terms and clicked on the authorization button
4. Clicked Continue with Google and entered my login
5. Receive a message about an unreliable browser

**Expected behavior:** Authorized and got additional settings

**Actual behavior:** Can't enter password to login

**Reproduces how often:** each time

### Additional Information

![image](https://user-images.githubusercontent.com/11369340/92252671-3a32ab80-eed7-11ea-8b65-8b0ce9ac13cc.png)

**Comment by hovancik** [comment]
Hi and thanks for the report! 

Not sure why google is not liking it, version 1.0 uses Chromium 83. Can you, as a workaround, create a password for your Patreon account, if possible? 

Skipping Google altogether...

**Comment by Neiromaster** [comment]
I have done so now. Authorization in Patreon was a success.
I will continue to support you at Patreon.

**Comment by hovancik** [comment]
Thanks @Neiromaster , I googled around and many electron apps have this issue. Usually they change how they do Google auth, but that's not something that I do here, it's Patreon. I could set some supported user-agent string, but obviously that's against the Google ToS. 

I guess setting password and using it, is good workaround for now :)
