### ISSUE TITLE
A JavaScript error occurred in the main process 

### ISSUE THREAD

**Issue by birkany** [hovancik/stretchly#68]
I was just dragging two files on to my email (gmail) for attaching them, and a micro break screen popped out :) and I saw that the file contents are put into green stretchly screen :) and after micro-break screen disappeared, an error message popped out. I hope I had given enough information :) 

P.S. files were text files of  10-50 lines matlab code 

![image](https://cloud.githubusercontent.com/assets/22783750/24106767/43ac1bb4-0dcc-11e7-8a9b-3164792cd8f7.png)

**Comment by hovancik** [comment]
Thanks, I will try to reproduce. What platform are you on?

**Comment by birkany** [comment]
Mac Os X 10.9.5

**Comment by hovancik** [comment]
Thanks. I've found out that drag'n'drop is enabled by default. I will be blocking it from now on, that should prevent the issue.
