### ISSUE TITLE
FR: Different sound for breaks and other for microbreaks

### ISSUE THREAD

**Issue by mwoz123** [hovancik/stretchly#687]
### Prerequisites

- [X] I'm using latest version: v 
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

Until #524 is fix in electron. I propose as kind of workaround to option to have different sound at break and different sound at microbreak. 
There could be a checkbox:
"different sound at break" which will enable option to choose different sound for "break". microbreak will have current selected sound.

**Comment by hovancik** [comment]
Hi @mwoz123 , I am not sure what you mean, how it is supposed to help?  

There is advanced option to have also sound at the beginning of the breaks https://github.com/hovancik/stretchly#play-sound-at-the-start-of-the-break-  

In general, I would prefer not to make changes to break/mirobreak sounds at this time. In future I would like to have some sort of "plugin" system for breaks, where people can do own break behavior.

**Comment by Chealer** [comment]
Thank you for this request. I suggest avoiding the "FR" acronym. It is highly ambiguous and I have never seen it in use before.

Workrave is one Stretchly equivalent which allows such a distinction. In fact, it is built-in, and I would recommend to build it in Stretchly too. As indicated in ticket #910, the signal for longer breaks needs to be louder. The current sound for microbreak ends is way too prominent/distracting.

**Comment by ghost** [comment]
Is this possible currently? I am also interested in this one. 

Also, it will be interesting to have different sounds at the start of breaks (mini or long) and at the end of the breaks (mini or long). In that way you do not need to be in front of the screen. Something like in gnome-pomodoro.

**Comment by hovancik** [comment]
in general, if issue is still open, it means it has not been implemented, yet. 

Related: #1084

**Comment by Chealer** [comment]
Thank you very much @hovancik 

Stretchly 1.14 [introduced a `miniBreakAudio` preference](https://github.com/hovancik/stretchly/pull/1295) which is documented in [the README's _Different sound for Mini and Long breaks_ section](https://github.com/hovancik/stretchly/blob/trunk/README.md#play-sound-at-the-start-of-the-break-). Unfortunately:

1. The sounds remain identical by default, as reported in ticket #1564.
2. The GUI does not allow changing just one of them.

**Comment by hovancik** [comment]
Hi, I don't plan to take this out of advanced preferences. I prefer to keep "Preferences" as simple as possible with basic settings and have rest editable via file.
