### ISSUE TITLE
Overlay not completely removed after break.

### ISSUE THREAD

**Issue by davidwessman** [hovancik/stretchly#690]
### Prerequisites

- [x] I'm using latest version: v 1.1.0
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

Overlay not completely removed after break.

Operating system: Mac OS 10.15.6

### Steps to Reproduce

1. Turn off Stretchly completely
1. Start Stretchly, see it in the top bar
1. cmd + tab -> Shows no Stretchly icon
1. Start a mini break
1. cmd + tab -> There is a Stretchly icon.
1. After break there is a transparent overlay and ~a lot of keys~ keyboard is unresponsive.

**Expected behavior:** After break there should be no Stretchly-overlay or Stretchly-icon available if you use cmd + tab to switch between applications.

**Actual behavior:** After a break Stretchly-overlay is not completely closed.

**Reproduces how often:** [What percentage of the time does it reproduce?] 100% so far.

### Additional Information

Did not experience this in v 1.0.0.

**Comment by davidwessman** [comment]
Thank you for a great application and please tell me if I can help with more information.

**Comment by hovancik** [comment]
Hi @davidwessman , what do you mean by overlay after break? 

I am seeing Stretchly in `cmd+tab` after breaks finishes, but not any overlay or keys not working. 

Maybe send screenshot? Keys you mean keyboard?

**Comment by davidwessman** [comment]
**Update**

After the break, the Stretchly overlay is not always in focus - but if I switch to the window using cmd + tab the keyboard becomes completely unresponsive. If I click anywhere it focuses on the window in the background instead and I can use the keyboard again.

First image: Just selected Stretchly with cmd + tab.
Second image: Stretchly is selected and the top bar is fading out (as when an application goes full screen). Here the keyboard is unresponsive until I click with the pointer.

(I had to do a screen recording to get the cmd + tab interaction, but could not upload the file here)


<img width="1120" alt="before-switch" src="https://user-images.githubusercontent.com/6763624/93167632-53322c80-f721-11ea-8f3a-690db0ecadf5.png">
<img width="1120" alt="after-switch" src="https://user-images.githubusercontent.com/6763624/93167652-5d542b00-f721-11ea-8e80-05909349a3c5.png">

**Comment by HugooB** [comment]
Same issue here on Catalina 10.15.6!

**Comment by sshishov** [comment]
Having exactly the same issue, making some pain, as a workaround, after break I am quitting the app and launching it back.

**Comment by hovancik** [comment]
Did you guys change any settings? Having troubles reproducing

**Comment by hovancik** [comment]
Seems that this is the bug in electron? https://github.com/electron/electron/issues/25427

**Comment by sshishov** [comment]
@hovancik it seems that the problem with fullscreen app. I have a setting to show breaks in fullscreen app. And after showing the break it happens. Thanks.

**Comment by hgkuper** [comment]
> Same issue here on Catalina 10.15.6!

Also experiencing the same issue in macOS 10.15.6 (on MacBook Pro). There is no escape for me once I have entered the trap via CMD+TAB. Cannot (force) quit, keyboard and trackpad are unresponsive and I have to restart to regain control.  I have only experienced this behaviour since Stretchly 1.1.0.

Aside from that, this is a great app which has really improved my daily worklife. Thank you very much!

**Comment by jjstickel** [comment]
I am experiencing some of these symptoms as well on Mac 10.14.6. Mainly, I notice the Stretchly icon in the dock after a break. I have to quite and restart Stretchly to make it go away. I am *not* using Stretchly in fullscreen mode. Maybe that is why my keyboard remains responsive.

**Comment by Aziks0** [comment]
Are you all using Stretchly 1.1.0 ? Do you have the transparency enabled or disabled in Theme ?

**Comment by davidwessman** [comment]
These are my settings (I have tried using windowed mode, it still behaves weird but less intrusive).

<img width="599" alt="Screenshot 2020-09-17 at 06 40 24" src="https://user-images.githubusercontent.com/6763624/93421061-ac7c9600-f8b0-11ea-9119-3f408432659b.png">
<img width="597" alt="Screenshot 2020-09-17 at 06 40 37" src="https://user-images.githubusercontent.com/6763624/93421079-b3a3a400-f8b0-11ea-9cc1-755f64469242.png">
<img width="599" alt="Screenshot 2020-09-17 at 06 40 48" src="https://user-images.githubusercontent.com/6763624/93421088-ba321b80-f8b0-11ea-830d-f1172f29b764.png">
<img width="600" alt="Screenshot 2020-09-17 at 06 41 11" src="https://user-images.githubusercontent.com/6763624/93421128-c918ce00-f8b0-11ea-8e75-316c68992869.png">

**Comment by HugooB** [comment]
Installed through `brew`, maybe that helps recreating the error? And yes, I'm in full screen mode

**Comment by Aziks0** [comment]
@hovancik The bug could be related to the background color being in ARGB even when transparency is disabled, which means that the opacity of the background is set regardless of the value of transparency. It's the only thing that changed in the options of BrowserWindow for the breaks windows in v1.1.0.

**Comment by hovancik** [comment]
I'll try to reproduce tomorrow, then I can test the transparency thingy. Could be also the electron issue I linked to.

**Comment by cameronsstone** [comment]
@hovancik commented 4 days ago:
> I am seeing Stretchly in `cmd+tab` after breaks finishes

Was that an intentional change or part of this issue? If it was intentional, can you make it optional, as I'd prefer not to have Stretchly in the apps listed during cmd+tab.

**Comment by hovancik** [comment]
@cameronsstone not intentional, no idea why it's there.

**Comment by hovancik** [comment]
Good news, I've been able to reproduce :) 

I've tried to disable dock icon - did not help
I've tried to remove transparency from background color - did not help
Downgrading electron to 9.1 - helped. 

I'll comment to similar Electron issue that I have found as it's 99.9% related I would say

**Comment by hovancik** [comment]
Good news, I've been able to reproduce :)

I've tried to disable dock icon - did not help
I've tried to remove transparency from background color - did not help

Downgrading electron to 9.1 - this seems to help in combination with hiding dock. **Which is weird** because it would suggest that 1.0 should have the same issue as dock icon was reintroduced in 1.0

I'll comment in the similar issue in Electron that I have found earlier

**Comment by davidwessman** [comment]
> Good news, I've been able to reproduce :)
> 
> 
> 
> I've tried to disable dock icon - did not help
> 
> I've tried to remove transparency from background color - did not help
> 
> 
> 
> Downgrading electron to 9.1 - this seems to help in combination with hiding dock. **Which is weird** because it would suggest that 1.0 should have the same issue as dock icon was reintroduced in 1.0
> 
> 
> 
> I'll comment in the similar issue in Electron that I have found earlier

Please reach out if we can help in any other way! 🙂

**Comment by hovancik** [comment]
I am downgrading for now and disabling dock icon.
