### ISSUE TITLE
Add feature to customize postpone shortcut key

### ISSUE THREAD

**Issue by AvdylKrasniqi** [hovancik/stretchly#692]
Hi there, letting user to choose the shortcut key to postpone the break would be cool.

While I am coding and I press ctrl+X to pause the break it also cuts lines on background. 
U have to go and click by mouse in order to prevent doing stuff on background!

So giving us the option to choose the shortcut key, or preventing Strechtly to bind keys on background apps would be very nice!

Linux smease 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by hovancik** [comment]
Hi, you can do that by editing config file :) 

https://github.com/hovancik/stretchly#postponefinish-break-shortcut
