### ISSUE TITLE
README suggests a deprecated brew command.

### ISSUE THREAD

**Issue by pierre-vr** [hovancik/stretchly#694]
### Description

README suggested to use `brew update && brew cask upgrade` to upgrade. It seems `brew cask upgrade` is deprecated.

Operating system: MacOs

### Steps to Reproduce

1. run `brew update && brew cask upgrade`

**Expected behavior:**
Should not get a warning.

**Actual behavior:**
Get a warning:
`Warning: Calling brew cask upgrade is deprecated! Use brew upgrade --cask instead.`

**Reproduces how often:** 100%

**Comment by hovancik** [comment]
Hi @pierre-vr and thanks for report :) 

Would you like to make a fix?
