### ISSUE TITLE
Brew update does not update // Updates suggestions 

### ISSUE THREAD

**Issue by Ni-Ar** [hovancik/stretchly#695]
Hi, 

I'm trying to update from v1.0 to v1.1 and I'd like to use the command line not to be bothered with too much point and clicking. 

Following the suggestion of #694 I did:

```
> brew upgrade --cask
==> Updated Formulae
[omissis]
stretchly
```
but I still have the v1.0 installed. Am I doing something wrong?

As a feature requests it would be great to have:
- [ ] Automatic updates
- [ ] Turn off new version notifications (pretty annoying and distracting)

OS: 
MacOS v10.15.15

Thanks for this super cool tool
Ciao
Nicco

**Comment by HugooB** [comment]
Maybe try `brew update && brew upgrade`, and if that didn't work:

```bash
brew update-reset
brew update
```

**Comment by Ni-Ar** [comment]
Tried both solutions and did not work...

**Comment by hovancik** [comment]
Hi @Ni-Ar ,
you can disable new version notification in Preferences. 

Did you quit Stretchly before updating?

**Comment by Ni-Ar** [comment]
> you can disable new version notification in Preferences.
Good.

> Did you quit Stretchly before updating?
Yes, of course. Still no update from command line. Maybe it's because in the very beginning I installed not from the command line?

**Comment by hovancik** [comment]
Yeah that could be the problem. 

 Do you have by any change whole output of `brew` command?  

Anyway the safest way would be to remove Stretchly and then install from ground zero with `brew`, if you would like to use `brew` for upgrades.
