### ISSUE TITLE
Icons missing, show as broken image icons

### ISSUE THREAD

**Issue by mikedixson** [hovancik/stretchly#701]
### Prerequisites

- [X ] I'm using latest version: v1.1.0 
- [X ] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [X ] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

In the preferences and at the end of the Skip this break text on a break pop up, the icons/image are missing.

Operating system: Windows 1909

### Steps to Reproduce

1. Right click Stretchly and go to preferences - notice missing icons across top of preferences nav and also on some pages like the about page.
2. Right click Strechly and skip to next break (micro or otherwise) and notice that the click icon from the end of the skip break link/line of text is a broken image icon.

**Expected behavior:** Icons should be presently.

**Actual behavior:** Icons are missing and a broke image icon is should in it's place.

**Reproduces how often:** 100% of the time

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

Originally this was fine, until the new version of stretchly with the new icons upgraded.
Since then the icons have been missing. I've upgrades, resinstalled but no success from this.
![Screenshot 2020-09-21 151204](https://user-images.githubusercontent.com/3373271/93777577-e46f3a80-fc1c-11ea-8656-4c5659b57c53.png)
![Screenshot 2020-09-21 151229](https://user-images.githubusercontent.com/3373271/93777580-e507d100-fc1c-11ea-85b4-666aefe83050.png)

**Comment by hovancik** [comment]
Hi @mikedixson ,

what installer did you use?

**Comment by mikedixson** [comment]
Hi,

I used the offline installer initially.
I've since used chocolately but the same issue persists.

I've used chocolately to uninstall and reinstall too.

Thanks
Mike

**Comment by hovancik** [comment]
Hi @mikedixson , I'm just trying to install in virtual machine with `choco install stretchly` and everything went fine. Do you install as admin? Or maybe some antivirus is blocking the files? 

I'm not using Windows OS so not sure, TBH.

**Comment by mikedixson** [comment]
Yeah I'm admin.
Could be antivirus possibly. I'll do an uninstall and clean everything out
and see how that goes and maybe try a VM with and without Windows defender
enabled to see if it works

**Comment by hovancik** [comment]
In my VM, there is Windows defender running.

**Comment by hovancik** [comment]
Is this still an issue?

**Comment by mikedixson** [comment]
Hi Jan,

Yes I'm afraid so :-(

**Comment by hovancik** [comment]
Hi, maybe you can try getting the chromium debugger by hitting `Ctrl+Shift+I` and checking what the error is?

**Comment by hovancik** [comment]
Hi, is this still issue in new versions? I'll close this but let me know if the issue persists.
