### ISSUE TITLE
Re-add option to hide dock icon

### ISSUE THREAD

**Issue by MrAlexWeber** [hovancik/stretchly#702]
### Prerequisites

- [x] I'm using latest version: v 1.10
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

Version 1.0.0 permanently displays the dock and task switcher icon. It would be nice to re-add the option to hide this icon from dock and task switcher.

Operating system: MacOS Catalina 10.15.6

### Steps to Reproduce

1. Launch Stretchly
2. Browse settings
3. There is no option to hide the dock icon
4. The dock icon is always visible, including task switcher

**Expected behavior:** There is an option at step 3. to hide the icon, and the icon is hidden from dock/task switcher.

**Actual behavior:** There is no option and the icon is always visible.

**Reproduces how often:** 100%

### Additional Information

I'm aware that there are some issues with Electron that may be related to this, but I wanted to create this issue to track whether there would be an option to hide the dock icon.

**Comment by hovancik** [comment]
Yeah I will see how it goes with electron bug, probably just hide it as it was pre-1.0.

**Comment by hovancik** [comment]
I've hidden it altogether for now.
