### ISSUE TITLE
PPA for Stretchly

### ISSUE THREAD

**Issue by warpi** [hovancik/stretchly#703]
### Prerequisites

- [X] I'm using latest version: v 
- [X] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [X] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

PPA for Stretchly

Operating system: 

### Steps to Reproduce

1. Go to google.com
2. Search for Stretchly PPA
3. No relevant hits
4. Same thing goes for https://github.com/hovancik/stretchly and https://hovancik.net/stretchly/

**Expected behavior:** Find a PPA for ubuntu

**Actual behavior:** No hits

**Reproduces how often:** 100%

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by hovancik** [comment]
I've created account on fury.io which seems to have free account for public repos but it seems to me that this would complicate my release process. I'll try checking whether they have some automations

**Comment by hovancik** [comment]
To enable, add the following file /etc/apt/sources.list.d/fury.list:

```deb [trusted=yes] https://apt.fury.io/hovancik/ /```

**Comment by hovancik** [comment]
I won't be creating PPA but I added `apt` repo.
