### ISSUE TITLE
Korean Translation Has a Few Kinks

### ISSUE THREAD

**Issue by hcsong213** [hovancik/stretchly#704]
### Prerequisites

- [x] I'm using latest version: v 1.1.0 
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

Korean translation for "skip to next break" is awkward. Current phrasing is more similar to "get/receive next break".

Beside this, this Issue also serves to express my general interest in refining and expanding the Korean translation.

Operating system:  Windows 10

### Steps to Reproduce

1. Click on stretchly icon in taskbar
2. See the button for "skip to next break" translated as "쉬는 시간 갖기" (갖기 is not the best phrasing here)

**Expected behavior:** Said button translated as "다음 쉬는시간 으로" (translates roughly as "to next break"; more natural in my and my parents' opinions) 

**Actual behavior:** Said button translated as "쉬는 시간 갖기" 

**Reproduces how often:** 100% 

### Additional Information

To briefly state my relationship with Korean, I immigrated from South Korea and use Korean in my house daily. I frequently use Korean websites which include UI elements similar to the one discussed in this Issue.

There are other elements of the translation that is culturally off-putting.

By no means am I trying to sound derogatory. I appreciate the devs including so many languages so that more people could use this app. ❤️

**Comment by hovancik** [comment]
Hi, feel free to create a PR with fix :)

**Comment by hcsong213** [comment]
Can I also translate other components that haven't been translated yet?

**Comment by hovancik** [comment]
Sure :) There are always new features so translations go out of date easy
