### ISSUE TITLE
Rest screens are not displayed

### ISSUE THREAD

**Issue by Korb** [hovancik/stretchly#706]
I'm using latest version: v1.1.0
Microsoft Windows 10.0.19041.508

![2020-09-25_18-36-42](https://user-images.githubusercontent.com/3509797/94286810-2de1c180-ff5e-11ea-95da-19fe7e4100af.png)
![2020-09-25_18-37-01](https://user-images.githubusercontent.com/3509797/94286812-2e7a5800-ff5e-11ea-8f93-d2b31dcc800e.png)
![2020-09-25_18-37-05](https://user-images.githubusercontent.com/3509797/94286813-2f12ee80-ff5e-11ea-93aa-51869a1122da.png)
![2020-09-25_18-37-08](https://user-images.githubusercontent.com/3509797/94286814-2f12ee80-ff5e-11ea-894e-d447ed791445.png)

There are only pop-up notifications that the break time is coming.

**Comment by hovancik** [comment]
Hi, this has been fixed in #705 , next release will contain the fix.
