### ISSUE TITLE
Break Countdown

### ISSUE THREAD

**Issue by Robert-M-Muench** [hovancik/stretchly#71]
If a break is currently active a countdown would be nice so I can see how long the break will last.

For some ideas: http://www.dejal.com/timeout/

**Comment by hovancik** [comment]
Thanks, I'll implement a simple progress bar.

**Comment by hovancik** [comment]
How about this? 
![screen shot 2017-03-24 at 14 23 01](https://cloud.githubusercontent.com/assets/4745859/24296107/fb3ac612-109d-11e7-8309-909022d19c74.png)

There is also  #63 but that will take more time.

**Comment by Robert-M-Muench** [comment]
Looks great! How about adding the numbers counting backward? Or the time passed to fit the progress bar.

**Comment by hovancik** [comment]
Where would you add it? Not sure where to put it. 
I, personally, am minimalist, so I don't like too much stuff being show.

**Comment by Robert-M-Muench** [comment]
Me too. Small text below the bar would fit.

The idea here is: If I have a 5-minute break, I go, grab some water, fresh air. Come back and glance at the screen "ah, still 2 minutes. Ok, I still can do ..."

**Comment by hovancik** [comment]
![screen shot 2017-03-24 at 16 42 35](https://cloud.githubusercontent.com/assets/4745859/24301870/fc26bd02-10b0-11e7-8d3c-d83c2cdb7a26.png)

**Comment by didil** [comment]
👍 on the feature last screenshot
