### ISSUE TITLE
Breaks don't show up in full screen applications

### ISSUE THREAD

**Issue by Lucianod28** [hovancik/stretchly#713]
### Prerequisites

- [x] I'm using latest version: v1.1.0
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

The break window doesn't appear over fullscreen applications. It only appears on the desktop.

Operating system: macOS Catalina 10.15.6

### Steps to Reproduce

1. Enter full screen mode in any application, using Control + Command + F or by clicking the fullscreen button at the top left.
2. In the Stretchly menu, skip to the next mini break.

**Expected behavior:** The break window should show up over the current application.

**Actual behavior:** The break window does not show up. If I navigate to the desktop, I see the break window there, but not over any of my fullscreen applications.

**Reproduces how often:** 100%

### Additional Information

This started happening when I updated to v1.1.0.

**Comment by marcel-goldammer** [comment]
I have the same behaviour with Windows 10.

**Comment by hovancik** [comment]
@Lucianod28 Thanks for the report! macOS used to be the only platform that worked without issues, but not anymore, I guess ;/ 

@marcel-goldammer fix for Windows should come with next release :) It has been merged already

**Comment by Lucianod28** [comment]
Fixed in v1.2.0!
