### ISSUE TITLE
Postpone Break for X minutes

### ISSUE THREAD

**Issue by Robert-M-Muench** [hovancik/stretchly#72]
Sometimes your are really concentrated and actively working, and a break in that second is just annoying. Two ideas:
* Monitor keyboard activity and wait for a X seconds gap before showing the break
* Add a "postpone by  X minutes" option. See: http://www.dejal.com/timeout/

**Comment by birkany** [comment]
What if keyboard activity never stops? and indefinitely waiting for X seconds gap seems conflicting with the philosophy of the program.

**Comment by hovancik** [comment]
The main idea of stretchly is to **enforce** breaks (even thought you might think you are in *flow*). 

I do not plan to add postpone, as you can skip break (with keyboard if you like). What I plan to add is maximum number of skip-able  breaks, after which you wont be able to skip break anymore.

Right now, you can skip break and then start it later, when finished with your current task.

**Comment by Robert-M-Muench** [comment]
I would use a threshold to wait and then show the break. The idea is, that I just don't want to be reminded for a break now but maybe in 3 minutes when I just finished this one task.

Interruption is productivity killer number 1. Breaks are important, so there needs to be an intelligent balance.

**Comment by hovancik** [comment]
What do you mean by threshold? I don't understand it. Maybe some example?

**Comment by Robert-M-Muench** [comment]
Scenario: I'm working and use the keyboard, then a break is triggered Stretchly now checks if I stop typing within a threshold (let's say 3 minutes) and if, starts the break then. If the threshold is passed, the break breaks in and interrupts me.

The idea is, to minimize interruptions in concentrated work sessions. I like these tools but all suffer, that sometimes I don't want to have hard breaks but more a dynamic triggering when I'm not that active anyway.

**Comment by hovancik** [comment]
I like it. Problem is that I don't know how to implement it cross-platform. Don't wanna do it macOS only.

**Comment by Robert-M-Muench** [comment]
I don't have any experience with Electron. Do you know if it's possible to register for native messages or something like this? Or to access the native platform in any way? In the latter case a simple proxy "keyboard activity tracker" could be implemented.

**Comment by hovancik** [comment]
Didn't research it thoroughly, but : https://stackoverflow.com/questions/32986359/listen-for-keyboard-events-and-mouse-movement-outside-of-electron-app/33693917#33693917

This app is exercise in writing nodejs app, so I am kinda reluctant in doing/using stuff that I do not understand (They are some packages trying to detect user idle time).

**Comment by Mil0dV** [comment]
For me this could be very much improved by announcing the break shortly before the actual break. I get really annoyed when it interrupts me mid sentence, so I tend to skip most of the breaks. An OS notification announcing a break a few seconds before it starts allows me to finish the sentence(segment) or line of code and then take the break.

**Comment by hovancik** [comment]
That's good idea. I'll add.

**Comment by Mil0dV** [comment]
@hovancik thanks for the quick fix! However, 30s just feels off for me - way too long. Could you make it configurable or perhaps set it to a default of say 5-10s? (or tell me how to hack this)

**Comment by hovancik** [comment]
@Mil0dV yeah you can hack it by editing config file https://github.com/hovancik/stretchly#advanced-settings

**Comment by cipri-tom** [comment]
I understand your concern with postponing.
I just want to mention how WorkRave has done it (long time ago) and it works quite nicely.

You can postpone the break (with the setting that you configured, e.g. 5 minutes) and after a max number of postponings (say 3, configured), you canot postpone, only skip (so it will leave you alone until the next break).
Here's the catch: it tracks how many times you postponed / skipped so you can see it (and feel bad haha). So I guess #86 would be nice to have before this

**Comment by hovancik** [comment]
I don't plan to implement postponing so closing this.
