### ISSUE TITLE
Stretchly ignores disabled 'Show breaks even in Do Not Disturb mode'

### ISSUE THREAD

**Issue by denisko** [hovancik/stretchly#722]
### Prerequisites

- [X] I'm using latest version: 1.2
- [X] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [X] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

Stretchly shows paused icon when DnD is enabled, but still breaks appear.

Operating system: Mac OS 10.15.7

### Steps to Reproduce

1. Start Stretchly
2. Open Stretchly preference panel and verify that 'Show breaks even in Do Not Disturb mode' is disabled.
2. Enable Do-no-disturb in notification panel
3. Verify that pause icon shows for Stretchly in the menubar
4. Wait x minutes and see that still the micro break appears

**Expected behavior:** Breaks disabled when dnd is enabled

**Actual behavior:** Stretchly breaks show

**Reproduces how often:** always

### Additional Information

?

**Comment by hovancik** [comment]
Hi @denisko ,

I can't reproduce this. 

Here's my setup: 

<img width="599" alt="image" src="https://user-images.githubusercontent.com/4745859/95106021-3ee9ba00-0738-11eb-8340-42336eaa8ad4.png">

<img width="344" alt="image" src="https://user-images.githubusercontent.com/4745859/95106129-650f5a00-0738-11eb-8926-d0e7581e170f.png">

This is what I see in Tray when I enable DND in macOS

<img width="238" alt="image" src="https://user-images.githubusercontent.com/4745859/95106095-5aed5b80-0738-11eb-82be-9f7b2dda6721.png">

What do you see in `Preferences` ->  `About` -> `Cmd+D` ? 

You should get something like: 
```
            breakPlanner: {reference: ,
            timeleft: 0 seconds remaining,
            breakNumber: 0,
            postponesNumber: 0,
            Do Not Disturb: true}
            
            settingsFile: /Users/xxx/Library/Application Support/Stretchly/config.json
            
            logsfile:  /Users/xxx/Library/Logs/Stretchly/main.log
            Node.js: 12.14.1
            Chromium: 83.0.4103.122,
            Electron: 9.1.0
```

**Comment by denisko** [comment]
Hi @hovancik,

I had some difficulties reproducing, but in the end succeeded. Below the debug output and a screenshot. 

The problem didn't show immediately, maybe there is some relation with machine going to sleep, and after wake up the DnD setting is ignored.

```
             breakPlanner: {reference: startMicrobreak,
            timeleft: About 20 minutes remaining,
            breakNumber: 2,
            postponesNumber: 0,
            Do Not Disturb: true}
            
            settingsFile: /Users/xxx/Library/Application Support/Stretchly/config.json
            
            logsfile:  /Users/xxx/Library/Logs/Stretchly/main.log
            Node.js: 12.14.1
            Chromium: 83.0.4103.122,
            Electron: 9.1.0
                 
```

<img width="600" alt="Screenshot 2020-10-06 at 16 02 29 (2)" src="https://user-images.githubusercontent.com/1140456/95212809-5f744b80-07ee-11eb-9930-710cca20998c.png">

**Comment by hovancik** [comment]
Thanks! 

Can you also share your logs file? We should be able to see from there what was happening.

**Comment by denisko** [comment]
I managed to reproduce:
1. Start Stretchly
2. Open Stretchly preference panel and verify that 'Show breaks even in Do Not Disturb mode' is disabled.
3. Enable Do-no-disturb in notification panel
4. Verify that pause icon shows for Stretchly in the menubar
**5. Lock screen
6. Unlock screen**
7. Verify that Do-not-disturb is still enabled in notification panel, and pause icon is still showing for Stretchly.
8. Open Stretchly preference window
8. About screen shows:

```
breakPlanner: {reference: startMicrobreak, timeleft: About 13 minutes remaining, breakNumber: 2, postponesNumber: 0, Do Not Disturb: true}
settingsFile: /Users/xxx/Library/Application Support/Stretchly/config.json
logsfile: /Users/xxx/Library/Logs/Stretchly/main.log
Node.js: 12.14.1 Chromium: 83.0.4103.122, Electron: 9.1.0
```

**Comment by Merlin2001** [comment]
The same issue exists on Windows - The taskbar icon shows "Paused - Do Not Disturb is on", but break screens still appear as if DND wasn't activated. This seems to be a regression compared to v1.1.

**Comment by hovancik** [comment]
Hi @Merlin2001 , is it also after Locking/Unlocking? 

There was no change between 1.1 and 1.2 in the code related https://github.com/hovancik/stretchly/compare/v1.1.0...v1.2.0

@denisko thanks, I'll try over weekend. There's some logic I do when user comes back from lock so probably something there :)

**Comment by Merlin2001** [comment]
Yes, I just tried it out after a fresh restart - pausing the breaks correctly worked until I had locked my computer for the lunch break today. After that, the break screen showed up even though the taskbar icons still (correctly) displayed the _pause_ symbol.

**Comment by hovancik** [comment]
Interesting issue :) 

When Stretchly is not paused, I am pausing it when going to Lock/Sleep/Howevertheycallit. But pausing for DND is not real "Pause". When we come back from Lock/Etc, Stretchly resumes breaks, thus ignoring DND. 

The same would happen if one would pause for hour, and then went to DND: after hour it would resume the breaks even in DND.
