### ISSUE TITLE
Windows Smartscreen/ Defender shows unsafe program warning in 1.2.0

### ISSUE THREAD

**Issue by vikrantpogula** [hovancik/stretchly#723]
### Prerequisites

- [x] I'm using latest version: v 1.2.0
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

When using the latest setup of Stretchly 1.2.0, windows shows a Warning that it may be unsafe to install (Smart Screen filter). This was NOT an issue with 1.1.0. You can still skip the warning via "More Info -> Install Anyway" Was wondering if anything changed with respect to the build ?

Operating system: Windows 10 - Latest

### Steps to Reproduce

1. Install Strethcly-Setup-1.2.0.exe on Windows - warning shows up
2.  Install Strethcly-Setup-1.1.0.exe on Windows - warning shows up 

**Expected behavior:** No Warning should show up.

**Actual behavior:** Warning shows up

**Reproduces how often:** For me - 100% of the times

**Comment by hovancik** [comment]
Hi there, 

nothing changed with the build. This happens to few lucky ones with every release with different antiviruses until few people mark it as false positive ;/ 

Well, I mean if you downloaded official packages :)
