### ISSUE TITLE
Breaks window is oversized

### ISSUE THREAD

**Issue by borna761** [hovancik/stretchly#724]
### Prerequisites

- [x] I'm using latest version: v 
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

Operating system:
Mac OS Catalina, 10.15.7

### Steps to Reproduce

1. Set show breaks in Window
2. Wait for a break

**Expected behavior:**
Break window takes up a small part of the screen (like in 1.1.0 and before)

**Actual behavior:**
Window is HUGE:
![image](https://user-images.githubusercontent.com/9056534/95097391-6d956f80-06fb-11eb-845f-6cf60b817426.png)

**Reproduces how often:**
Always

### Additional Information
My monitor is a 3440 x 1440 widescreen.

**Comment by hovancik** [comment]
Hi @borna761 ,

this is new Stretchly behavior: Breaks cover 85% of screen size. 

You can change this by editing config file (https://github.com/hovancik/stretchly#advanced-preferences) and editing the values:  https://github.com/hovancik/stretchly#break-window-size-
