### ISSUE TITLE
Taskbar visible during brakes

### ISSUE THREAD

**Issue by PalladiumUser** [hovancik/stretchly#725]
### Prerequisites

- [X] I'm using latest version: v 1.2.0
- [X] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues) YES
- [X] I've checked [Open issues](https://github.com/hovancik/stretchly/issues) YES

### Description

The taskbar is visible during brakes.

Operating system:  Windows 10 64bit

### Steps to Reproduce

1. [First Step] Install Stretchly
2. [Second Step] Jump to the next mini break or long break
3. [and so on...] The taskbar is visible, image is attached

**Expected behavior:** [What you expect to happen] The taskbar should be hidden - it was like that until some newer version came.

**Reproduces how often:** [What percentage of the time does it reproduce?] Every break

PS: I am the patreon supporter.

![2020-10-06_12-41-57](https://user-images.githubusercontent.com/72444312/95193670-75751280-07d4-11eb-8c9e-89534f4c4894.jpg)

**Comment by hovancik** [comment]
Interesting, I can reproduce this only when taskbar is not on its default position, on the bottom side. Not sure why that would be the case, yet.
