### ISSUE TITLE
FR: Have window and full screen mode 

### ISSUE THREAD

**Issue by AgentDiamond** [hovancik/stretchly#729]
### Prerequisites

- [x] I'm using latest version: 1.2.0
- [x] I've checked [Known issues]
- [x] I've checked [Open issues]

### Description

Have a windowed and full screen option. I often switch between the two and want stretchly to remind me of breaks in both.

Operating system: Windows 10

**Comment by hovancik** [comment]
Hi there, could you please explain more? I am not sure if I understand. You can pick between `Window` and `Fullscreen` already, what would you like to have?

**Comment by AgentDiamond** [comment]
Ah, I seem to have misunderstood. I'm guessing it means that it shows the breaks as a  window or full screen? "Shows breaks in window / full screen" is a bit ambiguous...I thought it meant that the breaks would only show if you are in a windowed mode or in full screen...still though, if the breaks are windowed does that mean I should be able to drag them and minimise them? I don't seem to be able to do that

**Comment by hovancik** [comment]
Hi @AgentDiamond , yeah, it means whether you want breaks to appear in fullscreen or as a window. 

In both cases, you can't move or minimize them.

**Comment by AgentDiamond** [comment]
Would be good to have them minimisable...can be intrusive to have a huge window appear. Maybe a sound only option would be good with different sounds for short and long breaks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hovancik** [comment]
Ah well, that's the philosophy of Stretchly, I want it to be obtrusive so it forces to take a break :)
