### ISSUE TITLE
v1.2.0: break window is very large on macOS

### ISSUE THREAD

**Issue by samcramer** [hovancik/stretchly#732]
### Prerequisites

- [X] I'm using latest version: v1.2.0 
- [X] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [X] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

The window that pops up for a break is very large, covering most, but not all, of the whole screen.  This started happening after I used "brew" to upgrade from v1.1.0 to v1.2.0

Operating system: macOS Catalina 10.15.7 

### Steps to Reproduce

1. Upgrade from version 1.1.0 to version 1.1.2 by running "brew update && brew upgrade"
2. Select "Skip to the next mini-break" using the icon in the menu bar.
3. Observe that the displayed window is very large.

**Expected behavior:** [What you expect to happen]

A small window to be displayed.

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Additional Information

1. I have checked the settings and "Show breaks in: Window" is selected.
2. I am using a MacBook Pro with an external monitor.   The external monitor is the primary display.
3. I forgot to quit Stretchly before upgrading.   After upgrading, I continually saw a pop-up complaining about a javascript error (if memory serves).  I needed to kill all the Stretchly processes (using pkill) in order to get rid of the pop-up and cause Stretchly to exit.  Maybe some preferences got scribbled on due to my failure to quit before upgrading or my subsequently killing the processes using the default TERM signal.
4. I removed version 1.2.0 using "brew cask uninstall Stretchly" and then installed the version 1.1.0 .dmg found at https://github.com/hovancik/stretchly/releases.  That version works as expected, so this seems to be 1.2.0-specific.

**Comment by hovancik** [comment]
Hi, this is new default behavior, Stretchly is covering 85% of screen. You can change the percentage by editing preferences file: https://github.com/hovancik/stretchly#break-window-size-

https://github.com/hovancik/stretchly#advanced-preferences

**Comment by decadent** [comment]
Just to note: a side effect of this is that Stretchly covers its own status-bar menu, only the top two lines are visible and accessible. Hence, if you want to pause the breaks after one starts (e.g. when watching a film), you have to wait until the ‘next break’ lines disappear—which doesn't happen immediately—and ‘pause breaks’ moves higher.

IMO though, the window shouldn't cover menus in the first place, but dunno yet why that occurs.

**Comment by hovancik** [comment]
@decadent do you mean that opposite of this is happening? (That black thingy is Stretchly's break window)

![image](https://user-images.githubusercontent.com/4745859/110237146-743e4200-7f3a-11eb-95c1-4ec20d760a14.png)

This is for me on Linux (Debian KDE)

**Comment by decadent** [comment]
Yeah, below is what it looks like for me. Notably, I've never seen another app that covers the menus.

I also don't think the covering occurred before 1.2 or so (possibly earlier). Will check that later.

![image](https://user-images.githubusercontent.com/240699/110237287-4bbf4380-7f4c-11eb-954b-006bf2ce72a6.png)

**Comment by hovancik** [comment]
I guess it's because how we set no top: https://www.electronjs.org/docs/api/browser-window#winsetalwaysontopflag-level-relativelevel

```
    breakWinLocal.setAlwaysOnTop(true, 'screen-saver')
```

Different `level` might work as expected. There was some reason, I think, why `screen-saver` was used but don't remember now.

**Comment by decadent** [comment]
Also, while testing this, I realized that transparency doesn't always work, and ‘postpone the break‘ doesn't always appear on the mini-break window. I'm betting on race conditions—probably some flags/actions should be triggered before displaying the window, but are occasionally triggered afterwards. Something in this vein.
