### ISSUE TITLE
Feature Request: systematic messages of drinking water during micro-breaks

### ISSUE THREAD

**Issue by rtrad89** [hovancik/stretchly#737]
### Prerequisites

- [x] I'm using latest version: 1.2.0 
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

"Grab a glass of water" message during micro-breaks shows up randomly. If it can be shown systematically to prod users into drinking enough water, it would be a great health benefit. Keeping oneself hydrated is an additional important aid towards eye preservation. 

Operating system: Windows 10 Pro x64, Version 2004 

### Steps to Reproduce

NA

**Expected behavior:**  Reminders of drinking water show up systematically with a frequency that can be governed through settings.

**Actual behavior:** Reminders of drinking water show up randomly.

**Reproduces how often:** 100%

### Additional Information

None.

**Comment by hovancik** [comment]
Hi @rtrad89 ,

I understand what you're saying but I don't think it's direction where I want to go with Stretchly. Adding this would complicate a code quite a bit and then there are many other things that could further complicate the code (ie:  remind me to take a lunch, remind me to do x, do something after I am inactive etc..). 

If you have smartphone, there are many apps that do exactly that - I mean reminders to drink water; or many tools to make custom reminders that will do it better then Stretchly.

**Comment by hovancik** [comment]
Hey, I've also hacked around this week and created https://github.com/hovancik/later-on which allows custom notifications. It's very alpha but might be also what you're looking for.
