### ISSUE TITLE
Negative wait time for Long Break

### ISSUE THREAD

**Issue by dummy26** [hovancik/stretchly#739]
### Prerequisites

- [x] I'm using latest version: v 1.2.0
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

[Description of the issue]

Operating system: Windows 8.1

### Steps to Reproduce

I really don't have any idea

**Expected behavior:** Positive wait time

**Actual behavior:** Negative wait time

**Reproduces how often:** 2-3% maybe
![Screenshot (5)](https://user-images.githubusercontent.com/40134444/96359346-6a54a780-112f-11eb-9c45-2bb2803cca0c.png)

###Additional Information

Might be related to #648

**Comment by hovancik** [comment]
Hi @dummy26  and thanks for the report :) 

When this happens next time, could you paste the log file? You can find the location of log file by going Preferences -> About -> `Ctrl+d` shortcut

**Comment by hovancik** [comment]
Also, please paste all the debug information you will see there :)

**Comment by dummy26** [comment]
Faced the issue again. Here are the files -
[log.txt](https://github.com/hovancik/stretchly/files/5406410/log.txt)
[main.log](https://github.com/hovancik/stretchly/files/5406411/main.log)

Here is the config file-

{
    "microbreakDuration": 10000,
    "microbreakInterval": 600000,
    "breakDuration": 60000,
    "breakInterval": 2,
    "breakNotification": false,
    "microbreakNotification": false,
    "breakNotificationInterval": 30000,
    "microbreakNotificationInterval": 10000,
    "microbreak": true,
    "break": true,
    "microbreakStrictMode": false,
    "breakStrictMode": false,
    "morningHour": 6,
    "microbreakPostpone": true,
    "breakPostpone": true,
    "microbreakPostponeTime": 120000,
    "breakPostponeTime": 300000,
    "microbreakPostponesLimit": 1,
    "microbreakPostponableDurationPercent": 30,
    "breakPostponesLimit": 1,
    "breakPostponableDurationPercent": 30,
    "mainColor": "#478484",
    "transparentMode": true,
    "opacity": 0.9,
    "audio": "wind-chime",
    "volume": 1,
    "fullscreen": false,
    "ideas": true,
    "naturalBreaks": true,
    "naturalBreaksInactivityResetTime": 300000,
    "allScreens": true,
    "useIdeasFromSettings": false,
    "language": "en",
    "notifyNewVersion": true,
    "isFirstRun": false,
    "posLatitude": 0,
    "posLongitude": 0,
    "useMonochromeTrayIcon": false,
    "useMonochromeInvertedTrayIcon": false,
    "silentNotifications": false,
    "monitorDnd": true,
    "microbreakStartSoundPlaying": false,
    "breakStartSoundPlaying": false,
    "themeSource": "system",
    "endBreakShortcut": "CmdOrCtrl+X",
    "breakWindowWidth": 0.85,
    "breakWindowHeight": 0.85,
    "breakIdeas": [
        {
            "data": [
                "Not alone",
                "Do you find it hard to take a break alone? Try to do it with a co-worker. Aside from making it easier to stick to breaks, you will have a chance to get to know them better. Taking breaks together increases productivity."
            ],
            "enabled": true
        },
        {
            "data": [
                "Step away",
                "Do you ever notice how your brain can figure things out by itself? All it takes is to step away from the computer and take a break to think about something totally unrelated."
            ],
            "enabled": true
        },
        {
            "data": [
                "Microbreaks",
                "Rest is a key component in ensuring the performance of the musculoskeletal system. Frequent breaks can decrease the duration of a task and help lower the exposure to ergonomic injury risk."
            ],
            "enabled": true
        },
        {
            "data": [
                "Meditation",
                "Research studies suggest that mindfulness-based exercises help decrease anxiety, depression, stress, and pain, and help improve general health, mental health, and quality of life. Not sure how to start? There are numerous apps to help you out."
            ],
            "enabled": true
        },
        {
            "data": [
                "Blink",
                "Looking at screens for a long time causes you to blink less, thus exposing your eyes to the air. Blink rapidly for a few seconds to refresh the tear film and clear dust from the eye surface."
            ],
            "enabled": true
        },
        {
            "data": [
                "Ergonomics",
                "Improper height and angle of the keyboard, mouse, monitor or working surface can cause health problems. Take some time to read about desk ergonomics."
            ],
            "enabled": true
        },
        {
            "data": [
                "Move",
                "There are a lot of ways you can exercise within your office. Try marching in place or doing desk push-ups."
            ],
            "enabled": true
        },
        {
            "data": [
                "Change",
                "Do you have a stability ball or standing work desk? Consider replacing your desk chair with them for a while."
            ],
            "enabled": true
        },
        {
            "data": [
                "Notice",
                "Are you daydreaming or having trouble focusing? It is a sign that you need to take a break."
            ],
            "enabled": true
        },
        {
            "data": [
                "Tech",
                "How about taking a no-tech walk?"
            ],
            "enabled": true
        },
        {
            "data": [
                "Metabolism",
                "Emerging research shows that sitting for long periods of time contributes to risk of metabolic syndrome, heart attack and stroke risk and overall death risk, among others. Taking regular walking breaks can help your circulation, working to counteract some of those problems."
            ],
            "enabled": true
        },
        {
            "data": [
                "Active Meetings",
                "How about moving meetings from the conference room to the concourse? Walking not only burns calories but it may even foster a sense of collaboration."
            ],
            "enabled": true
        },
        {
            "data": [
                "Fruit",
                "Take your time and eat some fruit. Slowly. Notice the flavor, the texture, the freshness."
            ],
            "enabled": true
        },
        {
            "data": [
                "Bathrooms",
                "Walk to the farthest bathroom in the worksite facility when going to the restroom."
            ],
            "enabled": true
        },
        {
            "data": [
                "Coffee break",
                "Going on coffee break? Consider doing a 5-minute walk every time you go for one."
            ],
            "enabled": true
        },
        {
            "data": [
                "Colleagues",
                "Do not email or message office colleagues, walk to their desks to communicate with them."
            ],
            "enabled": true
        },
        {
            "data": [
                "Learning",
                "In a study of healthy volunteers, NIH researchers found that taking short breaks, early and often, may help our brains learn new skills."
            ],
            "enabled": true
        },
        {
            "data": [
                "Exercise",
                "Evidence suggests small amounts of regular exercise can bring dramatic health benefits, including measurably reducing stress."
            ],
            "enabled": true
        },
        {
            "data": [
                "Repeat",
                "Have you found your stretch-ly-routine? Do not forget to repeat it for more than once to better fight effects of prolonged sitting."
            ],
            "enabled": true
        },
        {
            "data": [
                "Wrist and forearm",
                "Extend your arms with the palms facing towards you, then slowly rotate the hands four times clockwise, then four times counter-clockwise."
            ],
            "enabled": true
        },
        {
            "data": [
                "Back stretching",
                "Join your hands behind your head, then lift them together up above your head ending with your palms facing upward."
            ],
            "enabled": true
        },
        {
            "data": [
                "Mobilize",
                "For every thirty minutes of stagnation, you should have at least one minute of stimulation."
            ],
            "enabled": true
        },
        {
            "data": [
                "7 Minute Workout",
                "This workout packs in a full-body exercise routine in a fraction of the time. But as with any excercise, be careful. There are numerous apps to get you started."
            ],
            "enabled": true
        },
        {
            "data": [
                "Pulse",
                " Raise your pulse rate to 120 beats per minute for 20 straight minutes four or five times a week doing anything you enjoy. Regularly raising your heart rate results in improved cardiovascular health."
            ],
            "enabled": true
        },
        {
            "data": [
                "Take the stairs ",
                "Studies have shown that stair climbing, which is considered vigorous-intensity physical activity, burns more calories per minute than jogging."
            ],
            "enabled": true
        },
        {
            "data": [
                "Make art",
                "Art therapy is known to have great mental health benefits, especially when it comes to stress management. How about writing a quick poem, taking a picture or painting something small?"
            ],
            "enabled": true
        },
        {
            "data": [
                "Declutter",
                "A clean space helps your focus at work and is often linked to positive emotions like happiness."
            ],
            "enabled": true
        },
        {
            "data": [
                "Lunch outside",
                "Nature is linked to positive emotions and decreased stress and anxiety. Whenever possible, try to take your daily lunch break outside, surrounded by some greenery."
            ],
            "enabled": true
        },
        {
            "data": [
                "Public Transport",
                "If you use public transport regularly, you can stand instead of sitting. If it is possible, try to replace as many of your daily trips as possible with walking or cycling."
            ],
            "enabled": true
        }
    ],
    "microbreakIdeas": [
        {
            "data": "Go grab a glass of water.",
            "enabled": true
        },
        {
            "data": "Slowly look all the way left, then right.",
            "enabled": true
        },
        {
            "data": "Slowly look all the way up, then down.",
            "enabled": true
        },
        {
            "data": "Close your eyes and take few deep breaths.",
            "enabled": true
        },
        {
            "data": "Close your eyes and relax.",
            "enabled": true
        },
        {
            "data": "Stretch your legs.",
            "enabled": true
        },
        {
            "data": "Stretch your arms.",
            "enabled": true
        },
        {
            "data": "Is your sitting posture correct?",
            "enabled": true
        },
        {
            "data": "Slowly turn head to side and hold for 10 seconds.",
            "enabled": true
        },
        {
            "data": "Slowly tilt head to side and hold for 5-10 seconds.",
            "enabled": true
        },
        {
            "data": "Stand from your chair and stretch.",
            "enabled": true
        },
        {
            "data": "Refocus your eyes on an object at least 20 meters away.",
            "enabled": true
        },
        {
            "data": "Take a moment to think about something you appreciate.",
            "enabled": true
        },
        {
            "data": "Take a moment to smile at being alive.",
            "enabled": true
        },
        {
            "data": "A truly ergonomic workstation is one that you regularly push away from.",
            "enabled": true
        },
        {
            "data": "Close your eyes and count your breaths.",
            "enabled": true
        },
        {
            "data": "Close your eyes and name the things you hear.",
            "enabled": true
        },
        {
            "data": "Place your fingertips on your shoulders. Roll your shoulders forward for 10 seconds, then backward.",
            "enabled": true
        },
        {
            "data": "Raise your right arm, stretch it over your head to the left, and hold for 10 seconds. Repeat on the other side.",
            "enabled": true
        },
        {
            "data": "With your right hand, grab each finger of your left hand in turn and squeeze. Repeat on the other side.",
            "enabled": true
        },
        {
            "data": "Stand up and do a lunge. Hold for 10 seconds, then do the other leg.",
            "enabled": true
        },
        {
            "data": "Close your eyes and simply notice whatever arises in current moment, without judgement.",
            "enabled": true
        },
        {
            "data": "One should focus every 20 minutes for 20 seconds on an object that is 20 feet distance.",
            "enabled": true
        },
        {
            "data": "If you need help, ask for it.",
            "enabled": true
        },
        {
            "data": "Do one thing at a time.",
            "enabled": true
        },
        {
            "data": "Is your attention spent wisely?",
            "enabled": true
        },
        {
            "data": "Change your sitting posture.",
            "enabled": true
        }
    ],
    "checkNewVersion": true
}

**Comment by hovancik** [comment]
So these are related logs: 

```
[2020-10-20 09:59:35.619] [info] Stretchly: loading settings
[2020-10-20 09:59:35.637] [info] Stretchly: starting Idle time monitoring
[2020-10-20 09:59:35.650] [info] Stretchly: starting DND monitoring
[2020-10-20 10:04:45.042] [info] Stretchly: pausing breaks because of idle time
[2020-10-20 10:11:51.557] [info] Stretchly: resuming breaks after idle time
[2020-10-20 10:12:09.325] [info] Stretchly: skipping to Mini Break
[2020-10-20 10:12:10.106] [info] Stretchly: showing window 1 of 1
[2020-10-20 10:12:10.138] [info] Stretchly: starting Mini Break
[2020-10-20 10:12:20.148] [info] Stretchly: finishing Mini Break
[2020-10-20 10:17:35.001] [info] Stretchly: pausing breaks because of idle time
[2020-10-20 10:18:05.038] [info] Stretchly: resuming breaks after idle time
[2020-10-20 10:28:05.039] [warn] Stretchly: in natural break, not starting Mini Break
```

App was started, after few minutes breaks were paused because of inactivity. You came back and skipped to mini break. Then breaks were paused because of inactivity again.  Then you came back. Next break did not start because `in natural break, not starting Mini Break`. 

I am not sure how that could happen, yet, as the message before that is that idle time has finished and we are resuming breaks.

**Comment by dummy26** [comment]
Negative wait time have become more common now and so I decided to uninstall Stretchly. May reinstall later.
Also I wanna thank you for such a great app . U are awesome!

**Comment by hovancik** [comment]
Note to self: 

```
  if (breakPlanner.naturalBreaksManager.idleTime > settings.get('breakDuration')) {
    log.warn('Stretchly: in natural break, not starting Mini Break')
    return
  }
```

```
"breakDuration": 60000,
```
That's the issue probably: your breaks are 1 minute, but idle time starts after 20 seconds, pausing after 5 minutes. 

I think solution might be just deleting that part of code. Will need to think about consequences.

**Comment by hovancik** [comment]
Ok @dummy26 , thanks :) 

I think disabling idle time monitoring would fix the issue for you.

**Comment by dummy26** [comment]
Thanks @hovancik for the fix. Might try the fix later on.
