### ISSUE TITLE
"Pause until Morning" not working

### ISSUE THREAD

**Issue by edenman** [hovancik/stretchly#741]
### Prerequisites

- [👍] I'm using latest version: v1.2.0
- [👍] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [👍] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

The "pause breaks" -> "until morning" menu does not actually pause breaks.

Operating system: MacOS Catalina 10.15.7

### Steps to Reproduce

1. Select the menu option
2. Note that the breaks are not paused

**Reproduces how often:** 
100%
I feel like sometimes it works (maybe on a previous version of the app?), but right now it's reproducible 100%.

### Additional Information

Could be timezone-related?  I'm based in New Zealand, maybe something about the "morning" detection is hardcoded to a different timezone or something?

![ezgif-1-8566e70f0514](https://user-images.githubusercontent.com/1063557/96648713-4346e180-138c-11eb-9598-f2cd06339e81.gif)

**Comment by edenman** [comment]
Definitely might be timezone related.  It's now late afternoon here and I was just able to successfully pause until morning.

**Comment by hovancik** [comment]
Did you change any settings? By default it pauses it 6am, based on your current time so no time zone.

**Comment by hovancik** [comment]
could you also paste the log file after trying to pause till morning? you can get the location in About section of Preferences by hitting `Cmd+D`. 

This line should be enough: `16:10:21.147 › Stretchly: pausing breaks for 49779002` 

it's in milliseconds.

**Comment by edenman** [comment]
```
[2020-10-25 08:57:44.426] [info] Stretchly: pausing breaks for -10663999
[2020-10-25 08:57:44.431] [info] Stretchly: resuming breaks
```

**Comment by edenman** [comment]
About Page, for reference:
```
            breakPlanner: {reference: startMicrobreakNotification,
            timeleft: About 10 minutes remaining,
            breakNumber: 1,
            postponesNumber: 0,
            Do Not Disturb: false}
            
            settingsFile: /Users/edenman/Library/Application Support/Stretchly/config.json
            
            logsfile:  /Users/edenman/Library/Logs/Stretchly/main.log
            Node.js: 12.14.1
            Chromium: 83.0.4103.122,
            Electron: 9.1.0

**Comment by edenman** [comment]
My javascript-fu isn't great, but I'm guessing it's something here-ish: https://github.com/hovancik/stretchly/blob/db15168c1d1ae1c6279d5ab63d72aab7761d5563/app/utils/untilMorning.js#L35

NZ is GMT+13 which means when it's morning here on October 25, it's still October 24 in UTC.  So the morning time is calculated on October 24 which results in a negative offset?

**Comment by hovancik** [comment]
@edenman  and did you change any settings regarding pause to morning feature?

**Comment by hovancik** [comment]
I changed my timezone to Auckland and I am seeing my time being 3.23 AM. Pausing till morning makes it pause for 2 hours and 37 minutes which is correct.

**Comment by edenman** [comment]
No settings changed.  Maybe it only happens after 6am NZT?  I'll see if I can try it before 6am if I happen to be awake that late sometime this week.

**Comment by hovancik** [comment]
I think the issue sits with that feature trying to convert times to UTC. I started to implement new way of using local time instead. Will take some time :)

**Comment by edenman** [comment]
Let me know if you need any help testing the fix!

**Comment by hovancik** [comment]
Hey @edenman , if you know how to run from source, you could try `fix/until-morning` branch. 

Works fine for me, but then, it also did before :)

**Comment by edenman** [comment]
yay, it works!  thanks @hovancik!
