### ISSUE TITLE
Code refactoring (combining micro and long break)

### ISSUE THREAD

**Issue by BenediktAllendorf** [hovancik/stretchly#744]
This is more a discussion/idea than an actual issue.

While thinking about and debugging #743, I noticed that a lot of code exists twice, once for (long) breaks, once for micro breaks. But most of the stuff is the same and only duplicated. This means that certain fixes/changes have to be implemented twice.

Is this a deliberate decision? If not, I created an example of how I think this could be simplified. It's not yet done fully comprehensive but you should get the basic idea: https://github.com/hovancik/stretchly/compare/master...BenediktAllendorf:refactor

**Comment by hovancik** [comment]
Well, there are many similar places across the app. I've also tried your approach, but one thing that I don't like is that it brings many `if`s and `switch`es and so on. It might be a bit less code in the end, but it's cognitively harder. 

I might be wrong, hard to tell :) 

Btw, it's `Mini Breaks` now. They were `microbreaks` before 1.0, but in code I mostly left as it was because I didn't want to do changes to preferences/settings.

**Comment by BenediktAllendorf** [comment]
Yeah, I can see how additional `if`s and `switch`es are annoying (but only three have been introduced and two of the occurrences are only intermediate steps anyway). Maybe it could be tackled by inheritance? Having a Break-Supertype and Subclass like LongBreak and MiniBreak which share most of their functionally.

Independently, lots of duplicated code could be refactored into functions (e.g `generateWindowOptions()`)?

**Comment by BenediktAllendorf** [comment]
I tried the extract approach and introduced three new helper methods (I didn't think too hard about the naming): https://github.com/hovancik/stretchly/compare/master...BenediktAllendorf:duplicated_code

Those were lines with almost identical code except the one variable being worked with. I'm very much used to fixing my Intelij warnings, that's how I encountered the duplicates.

Additionally, it seems that the whole content of both defaultMicrobreakIdeas.js and defaultBreakIdeas.js is also included in defaultSettings.js.

**Comment by hovancik** [comment]
Hi @BenediktAllendorf , sorry for late replies. I am doing new release today/tomorrow and will take a look after :) 

I duplicate default ideas in default settings because they also get replaces when user resets settings.

**Comment by BenediktAllendorf** [comment]
Sure, no worries. Changes like this are kind of hard to review and I'm not sure if they are worth it. On the one hand, reducing duplication seems like a good thing to do, on the other hand, I don't think it should be combined with functional changes.

**Comment by hovancik** [comment]
Yeah, I will try running it locally for a few days to see if I notice any issues

**Comment by hovancik** [comment]
I'm getting Error when break should start

![image](https://user-images.githubusercontent.com/4745859/98643694-aabed400-232f-11eb-95d9-9e3728052d23.png)

**Comment by BenediktAllendorf** [comment]
😓 yeah, got messed up there. It's fixed now (and running locally here).

**Comment by hovancik** [comment]
I've created PR to better see changes :) #768
