### ISSUE TITLE
Redundant title notification on windows 2004 

### ISSUE THREAD

**Issue by Esildor** [hovancik/stretchly#745]
### Prerequisites

- [✔] I'm using the latest version: v 1.2.0
- [✔] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [✔] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

A new windows update changed a bit how notifications appear. Now there is duplicated information. Please change this to include more relevant or less information.

Operating system: Windows 10 (20H2) (OS Build 19042.572)

### Steps to Reproduce

1. Get pushed a notification

**Expected behavior:**
The notification doesn't contain duplicate information, in this case, the app title

**Actual behavior:**
Two titles

**Reproduces how often:**
100% of all notifications 

### Additional Information
Image for context:
![Screenshot 2020-10-22 113750](https://user-images.githubusercontent.com/5234969/96896041-131a4400-145b-11eb-9660-9618d43a301c.png)

**Comment by hovancik** [comment]
Is that some special Windows version? I am trying in latest Windows version Microsoft sends me updates for and not seeing double title.

**Comment by Esildor** [comment]
You must not be on the latest version of windows, you should force an update via the Update Assistant:

https://www.microsoft.com/en-us/software-download/windows10

**Comment by tech189** [comment]
I have the same issue except my notifications display the uglier 'net.hovancik.stretchly'
![Twinkle_Tray_fswZx6Pmhv](https://user-images.githubusercontent.com/10728085/97432908-9bde2780-1914-11eb-98e0-517bad4ed851.png)

**Comment by BenediktAllendorf** [comment]
I now have it as well, it depends on the new 20H2 Update, see (you have to scroll down) [Notifications](https://www.neowin.net/news/windows-10-version-20h2-is-coming---heres-whats-you-need-to-know/).

It seems easily fixable by checking whether Stretchly is running on 20H2 or newer (build version equal or higher than 19042) and then omit the notification's title. This only helps with the original issue though, not the one @tech189 is seeing.

**Comment by hovancik** [comment]
Hey sorry guys I only have Virtual machine and no space to upgrade as it wants many gigis :)
I don't understand why microsoft is doing this, Notification is pretty standard across all OSes ;/ not sure if we can get build number

@tech189 what version are you running?

**Comment by tech189** [comment]
I am on version 1.2.0. I think the issue is that I installed Stretchly with [Scoop](https://github.com/lukesampson/scoop) so that updates are less painless and can be done through the command line, maybe Windows doesn't like that it is effectively a portable program? I've switched to the normal installer and it is fixed :/

**Comment by hovancik** [comment]
@tech189 Might be worth creating an issue there so they can possibly make a fix :)
