### ISSUE TITLE
[Request] Time range when Stretchly is active

### ISSUE THREAD

**Issue by oranges13** [hovancik/stretchly#750]
### Prerequisites

- [x] I'm using latest version: v 1.2.0
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

I have one computer, which I use for work and for leisure. During the work day, I greatly enjoy Stretchly to keep me taking breaks often, but in the evenings, I usually am writing or gaming or something that requires more long-term attention. On Macbook, I have used Timely which gives you the option to set a start and end time for break notifications during the day.

For example, I would like break reminders to be displayed between 8am and 5pm on certain days, but not on Saturday or Sundays or in the evenings. I did find https://github.com/hovancik/stretchly/issues/85 this issue, but I believe this feature would be useful and is still needed.

If there is another way to accomplish this in the settings, let me know.

Operating system: Linux Mint 20.01 & MacOS

**Comment by hovancik** [comment]
Hi @oranges13 , yeah, I closed that issue because it was opened long time ago and I unfortunately don't have infinite time so it never happened ;/ 

What you can do right now is simply to pause breaks from tray menu and then resume them when you want breaks to start again.

**Comment by hovancik** [comment]
#342 Actually, can you follow here for updates? I left that one opened.
