### ISSUE TITLE
Typo in preferences screen: 'langauge' -> 'language'

### ISSUE THREAD

**Issue by pcrama** [hovancik/stretchly#763]
### Prerequisites

- [X] I'm using latest version: v 1.3.0
- [X] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [X] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

There is a typo in the Settings tab of the preferences dialog

Operating system: Windows 10 (64 bit, Enterprise)

### Steps to Reproduce

1. Open preferences
2. Look at settings tab at the bottom (language selection)

**Expected behavior:** The language selection should be preceded by correctly spelled "Select language:"

**Actual behavior:** The language selection is preceded by incorrectly spelled "Select lang**au**ge:" (emphasis mine)

**Reproduces how often:** 100%

### Additional Information

I'm using the English (probably default, I don't remember setting any language preference) locale.

**Comment by hovancik** [comment]
Nice catch :)
