### ISSUE TITLE
Randomly crashes in Ubuntu

### ISSUE THREAD

**Issue by fvictorio** [hovancik/stretchly#765]
### Prerequisites

- [x] I'm using latest version: v 
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

Stretchly crashes and closes after using it some time. I know this isn't a lot of information, but I couldn't find a reproducible way of making it crash: it just happens.

I suspected that it might have to do with my computer going to sleep, but I suspended it and it continued to work fine.

I just disabled the "Monitor activity" checkbox to see if it continues to happen after that. I will update the issue if I notice that it's fixed after that.

Operating system: Ubuntu 20.04

### Steps to Reproduce

I don't have reproduction steps, sorry :cry: 

### Additional Information

Installed via `Stretchly_1.3.0_amd64.deb`

**Comment by hovancik** [comment]
Hi @fvictorio and thanks for the report! 

I think this might be related to issue some people have with few distributions and what version of libappindicator they have (there is a upstream issue there). 

There's a message from one Ubuntu user here, in which they fix it by using fixed version: https://github.com/hovancik/stretchly/issues/633#issuecomment-716394124 

Might be worth trying, if you have no issues with adding new repos to your sources.

**Comment by fvictorio** [comment]
Oh, sorry, didn't find that issue. Feel free to close this one (although maybe it's good to have it open for searchability). In any case, I tried that fix, I'll report back if it fixes it (or not).

**Comment by hovancik** [comment]
Let's wait what you will see after some time, whether it's that issue or something else.

**Comment by fvictorio** [comment]
Well, it's been like a whole day and it didn't crash, so I'm going to close this. I'll reopen it if it happens. Thanks @hovancik!

**Comment by foundryspatial-duncan** [comment]
I noticed the snap image version was randomly segfault-ing on Ubuntu 18.04.. I've uninstalled it to try the .deb version and I'll open my own issue if I discover anything...
