### ISSUE TITLE
Redundant title notification on macOS Big Sur 

### ISSUE THREAD

**Issue by tech189** [hovancik/stretchly#767]
### Prerequisites

- [✅] I'm using latest version: v1.3.0 
- [✅] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [✅] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

In the latest update of macOS, each notification includes the app name and icon, so it would be good to hide the second 'Stretchly' in Big Sur.

Operating system: macOS Big Sur 11.0.1 

### Steps to Reproduce

1. Wait for a break notification
2. See the duplicate app name

**Expected behavior:** No duplication of name

**Actual behavior:** Duplication of name

**Reproduces how often:** Every notification

### Additional Information

Screenshot for reference:
<img width="390" alt="Screenshot 2020-11-13 at 12 36 47" src="https://user-images.githubusercontent.com/10728085/99073519-f2eb2a00-25ad-11eb-95a1-a9461d31800d.png">

Probably can be mitigated with a small fix, see #745

**Comment by hovancik** [comment]
Ah, interesting. If anyone is interested in making a PR, go ahead. I've seen a lot of people having issues with Big Sur, so I will wait a bit before upgrading my test machine.

**Comment by hovancik** [comment]
@tech189 , I wonder, could you get some system notification screenshot? I would like to know if we should simply remove `Stretchly` or replace it with `Mini break....`

**Comment by tech189** [comment]
I couldn't get any system notifications but the Screen Time one is built-in (see the OneNote notification has no title for comparison)
<img width="354" alt="Screenshot 2020-11-15 at 10 51 28" src="https://user-images.githubusercontent.com/10728085/99183077-420d9800-2731-11eb-9439-b89009d1325f.png">

And here is a sample one from Apple's website:
<img width="222" alt="image" src="https://user-images.githubusercontent.com/10728085/99183320-bdbc1480-2732-11eb-995c-76a321ef3944.png">


Maybe the Stretchly notification could be something like this:
STRETCHLY
**Mini Break Starting Soon**
Time to take a rest in 10 seconds
