### ISSUE TITLE
Add contrast color theme - black text on white background

### ISSUE THREAD

**Issue by mwoz123** [hovancik/stretchly#769]
### Prerequisites

- [X] I'm using latest version: git latest
- [X] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [X] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

Add contrast color theme - black text on white background - white background would be clearly visible also for E-ink monitors like Dasung.

Operating system: all

**Comment by mwoz123** [comment]
could be simple as: 

> <input type="radio" value="#fffff" name="mainColor" **_data-font-color=_**"#000000" id="blackOnWhite">

**Comment by hovancik** [comment]
Thanks :) I like that. I am superbusy with life right now but I think I would probably add new theme. WIll need some work on theme html and css
