### ISSUE TITLE
[bug] Object destroyed at Timeout.finishMicroBreak

### ISSUE THREAD

**Issue by sxmanton** [hovancik/stretchly#77]
Hi, I encountered this error a couple times. Seems like it may be related to https://github.com/hovancik/stretchly/issues/68 due to same stack trace.

I am unsure of what the trigger may have been, I do not remember if I was doing any specific action before the break window appeared that would trigger it. For what it's worth I don't think I was drag and dropping at the time, but I'm not totally sure. I will try to pay more attention and reproduce it if I can.

I encountered it only when running in development (i.e. npm start), so far have not encountered it in the production release, but I also have only just started using the app.

![image](https://cloud.githubusercontent.com/assets/4335536/24838810/34a7ddc8-1d1d-11e7-92ba-102b95b1fee2.png)

**Comment by hovancik** [comment]
Thanks. Seems that I can reproduce it by doing "Cmd/ctrl+R" when in break window. Which probably causes the part of code that counts how much time is left to init twice. I'll find time to debug that.
