### ISSUE TITLE
Github sponsorship detection requires public sponsorship

### ISSUE THREAD

**Issue by bharrisau** [hovancik/stretchly#770]
### Prerequisites

- [X] I'm using latest version: v1.3.0
- [X] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [X] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

When sponsoring, the app is unable to detect the sponsorship if 'Private' is selected. Changing to 'Everyone' and restarting the app detects the sponsorship. Would suggest adding this to the README, I got stuck on it for a while.

**Comment by hovancik** [comment]
Hi @bharrisau and thanks for the report. Github API actually allows me to also get private ones with `includePrivate`so I'll do that

**Comment by hovancik** [comment]
Should work now :)
