### ISSUE TITLE
[Request]Show Countdown Timer Option

### ISSUE THREAD

**Issue by acaccia73** [hovancik/stretchly#771]
Hi, great job guys! Would it be possible to have an option that displays how long it is until the next break or mini break? Now this information is available if you go to the tray icon with the mouse, but it would be handy if there was a countdown that indicates the time left, always visible.

**Comment by hovancik** [comment]
Hi, plan is to add it to icon itself. I won't be time, but it will be function of time left. Feel free to subscribe there to watch progress. 

https://github.com/hovancik/stretchly/issues/717
