### ISSUE TITLE
DND resets break timers

### ISSUE THREAD

**Issue by BenediktAllendorf** [hovancik/stretchly#772]
### Prerequisites

- [x] I'm using latest version: v1.3.0 
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

If the DND modus is activated once, all timers are reset. (When the "breaks in DND" setting is not activated).

Operating system: Windows 10 (20H2)

### Steps to Reproduce

1. Have your timer run a bit
2. Start the DND (in my case, by watching fullscreen YouTube for a few seconds)
3. Turn off DND

**Expected behavior:** 
After DND is turned off again, I'd expect the timer(s) to continue where they were left. Maybe even have them keep running while in DND and force a break instantly after turning it off (if the timer is expired while in DND).

**Actual behavior:**
When DND is deactivated, all timers are reset.

**Reproduces how often:**
Every time

### Additional Information
I'm not sure if this is intended, but it's not what I'd expect. I like the option to not be disturbed while in fullscreen but I'd also like to keep the timer(s) running.

**Comment by hovancik** [comment]
Hi @BenediktAllendorf, yeah, that is intended. When DND is turned on, I simply pause Stretchly and then Resume it when DND is off. 

There is only one Pause which clears all timers and I use it for DND, Idle time etc...

This could be changed but then, when I have for example 10 hours DND during night, I would expect it reset timers in the morning.

**Comment by BenediktAllendorf** [comment]
That case should be covered by the "Monitor system idle time", which resets the timer (regardless of DND)?

**Comment by hovancik** [comment]
closing in favor of #1248

**Comment by neilmenon** [comment]
I had a similar issue where taking a screenshot with ShareX reset the break. Unticking `Show breaks even in Do Not Disturb mode` (`monitorDnd = false`) resolved the issue.
