### ISSUE TITLE
Feature request: Button to convert long break to mini break

### ISSUE THREAD

**Issue by edemaine** [hovancik/stretchly#775]
### Prerequisites

- [x] I'm using latest version: v1.3.0
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

I frequently find myself not always having time to take a Long Break, but still wanting to take a Mini Break according to my schedule.  Currently, when such a long break occurs, I count out the 20 seconds of a Mini Break and then click postpone/skip Long Break.

It would be nice to have an alternative option/button "convert to mini break" so that I don't have to count it out manually, and then resetting the long break timer. ~~Alternatively, this option could appear automatically when enough time has elapsed...~~ I see that "skip" (which is the equivalent of having converted to a mini break) already appears after the appropriate time has elapsed.

Operating system: Windows 10

**Comment by hovancik** [comment]
Hi @edemaine , you can do this now from tray menu by doing "Skip to next". Alternatively, Stretchly now also has a sort of command line interface (`stretchly help`), if you find yourself on command line :) 

I prefer not to add any new buttons to break screen, reasoning being that over years people requested many buttons there, so if I would do that, there would be bunch of them and it would not be nice :)

**Comment by edemaine** [comment]
Sounds good. Thanks for considering!

One more idea: I suspect that the switch from delay to skip button is a fixed percentage of the break. Could we make that percentage configurable?

I didn't know about the CLI - I'll give it a try! I've often wanted to delay breaks for a specific amount of time (like 30 or 90 minutes, e.g. duration of a class) so maybe that will fix that for me!

**Comment by hovancik** [comment]
Hi @edemaine , yes it is configurable, you can also set how many times you want to allow to skip :) https://github.com/hovancik/stretchly#editing-postpone-functionality-

also see this, in future I will add global shortcuts #791
