### ISSUE TITLE
"automatically notify on app updates" doesn't seem to prevent notifications

### ISSUE THREAD

**Issue by Draknek** [hovancik/stretchly#777]
### Prerequisites

- [ N ] I'm using latest version: running v 1.2.0, latest 1.3.0
- [ Y ] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [ Y ] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

I have the option "automatically notify on app updates" unchecked, but I still get notifications when there is an update available.

Due to the nature of the issue I can't test it on the latest version. I have seen it on previous versions also.

Operating system: Windows 10 Home version 2004

### Steps to Reproduce

1. Leave stretchly running long enough that it checks if an update is available

**Expected behavior:**
If "automatically notify on app updates" is unchecked, no notification that an update is available

**Actual behavior:**
If "automatically notify on app updates" is unchecked, a notification that an update is available appears

**Reproduces how often:**
Once a day or so

**Comment by hovancik** [comment]
Thanks for the report, I'll try to reproduce! 

To be sure, by notification you mean system notification or in Stretchly?

**Comment by Draknek** [comment]
It's a system notification. I can get a screenshot the next time it happens if that would be useful to confirm?

Now that I think about it, I could probably resolve the problem by disabling notifications from Stretchly at the system level

**Comment by Draknek** [comment]
Screenshot of notification:
![image](https://user-images.githubusercontent.com/184057/101229871-40812100-369a-11eb-948c-6c2c7184163a.png)

Screenshot of Stretchly settings: 
![image](https://user-images.githubusercontent.com/184057/101229884-5c84c280-369a-11eb-9729-0089b84e020f.png)

**Comment by hovancik** [comment]
That's really strange. Can't reproduce. 

How I tested: 

When stretchly starts, I notify right away that new version is out. So I installed 1.2 and when I started it, it sent notification right away. I went to settings and disabled the notification. When I restarted the app there was no notification on start. 

Let me check the code, maybe the issue is that somehow settings are badly communicated if app is not restarted. 

Can you check if you get notification if you restart the app?

**Comment by hovancik** [comment]
Ou yeah so there is some error :) Will try to fix it :)
