### ISSUE TITLE
Feature request: Add "Reset Breaks" global hotkey

### ISSUE THREAD

**Issue by Alexsey** [hovancik/stretchly#778]
### Prerequisites

- [x] I'm using latest version: v 1.3.0
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

Operating system: Windows 10 

Every time I'm getting back to the computer if I was not using my smartphone I prefer to reset breaks. It would be really nice if this could be done without using a mouse. It would be even better if the hotkey would be configurable the same way as skip hotkey - through `config.json`

Thank you :)

**Comment by hovancik** [comment]
Yeah, I was thinking about adding shortcuts for more actions :) 

Do you have some defaults in mind? It's hard to grab some good one with globals, as there are many programs. I guess we would need some 3-parts shortcut.

**Comment by Alexsey** [comment]
Considering the fact that it should be accessible not only during break like Ctrl+X, I think it should be some thing non-conflicting, like Ctrl+F11/Cmd+F11... but I'm not the best person to advise - I'll remap it anyway because on Windows I'm always organizing my global shortcuts around Win-key and on Mac around Ctrl. This works perfectly on Windows, quite well on Mac, but I don't think it's some common practice

**Comment by hovancik** [comment]
Reset breaks is available from Tray menu as well, so I think should be global one.

**Comment by hovancik** [comment]
maybe `ctrl/cmd+\+r` for reset 
`+p` for pause 

I think I need to make a list of all places that could use a shortcut and then think of them all

**Comment by hovancik** [comment]
closing in favor of #791
