### ISSUE TITLE
 Feature request: Add Pause/Resume Breaks global hotkey

### ISSUE THREAD

**Issue by Alexsey** [hovancik/stretchly#779]
- [x] I'm using latest version: v 1.3.0 
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

Operating system: Windows 10

At least a few times a day I would like to turn the **Stretchly** off for some time, for example when I know I'm going to get from the computer soon or when I'm showing something on the computer to someone else. It would be much more comfortable to turn breaks on/off with just a keyboard shortcut without a need to get to the mouse. Been able to configure the shortcut in `config.json` the same way it's now implemented for skip break would be even better

Thank you!

**Comment by hovancik** [comment]
closing in favor of #791
