### ISSUE TITLE
restore previous application focus after break

### ISSUE THREAD

**Issue by mstorus** [hovancik/stretchly#78]
After a break or microbreak is over, I would like focus to be restored to the previously active application.
Currently, for example, if I have Chrome open and then a microbreak begins, when the microbreak is over (or I press Ctrl-x), focus is not automatically restored to Chrome. I have to click on the Chrome window or use the Mac application switcher to restore focus to Chrome. (the quickest way I've found to do that is to press `Cmd-Tab` then `Cmd-Shift-Tab`)

Details:
- stretchly 0.8.0
- Mac OS 10.12.3 Sierra

Thanks for making this app, I'm enjoying it!

**Comment by hovancik** [comment]
This might be OS specific thing, not solvable with electron, but I will try to find solution. 

I've just added `Menu.sendActionToFirstResponder('hide:');`in my code that seems to help, but I will need to test it more.
