### ISSUE TITLE
Feature Request: Sit/Stand Desk Prompts

### ISSUE THREAD

**Issue by stantond** [hovancik/stretchly#784]
As a sit-stand desk user, I want to be reminded to switch to standing mode, so that I don't end up sitting down all day, and I wanted to be reminded to sit back down, so that I don't stand for too long.

Prompt to stand up, possibly during an existing break/schedule, and prompt to sit down (timed based on current industry/medical recommendations)

**Comment by hovancik** [comment]
Hi @stantond , few similar requests have been made in past: remind to drink water every x hours, etc..  

As I try to make Stretchly simple, I am reluctant to add those as it would complicate code and there are reminder/timers apps where user can set regular intervals that can do that better than Stretchly.

**Comment by stantond** [comment]
I'm not sure it makes sense to compare the two, depends on what problem you're trying to solve with this app...

If it's something like "As someone who works at my desk all day, I want to be reminded to move around, so that I don't develop health issues", then sure, drinking water is good, but it's got nothing to do with what your app is trying to solve, whereas the purpose of a sit-stand desk is to help solve exactly the same problem that you're also trying to solve.

Looking at some commercial offerings like RSI Guard, support for sit-stand is a fairly common feature used in tandem with rest breaks, ideally using a break to do the height adjustment.

**Comment by hovancik** [comment]
Hey, I've hacked around this week and created https://github.com/hovancik/later-on which allows custom notifications. It's very alpha but might be also what you're looking for.
