### ISSUE TITLE
64-bit ARM on Linux

### ISSUE THREAD

**Issue by jwillikers** [hovancik/stretchly#785]
### Prerequisites

- [X] I'm using latest version: v1.3.0
- [X] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [X] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

I'm using a [Pinebook Pro](https://www.pine64.org/pinebook-pro/) ARM Linux laptop and would love to be able to use Stretchly on it, but would have to build from source because packages are not available for this combination architecture and operating system.

Operating system: Linux - Debian-based [Armbian](https://www.armbian.com/), 64-bit ARM

### Additional Information

A *deb* package would suffice, but I'd really like to be able to install directly as a *snap* package because then I'll receive updates automatically.

By the way, I really appreciate being able to install Stretchly as snap on my x86_64 machines. Thanks!

**Comment by hovancik** [comment]
I'll have to check if electron-builder supports it :)

**Comment by jwillikers** [comment]
I can build Stretchly locally on my Pinebook Pro and run it without issue, so that's good.

I'm not sure about the cross-compilation support in electron-builder for arm64. Using `--arm64` with it built the Stretchly snap with `arm64` in its name, but attempting to install that on my Pinebook Pro says it will only work for the amd64 architecture.
You might have to use an arm64 machine to generate the snap.
I found a great article on using electron-builder to build apps locally for armv7 and arm64 [here](https://www.beekeeperstudio.io/blog/electron-apps-for-arm-and-raspberry-pi).

**Comment by hovancik** [comment]
can you try? just trying building on some CI, built on amd64 so not sure if it will work fine

https://ufile.io/x28m7c3m

**Comment by jwillikers** [comment]
When I run it, it opens just fine with the welcome screen showing properly, but a pop-up says an error has occurred while running stretchly and then it crashes. L've pasted the terminal output below and was using the arm64 package.

```sh
jordan@pinebook-pro:~/Downloads$ stretchly 
17:49:56.239 › Stretchly: loading settings
17:49:56.272 › Stretchly: starting Idle time monitoring
17:49:56.274 › Stretchly: starting DND monitoring
(node:6889) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
(node:6889) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
17:49:57.314 › Error: /tmp/.org.chromium.Chromium.NyHfa5: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12710)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at bindings (/opt/Stretchly/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/opt/Stretchly/resources/app.asar/node_modules/macos-notification-state/lib/index.js:1:34)
17:49:58.281 › Error: /tmp/.org.chromium.Chromium.NyHfa5: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12710)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at bindings (/opt/Stretchly/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/opt/Stretchly/resources/app.asar/node_modules/macos-notification-state/lib/index.js:1:34)
17:49:59.295 › Error: /tmp/.org.chromium.Chromium.NyHfa5: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12710)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at bindings (/opt/Stretchly/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/opt/Stretchly/resources/app.asar/node_modules/macos-notification-state/lib/index.js:1:34)

```

**Comment by hovancik** [comment]
Try 2: https://ufile.io/jt9t5oml

there's a lot of issues related to arm in electron-builder, looks like mostly it doesn't work....

**Comment by jwillikers** [comment]
That's unfortunate, but I'm sure they'll get it figured out in time.

I get the following error attempting to install the latest version:

```sh
jordan@pinebook-pro:~/Downloads$ sudo gdebi ./Stretchly_1.3.99_arm64.deb 
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Traceback (most recent call last):
  File "/usr/bin/gdebi", line 86, in <module>
    if not debi.open(args[0]):
  File "/usr/share/gdebi/GDebi/GDebiCli.py", line 73, in open
    self._deb = DebPackage(file, self._cache)
  File "/usr/share/gdebi/GDebi/DebPackage.py", line 31, in __init__
    super(DebPackage, self).__init__(cache=cache, filename=filename)
  File "/usr/lib/python3/dist-packages/apt/debfile.py", line 77, in __init__
    self.open(filename)
  File "/usr/lib/python3/dist-packages/apt/debfile.py", line 88, in open
    control = self._debfile.control.extractdata("control")
LookupError: There is no member named 'control'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_share_gdebi_gdebi.0.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/gdebi", line 86, in <module>
    if not debi.open(args[0]):
  File "/usr/share/gdebi/GDebi/GDebiCli.py", line 73, in open
    self._deb = DebPackage(file, self._cache)
  File "/usr/share/gdebi/GDebi/DebPackage.py", line 31, in __init__
    super(DebPackage, self).__init__(cache=cache, filename=filename)
  File "/usr/lib/python3/dist-packages/apt/debfile.py", line 77, in __init__
    self.open(filename)
  File "/usr/lib/python3/dist-packages/apt/debfile.py", line 88, in open
    control = self._debfile.control.extractdata("control")
LookupError: There is no member named 'control'
```

Perhaps the Debian control file is missing?

**Comment by hovancik** [comment]
Well, I am not at all familiar with that ;/ I am pretty much setting `electron-builder` to build `deb` and hope for best.

does `sudo dpkg -i package.deb` returns the same error?

**Comment by jwillikers** [comment]
Attempting to install the package directly with `dpkg` generates the following error:

```sh
jordan@pinebook-pro:~/Downloads$ sudo dpkg -i Stretchly_1.3.99_arm64.deb 
[sudo] password for jordan: 
tar: Archive is compressed. Use -J option
tar: Error is not recoverable: exiting now
dpkg-deb: error: tar subprocess returned error exit status 2
dpkg: error processing archive Stretchly_1.3.99_arm64.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 Stretchly_1.3.99_arm64.deb
```

No worries if you want wait on this to get fixed upstream. 🙃

**Comment by jwillikers** [comment]
The `tar` error looks like it stems from issue jordansissel/fpm#1611 in FPM.

**Comment by hovancik** [comment]
I am installing fpm from local ruby as workaround for something I don't even remember, let me try if I can use version they say in issue. Currently I have fpm-1.11.0

**Comment by hovancik** [comment]
Let's try this: https://ufile.io/f96lwq5x

**Comment by jwillikers** [comment]
Works! Installs and runs without any issues!

**Comment by jwillikers** [comment]
@hovancik Awesome! Thanks for all the hard work on this! I noticed that [Stretchly in the Snap Store store](https://snapcraft.io/stretchly) only has an `amd64` version available. Will an `arm64` version be available there eventually? Just checking. I'm very excited to have Stretchly available on my laptop!

**Comment by hovancik** [comment]
Yep, I tried to build arm as well but I did not manage that as dependencies could not be installed in docker that I use for building, will have to try something else.

**Comment by hovancik** [comment]
Can you try this?  https://ufile.io/2e9w8vmj

**Comment by jwillikers** [comment]
No issues installing, but when running it the following error crops up:

```sh
$ snap run stretchly 
/usr/lib/snapd/snap-exec: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/lib/snapd/snap-exec)
```

**Comment by hovancik** [comment]
Do you have libc installed? I have found similar issue where someone could not open Chromium on manjaro: https://forum.manjaro.org/t/chromium-wont-open-says-glibc-2-32-not-found/23603

**Comment by hovancik** [comment]
Looks like issue with Snap: https://github.com/Kong/insomnia/issues/1622

**Comment by jwillikers** [comment]
I thought it might be a Manjaro issue, but it looks like the same issue occurs on Armbian, too.

```sh
$ snap run stretchly
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/snap/stretchly/x1/app/stretchly: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.30' not found (required by /snap/stretchly/x1/usr/lib/aarch64-linux-gnu/libnspr4.so)
```

**Comment by jwillikers** [comment]
On Armbian, I appear to have GLIBC 2.31.

```sh
$ ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.1) 2.31
```

**Comment by hovancik** [comment]
looks like issue with `electron-builder` maybe? https://github.com/electron-userland/electron-builder/issues/5452

**Comment by hovancik** [comment]
Interestingly these people have similar issue and say it's because of using 18.04 to build: https://github.com/AppImage/AppImageKit/issues/1078  

I am using `adferrand/snapcraft:arm64v8-stable` docker image, which uses ubuntu focal, if I understand this https://hub.docker.com/r/adferrand/snapcraft/dockerfile

Armbian is Debian, right?

**Comment by jwillikers** [comment]
You can choose to use either Debian or Ubuntu for Armbian.
I use the Ubuntu 20.04 build that Armbian produces.
Armbian provides its own kernel with specialized support to run on the Pinebook Pro, but otherwise it appears to use the Ubuntu repositories and Ubuntu's GLIBC in this case.

I'm pretty familiar with AppImages and know that they are supposed to be forwards-compatible for GLIBC.
They use the system's GLIBC.
Flatpaks and Snaps should use a bundled version of GLIBC since they virtualize their own version of Linux which should have that.
Could it be that since you use core18 you need to use an 18.04 Docker image as mentioned [here](https://forum.snapcraft.io/t/the-glibc-version-of-the-targeted-core-is-2-2x-a-newer-libc-will-be-required-for-the-following-files/9396/2)?

**Comment by hovancik** [comment]
Well, electron-builder seems to use core18. I've tried different docker images but getting another errors ;/

**Comment by jwillikers** [comment]
Thanks for looking into it! I think we can just track the upstream issue you found, electron-userland/electron-builder#5452, and perhaps try again when all the kinks have been worked out.
