### ISSUE TITLE
Non-responsive after graphics driver upgrade

### ISSUE THREAD

**Issue by Quitch** [hovancik/stretchly#792]
### Prerequisites

- [X] I'm using latest version: v1.3.0
- [X] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [X] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

After a graphics driver upgrade, breaks no longer trigger and the Stretchly icon no longer responds. The processes must be manually terminated and then Stretchly loaded again.

Operating system: Windows 10 x64 Pro 20H2

### Steps to Reproduce

1. Trigger in-place graphics upgrade

**Expected behavior:** Stretchly will continue to operate following the upgrade

**Actual behavior:** Breaks no longer occur and the notification area icon is non-responsive

**Reproduces how often:** 100%

### Additional Information

This has been happen for a long time, maybe as long as I've been using the app.

I perform all in-place upgrades via Geforce Experience.

I am using an Nvidia Geforce GTX 980 Ti

**Comment by hovancik** [comment]
Oh wow, to be honest I don't even know how to approach this. I don't own a Windows machine. Anyway, best hope would be to try upgrading electron (what I use under the hood) and hope it will help. There are bunch of issues when I search on Nvidia on electron https://github.com/electron/electron/search?o=desc&q=Nvidia&s=created&type=issues

I plan to try to upgrade electron before making new release.

**Comment by hovancik** [comment]
Can you try the new version?

**Comment by Quitch** [comment]
I'll let you know once I get a video driver restart. Following a couple of crashes, I should note this isn't related to the graphics driver upgrade per se, but rather to whatever mechanism Windows is using to restart it. The same issue occurs Windows has to restart the display driver following a crash.

**Comment by hovancik** [comment]
Hi @Quitch, is this is an issue with the latest Stretchly?

**Comment by Quitch** [comment]
I don't recall it *not* being an issue, but couldn't definitively say.

**Comment by hovancik** [comment]
Hi @Quitch , I know it's been a long time, did anything change meanwhile?

**Comment by Quitch** [comment]
I'm afraid I haven't run Stretchly in a while, so couldn't speak to this.

**Comment by hovancik** [comment]
No worries, I'll close this then :)
