### ISSUE TITLE
Natural breaks don't work on MacOS under some circumstances

### ISSUE THREAD

**Issue by cmavr8** [hovancik/stretchly#795]
### Prerequisites

- [X] I'm using latest version: v 1.3.0
- [X] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [X] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

Natural breaks don't seem to reset the timers.
Operating system: MacOS Catalina 10.15.7

### Steps to Reproduce

1. Start the app
2. Use the computer until e.g. 8 minutes before a break is due (e.g. 12' if you have set mini breaks to 20')
3. Stop using the computer. Take a break around 6 minutes
4. Come back to work on the computer

**Expected behavior:** All timers have reset, and I can work uninterrupted for the max time configured between breaks (20' in this case).

**Actual behavior:** After 2 minutes I am asked to do another break.

**Reproduces how often:** 100%

### Additional Information

The times given above are just an example.
Trying to fix this, I have manually given the app "control my computer" rights in the security & privacy > accessibility settings. Similar apps require this to make natural breaks work so I figured I'd try. Didn't help.

I've also trimmed the param for natural break trigger down to 3' but it doesn't help.:
```bash
~ grep -i natural "/Users/user/Library/Application Support/Stretchly/config.json"
    "naturalBreaks": true,
    "naturalBreaksInactivityResetTime": 200000,
            "data": "Expose your eyes to natural light.",
```

(PS offtopic: Thanks for making this app! It'd be awesome, if I can just make the natural breaks work)

**Comment by hovancik** [comment]
Hi and thanks for the report. Could you please paste the log file here, we should see from here what's happening. You can go to About, hit `Cmd+D` and you will see the location of file. 

By default, system needs to be idle for more then 5 minutes to then reset on user's return. You can change it in config file: `naturalBreaksInactivityResetTime`

Sometimes Idle detection is not perfect, ie when you run VLC it is never Idle and such, so could be also that.

**Comment by cmavr8** [comment]
I've lowered the `naturalBreaksInactivityResetTime` but it doesn't help.
Your hint on VLC was good. Shutting down spotify and a screensaver inhibitor fixes the issue.
I'll test a bit more and share conclusions and/or logs. Thanks!

**Comment by cmavr8** [comment]
Ok, so it's my screensaver inhibitor.
Stretchly uses the lock to pause breaks:
```
[2020-12-08 16:50:21.819] [info] System: suspend or lock
[2020-12-08 16:50:21.819] [info] Stretchly: pausing breaks for 1
[2020-12-08 17:01:09.711] [info] System: resume or unlock
[2020-12-08 17:01:09.712] [info] Stretchly: resuming breaks
```

Is there any way to use mouse and keyboard (non) input to pause breaks? 
With work from home this year, working in a physically secure environment, it's handy to not lock the screen constantly.

**Comment by hovancik** [comment]
What do you mean by mouse and keyboard (non) input to pause breaks? 

I am using this to check for idle time: https://www.electronjs.org/docs/api/power-monitor#powermonitorgetsystemidletime

**Comment by cmavr8** [comment]
By mouse and keyboard, I mean this:

* As a user, a few seconds after I stop moving the mouse and press any keys, I want to be considered idle. I am not using the computer anymore, so I would not like stretchly to be counting this as time used. On top of that, if such lack of input is as long as a break would be, I would like it to count as a natural break. During all this, my screen might be locked, or not (if I have a very long lock time or I have inhibited it altogether). It shouldn't matter.
* The current stretchly setup seems to rely on the locked/unlocked state of the computer to determine idleness. 
* Looking at electron's powerMonitor, it is implied that they do it the way I explain in the first bullet above, so it should be working fine :neutral_face:. But it doesn't. The powerMonitor description implies that idle and locked are not related, but it's not very clear. It could be that powerMonitor always considers the system `active` while a screensaver inhibitor is on.

One way around this would be to try using something else to get idle time, like https://github.com/bithavoc/node-desktop-idle but chances are it will yield similar results. Too much of a hassle to try, I suppose.

Any thoughts?

**Comment by hovancik** [comment]
Yeah so with Stretchly I do different things: 
- when system goes lock or suspend, I pause breaks
- when we unlock or resume system, I resume breaks

And also I check the idle time (whatever that means for Electron) and when it is longer then specified value, I also pause breaks and resume them when idle time is over. 

BUT, the thing with electron is, that it is simply put not very well supported and works differently on different OSes (and each platform has its quirks).

For example, for me, on Linux, all seems fine: I have a threshold set to 2 minutes, and after 2 minutes of inactivity I can see that icon has gone to "paused".  

If we could replicate your issue with https://github.com/electron/electron-quick-start, we could create issue on Electron repo. We could also try with package you recommend whether there is any difference. I am not sure if there would be any difference, because those libraries usually use some OS-level function. But might be worth trying.

**Comment by cmavr8** [comment]
Right, let's focus on whether this is an Electron bug. How would I test this with the quick-start? We'd need some code in main.js to read and print idle time, right? 

Sorry I don't have the time right now to figure this out (I'm not familiar with Electron at all). If you would prep something I could test it.

**Comment by hovancik** [comment]
Clone the repo and replace the `main.js` with
```
// Modules to control application life and create native browser window
const {app, BrowserWindow, powerMonitor} = require('electron')
const path = require('path')

function createWindow () {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js')
    }
  })

  // and load the index.html of the app.
  mainWindow.loadFile('index.html')

  // Open the DevTools.
  // mainWindow.webContents.openDevTools()
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(() => {
  createWindow()

  app.on('activate', function () {
    // On macOS it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') app.quit()
})

setInterval(() => { console.log(powerMonitor.getSystemIdleTime()) }, 5000)

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and require them here.

```
then you can `npm i` to install deps and `npm start` to run it

I've just made a small edit to print idle time to console every 5 seconds.

**Comment by cmavr8** [comment]
Despite your super-easy instructions, I failed to spend time on this until today. Sorry!

Anyway, it seems that lockscreen inhibitor _caffeine_ is indeed tricking electron into thinking that the device is still in use.

Here's the output of this test app with caffeine disabled (new lines replaced by comma & space):
> 0, 2, 7, 12, 17, 22, 27, 32

And here it is with caffeine enabled, while the user is not touching any inputs:
> 0, 3, 3, 8, 3, 8, 3, 8, 3, 8, 3, 8

If I make the app print every second, I see that the "timer" is reset every 10 seconds. So I guess that's how caffeine tricks MacOS into thinking there's user movement; one fabricated user input every 10 seconds.

Would that be an electron bug or a feature request for caffeine devs (to use some other method, or allow configurable fake-input time, so that a user can configure it just below lockscreen timeout)?

**Comment by hovancik** [comment]
That would be question for caffeine developers. But it looks to me that here we come to impossible scenario: trying to not to have inactivity for one reason but have it for another :)

**Comment by cmavr8** [comment]
Yeah, I think we can close this and I'll try to figure it out with the caffeine project.

I don't think it's impossible. The issue is caused by caffeine simulating activity instead of reconfiguring macos lockacreen settings to not trigger. If caffeine did the latter, stretchly would work fine. 

I've experienced this in ubuntu a few years back. Caffeine and workrave worked fine. Probably ubuntu offers easier access to system settings APIs than Macos :/

Thank you for the help all along! I think it's time to close this as it's not a stretchly bug.
