### ISSUE TITLE
Full screen breaks make Google Chrome unresponsive

### ISSUE THREAD

**Issue by KarlBishop** [hovancik/stretchly#800]
### Prerequisites

- [x] I'm using latest version: v1.3.0 
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

When returning to Google Chrome from a full screen break, the browser is unresponsive (can't scroll, click or continue typing).

Operating system: Windows 10 

### Steps to Reproduce

1. Set Stretchly to full screen mode
2. Use Google Chrome until a screen break occurs
3. After screen break finishes, try interacting with website you were browsing

**Expected behavior:** All apps are responsive after Stretchly relinquishes control of the screen.

**Actual behavior:** Chrome is unresponsive after Stretchly relinquishes control of the screen.

**Reproduces how often:** 100%

### Additional Details

If I transfer focus between applications - or Google Chrome instances - the browser becomes responsive again. For example, I can do this by alt-tabbing away and back again or briefly moving the mouse over a different window on the taskbar. The browser will then "catch up" with any scrolling/clicking/typing I did while it was unresponsive.

**Comment by hovancik** [comment]
I think this might be the same issue as #783. It should be fixed in next version.

**Comment by hovancik** [comment]
Can you try the new version?

**Comment by hovancik** [comment]
closing in favor of mentioned story

**Comment by KarlBishop** [comment]
Sorry, took me a while to get back to this - I'll add my followup on #783
