### ISSUE TITLE
Feature Request: Pause breaks when certain apps are in the foreground

### ISSUE THREAD

**Issue by jkleint** [hovancik/stretchly#801]
Great piece of software!  

I'm thinking of using Strechly with Zoom / conferencing software, especially when screen sharing.  It's annoying and embarrassing to have a break pop up when other people are watching your screen or you are trying to communicate.  It would be nice if you could set a list of application / processes for which, when they are in the foreground, breaks do not pop up.  (You probably still want the timers to keep running, so you get a popup when you close the app.)

Thanks!

**Comment by hovancik** [comment]
please follow here for updates: #389
