### ISSUE TITLE
How to customize the messages?

### ISSUE THREAD

**Issue by fspade** [hovancik/stretchly#806]
### Prerequisites

- [x] I'm using latest version: 1.30 
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

I like to customize the app and add my own tasks with individual messages and times.

Operating system: Windows 10 Pro 

### Steps to Reproduce

1. Run Stretchly
2. Look around where to customize it.
3. Come here and ask.
4. Hope for open ears and hearts.

**Expected behavior:** Present my own tasks.

**Actual behavior:** Somebody else made it up and they are repeated add infinitum.

**Reproduces how often:** Every time.

### Additional Information

This should be enough to present my wish. Thanks for listening.

**Comment by hovancik** [comment]
Hi @fspade 

look here: https://github.com/hovancik/stretchly#advanced-preferences and https://github.com/hovancik/stretchly#editing-break-ideas
