### ISSUE TITLE
Hide dock icon on MacOS 

### ISSUE THREAD

**Issue by HelperInCa** [hovancik/stretchly#807]
### Prerequisites

- [ ] I'm using latest version: v  v0.21
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

[Description of the issue]
Why cannot the dock icon be hidden from V1.0? I love this tool for my health but I seldom open it from the dock. So Why  has this feature been removed? 

Operating system: 
MacOS 10.15
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by hovancik** [comment]
Hi @HelperInCa, you are using some pretty old version :) v0.21

Latest version is 1.3 and it should now have dock icon.
