### ISSUE TITLE
Suggest better translation

### ISSUE THREAD

**Issue by x4base** [hovancik/stretchly#809]
Hi, I made some improvement in the translation in Traditional Chinese and created a commit here: https://github.com/x4base/stretchly .

In the meantime, I modified the translations on Weblate too. Which is the preferred way? How can I make my modification on Weblate applied? Or should I just create a pull request for my commit now?

Thanks

### Prerequisites

- [ v ] I'm using latest version: v 1.3.0
- [ v ] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [ v ] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

[Description of the issue]

Operating system: 

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by hovancik** [comment]
Hi @x4base , right now, Weblate is preferred. There are manual steps for me to make Weblate changes appear in Github. I'll be doing them on regular bases.

**Comment by hovancik** [comment]
Ah, but if you already made changes in GH, feel free to create a PR :)
