### ISSUE TITLE
Stretchly on Big Sur is paused due to DND even though DND is off

### ISSUE THREAD

**Issue by pelletencate** [hovancik/stretchly#810]
### Prerequisites

- [x] I'm using latest version: v1.3.0
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

[Description of the issue]

Operating system: macOS 11.0.1

### Steps to Reproduce

1. Make sure DND is switched off
2. Install and run Stretchly
3. Look at the tray icon

**Expected behavior:** [What you expect to happen]

It runs normally

**Actual behavior:** [What actually happens]

Breaks are paused due to DND being active

**Reproduces how often:** Deterministically (on my system)

### Additional Information

Tried:
* Toggling DND, had no effect on Stretchly's assessment
* Using CMM to uninstall and delete all preferences and related files, and reinstalling. Same issue.

**Comment by hovancik** [comment]
Hi there, will try to reproduce. Meanwhile you can disable DND check in preferences.

**Comment by hovancik** [comment]
Looks like library used in 1.3 do not support newest macOS: https://github.com/felixrieseberg/macos-notification-state/issues/11

I did update few days ago in #805 so all should be fine with new release.
