### ISSUE TITLE
ubuntu-appindicators log spamming

### ISSUE THREAD

**Issue by Thomi7** [hovancik/stretchly#812]
### Prerequisites

- [x] I'm using latest version: v1.3.0
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

I get these warnings in the systemd logs every 10 seconds:
`ubuntu-appindicators@ubuntu.com[2252]: Stretchly1, Impossible to lookup icon for 'Stretchly1_388-panel' in path /tmp/.org.chromium.Chromium.4u>
ubuntu-appindicators@ubuntu.com[2252]: unable to update icon for Stretchly1
ubuntu-appindicators@ubuntu.com[2252]: Stretchly1, Impossible to lookup icon for 'Stretchly1_389-panel' in path /tmp/.org.chromium.Chromium.xZ>
ubuntu-appindicators@ubuntu.com[2252]: unable to update icon for Stretchly1`

The icon index increments on every warning.

Operating system: Pop!_OS 20.10

### Steps to Reproduce

1. Install ubuntu-appindicator extension
2. Install stretchly over the .deb file 
3. Lookup the systemd logs (journalctl _UID=1000 -n 100)

**Expected behavior:** 
no warnings in the logs

**Actual behavior:** 
warnings every 10 seconds

**Reproduces how often:** 
every time

**Comment by hovancik** [comment]
What do you mean by icon index? Can you show the screenshot? I am not familiar with ubuntu-appindicators

**Comment by Thomi7** [comment]
By that I just meant that the index of e.g. Stretchly1_388-panel is incrementing. I thought that that would be the name of the tray icon file.

**Comment by sakralbar** [comment]
Some issue in ubuntu 20.04:
`ubuntu-appindicators@ubuntu.com[3088]: unable to update icon for Stretchly1
ubuntu-appindicators@ubuntu.com[3088]: Stretchly1, Impossible to lookup icon for 'Stretchly1_78-panel' in path /tmp/.org.chromium.Chromium.GBddZ2`

I've seen this on several previous versions of the app, and I had to manually clear the system log as it grew up to 8 gigabytes in size due to constantly writing to it.

**Comment by hovancik** [comment]
Looks like issue with appindicators. I am not familiar with it but it seems it was fixed few months ago, not sure if it was released

https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/236

**Comment by hovancik** [comment]
As this seems to be fixed in appindicator, I am closing this. If this persists, please check whether your version is up to date and report with them.
