### ISSUE TITLE
Feature Request: Remind me to stand up

### ISSUE THREAD

**Issue by Welldoor** [hovancik/stretchly#819]
### Prerequisites

- [x] I'm using latest version: v 
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description
1. People in our company getting moveable desks.
2. I read on a website, you should switch between working in sitting/standing situation every half an hour.
3. Add function to remind for sitting/standing change. Default could be half an hour. Should just be indicate to change position, since otherwise I guess it's very often the case, that you're in the "wrong" status for the app, apps says you should sit now but you already sit and visa verce.

This function was the feature we looked for in first place and I think this feature is very compatible to this app.

**Comment by hovancik** [comment]
There have been similar requests in past: remind to drink water, have timer for some exercise and so on. I agree that they are useful, but not what I am trying to do with Stretchly: I am showing break ideas but it's up to user to implement them. 

To cater for similar requests, I would have to implement system where user can create and setup custom timed reminders. That would be an app on itself, and my guess is that there are such a apps already, where you create custom reminders :)

**Comment by Welldoor** [comment]
Sure, it's up to you. But then I'm out here cause we won't use the app in company.

Thanks for fast reply!

**Comment by hovancik** [comment]
Hi, I don't mean that there are apps which can do both. I am saying that there are apps that are all about scheduling tasks.

And that's how it should be: different apps that do different things so that they can do them right. 
Quick google for example find this app for creating custom reminders: http://www.desktop-reminder.com/en/index.html

**Comment by hovancik** [comment]
Hey, I've also hacked around this week and created https://github.com/hovancik/later-on which allows custom notifications. It's very alpha but might be also what you're looking for.
