### ISSUE TITLE
[mac] Does not refocus active app after break

### ISSUE THREAD

**Issue by casmarrav** [hovancik/stretchly#82]
One of the most annoying factors for me at this time is when a break is over, the OS is in a state where stretchly is the active app, but no windows of it are open. This breaks a continuity in workflow for people who use mostly the keyboard (eg programmers).

**Comment by hovancik** [comment]
Hi, this is already fixed on master. Will try to release soon.

**Comment by casmarrav** [comment]
Awesome!
