### ISSUE TITLE
Unsigned Software - How to deal with that in a organisation?

### ISSUE THREAD

**Issue by Welldoor** [hovancik/stretchly#820]
### Prerequisites

- [x] I'm using latest version: v 
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

We're thinking about the use of this software in our company. Windows defender is complaning about unsigned Software. We don't want to deactivate this windows defender setting, thou it is useful in general.

Can you add in your documentation at https://github.com/hovancik/stretchly how to deal with this? Is there already a prefered way?

Operating system: Win10

### Steps to Reproduce

1. Download .zip/.7zp and start the exe.
2. Getting annoyed by windows defender,

**Comment by hovancik** [comment]
Hi @Welldoor , can you provide some documentation about what `unsigned` means? Do you get the same error when using installer? 

What I usually seen companies doing was as described here: https://github.com/hovancik/stretchly#windows

> You can install Stretchly for all users silently by running this as administrator: `installer.exe /S /allusers`.

**Comment by MiKr13** [comment]
Hi @hovancik please refer to this documentation on how to sign your application so that it is not flagged by Windows defender: https://interactiveknowledge.com/insights/how-code-sign-electron-app-windows

Basically, this shows that software can be trusted as it is signed by a trusted certificate.

**Comment by hovancik** [comment]
Thanks for the links. 

Considering there are no free certificates, I am building on CI and Stretchly is free, I am afraid this is the same as signing macOS apps: will not happen. 

Sorry for troubles.
