### ISSUE TITLE
Feature request: Whitelisting feature to only run when running certain productivity apps 

### ISSUE THREAD

**Issue by MiKr13** [hovancik/stretchly#823]
### Prerequisites

- [X] I'm using latest version: v 1.3.0
- [X] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [X] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

A whitelisting feature is required so that the app only works when certain productivity-related apps are open like VS Code etc.

Operating system: Windows 10 20H2

### Steps to Reproduce

1. Have VS Code open
2. Stretchly should run
3. VS Code or any other productivity apps marked by user closed, Stretchly gets paused

**Expected behavior:** Stretchly should pause on no productivity app running scenario

**Actual behavior:** Stretchly keeps running on no productivity app

**Comment by hovancik** [comment]
Thanks for the idea. Similar to #801 , but pretty much opposite.

**Comment by MiKr13** [comment]
@hovancik I am working on it using [find-process](https://www.npmjs.com/package/find-process). I am expecting to raise a PR by next month for this, currently am stuck in some other urgent requirements.

**Comment by hovancik** [comment]
Can we first talk about the User interface, if any? I am quite picky and we can save time by having deeper discussion before writing any code :) Might be worth thinking how to create some rule process where also #801 gets solved with this :) 

Anyway, might be easier to have this only available first via editing preferences file.

**Comment by decadent** [comment]
Now that Stretchly can be paused from the command line, this is much easier implemented with e.g. Hammerspoon (on Mac)—you can put any kind of custom logic in your HS configs, that will enable/disable Stretchly on all kinds of criteria.

I can share a simple HS config that pauses Stretchly when certains apps are focused.

**Comment by hovancik** [comment]
I've hacked around a PR with this function, feel free to try.
