### ISSUE TITLE
Issue: Away from computer does not count as away

### ISSUE THREAD

**Issue by immleo** [hovancik/stretchly#826]
### Prerequisites

- [X] I'm using latest version: v1.4.0
- [X] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [X] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description
Stretchly expected to count time as away when physically away from keyboard and mouse. Stretchly does not appear to count that time as away.
[Description of the issue]

Operating system: Win10 Home, V10.0.19041 Build 19041

### Steps to Reproduce

1. Run Stretchly
2. There is no secondstep

**Expected behavior:** [What you expect to happen]
When away from the computer, Stretchly counts that time as away

**Actual behavior:** [What actually happens]
Stretchly does not count the time away from the computer as away.
Away here means literally stepping away physically from the computer, no locking screen or screensaver.
Picture below reflects the timestamp when I was away from computer. However, it kept going and when I returned showed me the long break.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

### Debug information

You can find extra debugging information and location of Logs file on `Preferences` -> `About` page, after you hit `Cmd/Ctrl+D` shortcut.
![image](https://user-images.githubusercontent.com/640139/103241724-154cc300-4922-11eb-8b88-caefe9b19e60.png)

Please, review information provided there and paste relevant parts here.

**Comment by immleo** [comment]
[main.log](https://github.com/hovancik/stretchly/files/5749471/main.log)
Attached is the full log

**Comment by hovancik** [comment]
Hi @immleo and thanks for the report. 

I went through your log, and here is example where it worked fine, so it seems to work fine: 

```
[2020-12-26 21:07:58.504] [info] Stretchly: pausing breaks because of idle time
[2020-12-26 21:10:04.667] [info] Stretchly: resuming breaks after idle time
```

Few things to add here: 
- breaks are paused, by default, after 5 minutes of inactivity (you can change that value https://github.com/hovancik/stretchly#natural-breaks-inactivity-time-)
- idle monitoring is not perfect: I noticed that when some media players are active, there is never idle time

**Comment by immleo** [comment]
Ahh that makes sense!

I also think it might have also to do with using synergy which “may” be keeping my mouse active.

--
Leo

**Comment by hovancik** [comment]
I guess I can close this :) Let me know if anything else is needed
