### ISSUE TITLE
Request-password protect, prevent closing? Repeat...

### ISSUE THREAD

**Issue by itProfi** [hovancik/stretchly#835]
Hello, thanks for you program..I want ask you about this issue...https://github.com/hovancik/stretchly/issues/286
Is it possible? For child computer, not only sysadmin..

**Comment by hovancik** [comment]
Hi @itProfi , can you specify how do you imagine it would work? 

The issue, in general, is that Stretchly is regular app, thus user/child can easily close the app from Task manager or command line and such. 

I think approach would be to try to find some app that prevents child from closing specific app? I am not sure whether such a thing exists.
