### ISSUE TITLE
stretchly  can be stopped by shortcut keys

### ISSUE THREAD

**Issue by yuhlzu** [hovancik/stretchly#836]
1.4.0 

when stretchly is opened

windows
if shortcut: `Windows + L`  Lock screen，then unlock computer, stretchly is stopped，I can continue to use the computer.

mac
if shortcut: `ALT + TAB` ，I can continue to use the computer.

**Comment by hovancik** [comment]
Hi @yuhlzu and thanks for the report. Unfortunately Stretchly is regular app, so as you say there are different ways how user can close it,  i.e. from task manager and so on ;/ 

I haven't found a way how to prevent that
