### ISSUE TITLE
Notifications loop

### ISSUE THREAD

**Issue by rob-stewart** [hovancik/stretchly#840]
I'm reporting a problem with v1.3.0 related to the new version notification. It's possible v1.4.0 fixes this, but I wanted to report it in case that's not so. I won't know if the new version fixes the issue for quite some time because it happens infrequently.

Whenever the new version available notification appears coincident with the early warning notification for a long break, Stretchly gets into a loop. If I dismiss the notifications, by clicking the X, they reappear a moment later. If I ignore them, Stretchly shows new notifications once a second (untimed). (The sound plays and I think the existing notification is replaced by a new one, but I can't say with certainty that happens, since my goal is normally to just make it stop.) The only way I've learned to stop the loop is to Ctrl-X the break screen, then tell Stretchly to skip to the next long break.

Presumably, upgrading to the latest version when first prompted would mitigate the issue, but I can't always upgrade to the latest version immediately, and choose not to bother if the release notes cite changes that don't matter to me.

If I remember correctly, there was no other notification today for the new version, except the one that just happened at the time a long break was due this afternoon. Thus, the catalyst for this bug simply may be the new version notification, especially if that is only triggered at the time of a long break early warning.

Operating system: Windows 10 v1809.

**Comment by hovancik** [comment]
Thanks for the report! I'm running Linux and never noticed this, but I upgrade when there is new version right away, or run mostly development version. 

I've checked the code around notifications but don't see anything weird.

to be sure, ` long break early warning` you mean notification before break?

**Comment by hovancik** [comment]
Closing as no reply, let me know if this is still issue in latest version.
