### ISSUE TITLE
Feature: Minimal mode

### ISSUE THREAD

**Issue by WildOrangutan** [hovancik/stretchly#843]
**What**
Please implement an option, so that reminder shows in a small window, in a corner of the screen. Like a notification or something like that.

**Why**
I would like to obstruct less of screen estate, so I can finish my work before taking a break.

**How**
Example mockup: [image](https://user-images.githubusercontent.com/5972966/104359926-92765b80-5510-11eb-8e72-448a313bdd45.png)

**Version**
1.4.0

**Comment by MiKr13** [comment]
In works.

**Comment by hovancik** [comment]
Hi, right now, I don't plan to do that. Point of Stretchly is to "force" people to take a break. People often think that they are in flow and such, but research suggest that they would be better of by taking a break (as one of the Stretchly break ideas says). And let's be honest, if we would have small window for a break, we would just ignore it :) 

I would suggest to play with settings and figure out what timing is good for you... Looks like you need bigger interval for Breaks, or maybe disable Mini Breaks and have Long Breaks only. 

I hacked around https://github.com/hovancik/later-on which allows people to set reminders, maybe that would be better for you, but it's very alpha right now :)
