### ISSUE TITLE
Feature: Start break when ready

### ISSUE THREAD

**Issue by WildOrangutan** [hovancik/stretchly#844]
**What**
Option, that enables a button, so you can start a break when you're ready.

**Why**
I would like to finish my work, before I start the break. 
This probably makes more sense in combination with #843.

**How**
Example mockup: [image](https://user-images.githubusercontent.com/5972966/104361476-c9e60780-5512-11eb-94b9-091693474f88.png)

**Version**
1.4.0

**Comment by hovancik** [comment]
Hi, as I said in #843, I think you probably need to plat with Preferences and figure out how to customize to your liking. You can still cancel the break and then start it from Tray menu when you feel like having a break. There's also a command line interface that supports the same :)
