### ISSUE TITLE
donate in crypto

### ISSUE THREAD

**Issue by dzmitry-lahoda** [hovancik/stretchly#846]
if you will provide some (any) crypto donate button will donate equivalent of 21 USD.
if app will use 2x less resources  will donate USD 21 more (make it run of poor children laptops, right now it memory hog for such simple interface).

**Comment by hovancik** [comment]
Hi @dzmitry-lahoda , I have no coins yet :) Not even sure how would I put it into my taxes :) 

Is there some easy way how to allow for this? Never really looked into this...

**Comment by GirkovArpa** [comment]
@dzmitry-lahoda I've thrown together a quick foundation for a future Stretchly<sup>lite</sup> [here](https://github.com/GirkovArpa/stretchly-lite).  Maybe try it out and see how it performs on your laptop. 

It doesn't actually work yet, it's just the interface.
