### ISSUE TITLE
Add Finnish language to settings

### ISSUE THREAD

**Issue by The-Coding-Classroom** [hovancik/stretchly#847]
### Prerequisites

- [x] I'm using latest version: v 1.4.0
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

I would like to add translation of settings for Finnish language. I can either open a PR or manage the translation just in Weblate, whichever is the preferred way.

**Comment by hovancik** [comment]
Hi and thanks! At this point it's really up to you :) Translating via git will allow you check it if you can app run locally :) Also, you can edd it to Welcome and Preferences screen.
