### ISSUE TITLE
No tray icon on Fedora 33

### ISSUE THREAD

**Issue by cjao** [hovancik/stretchly#849]
### Prerequisites

- [x] I'm using latest version: v 
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

I downloaded the latest Stretchly appimage on Fedora 33 (Gnome). However, no tray icon appears when I run the app, even if the appindicator gnome shell extension is installed (other tray icons are visible). Since the tray icon is the sole access point for Stretchly's visible elements, I cannot control the app except through the command line.

Operating system: 
Fedora 33, everything up to date.

### Steps to Reproduce

1. Ensure that gnome-shell-extension-appindicator is installed and enabled.
2. Run Stretchly for the first time and dismiss the welcome screen. Note that while the application continues to run in the background, no tray icon appears.
3. After killing the process, observe that subsequent invocations present no GUI whatsoever. 

**Expected behavior:** 
Tray icon should appear in the top bar.

**Actual behavior:**
Nothing appears.

**Reproduces how often:**
Consistently.

Thanks for your work!

**Comment by hovancik** [comment]
Hi, have you tried searching for general issues with appimage and Gnome? I don't use Gnome. 

In here (https://www.electronjs.org/docs/api/tray), they say 

> On Linux the app indicator will be used if it is supported, otherwise GtkStatusIcon will be used instead.
> On Linux distributions that only have app indicator support, you have to install libappindicator1 to make the tray icon work.

Any chance you have another app from appimage that is electron-based?

**Comment by hovancik** [comment]
So I am trying in Ubuntu, and if this is Gnome, it seems to work. Might be some missing dependencies, then

![image](https://user-images.githubusercontent.com/4745859/106014449-cbd8ca80-60bd-11eb-8138-7013769150a9.png)

**Comment by cjao** [comment]
It seems my previous comment was lost, so here it is:

Thanks, installing libappindicator seems to do the trick. Should that library be bundled in the appimage?

**Comment by hovancik** [comment]
I am not sure to be honest. All I do is tell `electron-builder`to also build Appimage. Doesn't look like I could specify dependencies: https://www.electron.build/configuration/appimage.

Debian package allows that, and has `libappindicator1` by default https://www.electron.build/configuration/linux#debian-package-options

**Comment by hovancik** [comment]
I have also found [this old](https://github.com/electron-userland/electron-builder/commit/df7d3167471a399d64d04ea81b54a7ad55d300df) commit, but it's not in code anymore. Looks to me they [decided](https://github.com/electron-userland/electron-builder/issues/1082#issuecomment-272961636) not to bundle usually-installed packages.

I'll close this as they don't allow this anymore. If you think they should, you could open issue in `electron-builder` project.
