### ISSUE TITLE
FR: Time range when stretchly should be active

### ISSUE THREAD

**Issue by Robert-M-Muench** [hovancik/stretchly#85]
IMO it doesn't make sense that I get the 1st micro break indicator after a couple of minutes after I booted my system. I would like to be able to define a start time, when stretchly should begin. So I could set it to 10:00 and before I'm not interrupted.

**Comment by hovancik** [comment]
stretchly now suspend breaks when going to sleep (at least on macos) so I am closing this

https://github.com/hovancik/stretchly/pull/123
