### ISSUE TITLE
FR: Counter for finished / skipped breaks

### ISSUE THREAD

**Issue by Robert-M-Muench** [hovancik/stretchly#86]
I would like to see the ratio of done and skipped breaks. This could be tracked over time and shown so I can improve on doing breaks. I must say that I'm skipping micro breaks a lot as the interruption is just to annoying while working on something.

**Comment by hovancik** [comment]
I have idea about this from beginning, but didn't have time to implement it yet: 
- count how many micro/breaks are skipped and calculate some number (or another logical value)
- based on that number/value do not let skipping breaks and/or show break window with some "warning" graphics (the higher value, the more intensity)

**Comment by tsah20** [comment]
@hovancik  I want to work on this.

**Comment by hovancik** [comment]
Hi, please see this issue, it's related and I am talking there about how I imagine that should work: https://github.com/hovancik/stretchly/issues/200

**Comment by hovancik** [comment]
closing in favor of #266
