### ISSUE TITLE
Chocolately package does not exist?

### ISSUE THREAD

**Issue by diorcula** [hovancik/stretchly#860]
### Description

[Description of the issue]
Cannot install Stretchly as the package does not exist with chocolately?

Operating system: Windows 10 latest Feb 2021

### Steps to Reproduce. 
With Powershell in the Windows Terminal:

_choco install strectchly_

Chocolatey v0.10.15
Installing the following packages:
strectchly
By installing you accept licenses for the packages.
strectchly not installed. The package was not found with the source(s) listed.
 Source(s): 'https://chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://chocolatey.org/docs/troubleshooting for more
 assistance.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

**Comment by diorcula** [comment]
Solved by running PowerShell as admin, sorry for the ignorant opening of an issue

**Comment by hovancik** [comment]
No worries :) Glad you figured it out
