### ISSUE TITLE
Pause not working properly on macOS

### ISSUE THREAD

**Issue by ghost** [hovancik/stretchly#865]
When I pause the app til morning, it will restart with the next startup, even if it was 2 pm. If I pause undefined, it runs on the next startup. Maybe i'm getting it wrong.

I want to thank you for this wonderful app, thank you so much!

Operating system: v1.4.0 macOS

**Comment by hovancik** [comment]
Hi, what do you mean by next startup? If you turn off your computer, it will not remember the change. 

Can you tell me what exactly do you mean? 

Also, could you please paste the log here, we should see what exactly is happening:  pressing Ctrl/Cmd + D in the About section to show location of the log file (Clicking on file location will open it.)

**Comment by ghost** [comment]
I misunderstood. I thought that by selecting indefinite pause, it was kept in the successive starts.
(Sorry, little level of english) By next startup I meant to turn on after turning off the computer.

I think it's solved, ty
