### ISSUE TITLE
erroneous 'a new version is available' messages

### ISSUE THREAD

**Issue by mstorus** [hovancik/stretchly#87]
I'm on the latest version, 0.8.1, but I occasionally get messages popping up saying "a new version of Stretchly is available"

Also, the About screen shows `latest version: undefined`

![about stretchly v0 8 1](https://cloud.githubusercontent.com/assets/1182738/25550962/225020b6-2c33-11e7-9393-d386597dcfd9.jpg)

Mac OSX 10.12.4

**Comment by hovancik** [comment]
Thanks for the report. Are you online or offline when it happens?

**Comment by mstorus** [comment]
I'm online when it happens

**Comment by hovancik** [comment]
Thanks, not sure what is causing it, but there is an easy way to fix it. 

Right now I am doing 
```
if (version !== 'Error getting latest version' && data !== version)
```
which is bad way to do it. It should be checking whether version returned is in `A.B.C` format via regex or so. 

If anyone is interested, it should be easy to change. Just write here so more people wont do it at once. If no-one, I will do over next few days when I find a time.

**Comment by hovancik** [comment]
I'll do it then.
