### ISSUE TITLE
Feature proposal: Defining a workday schedule

### ISSUE THREAD

**Issue by deadpyxel** [hovancik/stretchly#873]
As the title implies, I'm proposing a feature where one could define a schedule of when he wants stretchly to send the notifications.

## Description

The idea would be that either in one of the existing tabs or in a new on it was possible to setup an "active time" for stretchly. For example, let's say you have a standard 9 to 5 workweek, there are some different ways I think this could be achieved:

1. **Only set the time and not weekdays:** Basically tell stretchly that it should notify you in the period of 9am to 5pm everyday, weekends and holidays included.
2. **Setup a "workweek":** Define what days compose your workweek in a tick-box or something similar as well as the times, so for example, you could say that it is 9am-5pm from Monday to Friday.
3. **Being able to setup any time for any day:** This could be considered one step further and I can see that it could be very problematic if the current application isn't aware of what is a "weekday" and so on, but that could be a big thing for people like me that have custom work schedules for working multiple projects.

>Another proposal that could be discussed in another issue would be somewhat the "contrary", instead of notifying you only in those set times, when it arrives at lets say 5pm, it would notify you that your "workday" is done and that you should finish up and get away from the computer/relax (this is a personal problem but I know many people have it)

## Context
This application is already amazing, and fortunately, works really well with my Archlinux system. This change/addition would probably be appreciated for those that use the personal computer to work and personal things (note that I don't think one should have bad practices in their personal time). Also, as mentioned above, support for a schedule definition could be used in another areas or future features.

## Possible Implementation
I am not familiar with the code base and to be honest, node/electron itself but if the current implementation is already aware of the current date and time, I think this should be doable if there's interest for it.

>One thing to keep in mind is that this is a cross platform application, so if it would be a hassle to implement this and still work on multiple systems, I can completely understand.

**Comment by hovancik** [comment]
Hi there, there is a issue opened for it: #342 

Feel free to add your ideas there.
