### ISSUE TITLE
Immediately crash after starting - prob. about Windows Update

### ISSUE THREAD

**Issue by Welldoor** [hovancik/stretchly#874]
### Prerequisites

- [X] I'm using latest version: v 
- [X] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [X] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

Installing the software from .exe, starting App, it crashes.

Operating system:
Edition	Windows 10 Pro
Version	20H2
Installiert am	‎24.‎11.‎2020
Betriebssystembuild	19042.804
Leistung	Windows Feature Experience Pack 120.2212.551.0

### Steps to Reproduce

1. Installing the software from .exe, 
2. starting App

**Expected behavior:** not crashing

**Actual behavior:** it crashes immediately
![stretchly_error](https://user-images.githubusercontent.com/76523622/108999686-eee9a080-76a2-11eb-94c6-25e7c8482203.PNG)

**Reproduces how often:** 100%

### Additional Information

For me and my colleague it worked before. He thinks it's about latest windows update.

### Debug information

How to get to the debug? Haven't found a log in install folder.

**Comment by hovancik** [comment]
Hi @Welldoor , what do you mean by installing from exe? What is the file name and where did you get it from? Are you admin on your computer?

**Comment by Welldoor** [comment]
Installing Stretchly-Setup-1.4.0.exe from https://github.com/hovancik/stretchly/releases.

Ok, it needs to be run as an admin to get rid of this message, which occurred by starting the app.

**Comment by hovancik** [comment]
You mean running the app as admin or installing? I guess it depends on how your system is setup, but usually you should run the installer as the admin and app as regular user.

**Comment by Welldoor** [comment]
had to start the app as admin to get rid of the message
when starting as regular user error occurs

**Comment by hovancik** [comment]
OK, this must be then how your OS is configured. I am not doing any configuration for that with Stretchly.
