### ISSUE TITLE
FR: Free configurable pause skipping

### ISSUE THREAD

**Issue by Robert-M-Muench** [hovancik/stretchly#89]
Most web meetings run 1h, so I log in 5 min before and maybe it runs 10 min longer.

Hence I would like to pause Stretchly for 1,5h because 1h is too short and 2h is normally too long.

**Comment by kavya-jain** [comment]
@hovancik I want to work on this.

**Comment by hovancik** [comment]
Awesome ;]  I think this setting should be in "advanced" setting. And by that I mean that it should be possibe to change this value by editing config file, not from UI. Eg. the same like editing break notification timer.

**Comment by purva98** [comment]
Do we want a solution where we can customize our pause time value ? Like:

![menu](https://user-images.githubusercontent.com/24644158/36355816-1c4a96f4-150f-11e8-9d67-6e8245fede68.png)
![pausewindow](https://user-images.githubusercontent.com/24644158/36355817-1cb6015a-150f-11e8-9dff-0b48a6a39d8a.png)


if yes then ,  
Here every time after setting a new customized pause value ,my tooltip is showing me the value of the previously set customized pause, Will I have to use something , which functions like "Reset Break"
(Reset Break present in settings), does anyone have an idea , then please share :)

**Comment by kavya-jain** [comment]
Hi @purva98 I'm working on this issue. Can you please work on something else.

**Comment by hovancik** [comment]
Hey @purva98, I'm already talking to @kavya-jain about it ;]

**Comment by riddhi99** [comment]
Okas :)
