### ISSUE TITLE
Select which monitor has the breakscreen

### ISSUE THREAD

**Issue by ChuckRT84** [hovancik/stretchly#890]
### Prerequisites

- [x] I'm using latest version: v1.4.0
- [ ] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [ ] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

Hello there, i really enjoy this app, thank u so much, hope u could help me with this, im using multiple monitors and i want to know if theres someway to select in which one will appear the breakscreen, i´ve change the order of the monitors and that works but if i turn off the computer, with every login, the breakscreen always reappear back to the same monitor in which i preffer to work

Operating system: <Windows 10>

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

### Debug information

You can find extra debugging information and location of Logs file on `Preferences` -> `About` page, after you hit `Cmd/Ctrl+D` shortcut.

Please, review information provided there and paste relevant parts here.

If you have changed any settings, please, provide the preferences file.
Logs will be a big help, as well.

**Comment by hovancik** [comment]
Hi there, by default, breaks should appear on every screen. Did you change that?

**Comment by djordjedjukic** [comment]
Hey, I wanted to ask the same question. 
I turned off option appear on every screen. 

I have two external monitors on laptop, and break screen is shown on laptop screen.
I would like to have it on one of external monitors.

**Comment by hovancik** [comment]
It takes the first monitor the OS gives it. Can you try playing with what monitor is selected as default in your OS? 

There is no option to change that in Stretchly, currently.
