### ISSUE TITLE
Error 2 on install via Windows Package Manager

### ISSUE THREAD

**Issue by denelon** [hovancik/stretchly#893]
### Prerequisites

- [ ] I'm using latest version: v 
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

An Issue was reported in the Windows Package Manager project related to install errors:
https://github.com/microsoft/winget-cli/issues/500

Operating system: Windows: Windows.Desktop v10.0.19042.746

### Steps to Reproduce

1. winget install Stretchly

**Expected behavior:** The Package should be installed.

**Actual behavior:** Installer Failed With Exit Code 2

**Reproduces how often:** 100% on the users machine. I did not encounter the error on my machine.

### Additional Information

Comment with logged output:
https://github.com/microsoft/winget-cli/issues/500#issuecomment-772331319

### Debug information

You can find extra debugging information and location of Logs file on `Preferences` -> `About` page, after you hit `Cmd/Ctrl+D` shortcut.

Please, review information provided there and paste relevant parts here.

If you have changed any settings, please, provide the preferences file.
Logs will be a big help, as well.

**Comment by hovancik** [comment]
Looks like `winget` issue to me, I am not sure how can I help...

**Comment by denelon** [comment]
@hovancik can you help shed light on what error 2 is? Maybe that would help us to troubleshoot. I'm not able to reproduce this error in my environment, but @kapsiR is.

**Comment by hovancik** [comment]
@denelon I am using `electron-builder` to create the installers without any real knowledge what it does under the hood :) 

But I think it uses NSIS installer, which has this on their website https://nsis.sourceforge.io/Docs/AppendixD.html#errorlevels
```
2 - Installation aborted by script
```
Which means that Windows Package Manager aborted? 

Putting that as search query on the internets brought me to: https://github.com/electron-userland/electron-builder/issues/4057

People say `22.9.1` should fix that which I used to release `1.4` so not sure... https://github.com/hovancik/stretchly/blob/v1.4.0/package.json#L44

People who has the issue, should try regular installer to say if that fails as well...

Also, should this be x86 ? https://github.com/microsoft/winget-pkgs/blob/master/manifests/s/Stretchly/Stretchly/1.4.0/Stretchly.Stretchly.yaml#L14

**Comment by mohamedGamalAbuGalala** [comment]
@hovancik 
same issue using choco install, web installer, and offline installer (tried 1.4)


![image](https://user-images.githubusercontent.com/14947957/113486864-19eebd80-94b5-11eb-852f-86a94647d62f.png)



**Update**: v1.3 worked with choco


**Update:** I successfully upgraded v1.3 to 1.4 using choco, I don't know why it didn't work in the first place 🤔 Anyway **it worked**

**Comment by hovancik** [comment]
Did you run installer as Administrator? I don't use Windows as my OS but seen that as an issue before. Not sure how those installers like choco and winget works in that sense.

**Comment by denelon** [comment]
@hovancik 
> Also, should this be x86 ? https://github.com/microsoft/winget-pkgs/blob/master/manifests/s/Stretchly/Stretchly/1.4.0/Stretchly.Stretchly.yaml#L14

I'm not sure which architecture the packages is built for. We support several Architectures: 
        "Architecture": {
          "type": "string",
          "enum": [
            "x86",
            "x64",
            "arm",
            "arm64",
            "neutral"
          ],

**Comment by mohamedGamalAbuGalala** [comment]
@hovancik 

Yes, I run the installer as Administrator.

**Comment by hovancik** [comment]
@denelon I guess it should be `x64`

**Comment by kapsiR** [comment]
@hovancik @denelon Yes, the installer (without using winget) works, even when I use the `/S` flag. (I already mentioned that in this [winget comment](https://github.com/microsoft/winget-cli/issues/500#issuecomment-772331319))

@denelon May there be an issue with the integrity level in combination with winget and specific installers?

**Comment by kapsiR** [comment]
I just wanted to note [here too](https://github.com/microsoft/winget-cli/issues/500#issuecomment-850659687) that the installation now works when using an elevated prompt.
If you try to install it from an user prompt, the installation fails while trying to write to `C:\Windows\TEMP` due to the lack of permissions.

**Comment by hovancik** [comment]
I'll close this as I have no idea how `winget` works and I am not contributing to the package that is there. I hope that maybe all works now as this issue is pretty old.

**Comment by kapsiR** [comment]
@hovancik Just to let anyone know here, this has been fixed in the winget cli - should be this one here:  
https://github.com/microsoft/winget-pkgs/issues/29148

![grafik](https://user-images.githubusercontent.com/7165033/229495617-53a79498-244f-4dfc-b55a-e2cc091b6659.png)
