### ISSUE TITLE
Avoid a new break immediately after natural breaks 

### ISSUE THREAD

**Issue by jt007** [hovancik/stretchly#898]
Hi,
I experience often that a new break starts immediately when I get back to my desk after have had a good break away from computer.

Would be nice if it could be possible for users to adjust in the settings how long break away from computer is needed, to avoid a new break first thing when coming back. Info on the same page about what is default setting would also be useful.

Version 1.4.0
Windows 10, 64 bit

Hope it's something you will consider. Thank you very much :-)

**Comment by jt007** [comment]
"Monitor system idle time" is switched On. Forgot to mention that.

**Comment by hovancik** [comment]
Hi, can you show me the logs? This should not happen as breaks are reset after the natural break. 

Settings are described in readme: https://github.com/hovancik/stretchly#natural-breaks-inactivity-time- 
Default value is 5 minutes (`300000`)

**Comment by jt007** [comment]
Solved :-)
