### ISSUE TITLE
Localization support for ideas

### ISSUE THREAD

**Issue by AssafKatz3** [hovancik/stretchly#899]
### Prerequisites

- [V] I'm using latest version: v1.5.0
- [V] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [V] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

Ideas cannot be localize effectively

### Steps to Reproduce

1. Install Stretchly
2. Switch to non-English langauge
3. Wait to mini or long break

**Expected behavior:** The message is displayed in chosen language 

**Actual behavior:** The message is displayed in English

**Reproduces how often:** Always

### Additional Information

1. This isn't only matter of translation, Hebrew for example require RTL support
2. Since the message address the user, they must be gender depended for some languages (e.g. Hebrew)
3. This requested support won't replace the customization of ideas, only just replace the default

### Debug information

A Hebrew male version of [config.json](https://github.com/hovancik/stretchly/files/6271805/config.json.txt) is attached.

**Comment by hovancik** [comment]
please add your comments here: #310
