### ISSUE TITLE
On Windows, Stretchly can be closed during a break by Win + D

### ISSUE THREAD

**Issue by Jerry8538** [hovancik/stretchly#900]
### Prerequisites

- [x] I'm using latest version:  
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

 Description - 

On Windows 10, we can just hit Win + D to show the taskbar, and then close stretchly, which is something I don't want to be able to do, but have done way too many times.

Operating system: Windows 10

 Steps to Reproduce - 

1. Run Stretchly
2. During a break, hit Win + D
3. Right click stretchly and close it.

**Expected behavior:** I would expect it to hide the taskbar, if hiding the icon from the taskbar is not possible.

**Actual behavior:** The taskbar is shown.

**Reproduces how often:** Always.

Ways I think it can be fixed - 

One way to fix it would be to have Stretchly running while having the taskbar icon hidden, or atleast hiding it during a break.

**Comment by hovancik** [comment]
Hi, `Win+D` is a OS shortcut, so there's no way to disable it, the same like I can't disable `Alt+Tab`. If you don't wanna use it at all, you can disable it completely by meddling with the OS itself: https://www.top-password.com/blog/disable-windows-key-shortcuts-hotkeys-in-windows-10/

**Comment by Jerry8538** [comment]
Okay, that makes sense, but is it possible to hide the Stretchly icon from the notification area on the taskbar?

**Comment by hovancik** [comment]
No that's not possible.
