### ISSUE TITLE
Feature request: DO NOT reset when unlocking Windows as an option

### ISSUE THREAD

**Issue by slayerjk** [hovancik/stretchly#901]
Hello.

Earlier there were "Feature request: reset when unlocking Windows"

May it be the option either Turn ON or Turn OFF such behaviour?
I don't like it at all reseting current break when I unlock my pc.
Usually I lock pc when breaks time comes, go away for some time, come back, unlock pc and want to see is break time is over and see nothing.
In very early versions there were no such inconvinient option, really miss that time.

**Comment by hovancik** [comment]
It was really buggy because "time" is not working correctly when PC is locked. I can bring that option but I will not support it working correctly.

**Comment by slayerjk** [comment]
> It was really buggy because "time" is not working correctly when PC is locked. I can bring that option but I will not support it working correctly.

I remember that it worked fine, I unlocked pc and saw the screen of break and time looked correct.
I really wish you add this option(on/off reset breaks when unlock pc).
Thank you for answer!
