### ISSUE TITLE
[feature request] have a group mode

### ISSUE THREAD

**Issue by mr-nano** [hovancik/stretchly#905]
I am often pairing of giving session to a group｡ I will line if our breaks can be sync'd. Something like adding a same seed Will made breaks come on same time for each person using the seed.

**Comment by hovancik** [comment]
@mr-nano can you explain again? I am not sure if I understand

**Comment by mr-nano** [comment]
Oh sorry. So I'm a developer trainer and in my role I introduce people to this amazing app Stretchly. 😇
I must have introduced this up to over 1,000 people. 😁 One of the issue though is that when we are on the same zoom call then our breaks are not synchronised. I would be sharing my screen or someone will be sharing the screen and they will get a break time reminder. That's great! But a minute later someone else will have a break time reminder on this system. And that can get annoying or distracting for that individual.
So what I am looking for is an ability to synchronise the brakes across a group of people who are working together (like either we are pairing or by mom programming or collectively in a discussion)
Does that make sense? Please let me know if it does not then I will try to elaborate further.

**Comment by hovancik** [comment]
Ah, ok, I think I understand. I am not sure how would I solve that, thought, as different people can have different Preferences. 

There is no feature right now that would allow to have synchronized breaks. The only think I can imagine now if people would have the same preferences and then do "Reset breaks" at the same time. But they would need to disable Idle time monitoring, DND monitoring, probably more things would need to be specificly setup for this to work. 

Stretchly also has CLI interface, so I guess the easiest would be to create some script that would run on all computers and control the breaks. 

```
Examples:
        stretchly pause                                  Pause breaks indefinitely
        stretchly pause -d 60                            Pause breaks for one hour
        stretchly pause -d 1h                            Pause breaks for one hour
        stretchly pause -d 1h20m                         Pause breaks for one hour and twenty minutes
        stretchly mini -T "Stretch up!"                  Start a Mini Break, with the title "Stretch up!"
        stretchly long -T "Stretch up!" --noskip         Set the next Break's title to "Stretch up!"
        stretchly long -T "Stretch up!" -t "Go stretch!" Start a long break, with the title "Stretch up!" and text "Go stretch!"
```

**Comment by mr-nano** [comment]
Hey thanks for getting back. And woah. I didn't know about the commandline! 

Is it possible for sync breaks feature to take an input like: "starting at time XX, we'll take a mini break every YY together and a larger break every ZZ together"
XX/YY/ZZ - could be time in some formats e.g.  XX - The time in long, YY - 10 minutes, ZZ - 45 minutes.

So the people can keep this schedule together.

**Comment by hovancik** [comment]
TBH, I don't have experience to write such a feature and I don't want to complicate the code with it, as it opens many new complications as different people would want to use this differently. The best course of action would be for you to write your own wrapper for Stretchly's CLI that would do what you would like to do.

**Comment by hovancik** [comment]
I will close this as I do not plan to implement this and would recommend people to use stretchly's CLI if they need this functionality.
