### ISSUE TITLE
[Feature request] Individual break times and end bell

### ISSUE THREAD

**Issue by fspade** [hovancik/stretchly#910]
Thanks again for providing and supporting this useful tool.

After using it for a while and after changing the messages to my liking, I came to wish I could place an optional timer value with some messages.

For longer breaks, I was wishing to be able to end with a different and/or louder signal. This could also be an optional value, which would'nt hurt any future upgrade, but open more possibilities.

A mayor improvement would be, to be able to display an image during a break, i.e. of a certain exercise, or even a YouTube video that leads through an exercise.

Just in case you got some spare time and energy to invest in this all. ;-)

Kind regards and keep up the good work,

Frank

**Comment by hovancik** [comment]
Thanks for the feedback! 

I don't see images/videos realistically but different sound per break type should not be that hard.

**Comment by Chealer** [comment]
Can you clarify what you mean by _Individual break timers_?

**Comment by Chealer** [comment]
Ticket #687 already requested distinguishing the sounds for mini and long breaks.
