### ISSUE TITLE
Cannot uninstall corrrupt version of Stretchly

### ISSUE THREAD

**Issue by jt007** [hovancik/stretchly#912]
Hi, I can't uninstall a corrupt Stretchly version through normal uninstall in windows. I want to uninstall to get the software working again.

Reason why Stretchly became corrupt:
I tried to configure the config.json file (via json formatter pro) to better match my personal preferences.
First I adjusted the window size because of the issues with Google Chrome in full screen mode. And then natural breaks time. The software worked fine after these.
The problem occured when I tried to configure the "endBreakShortcut" and tried to replace the shortcut with a text. Then I got this error message: "An error occured while running Stretchly and it will now quit. To report the issue, click Report". And it was not possible to open the program. 

Procedure to try to solve the problem:
- Uninstalled Stretchly via windows settings/apps menu
- Restart pc
- Stretchly now not available in start menu or in app list anymore, but it's still available in it's own default folder on C:
- Checked the Stretchly folder to search for an uninstall file, but no such file there (showed hidden files also)
-Installed new version Stretchly
-Got the same error message the moment I finished the install: "An error occured while running Stretchly and it will now quit. To report the issue, click Report".
-Try to open Stretchly, and then the same message came twice for every time I try.

Have tried the uninstall/restart/reinstall procedure several times, with just the same error message, and still can't open the program. When I open the json file now, it looks like it's missing line breaks for some reason (so it looks a little messy).

System:
-Stretchly 1.5.0. Windows 10, 64 bit, newest update. New pc with 16gb ram. Chrome, newest update. McAfee personal security (virus free)

[Preferences.txt](https://github.com/hovancik/stretchly/files/6313402/Preferences.txt)

[main.log](https://github.com/hovancik/stretchly/files/6313406/main.log)

Please help to make Stretchly work again! :)

**Comment by hovancik** [comment]
Hi @jt007 , sorry to hear about the troubles. 

I think we need to fix the `config.json`. Can you paste it here? And I will correct it for you. It should be located in the same folder as the `main.log`.

**Comment by jt007** [comment]
"\"{\\n  \\\"microbreakDuration\\\": 10000,\\n  \\\"microbreakInterval\\\": 600000,\\n  \\\"breakDuration\\\": 180000,\\n  \\\"breakInterval\\\": 5,\\n  \\\"breakNotification\\\": true,\\n  \\\"microbreakNotification\\\": false,\\n  \\\"breakNotificationInterval\\\": 30000,\\n  \\\"microbreakNotificationInterval\\\": 10000,\\n  \\\"microbreak\\\": true,\\n  \\\"break\\\": false,\\n  \\\"microbreakStrictMode\\\": false,\\n  \\\"breakStrictMode\\\": false,\\n  \\\"morningHour\\\": 6,\\n  \\\"microbreakPostpone\\\": false,\\n  \\\"breakPostpone\\\": false,\\n  \\\"microbreakPostponeTime\\\": 120000,\\n  \\\"breakPostponeTime\\\": 300000,\\n  \\\"microbreakPostponesLimit\\\": 1,\\n  \\\"microbreakPostponableDurationPercent\\\": 30,\\n  \\\"breakPostponesLimit\\\": 1,\\n  \\\"breakPostponableDurationPercent\\\": 30,\\n  \\\"mainColor\\\": \\\"#1D1F21\\\",\\n  \\\"transparentMode\\\": false,\\n  \\\"opacity\\\": 0.9,\\n  \\\"audio\\\": \\\"crystal-glass\\\",\\n  \\\"volume\\\": 1,\\n  \\\"fullscreen\\\": false,\\n  \\\"ideas\\\": false,\\n  \\\"naturalBreaks\\\": true,\\n  \\\"naturalBreaksInactivityResetTime\\\": 120000,\\n  \\\"allScreens\\\": true,\\n  \\\"useIdeasFromSettings\\\": false,\\n  \\\"language\\\": \\\"en\\\",\\n  \\\"notifyNewVersion\\\": true,\\n  \\\"isFirstRun\\\": false,\\n  \\\"posLatitude\\\": 0,\\n  \\\"posLongitude\\\": 0,\\n  \\\"useMonochromeTrayIcon\\\": false,\\n  \\\"useMonochromeInvertedTrayIcon\\\": false,\\n  \\\"silentNotifications\\\": false,\\n  \\\"monitorDnd\\\": false,\\n  \\\"microbreakStartSoundPlaying\\\": false,\\n  \\\"breakStartSoundPlaying\\\": false,\\n  \\\"themeSource\\\": \\\"system\\\",\\n  \\\"endBreakShortcut\\\": \"CmdOrCtrl+X\",  \\\"breakWindowWidth\\\": 0.9962,\\n  \\\"breakWindowHeight\\\": 0.9999999,\\n  \\\"checkNewVersion\\\": true,\\n  \\\"breakIdeas\\\": [\\n    {\\n      \\\"data\\\": [\\n        \\\"Not alone\\\",\\n        \\\"Do you find it hard to take a break alone? Try to do it with a co-worker. Aside from making it easier to stick to breaks, you will have a chance to get to know them better. Taking breaks together increases productivity.\\\"\\n      ],\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": [\\n        \\\"Step away\\\",\\n        \\\"Do you ever notice how your brain can figure things out by itself? All it takes is to step away from the computer and take a break to think about something totally unrelated.\\\"\\n      ],\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": [\\n        \\\"Microbreaks\\\",\\n        \\\"Rest is a key component in ensuring the performance of the musculoskeletal system. Frequent breaks can decrease the duration of a task and help lower the exposure to ergonomic injury risk.\\\"\\n      ],\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": [\\n        \\\"Meditation\\\",\\n        \\\"Research studies suggest that mindfulness-based exercises help decrease anxiety, depression, stress, and pain, and help improve general health, mental health, and quality of life. Not sure how to start? There are numerous apps to help you out.\\\"\\n      ],\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": [\\n        \\\"Blink\\\",\\n        \\\"Looking at screens for a long time causes you to blink less, thus exposing your eyes to the air. Blink rapidly for a few seconds to refresh the tear film and clear dust from the eye surface.\\\"\\n      ],\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": [\\n        \\\"Ergonomics\\\",\\n        \\\"Improper height and angle of the keyboard, mouse, monitor or working surface can cause health problems. Take some time to read about desk ergonomics.\\\"\\n      ],\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": [\\n        \\\"Move\\\",\\n        \\\"There are a lot of ways you can exercise within your office. Try marching in place or doing desk push-ups.\\\"\\n      ],\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": [\\n        \\\"Change\\\",\\n        \\\"Do you have a stability ball or standing work desk? Consider replacing your desk chair with them for a while.\\\"\\n      ],\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": [\\n        \\\"Notice\\\",\\n        \\\"Are you daydreaming or having trouble focusing? It is a sign that you need to take a break.\\\"\\n      ],\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": [\\n        \\\"Tech\\\",\\n        \\\"How about taking a no-tech walk?\\\"\\n      ],\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": [\\n        \\\"Metabolism\\\",\\n        \\\"Emerging research shows that sitting for long periods of time contributes to risk of metabolic syndrome, heart attack and stroke risk and overall death risk, among others. Taking regular walking breaks can help your circulation, working to counteract some of those problems.\\\"\\n      ],\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": [\\n        \\\"Active Meetings\\\",\\n        \\\"How about moving meetings from the conference room to the concourse? Walking not only burns calories but it may even foster a sense of collaboration.\\\"\\n      ],\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": [\\n        \\\"Fruit\\\",\\n        \\\"Take your time and eat some fruit. Slowly. Notice the flavor, the texture, the freshness.\\\"\\n      ],\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": [\\n        \\\"Bathrooms\\\",\\n        \\\"Walk to the farthest bathroom in the worksite facility when going to the restroom.\\\"\\n      ],\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": [\\n        \\\"Coffee break\\\",\\n        \\\"Going on coffee break? Consider doing a 5-minute walk every time you go for one.\\\"\\n      ],\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": [\\n        \\\"Colleagues\\\",\\n        \\\"Do not email or message office colleagues, walk to their desks to communicate with them.\\\"\\n      ],\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": [\\n        \\\"Learning\\\",\\n        \\\"In a study of healthy volunteers, NIH researchers found that taking short breaks, early and often, may help our brains learn new skills.\\\"\\n      ],\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": [\\n        \\\"Exercise\\\",\\n        \\\"Evidence suggests small amounts of regular exercise can bring dramatic health benefits, including measurably reducing stress.\\\"\\n      ],\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": [\\n        \\\"Repeat\\\",\\n        \\\"Have you found your stretch-ly-routine? Do not forget to repeat it for more than once to better fight effects of prolonged sitting.\\\"\\n      ],\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": [\\n        \\\"Wrist and forearm\\\",\\n        \\\"Extend your arms with the palms facing towards you, then slowly rotate the hands four times clockwise, then four times counter-clockwise.\\\"\\n      ],\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": [\\n        \\\"Back stretching\\\",\\n        \\\"Join your hands behind your head, then lift them together up above your head ending with your palms facing upward.\\\"\\n      ],\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": [\\n        \\\"Mobilize\\\",\\n        \\\"For every thirty minutes of stagnation, you should have at least one minute of stimulation.\\\"\\n      ],\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": [\\n        \\\"7 Minute Workout\\\",\\n        \\\"This workout packs in a full-body exercise routine in a fraction of the time. But as with any exercise, be careful. There are numerous apps to get you started.\\\"\\n      ],\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": [\\n        \\\"Pulse\\\",\\n        \\\" Raise your pulse rate to 120 beats per minute for 20 straight minutes four or five times a week doing anything you enjoy. Regularly raising your heart rate results in improved cardiovascular health.\\\"\\n      ],\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": [\\n        \\\"Take the stairs \\\",\\n        \\\"Studies have shown that stair climbing, which is considered vigorous-intensity physical activity, burns more calories per minute than jogging.\\\"\\n      ],\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": [\\n        \\\"Make art\\\",\\n        \\\"Art therapy is known to have great mental health benefits, especially when it comes to stress management. How about writing a quick poem, taking a picture or painting something small?\\\"\\n      ],\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": [\\n        \\\"Declutter\\\",\\n        \\\"A clean space helps your focus at work and is often linked to positive emotions like happiness.\\\"\\n      ],\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": [\\n        \\\"Lunch outside\\\",\\n        \\\"Nature is linked to positive emotions and decreased stress and anxiety. Whenever possible, try to take your daily lunch break outside, surrounded by some greenery.\\\"\\n      ],\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": [\\n        \\\"Public transport\\\",\\n        \\\"If you use public transport regularly, you can stand instead of sitting. If it is possible, try to replace as many of your daily trips as possible with walking or cycling.\\\"\\n      ],\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": [\\n        \\\"Yawning\\\",\\n        \\\"Yawning can be really helpful, as it produces tears to help moisten and lubricate the eyes.\\\"\\n      ],\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": [\\n        \\\"Focus change\\\",\\n        \\\"Hold one finger close to the eye an focus on it. Slowly move the finger away, focus far into the distance and then back to the finger. Bring the finger back and focus on something far away.\\\"\\n      ],\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": [\\n        \\\"Palming\\\",\\n        \\\"While seated, brace elbows on the desk and close to the desk edge. Let your weight fall forward and cup hands over eyes. Close your eyes and inhale slowly through nose and hold for few seconds. Continue deep breathing.\\\"\\n      ],\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": [\\n        \\\"Hand squeezes\\\",\\n        \\\"Squeeze a pair of balled-up socks or a soft rubber ball, hold for 5 seconds. Repeat whole process few times.\\\"\\n      ],\\n      \\\"enabled\\\": true\\n    }\\n  ],\\n  \\\"microbreakIdeas\\\": [\\n    {\\n      \\\"data\\\": \\\"Go grab a glass of water.\\\",\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": \\\"Slowly look all the way left, then right.\\\",\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": \\\"Slowly look all the way up, then down.\\\",\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": \\\"Close your eyes and take few deep breaths.\\\",\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": \\\"Close your eyes and relax.\\\",\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": \\\"Stretch your legs.\\\",\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": \\\"Stretch your arms.\\\",\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": \\\"Is your sitting posture correct?\\\",\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": \\\"Slowly turn head to side and hold for 10 seconds.\\\",\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": \\\"Slowly tilt head to side and hold for 5-10 seconds.\\\",\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": \\\"Stand from your chair and stretch.\\\",\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": \\\"Refocus your eyes on an object at least 20 meters away.\\\",\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": \\\"Take a moment to think about something you appreciate.\\\",\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": \\\"Take a moment to smile at being alive.\\\",\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": \\\"A truly ergonomic workstation is one that you regularly push away from.\\\",\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": \\\"Close your eyes and count your breaths.\\\",\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": \\\"Close your eyes and name the things you hear.\\\",\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": \\\"Place your fingertips on your shoulders. Roll your shoulders forward for 10 seconds, then backward.\\\",\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": \\\"Raise your right arm, stretch it over your head to the left, and hold for 10 seconds. Repeat on the other side.\\\",\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": \\\"With your right hand, grab each finger of your left hand in turn and squeeze. Repeat on the other side.\\\",\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": \\\"Stand up and do a lunge. Hold for 10 seconds, then do the other leg.\\\",\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": \\\"Close your eyes and simply notice whatever arises in current moment, without judgement.\\\",\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": \\\"One should focus every 20 minutes for 20 seconds on an object that is 20 feet distance.\\\",\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": \\\"If you need help, ask for it.\\\",\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": \\\"Do one thing at a time.\\\",\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": \\\"Is your attention spent wisely?\\\",\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": \\\"Change your sitting posture.\\\",\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": \\\"Expose your eyes to natural light.\\\",\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": \\\"With your eyes closed, slowly and gently move eyes up to the ceiling, then slowly down to the floor.\\\",\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": \\\"With your eyes closed, slowly and gently move eyes to the left, then slowly to the right.\\\",\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": \\\"Shake your hands out to get some relief.\\\",\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": \\\"One at a time, touch the tip of each finger to the tip of your thumb so they make an O-shape.\\\",\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": \\\"Make a fist and then slide your fingers up until they point toward the ceiling, like you're telling someone to stop.\\\",\\n      \\\"enabled\\\": true\\n    },\\n    {\\n      \\\"data\\\": \\\"Make a fist and then fan your fingers out and stretch them as far as you can.\\\",\\n      \\\"enabled\\\": true\\n    }\\n  ],\\n  \\\"showBreaksAsRegularWindows\\\": false,\\n  \\\"appExclusions\\\": []\\n}\""

**Comment by jt007** [comment]
Thank you very much! I tried to change that endBreakShortcut back to default, but I may have missed something. I tried to drop the entire file here, but the file format was not supported here.

**Comment by hovancik** [comment]
can you try putting this to the config.json? 

```
{
  "microbreakDuration": 10000,
  "microbreakInterval": 600000,
  "breakDuration": 180000,
  "breakInterval": 5,
  "breakNotification": true,
  "microbreakNotification": false,
  "breakNotificationInterval": 30000,
  "microbreakNotificationInterval": 10000,
  "microbreak": true,
  "break": false,
  "microbreakStrictMode": false,
  "breakStrictMode": false,
  "morningHour": 6,
  "microbreakPostpone": false,
  "breakPostpone": false,
  "microbreakPostponeTime": 120000,
  "breakPostponeTime": 300000,
  "microbreakPostponesLimit": 1,
  "microbreakPostponableDurationPercent": 30,
  "breakPostponesLimit": 1,
  "breakPostponableDurationPercent": 30,
  "mainColor": "#1D1F21",
  "transparentMode": false,
  "opacity": 0.9,
  "audio": "crystal-glass",
  "volume": 1,
  "fullscreen": false,
  "ideas": false,
  "naturalBreaks": true,
  "naturalBreaksInactivityResetTime": 120000,
  "allScreens": true,
  "useIdeasFromSettings": false,
  "language": "en",
  "notifyNewVersion": true,
  "isFirstRun": false,
  "posLatitude": 0,
  "posLongitude": 0,
  "useMonochromeTrayIcon": false,
  "useMonochromeInvertedTrayIcon": false,
  "silentNotifications": false,
  "monitorDnd": false,
  "microbreakStartSoundPlaying": false,
  "breakStartSoundPlaying": false,
  "themeSource": "system",
  "endBreakShortcut": "CmdOrCtrl+X",
  "breakWindowWidth": 0.9962,
  "breakWindowHeight": 0.9999999,
  "checkNewVersion": true,
  "breakIdeas": [
    {
      "data": [
        "Not alone",
        "Do you find it hard to take a break alone? Try to do it with a co-worker. Aside from making it easier to stick to breaks, you will have a chance to get to know them better. Taking breaks together increases productivity."
      ],
      "enabled": true
    },
    {
      "data": [
        "Step away",
        "Do you ever notice how your brain can figure things out by itself? All it takes is to step away from the computer and take a break to think about something totally unrelated."
      ],
      "enabled": true
    },
    {
      "data": [
        "Microbreaks",
        "Rest is a key component in ensuring the performance of the musculoskeletal system. Frequent breaks can decrease the duration of a task and help lower the exposure to ergonomic injury risk."
      ],
      "enabled": true
    },
    {
      "data": [
        "Meditation",
        "Research studies suggest that mindfulness-based exercises help decrease anxiety, depression, stress, and pain, and help improve general health, mental health, and quality of life. Not sure how to start? There are numerous apps to help you out."
      ],
      "enabled": true
    },
    {
      "data": [
        "Blink",
        "Looking at screens for a long time causes you to blink less, thus exposing your eyes to the air. Blink rapidly for a few seconds to refresh the tear film and clear dust from the eye surface."
      ],
      "enabled": true
    },
    {
      "data": [
        "Ergonomics",
        "Improper height and angle of the keyboard, mouse, monitor or working surface can cause health problems. Take some time to read about desk ergonomics."
      ],
      "enabled": true
    },
    {
      "data": [
        "Move",
        "There are a lot of ways you can exercise within your office. Try marching in place or doing desk push-ups."
      ],
      "enabled": true
    },
    {
      "data": [
        "Change",
        "Do you have a stability ball or standing work desk? Consider replacing your desk chair with them for a while."
      ],
      "enabled": true
    },
    {
      "data": [
        "Notice",
        "Are you daydreaming or having trouble focusing? It is a sign that you need to take a break."
      ],
      "enabled": true
    },
    {
      "data": [
        "Tech",
        "How about taking a no-tech walk?"
      ],
      "enabled": true
    },
    {
      "data": [
        "Metabolism",
        "Emerging research shows that sitting for long periods of time contributes to risk of metabolic syndrome, heart attack and stroke risk and overall death risk, among others. Taking regular walking breaks can help your circulation, working to counteract some of those problems."
      ],
      "enabled": true
    },
    {
      "data": [
        "Active Meetings",
        "How about moving meetings from the conference room to the concourse? Walking not only burns calories but it may even foster a sense of collaboration."
      ],
      "enabled": true
    },
    {
      "data": [
        "Fruit",
        "Take your time and eat some fruit. Slowly. Notice the flavor, the texture, the freshness."
      ],
      "enabled": true
    },
    {
      "data": [
        "Bathrooms",
        "Walk to the farthest bathroom in the worksite facility when going to the restroom."
      ],
      "enabled": true
    },
    {
      "data": [
        "Coffee break",
        "Going on coffee break? Consider doing a 5-minute walk every time you go for one."
      ],
      "enabled": true
    },
    {
      "data": [
        "Colleagues",
        "Do not email or message office colleagues, walk to their desks to communicate with them."
      ],
      "enabled": true
    },
    {
      "data": [
        "Learning",
        "In a study of healthy volunteers, NIH researchers found that taking short breaks, early and often, may help our brains learn new skills."
      ],
      "enabled": true
    },
    {
      "data": [
        "Exercise",
        "Evidence suggests small amounts of regular exercise can bring dramatic health benefits, including measurably reducing stress."
      ],
      "enabled": true
    },
    {
      "data": [
        "Repeat",
        "Have you found your stretch-ly-routine? Do not forget to repeat it for more than once to better fight effects of prolonged sitting."
      ],
      "enabled": true
    },
    {
      "data": [
        "Wrist and forearm",
        "Extend your arms with the palms facing towards you, then slowly rotate the hands four times clockwise, then four times counter-clockwise."
      ],
      "enabled": true
    },
    {
      "data": [
        "Back stretching",
        "Join your hands behind your head, then lift them together up above your head ending with your palms facing upward."
      ],
      "enabled": true
    },
    {
      "data": [
        "Mobilize",
        "For every thirty minutes of stagnation, you should have at least one minute of stimulation."
      ],
      "enabled": true
    },
    {
      "data": [
        "7 Minute Workout",
        "This workout packs in a full-body exercise routine in a fraction of the time. But as with any exercise, be careful. There are numerous apps to get you started."
      ],
      "enabled": true
    },
    {
      "data": [
        "Pulse",
        " Raise your pulse rate to 120 beats per minute for 20 straight minutes four or five times a week doing anything you enjoy. Regularly raising your heart rate results in improved cardiovascular health."
      ],
      "enabled": true
    },
    {
      "data": [
        "Take the stairs ",
        "Studies have shown that stair climbing, which is considered vigorous-intensity physical activity, burns more calories per minute than jogging."
      ],
      "enabled": true
    },
    {
      "data": [
        "Make art",
        "Art therapy is known to have great mental health benefits, especially when it comes to stress management. How about writing a quick poem, taking a picture or painting something small?"
      ],
      "enabled": true
    },
    {
      "data": [
        "Declutter",
        "A clean space helps your focus at work and is often linked to positive emotions like happiness."
      ],
      "enabled": true
    },
    {
      "data": [
        "Lunch outside",
        "Nature is linked to positive emotions and decreased stress and anxiety. Whenever possible, try to take your daily lunch break outside, surrounded by some greenery."
      ],
      "enabled": true
    },
    {
      "data": [
        "Public transport",
        "If you use public transport regularly, you can stand instead of sitting. If it is possible, try to replace as many of your daily trips as possible with walking or cycling."
      ],
      "enabled": true
    },
    {
      "data": [
        "Yawning",
        "Yawning can be really helpful, as it produces tears to help moisten and lubricate the eyes."
      ],
      "enabled": true
    },
    {
      "data": [
        "Focus change",
        "Hold one finger close to the eye an focus on it. Slowly move the finger away, focus far into the distance and then back to the finger. Bring the finger back and focus on something far away."
      ],
      "enabled": true
    },
    {
      "data": [
        "Palming",
        "While seated, brace elbows on the desk and close to the desk edge. Let your weight fall forward and cup hands over eyes. Close your eyes and inhale slowly through nose and hold for few seconds. Continue deep breathing."
      ],
      "enabled": true
    },
    {
      "data": [
        "Hand squeezes",
        "Squeeze a pair of balled-up socks or a soft rubber ball, hold for 5 seconds. Repeat whole process few times."
      ],
      "enabled": true
    }
  ],
  "microbreakIdeas": [
    {
      "data": "Go grab a glass of water.",
      "enabled": true
    },
    {
      "data": "Slowly look all the way left, then right.",
      "enabled": true
    },
    {
      "data": "Slowly look all the way up, then down.",
      "enabled": true
    },
    {
      "data": "Close your eyes and take few deep breaths.",
      "enabled": true
    },
    {
      "data": "Close your eyes and relax.",
      "enabled": true
    },
    {
      "data": "Stretch your legs.",
      "enabled": true
    },
    {
      "data": "Stretch your arms.",
      "enabled": true
    },
    {
      "data": "Is your sitting posture correct?",
      "enabled": true
    },
    {
      "data": "Slowly turn head to side and hold for 10 seconds.",
      "enabled": true
    },
    {
      "data": "Slowly tilt head to side and hold for 5-10 seconds.",
      "enabled": true
    },
    {
      "data": "Stand from your chair and stretch.",
      "enabled": true
    },
    {
      "data": "Refocus your eyes on an object at least 20 meters away.",
      "enabled": true
    },
    {
      "data": "Take a moment to think about something you appreciate.",
      "enabled": true
    },
    {
      "data": "Take a moment to smile at being alive.",
      "enabled": true
    },
    {
      "data": "A truly ergonomic workstation is one that you regularly push away from.",
      "enabled": true
    },
    {
      "data": "Close your eyes and count your breaths.",
      "enabled": true
    },
    {
      "data": "Close your eyes and name the things you hear.",
      "enabled": true
    },
    {
      "data": "Place your fingertips on your shoulders. Roll your shoulders forward for 10 seconds, then backward.",
      "enabled": true
    },
    {
      "data": "Raise your right arm, stretch it over your head to the left, and hold for 10 seconds. Repeat on the other side.",
      "enabled": true
    },
    {
      "data": "With your right hand, grab each finger of your left hand in turn and squeeze. Repeat on the other side.",
      "enabled": true
    },
    {
      "data": "Stand up and do a lunge. Hold for 10 seconds, then do the other leg.",
      "enabled": true
    },
    {
      "data": "Close your eyes and simply notice whatever arises in current moment, without judgement.",
      "enabled": true
    },
    {
      "data": "One should focus every 20 minutes for 20 seconds on an object that is 20 feet distance.",
      "enabled": true
    },
    {
      "data": "If you need help, ask for it.",
      "enabled": true
    },
    {
      "data": "Do one thing at a time.",
      "enabled": true
    },
    {
      "data": "Is your attention spent wisely?",
      "enabled": true
    },
    {
      "data": "Change your sitting posture.",
      "enabled": true
    },
    {
      "data": "Expose your eyes to natural light.",
      "enabled": true
    },
    {
      "data": "With your eyes closed, slowly and gently move eyes up to the ceiling, then slowly down to the floor.",
      "enabled": true
    },
    {
      "data": "With your eyes closed, slowly and gently move eyes to the left, then slowly to the right.",
      "enabled": true
    },
    {
      "data": "Shake your hands out to get some relief.",
      "enabled": true
    },
    {
      "data": "One at a time, touch the tip of each finger to the tip of your thumb so they make an O-shape.",
      "enabled": true
    },
    {
      "data": "Make a fist and then slide your fingers up until they point toward the ceiling, like you're telling someone to stop.",
      "enabled": true
    },
    {
      "data": "Make a fist and then fan your fingers out and stretch them as far as you can.",
      "enabled": true
    }
  ],
  "showBreaksAsRegularWindows": false,
  "appExclusions": []
}
```

What was the shortcut you wanted to use?

**Comment by jt007** [comment]
Thank you very much :)
Instead of a shortcut (which is easier for me to misuse) I would like to use a text string to end the break in certain circumstances. The text string should be like: 
jeg må legge inn ordre nå

**Comment by hovancik** [comment]
Gotcha, that's not possible with shortcutting system :( 

You can read here what's possible: https://www.electronjs.org/docs/api/accelerator

**Comment by jt007** [comment]
Ok i see. Does it need to be only one letter etc after that special key, or could it be several letters?

**Comment by hovancik** [comment]
As I understand, it can only be one letter.

**Comment by hovancik** [comment]
I'm gonna close this one, as it seems to work now :) Let me know if you need further help

**Comment by jt007** [comment]
It works now! Thank you very much for your help :-) You're great man
