### ISSUE TITLE
Mac external monitors are not restored after break

### ISSUE THREAD

**Issue by smcdonald-earnup** [hovancik/stretchly#913]
### Prerequisites

- [ 1.5.0 ] I'm using latest version: v 
- [ Yes ] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [ Yes ] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

I have 3 external monitors on Mac running Big Sur 11.2.3
I have the preferences setup to use full screen to show breaks and show on 'all screens' 
When I get the full screen prompt, all monitors show breaks as expected.

The issue comes when I click 'Postpone' or 'Skip Break'.  In either of these cases, only the primary screen is restored.  All other screen remain black.

If I quit Stretchly, screens are restored.

Operating system:  Big Sur 11.2.3

### Steps to Reproduce

1. Setup a Mac with more than 1 external monitor
2. Set preferences to full screen and show on all screens
3. Allow break prompt show
4. Click Postpone/Skip
5. Primary monitor is restored but other monitors are not

**Expected behavior:** 

Upon 'Postpone/Skip Break' or at the end of a break all monitors should be restored.

**Actual behavior:** 

Primary monitor is restored only

**Reproduces how often:** [What percentage of the time does it reproduce?]

Currently, I am able to reproduce each time I follow the steps above.  

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

### Debug information

You can find extra debugging information and location of Logs file on `Preferences` -> `About` page, after you hit `Cmd/Ctrl+D` shortcut.

Attaching log and preferences files in Stretchly.zip
[Stretchly.zip](https://github.com/hovancik/stretchly/files/6313621/Stretchly.zip)

If you have changed any settings, please, provide the preferences file.
Logs will be a big help, as well.

**Comment by hovancik** [comment]
Hi @smcdonald-earnup , this has been fixed and over weekend I should be able to release new version :)
