### ISSUE TITLE
[Feature request] Allow ignore breakes when some apps are working

### ISSUE THREAD

**Issue by senpl** [hovancik/stretchly#915]
It would be nice to have option, that when some app(game runs) do not turn breaks. Or time window when breaks are just not shown. Sure it could be solve other way, but for not advanced users this seems like simplest solution. So I think adding blacklist of apps that when running not turn on breaks.

**Expected behavior:** When added process is running not activate breaks.

**Actual behavior:** Breaks run no matter what process is running.

**Reproduces how often:** always

### Additional Information

This might require some knowledge of what is working, but it should not be problem(similar mechanism I saw in f.lux)

version 1.5.0

**Comment by hovancik** [comment]
https://github.com/hovancik/stretchly#pauseresume-breaks-only-when-specific-command-is-running

**Comment by hovancik** [comment]
note: windows version is currently broken but fix will be out this weekend
