### ISSUE TITLE
Big Sur Not Launching

### ISSUE THREAD

**Issue by batyrch** [hovancik/stretchly#918]
Not launching after latest update. 

MacOS Big Sur. 

![Screenshot 2021-04-17 at 8 54 39 PM](https://user-images.githubusercontent.com/48865353/115120602-6232d300-9fbf-11eb-9414-9f03d3ca8fe3.png)

**Comment by hovancik** [comment]
Please see the readme: https://github.com/hovancik/stretchly#macos
