### ISSUE TITLE
Use Photino instead of Electron

### ISSUE THREAD

**Issue by xperiandri** [hovancik/stretchly#920]
### Prerequisites

- [X] I'm using latest version: v 
- [X] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [X] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

Use [Photino](https://www.tryphotino.io/) instead of Electron

**Comment by hovancik** [comment]
I'm using too many of Electron features to be ever able to replace it without basically rewrite from scratch. 

There are many alternatives to Electron and they are usually lacking
- crossplatform installers
- tray icon support
- native modules support
- many platform specific functions

With Photino, looks like it is in very early stage and in .Net, which I don't speak.
