### ISSUE TITLE
[BUG] Strict mode easily bypassed

### ISSUE THREAD

**Issue by jlildev** [hovancik/stretchly#923]
### Prerequisites

- [x] I'm using latest version: v (1.6.0)
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)
- [x] I've read [Code of Conduct](https://github.com/hovancik/stretchly/blob/master/CODE_OF_CONDUCT.md). By filing an Issue, you are expected to comply with it, including treating everyone with respect.

### Description

Strict mode easily bypassed when lock windows and reopen it.

Operating system: (Windows 10)

**Comment by hovancik** [comment]
Hi there, Stretchly is regular app, so there will always be a way how to close it etc :( 

With this specific thing, you could try https://github.com/hovancik/stretchly#pause-breaks-on-suspendlock from advanced prefs (https://github.com/hovancik/stretchly#advanced-preferences)
