### ISSUE TITLE
installing on Edge requires clicking through 1000 "yes it is safe" buttons

### ISSUE THREAD

**Issue by jmagaram** [hovancik/stretchly#924]
### Prerequisites

- [x] VERSION 1.5 I'm using latest version: v (type your version from `Preferences` -  `About`)
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)
- [x ] I've read [Code of Conduct](https://github.com/hovancik/stretchly/blob/master/CODE_OF_CONDUCT.md). By filing an Issue, you are expected to comply with it, including treating everyone with respect.

### Description

Trying to upgrade to 1.6 using Edge on Windows 10. Windows tries to stop me from installing the update - using Windows installer - giving me warnings about it is going to harm my computer, smart screen defender, etc. I think I need to click through at least 5 such warnings. I know it is safe. But this installation hassle combined with the frequent app updates makes me want to turn off the new-version notifications. I've also started to wonder if the app is really safe.

Operating system: (type your OS and version)

Windows 10

I'm pretty sure if you have a digitally signed app Windows wouldn't give the warnings. There are probably other ways to get Windows to stop bothering me.

### Steps to Reproduce

1. Using Edge on Windows 10, click the "Download the installer" link on https://hovancik.net/stretchly/downloads/
2. Notice the message "Stretchly.Setup 1.6 was blocked because it can harm your device." 
3. Click the 3 dots menu and choose "Keep"
4. Notice the message "This app might arm your device" with a big fat Delete button. Click "Show more" and choose "Keep anyway..."
5. Etc. Just try to get the thing installed.

**Expected behavior:** No warnings from Windows

**Actual behavior:** Zillions of warnings from Windows

**Reproduces how often:** Every time I attempt to install

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

### Debug information

You can find extra debugging information and location of Logs file on `Preferences` -> `About` page, after you hit `Cmd/Ctrl+D` shortcut.

Please, review information provided there and paste relevant parts here.

If you have changed any preferences, please, provide the whole file (`config.json`).
Logs will be a big help, as well.

**Comment by hovancik** [comment]
Hi and sorry for the trouble.

Looks like a Windows issue to me, though :) MacOS asks once and then it doesn't bother people again. 

I could sign app for MacOS and Windows but it's not free so I do not plan to do it (ie $249.00 /year for Windows). (Considering I want to keep Stretchly as a free software.)

**Comment by hovancik** [comment]
As a workaround, you might use `winget` which is commandline Microsoft client to install apps. I guess they don't do the checks there... But can't tell as I do not have any Windows computer to try.
