### ISSUE TITLE
[Bug]: Usage of ~260 MB of system memory

### ISSUE THREAD

**Issue by LaPeste** [hovancik/stretchly#927]
### Version

- [X] I'm using version 1.6.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

Windows

### Operating System Version

Windows 10 20H2 (build 19042)

### Reproduction steps

Just keep the app running in the background

### Expected Behavior

Applications like slack (~175 MB), signal messaging (~245 MB), VSCode (~270 MB for the current project) manage to accomplish so much with the same or less amount of memory. I'd have expected memory usage to go up with complexity of features and quality and amount of graphic assets. So I'd have expected stretchly to basically have an insignificat memory footprint.

### Actual Behavior

Stretchly uses on average somewhere around 260 MB of system memory, almost as much a code editor (VSCode).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
I am pretty sure with the amount of devs that slack has, they can manage better :) Anyway, see/subscribe #925 , there is a bug in electron.
