### ISSUE TITLE
[Bug]:   Keyboard shortcuts don't work

### ISSUE THREAD

**Issue by tzugen** [hovancik/stretchly#930]
### Version

- [X] I'm using version 1.6.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

Linux

### Operating System Version

Debian

### Reproduction steps

Ctrl + x, or ctrl + d in the preferences have no effect.

### Expected Behavior

see above

### Actual Behavior

see above

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tzugen** [comment]
Correction, sometimes they do work :confused:

**Comment by hovancik** [comment]
@tzugen 

`Ctrl+X` is in Break Window and works **only** when you can see text "Postpone" or "Skip this break" in the bottom of the Break Window. 

`Ctrl+D` will **only** work in Preferences -> About

Could you please check what you get?

**Comment by tzugen** [comment]
Yes, I don't know what was the Problem. A few times Ctr X didnt work at all, but now it seems to work.. I am confused...

24.04.2021 19:37:52 Jan Hovancik ***@***.***>:

**Comment by hovancik** [comment]
It is not available for the whole duration of Break (depending on your Preferences) so maybe that :) 

I'll close this and if it happens again, we can reopen.

**Comment by tzugen** [comment]
> It is not available for the whole duration of Break (depending on your Preferences) so maybe that :)

Where do I find this preference?
I believe there is actually a bug there:

The keyboard shortcuts often don't work in the beginning of the break (maybe due to this preference), but what happens, is that the input event is then still passed on to the application that is now invisible.

For example I work in the terminal, Stretchly activates, I press Cmd+X, Stretchly doesn't do anything, but the command that was running in the terminal gets cancelled.

**Comment by hovancik** [comment]
One preference is here: 
https://github.com/hovancik/stretchly#editing-postpone-functionality-

Setting Strick mode also changes the behaviour. 

Basically if you see on Break screen "Postpone" or "Skip" actions athe bottom, "Cmd/Ctrl+X" should work. 

Stretchly is not taking the focus, so for example when you are writing into terminal and break starts, you can keep writing.
