### ISSUE TITLE
[Feature request]: Ability to turn off certain exercise tips or exercise tip categories in the interface

### ISSUE THREAD

**Issue by bass-blowfish** [hovancik/stretchly#932]
### Version

- [X] I'm using version 1.6.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

macOS

### Operating System Version

10.13.6

### Problem description

I think the name "exercise tips" is a misnomer currently. Especially with certain questions like "Are you spending your time wisely?".  This one in particular always stands out to me because it doesn't contribute to my wellbeing and seem out of place next to the more objective suggestions. I often leave the stretch timer on while screensharing during writing sessions and usually everyone appreciates it, but we all agree when this one and other non-exercise related tips comes up it seems unhelpful and out of place. It comes off as a little smug and judgemental and can be guilt inducing. We often choose to spend our time less wisely than we'd like because of job responsibilities or because we have to write that letter to the landlord or whatever. 

I think most of us use this app to promote stretching and breaks, not to be prompted with existential questions, I have meditation and other apps for that. I think keeping actionable suggestions is a good route to go rather than more context dependent questions. I think there is another one about commuting which is a bit close-minded. First of all, pandemic. Second, not every city has good public transit options. It just seems like a wasted opportunity to instead show another actual helpful stretch or exercise that I can actually do right now. Ok, rant over, love the app, that's why I just want to remove any remaining friction I have with it. Thanks for all the hard work.

### Possible solution

Categorize all non-exercise "tips" into some new category and have a toggle/checkbox for that. Perhaps "Mental exercise tips" or "Additional Suggestions"

### Alternative solutions

Add ability to a raw list of all prompts and have checkboxes/toggles to turn individual ones on or off in the interface. This might be good for those with disabilities, where maybe leg exercises simply aren't an option for example.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
You can edit what breaks messages are shown via advanced preferences: https://github.com/hovancik/stretchly#advanced-preferences  https://github.com/hovancik/stretchly#editing-break-ideas

I am planning to add different "sources" of break ideas, but honestly, it will take some time (probably long time) as you can see what number of issues and ideas in here... 

I've described the idea here, please follow there for progress https://github.com/hovancik/stretchly/issues/310#issuecomment-557877850
