### ISSUE TITLE
[Bug]:   Preferences window opens only on 1 Desktop

### ISSUE THREAD

**Issue by dorkypants** [hovancik/stretchly#935]
### Version

- [X] I'm using version 1.6.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

macOS

### Operating System Version

Big Sur 11.2.3

### Reproduction steps

1. set up multiple desktops
2. open Stretchly's Preferences
3. switch to another desktop
4. from the menubar, pick Stretchly>Preferences
...
**Reproduces how often:** [What percentage of the time does it reproduce?] 100%

### Expected Behavior

Preferences window should appear on screen (in the current Desktop) or already be visible

### Actual Behavior

It looks as though Stretchly>Preferences isn't working (doesn't appear on screen), but it's just that the Preferences window is still open on the original Desktop. macOS has options for ordinary apps that appear in its Dock to "Assign to"… "All Desktops", "This Desktop", or "None". Stretchly should default, in effect, to "All Desktops"

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
I am not regular macOS user, so not sure how things work there, but here's what I see: 

- I created 2 desktops:  Desktop 1 and Desktop 2
- I opened Preferences on Desktop 1
- I went to Desktop 2 and opened Preferences again
- I was redirected back to Desktop 1 to my Preferences window

This seems like how it should be as I opened Preferences on Desktop 1. 

I have a another Tray app called Syncthing that has tray menu option called "Open" which worked the same as well: when I used it on Desktop 1, then moved cursor to Desktop 2 and tried the same menu option again, I was redirected to Desktop 1. So this seems like correct behavior. 

Regarding Dock: Stretchly does not have Dock integration. It was causing issues so it is hidden/disabled/turned-off on app start.

**Comment by dorkypants** [comment]
I’m not able to reproduce the problem I reported. As you say, when I choose Stretchly>Preferences from a different Desktop after having already opened it, macOS switches to the Desktop on which the Preferences window originally opened. It must have been some glitch in my system

Michael Khaw

**Comment by hovancik** [comment]
Ok, thanks for letting me know. I'll close this, then.
