### ISSUE TITLE
[Feature request]: allow mini- and long break intervals and durations to overlap

### ISSUE THREAD

**Issue by dorkypants** [hovancik/stretchly#936]
### Version

- [X] I'm using version 1.6.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

macOS

### Operating System Version

Big Sur 11.2.3

### Problem description

I'd like to have a break for 2 minutes every 18 minutes. There's no way to set it currently as mini breaks max out at 20 seconds every 10 minutes, while long breaks bottom out at 2 minutes every 20 minutes

### Possible solution

Allow mini breaks up to every 20 minutes and last up to 2 minutes, or allow long breaks as short as 20 seconds as often as every 10 minutes

### Alternative solutions

No alternative possible currently in Stretchly

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
I am not sure if I understand but

> There's no way to set it currently as mini breaks max out at 20 seconds every 10 minutes, while long breaks bottom out at 2 minutes every 20 minutes

in Preferences, you can set Mini Breaks for 10 seconds to 10 minutes and for every 5 - 65 minutes

Long Breaks depend on how small breaks are setup as it is basically "Have long break after X Mini breaks". 

This will not change, as it is core logic for Stretchly. 

If the values in UI are not enough for you, you can change them via preferences file: https://github.com/hovancik/stretchly#advanced-preferences

**Comment by dorkypants** [comment]
Ah, thanks, I didn’t see that mini-breaks could occur at intervals longer than the minimum interval for long breaks and can last as long as 10 minutes.

I’ve edited the values in the JSON file so mini breaks are every 1080000 (18 minutes) and their duration 120000 (2 minutes). In the Preferences window, the interval still displays as “20 minutes”.

Michael Khaw

**Comment by hovancik** [comment]
Yeah, that's expected because "the step" in UI is set to `5`minutes so it can not handle value `18`. As far as you do not change it by using the range, it will be your specified value even thought not being correctly shown in the UI.
