### ISSUE TITLE
[Feature request]: Link to configuration file via menu

### ISSUE THREAD

**Issue by rmcmullanLB** [hovancik/stretchly#938]
### Version

- [X] I'm using version 1.6.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Windows

### Operating System Version

Win10, 10.0.18363

### Problem description

I always have to hunt down the proper folder to access the configuration file for adding custom break ideas.

### Possible solution

Simple request:  in the Contributor Preferences menu, provide a link to the configuration file for creating custom break ideas.  I always have to hunt down the proper folder to access it, so it would save me time to have a direct link.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi @rmcmullanLB , this information is available at: Preferences -> About -> `Ctrl+D`

![image](https://user-images.githubusercontent.com/4745859/116659601-23732480-a992-11eb-99b5-7b8a2aee4122.png)

**Comment by rmcmullanLB** [comment]
Great.  Thank you.
