### ISSUE TITLE
Refactor schedule management responsibilities into a single class

### ISSUE THREAD

**Issue by mdekstrand** [hovancik/stretchly#94]
Right now, `BreaksPlanner` plans the next break, but executing that break is handled by code in `main.js`. This means the 'what state are we in?' logic is split between these two files, with a complex interaction bouncing between them through interval timers.

In #93, I integrated the idle time break skipping into `BreaksPlanner`, but this solution feels somewhat hacky.

I think it might help to have a single schedule management object that is responsible for all aspects of planning both the start and the ends of breaks, as well as monitoring idle time for natural breaks. It can be an `EventEmitter` and use events to tell the UI to show/hide the break window, update break progress bars, etc. It can also serve as a single source of information about the current state of the break timings (simplifying the solution to #63), in addition to cleaning up my solution to #59. It would further make it easier to use the idle time detection logic to make the 'in a break' timer only tick down when you're actually stopping use of the computer, like Workrave.

This object may also benefit from a defined state machine to record different states, but I haven't thought enough about what the state machine would look like to have a good handle on how useful it would be.

**Comment by hovancik** [comment]
Hi, I totally agree. To be honest, stretchly is learning exercise of nodejs/JS for me. I wanted to create single object responsible for everything you mentioned, but I did not/do not have knowledge of how to do it node way. Basically, I hoped one day stretchly would get some attention and someone would come and critique my code and help me learn something. So I am glad you started this issue. 

Eg, right now I am doing `constructor (settings, microbreakFunc, breakFunc)`which I am not sure it's good or bad. 

I am not familiar with `EvenEmmiter`s but if you could write simple pseudo code of how you imagine it could work, that would be great. I guess more people with experience can comment.

**Comment by mdekstrand** [comment]
Glad to help!

Life is made easier since you're using ES6 classes :). You can write:

```javascript
class BreakManager extends EventEmitter {
}
```

The `EventEmitter` base class takes care of all the event handler management for you. So then code in the break manager can write:

```
this.emit('start-break');
this.emit('break-progress-update', {total: 300000, elapsed: 102383})
```

And other code can write:

```
manager.on('start-break', () => {
    // show the break window
});
```

I personally think it would be a better separation of concerns if the manager is responsible for starting *and* stopping the break on its own, and all the event handlers do is show/hide windows, instead of having the 'start-break' listener arrange for the next break to be scheduled.

**Comment by hovancik** [comment]
For the sake of other people and me reminding myself, here is how it's working now: 

 - `Scheduler` - takes in function and delay and basically calling `setTimeout` when doing`scheduler.plan()`
- `BreaksPlanner` - takes care of planning next break (figuring out what kind of break it should be based on settings) and returns `Scheduler` (also skipping to micro/break, pause, resume, reset)
    - some functions returns Scheduler, some already plan it, which is bad
    - also creates status message for tray
- `main.js` 
    - when app starts, we create `breakPlanner` and plan first break 
    - when break starts, we create timer to finish it, which when called, is asking `breakPlanner` to plan next break

**Comment by sxmanton** [comment]
On this topic, I wanted to inquire, I'm a little confused why the scheduler has the plan function in the first place. I know in some spots you call nextBreak and then check that the result was not null before calling plan, but I don't really see what that accomplishes. Every instance of that happening is basically like
```
let nb = breakPlanner.nextBreak()
if (nb)
    nb.plan()
    //other logic
```
 I think that the setTimeout call could just occur in the constructor for Scheduler, and then there would be less risk of forgetting to actually call plan, like happened with the bug with the reset function that I fixed. The other logic that relies on nextbreak not being null can still happen, it would just get reduced to
```
let nb = breakPlanner.nextBreak()
if (nb) //nb != null means setTimeout already occurred
    //other logic
```

**Comment by mdekstrand** [comment]
With a break scheduler/planner/manager responsible for everything, there's yet another design that would be my go-to that doesn't even require `Scheduler`, and makes the break manager more like a state machine.

Basically, have a method `BreakManager.update()` that runs periodically and does a few things:

1. Get current idle time (if enabled)
2. See if we need to transition states (start or stop a break, update progress, cancel a break because of idle, etc.)
3. Activate state transition
4. Figure out how long to wait until the next update is need (if idle time is enabled, should be e.g. 5s to check idle again)
5. Schedule its next invocation

**Comment by hovancik** [comment]
@sxmanton plan was to have BreaksScheduler only schedule breaks, do not actually create timers. When I created it, I wasn't sure what would be the node way to talk between processes/objects and so on, so I did it the way I did it. I agree it could be simplified, I hope we gonna find some good consensus here. 

@mdekstrand that could be interesting as well. Maybe we can try different approaches and make PR to see if its good idea? I didn't have time yet to check how Events works, but I plan to find some. I hope to refactor break scheduling before working on other features.

**Comment by hovancik** [comment]
Guys, feel free to check changes I made and comment.

**Comment by sxmanton** [comment]
Had a quick skim over and it looked pretty good to me. I can try to review more thoroughly sometime, although also I think @mdekstrand has a better understanding of event emitter architecture, so mostly will defer to his thoughts on this one.
