### ISSUE TITLE
[Feature request]: Conditions to cancel breaks (user defined)

### ISSUE THREAD

**Issue by jt007** [hovancik/stretchly#942]
### Version

- [X] I'm using version 1.6.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Home, 20H2

### Problem description

Hi,
I'm sometimes frustrated when I am in a really hurry to do some very important work, and then the break starts in strict mode. It's stressful to not be able to complete important and very time sensitive tasks.

I know myself good enough, that if I'am not using strict mode, I just skip most of my breaks 

The available options today to cancel a break is a mouse click or "cmd/ctrl +X". Both these options are easily performed on auto pilot, without any considerations from myself about how important it really is to skip just this break. My challenges with sticking to my break scheduele is as follows depending on my settings:

*Not strict mode: easy to just skip most of the breaks on auto pilot.
*Strict mode: Sometimes the breaks starts when it’s VERY inappropriate for different reasons! And it’s impossible to do anything about it. Bad for business etc..
*Stricts mode +Postponements: Easy to abuse those postponements to just skip the breaks on auto pilot whenever possible.

### Possible solution

Let users define 1-5 conditions to cancel a break in strict mode, where at least one of them has to be met to cancel the break. These conditions should be created by users in the Preferences, and it should be possible to enable/disable this feature. 

When a break has started and we don’t want a break, we just click on the word “conditions” in the bottom of the screen. This opens a popup window which displays those user defined conditions (questions). We click [yes] or [no] to the questions. As soon as one of the questions is answered with [yes], the break is disabled. This means it's just needed to answer one of them.

Examples of conditions to skip a break (should be defined individually by each user):
-I am on a live video call now?
-It’s very bad for my business to take a short break now?
-An important chat will be shut down if I wait a few minutes?
-Very important things for me are at stake if taking a short break now?

This requires some brain activity from the users, which may prevent just clicking most breaks away on auto pilot. And it makes it possible to cancel a break even in strict mode when it’s really important, IF one of the conditions are met. And at times when we need it to be 100% strict, we can still disable the feature in the settings.

This could be a really powerful feature which can help us be more conscious about when to actually skip breaks. I think it will be very much easier to actually stick to our break schedule, and at the same time not be forced to take a break in those moments when it’s a LOT at stake!

Would be awesome if it’s possible to make something like this. Do you think you could fix it?

### Alternative solutions

An alternative solution could be to enable passwords or password phrases to skip breaks in strict mode.

An example of a such password phrase could be:
"I need to do very important work now, and I cannot wait a few minutes"      or
"A short break now could be very bad for my job"

This might also require some brain activity from us to decide how important it really is to skip just this break. Instead of just skipping it on auto pilot through a mouse click.

Such phrases could work without space in between the words as well. If I feel that I'am lying to myself by writing such a password, I will not complete the password. I will take the break instead. Goal achieved!

As my first solution about answering yes/no to user defined conditions take into account several important reasons to cancel a break, a password phrase will just take one reason into account. It might feel like a crisis if the break starts at the moment, but it might not be the same reason as in the password phrase. A way to solve this could be to allow for e.g. 5 different passwords/password phrases, so it needs to match with one of them.

I guess my first solution is the absolutely best and most smooth, but the alternative here could also work if it allows for e.g. five different passwords (or -phrases).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi,

the issue with autopilot is that almost anything can be done with autopilot: I can type my 30+ characters password in few seconds without thinking about it. 

I can see that a lot of people have hard times following breaks but I am afraid that something technology can't fix. I could add some really difficult math problem that one would have to solve, or even make it unsolvable in any reasonable time , but then, you can quit Stretchly anytime, it's regular app in the end. I would then be adding more and more levels which would make the app confusing.

Therefore I don't plan to add any more features with that, it's on all of us to figure out how to overcome the want to "skip" by ourself.

Sorry about this, I hope you'll find some way that works for you.
