### ISSUE TITLE
Stretchly no splash or settings screen

### ISSUE THREAD

**Issue by stevenmonrad** [hovancik/stretchly#946]
I'm using latest version: Stretchly.Setup.1.6.0.exe   113 MB downloaded as Admin today   2021 05 03
Description
Stretchly installed and used for approximately one year. Then stopped functioning. App shows up on Windows search but nothing happens on click, double click.  Locate .exe file in folder and click on that - nothing happens.

Operating system:  Windows 10 updated  2021 05 03

Steps to Reproduce
[First Step]  Windows search for app. Stretchly App logo as app appears normally.
[Second Step]  Click on App
[and so on...]
Expected behavior:  A splash or settings screen, something to set frequency and durations

Actual behavior: No result

Reproduces how often: Always

Additional Information

Stretchly continued to appear as App when searched in Windows but non-responsive as above, 
Updated Windows, no change.
Uninstalled Stretchly with the uninstall.exe file successfully.
Windows restart. No change.
Downloaded as above and reinstalled. App and .exe file appear but remain no-responsive as above.
Windows restart. No change.
Uninstalled Stretchly again.
Restarted Windows 10 as Admin.
Reinstalled Stretchly from Github as above.
App on Windows Search appears normally. exe file present
App / .exe file still non responsive
Stretchly mini-splash appears "10 seconds to Mini-Break"
Break screen appears with motion instructions, lasts 10 seconds.
SINCE there is no App splash or settings screen it is not possible to tell when this mini-break or anything else is set,
frequency or duration. HOW to get App to normal function, open from App and see settings?
I used the App for about one year and was able to change frequency and durations, etc. but not now.
No other computer user, no repairs, no changes other than Windows 10 updates.
It has now given me a popup for a Long Break in 30 seconds, then 5 min break screen, and postpones normally.
I would really like to know how to open a settings screen as on original install about 2 years ago.

stevenmonrad@gmail.com

**Comment by stevenmonrad** [comment]
ThinkPad P71
Device name	LAPTOP-RL19VKR6
Processor	Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz   2.90 GHz
Installed RAM	64.0 GB (63.9 GB usable)
Device ID	
Product ID	
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
Edition	Windows 10 Pro
Version	20H2
Installed on	‎21/‎04/‎03
OS build	19042.928
Serial number	PF10BFFX
Experience	Windows Feature Experience Pack 120.2212.551.0

**Comment by hovancik** [comment]
Hi @stevenmonrad , the menu for Stretchly appears in tray area. Here's how I can get there on win 10: 

![image](https://user-images.githubusercontent.com/4745859/116976840-f1c7c980-acc1-11eb-811a-3bc92a318ef4.png)

click on `^`

![image](https://user-images.githubusercontent.com/4745859/116976916-0ad07a80-acc2-11eb-934f-8bcbb2a7020b.png)

click on stretchly icon 

![image](https://user-images.githubusercontent.com/4745859/116976956-2045a480-acc2-11eb-9af3-c701c8072bb5.png)

Then you can click on different things :)
