### ISSUE TITLE
Running tests causes test-missing.json to be deleted

### ISSUE THREAD

**Issue by sxmanton** [hovancik/stretchly#95]
At any rate, any time I run the full test suite, the test-missing.json file is deleted and I have to be careful not to add the deletion into the commit, and git reset it to restore it. Is this an intentional behavior?

The cause seems to be, in the test/settings.js:
```
afterEach(() => {
    if (settings && settings.destroy) {
      settings.destroy()
      settings = null
    }
  })

```
and in app/utils/settings.js:

```
destroy () {
    this.data = null
    fs.unlinkSync(this.settingsFile)
  }
```

What is the reason for this destroy function? I can't find it being called anywhere besides in the test.

**Comment by hovancik** [comment]
Yeah, it's in `afterEach`, so it gets called after every test, to make sure test data are always correct. 

In this case, I guess I could do `missingSettings = new Settings(testMissingFileLocation)` instead of `settings = new Settings(testMissingFileLocation)` to avoid it.

**Comment by hovancik** [comment]
It will get changed anyway.. Not sure how to fix this.
