### ISSUE TITLE
[Feature request]: Show timer in the Taskbar Icon (like MacOS Time Out App)

### ISSUE THREAD

**Issue by narcisbugeag** [hovancik/stretchly#952]
### Version

- [X] I'm using version 1.6.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Windows

### Operating System Version

Windows 10 20H2

### Problem description

It would be nice to see in the taskbar icon how much time  you've until the next break. 

Like: **MacOS Time Out App**
![](https://i.imgur.com/CtW2VEx.png)

### Possible solution

It would be much easier and more interactive... not to hover your mouse over the icon to display how much time you have until the next break...

### Alternative solutions

I don't see any other alternative to this request. 

### Additional information

No.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, this only supported on MacOS so I don't plan to implement this. 

I would like to show times in tray icon, but only as graphic representation (#717 )
