### ISSUE TITLE
[Feature request]: transparent overly for games

### ISSUE THREAD

**Issue by senpl** [hovancik/stretchly#953]
### Version

- [X] I'm using version 1.6.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Linux

### Operating System Version

Arch

### Problem description

Current break might not be optimal for dynamic games. User could be able to turn intrusive small transparent overly window over current game. Goal is to remaind user, but not ruin his current game. I guess semitransparent element best on defined height would be enough. Of course it could be done in many ways, i just guess this seems simple enough.

### Possible solution

I would like option to show users element semi transparent to remaind him to take break.

### Alternative solutions

Game mode is generally alternative, so give user undisturbed experienced experience

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
My goal for Stretchly is to force one to take a break, so with gaming this means "to ruin" gaming experience :) If you don't wanna be disturbed while gaming, you should turn it off while playing, I think. You can pause for X hours, or set it to pause when your game is running automatically. You can also specify how  big break window you want, or how transparent you want it to be. Transparency works great for me on Mac, but for Linux I've seen mixed results.

**Comment by senpl** [comment]
Still I think adding it as option would not hurt anyone and it is better option then hold app (because it still remaind, but in way that still allow to play). I could try to implement it and turn it of by default, I just would like an option to allow it to users.

**Comment by hovancik** [comment]
TBH, I don't want it. I did things like that in the past and I regret them because it's impossible to remove feature once added and it makes it hard to maintain. Now I prefer to keep it as simple as possible. With ability to specify params of Break window, I think that's enough.
