### ISSUE TITLE
[Feature request]: Change break timer to reset when being idle

### ISSUE THREAD

**Issue by i-zanis** [hovancik/stretchly#955]
### Version

- [X] I'm using version 1.7.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Windows

### Operating System Version

10

### Problem description

The timer pauses when you go idle.

### Possible solution

The logic behind is not well thought. The way it should behave is to reset the timer when you go idle. 
Someone is idle most of the time because he is taking a break or away from a computer screen.
Remove the pause on break and turn into reset timer to start when you come back.

### Alternative solutions

No other potential solution other than uninstall. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kazerniel** [comment]
Agreed with this. No point of getting a break when I have just returned from a break.

**Comment by HenryZhou19** [comment]
But it's easy for windows to be in idle mode, even when I am just looking at the screen without moving the mouse for a while. So the timer is always set to its longest time, and I am hardly notified to have a break.(so sad)

**Comment by HenryZhou19** [comment]
So I suggest to make a threshold for idle mode. Maybe 2/3 of the minibreak's interval will be good.

**Comment by hovancik** [comment]
Hi @SolidreamHZ there is such a threshold:  

https://github.com/hovancik/stretchly#advanced-preferences
https://github.com/hovancik/stretchly#natural-breaks-inactivity-time-
