### ISSUE TITLE
[Feature request]: JSON edit via powershell seems to fail

### ISSUE THREAD

**Issue by mike-crawfurd** [hovancik/stretchly#961]
### Version

- [X] I'm using version 1.7.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Windows

### Operating System Version

20H2

### Problem description

I want to update the settings for my company using PowerShell to change the settings. However it seems that either the JSON config file is not meeting the standards or there is a PowerShell issue working with JSON files.

**Powershell script tat changes the height from 0.85 to 0.4**
$filelocation = "$env:APPDATA\Stretchly"
$filePath = "$filelocation\Config.json"
$file = ([System.IO.File]::ReadAllText($filePath)  | ConvertFrom-Json)
$Height = $file.breakWindowHeight
$Width = $file.breakWindowWidth

if($Height -eq '0.85')
{​​​​​​​
    $file.breakWindowHeight = 0.4
    $file | ConvertTo-Json | Out-File –FilePath $filePath –Encoding utf8 –Force
 }​​​​​​​

However this seems to result in a json file that fails, it actually cannot handle the breakideas and the microbreaks texts.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/24622847/118624392-696d1c80-b7c9-11eb-8844-c03b4e761a4e.png)

I am not 100% if PowerShell has a bug or json is not in the right format. I updated other json files using this method which worked fine, but it really crashes Stretchly. 

### Possible solution

Change some of the options for Windows to registry so we can easily update them

### Alternative solutions

Options to deploy setting as part of the installation

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi @mike-crawfurd, I am not sure whether I can help, I am not familiar with WIndows/PowerShell at all. 

Could we somehow figure out whether it's config file issue or PowerShell? When I put Stretchly's JSON file to any sort of JSON linter, I am not seeing any issues so I think it's the script that changes the value or powershell or something else.

**Comment by ztrhgf** [comment]
Hi,
you have to save the file as UTF-8 **without BOM**. 

So:

    $filelocation = "$env:APPDATA\Stretchly"
    $filePath = "$filelocation\Config.json"
    $file = ([System.IO.File]::ReadAllText($filePath) | ConvertFrom-Json)
    $Height = $file.breakWindowHeight
    $Width = $file.breakWindowWidth

    if ($Height -eq '0.85') {
        ​​​​​​​
        $file.breakWindowHeight = 0.4

        $MyRawString = $file | ConvertTo-Json
        $Utf8NoBomEncoding = New-Object System.Text.UTF8Encoding $False
        [System.IO.File]::WriteAllLines($filePath, $MyRawString, $Utf8NoBomEncoding)
    }​​​​​​​

**Comment by mike-crawfurd** [comment]
Thanks ztrhgf, that works like a charm!

**Comment by mike-crawfurd** [comment]
Feedback from ztrhgf worked, nobom or ascii works!
