### ISSUE TITLE
I can't open on a Mac anymore

### ISSUE THREAD

**Issue by ghost** [hovancik/stretchly#963]
After I installed version 1.7 was released, I was not able to open stretchy anymore. I got the screenshot below. BUT when I installed version 1.6, I still got the same error message.

I'm on a MacBook Pro

<img width="413" alt="Screen Shot 2021-05-24 at 7 39 00 AM" src="https://user-images.githubusercontent.com/41455955/119349076-547a0880-bc63-11eb-96c3-c761766ea28b.png">

**Comment by hovancik** [comment]
Please see the readme. https://github.com/hovancik/stretchly#macos
