### ISSUE TITLE
[Feature request]: Add 30mins option to "Pause Breaks"

### ISSUE THREAD

**Issue by BillionJothi** [hovancik/stretchly#964]
### Version

- [X] I'm using version 1.7.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Windows

### Operating System Version

Edition	Windows 10 Pro Version	20H2 Installed on	‎16/‎1/‎2021 OS build	19042.985 Experience	Windows Feature Experience Pack 120.2212.2020.0

### Problem description

Need to pause breaks for a short period of time to quickly finish a near ending task. However, min pausing of the break is 1 hour which is too long as users would forget to take their break and then began the next task there-by repeating the cycle endlessly - rendering the application as irritating/useless.

- Skipping to the next break forces the user to take a break now when the user intends to finish up the near ending task before taking a break
- Forcing the user to endure (break notifications) which can be distracting to the ending task & then forcing the user to click postpone break would break the concentration of the user.

### Possible solution

Add 30mins option to "Pause Break"

### Alternative solutions

- Allow users to specify custom values in "Pause Breaks"
- Allow users to specify custom values for postponement of break (temporary solution - might affect other intended purposes of application)
- Set Variable schedules (very hard to implement & does not meet other Edge cases)

### Additional information

I understand the purpose of the application and how it forces users to take breaks and I intend to build into a routine with it. However, being a novice/new user to the application, I find it very irritating and counterproductive. I usually end up either:
- positioning break for the max period (and taking my real breaks out of sync with the application),
- completely closing the application (and forgetting that I need breaks/its deactivated), 
- using the 1 hour break option (in which case I usually start my next task and get stuck in a cycle of postponing breaks)
- Allowing the breaks to pop-up and click postpone/skip break until I lose track of the breaks I skipped or get irritated with it and select a different option

(Break setting on original 20/60)
I understand the possibility of lengthening the break intervals, however, resist it as aiming to fit into it (as recommended officially as well). Also, the above situation happens during deep concentration works that are near ending only (however, given the high occurrence rate (given application always on), it causes difficulties utilizing/integrating the application.)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi and thnanks for the input! 

I usually don't wanna add new values to the list, as it is very subjective and many options make app unusable, but right now, I gues,s adding 30 minutes is not problematic. 

I'll add a flag to this issue as it should be easy to implement for people who wanna get contribution.

You can specify custom time for pausing by using command line interface (run `stretchly` in command line to get examples)
You can also change the postpone behaviour as well: https://github.com/hovancik/stretchly#editing-postpone-functionality-
