### ISSUE TITLE
[Bug]:   Timer only increments by 10

### ISSUE THREAD

**Issue by i-zanis** [hovancik/stretchly#967]
### Version

- [X] I'm using version 1.7.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

Linux

### Operating System Version

Ubuntu

### Reproduction steps

1.Go to Big Break Timer
2.Use arrows mouse to increase adjust the slider
3. Slider increments by units of 10

### Expected Behavior

I have used Stretchly on Windows.
The timer should increment by units of 1.

### Actual Behavior

Increments by 10.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by senpl** [comment]
This is currently calculated as (settings.get('breakInterval') + 1)*10 . Refactor to value other will be a big, coz this is calculated currently in many places. This should not be hard to change, but change in that many places will be hard to test.

**Comment by senpl** [comment]
Also topic should be updated to minutes timer.

**Comment by hovancik** [comment]
@i-zanis what slider do you mean? 

I guess you mean for Long Breaks. 

The value there depends on what is your value in Mini Breaks as it is basically: Show Long Breaks after X Mini Breaks. 
So if the Mini Break is every 10 minutes then Long Break can be every 20, 30, 40... minutes. 

General in UI, I had to make choice between allowing everything and lowering complexity of the UI, therefore UI does not allow everything. For special case, config file can be used to change the values.

**Comment by senpl** [comment]
@hovancik I does not agree. User should be able to set long break to any minute, Workrave do this and no one complains about it. I could do this, of course after tray icon time indicator.

**Comment by hovancik** [comment]
How would it work then? 

Right now, I can only write as I described, so Long after X Mini. 

Let's say user puts long break every 12 minutes, Mini every 10 as is by default. How are breaks working?

**Comment by senpl** [comment]
I think they use seperate timers. I know you do not want to seperate timers, still this seems like simplest solution. Alternatively this option could be provided where no mini breaks are enabled, coz short breaks are not that useful, and then no problem with Micro breaks interaction.

**Comment by i-zanis** [comment]
Currently I have no mini enabled.

Most people that use applications such as these as very detail-oriented.
Not being able to adjust such a detail is a deal breaker. There is no other
option other than uninstall.

The fanciness of a UI cannot overcome health concerns along with strict
deadlines.

The feature does a lot and is easy to implement.

**Comment by hovancik** [comment]
@i-zanis please consider what I wrote: 

> The value there depends on what is your value in Mini Breaks as it is basically: Show Long Breaks after X Mini Breaks.
So if the Mini Break is every 10 minutes then Long Break can be every 20, 30, 40... minutes.

> General in UI, I had to make choice between allowing everything and lowering complexity of the UI, therefore UI does not allow everything. For special case, config file can be used to change the values. 

Your conclusions should be: 

1. Ah, so let's say I want Long Break to be interval of 60, 90, 120 minutes, then I need my Mini Break interval to be 30 minutes.  Let's say I want it to be 10, 15, 20 minutes, then my Mini Breaks need to be 5 minutes. Let's say I want 20, 30, 40, then I setup Mini for 10. 
2. If my dream value is not in UI, I can set it up via editing config file. 

Stretchly is opinionated, and the aim is not to solve every possible usecase. I would not be able to do that even if I were working on Stretchly fulltime. There are many apps in this space and everyone is free to choose according to their needs.

**Comment by hovancik** [comment]
@senpl 

> I think they use seperate timers. I know you do not want to seperate timers, still this seems like simplest solution. 

I guess they use separate timer but my question is how the breaks looks like?

> Let's say user puts long break every 12 minutes, Mini every 10 as is by default. How are breaks working?

I start app at 5 am. What happens?

5:10 Mini Break -> 5:12 Long Break?
5:10 Mini Break -> 5:22 Long Break? 

When is then the next Mini Break? What happens when timers occur on the same time? What Break to show? What does "same time" mean? When they are in the exactly same time or maybe a minute difference? 
What if Long Break is halfway and timer for Mini comes? and vice versa. How is next break calculated? 

This is very arbitrary  and different people will want different things: don't show long when break last Mini was X minutes before, or show it anyway. Don't cancel running break when some other is halfway, ignore it. Or don't ignore it, but only if it was Long. Etc etc. 

Therefore I designed a system that there are mini breaks and then long break after X of mini breaks. You can still pretty much put any interval for Longs Breaks even if you don't use mini breaks.
