### ISSUE TITLE
[Feature request]: Configure time for long breaks

### ISSUE THREAD

**Issue by rob-stewart** [hovancik/stretchly#968]
### Version

- [X] I'm using version 1.7.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Problem description

Breaks occur at different times, depending upon when Stretchly is started. Meetings are scheduled relative to the clock and usually begin at the top of the hour. I'd like to be able to specify that long breaks occur at, say, 35 minutes past the hour. That way, they don't begin until after a 30 minute meeting ends (including a bit of time for meetings that run over time) and they also don't begin right near the beginning of a meeting.

Once the timing of long breaks is set, the short breaks can be scheduled accordingly.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi @rob-stewart , unfortunatelly, with how Stretchly has been written, this won't be possible to do. 

Stretchly has command-line interface where you can pause/start breaks so one could write a script to do what you describe.
