### ISSUE TITLE
[Feature request]: Use a font which is supporting all the application languages

### ISSUE THREAD

**Issue by ghost** [hovancik/stretchly#970]
### Version

- [X] I'm using version 1.7.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Linux

### Operating System Version

Kubuntu 21.04

### Problem description

Please use a font which is supporting more languages, or even all the languages of the localized version of Stretchly.

### Possible solution

Replace the font, or merge more glyphs.

### Alternative solutions

Fallback (sans) fonts are a good solution too.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
This is what I have right now: https://github.com/hovancik/stretchly/tree/trunk/app/css/fonts

What are you missing? TBH I am not familiar with fonts and CSS much

**Comment by ghost** [comment]
Hebrew glyphs are missing. A font like DejaVu Sans can cover more glyphs, including Hebrew and Arabic ones.

**Comment by hovancik** [comment]
So which one is better? I am not seeing the difference TBH as I don't know that language

<img width="599" alt="image" src="https://user-images.githubusercontent.com/4745859/121361545-ad20f500-c935-11eb-89e9-0ea0557485d1.png">

<img width="594" alt="image" src="https://user-images.githubusercontent.com/4745859/121361674-cf1a7780-c935-11eb-8dd4-c0b0f5437ec4.png">

**Comment by ghost** [comment]
> So which one is better? I am not seeing the difference TBH as I don't know that language
> 
> <img alt="image" width="599" src="https://user-images.githubusercontent.com/4745859/121361545-ad20f500-c935-11eb-89e9-0ea0557485d1.png">
> 
> <img alt="image" width="594" src="https://user-images.githubusercontent.com/4745859/121361674-cf1a7780-c935-11eb-8dd4-c0b0f5437ec4.png">

The first one is better.

**Comment by hovancik** [comment]
That was verdana I think, but seems it does not support "all" languages. So I searched and found that Noto should support everything. 

Here it is: 
<img width="591" alt="image" src="https://user-images.githubusercontent.com/4745859/121485497-8794f980-c9d0-11eb-9be8-5b0a3ea31c60.png">


But what's weird is that dev tools seems to suggest that is not really being used 100%: 

<img width="286" alt="image" src="https://user-images.githubusercontent.com/4745859/121485398-721fcf80-c9d0-11eb-942c-afaf4b087a07.png">

Same goes for the all that I tried, for example the current one: 

<img width="300" alt="image" src="https://user-images.githubusercontent.com/4745859/121485791-d2af0c80-c9d0-11eb-8850-596bd77ec6bc.png">

**Comment by ghost** [comment]
> That was verdana I think, but seems it does not support "all" languages. So I searched and found that Noto should support everything.
> 
> Here it is:
> <img alt="image" width="591" src="https://user-images.githubusercontent.com/4745859/121485497-8794f980-c9d0-11eb-9be8-5b0a3ea31c60.png">
> 
> But what's weird is that dev tools seems to suggest that is not really being used 100%:
> 
> <img alt="image" width="286" src="https://user-images.githubusercontent.com/4745859/121485398-721fcf80-c9d0-11eb-942c-afaf4b087a07.png">
> 
> Same goes for the all that I tried, for example the current one:
> 
> <img alt="image" width="300" src="https://user-images.githubusercontent.com/4745859/121485791-d2af0c80-c9d0-11eb-8850-596bd77ec6bc.png">

Noto uses lots of separate font extensions to support all the languages. Without them, only LGC glyphs are supported.
The first font in the previous message was DejaVu Sans, as Vedrana does not support Hebrew.

**Comment by hovancik** [comment]
I see, I thought it would be all in one. I'll need to figure out how it works...
