### ISSUE TITLE
[Feature request]: About postponement

### ISSUE THREAD

**Issue by lvksh** [hovancik/stretchly#972]
### Version

- [X] I'm using version 1.7.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

macOS

### Operating System Version

Catalina 10.15.7

### Problem description

When I am working, stretchly may sometimes pop out in an awkward timing for example I want to finish this part before my thoughts went away. The postponement can help but sometimes I want more postponement time like 5 minutes or even 10 minutes. Could you add a feature that I can customize the postponement time for each break?  

### Possible solution

Add a feature that I can customize the postponement time for each break, better if I can set the postponement time with a simple keyboard binding with pre-set time period (5mins, 10mins).

### Alternative solutions

Not really

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi there, 

there is more complex system of postponments, read more here https://github.com/hovancik/stretchly#editing-postpone-functionality- about how to set it up :) 

It's not exactly what you ask for, but I hope it will be sufficient for you. For now, I would prefer not to complicate it further with different postpone times and shortcuts.
