### ISSUE TITLE
[Bug]: Error occurs when /tmp is mounted noexec

### ISSUE THREAD

**Issue by nihil-admirari** [hovancik/stretchly#976]
### Version

- [X] I'm using version 1.7.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

Linux

### Operating System Version

Ubuntu 20.10

### Reproduction steps

1. `sudo mount -o remount,noexec /tmp` if it's not mounted `noexec` already.
2. Start stretchly.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% of the time.

### Expected Behavior

If I understand it correctly, application should not attempt to load a shared library from `/tmp`.

### Actual Behavior

Error pops up, and the following is printed to the console:
```
Error: /tmp/.org.chromium.Chromium.UMBBQC: failed to map segment from shared object
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (/opt/Stretchly/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/opt/Stretchly/resources/app.asar/node_modules/macos-notification-state/lib/index.js:1:34)
```
Application, however, appears to be functional: I can open preferences etc., but the error popup doesn't go away, and if you dismiss it, the application will close.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
So what does that `noexec` does? That's beyond my knowledge? 

I've tried to search that error in Electron repo but no results

**Comment by hovancik** [comment]
I see signal has the same issue: https://github.com/signalapp/Signal-Desktop/issues/2595 , especially https://github.com/signalapp/Signal-Desktop/issues/2595#issuecomment-648953340 

I'm using `electron-builder` to build executables/installers but there seems to be no issue about this

**Comment by nihil-admirari** [comment]
It prevents execution from a mount point. Sorry, I forgot to mention that `/tmp` must be a separate partition. Here's my `/etc/fstab` entry:
```
none  /tmp  tmpfs  noexec,nosuid,nodev,noatime  0 0
```

**Comment by nihil-admirari** [comment]
I found a comment in [jitsi-meet-electron](https://github.com/jitsi/jitsi-meet-electron/issues/556#issuecomment-814479734) referencing [Electron build documentation](https://www.electron.build/generated/platformspecificbuildoptions):

> asar = true AsarOptions | Boolean - Whether to package the application’s source code into an archive, using Electron’s archive format.
   Node modules, that must be unpacked, will be detected automatically, you don’t need to explicitly set asarUnpack - please file an issue if this doesn’t work.
   ...
    asarUnpack Array<String> | String - A glob patterns relative to the app directory, which specifies which files to unpack when creating the asar archive.

I'm not an Electron developer, so I cannot really provide any guidance, but maybe setting `asarUnpack ['**/node_modules/macos-notification-state/**']` would help?

**Comment by hovancik** [comment]
Thanks! 

The documentation says that that value is a boolean and that it is set to `true` by default so it should already do what we want it do? TBH I am not familiar with this

> smartUnpack = true Boolean - Whether to automatically unpack executables files.

**Comment by nihil-admirari** [comment]
Documentation does say that executables should be unpacked by default, but apparently it's just not happening.  Comment in [jitsi-meet-electron](https://github.com/jitsi/jitsi-meet-electron/issues/556#issuecomment-814479734) noted that too:
> The odd thing is, the documentation suggests all of this should be already happening for you

Maybe it's a bug in electron build.

**Comment by nihil-admirari** [comment]
Electron builder issue: https://github.com/electron-userland/electron-builder/issues/5821.

Issue is reproducible on a locked down Windows machine:
1. Enable AppLocker (Local Security Policy > Application Control Policies > AppLocker > Configure rule enforcement: Enable all rules including DLL).
2. Create default rules in each category (Executable Rules > Right click > Create Default Rules).
3. If Stretchly is not in `%ProgramFiles%`, create an executable and a DLL rule for it (Create New Rule > Allow All > Path).
4. Start `stretchly` from console.
```
00:29:58.521 > Error: error: 1260\\?\C:\Users\User\AppData\Local\Temp\5b986260-a283-4090-90a7-7d79c826ffd9.tmp.node
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (C:\Users\User\Desktop\Stretchly-1.7.0-win\resources\app.asar\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\Users\User\Desktop\Stretchly-1.7.0-win\resources\app.asar\node_modules\windows-notification-state\lib\index.js:1:65)
```

I don't have a Mac, but I guess that disabling execution from temp directory (via e.g. [Google Santa](https://github.com/google/santa)) will result in a similar error.

**Comment by hovancik** [comment]
Seems to me that issue is that Linux/Windows even add `macos-notification-state` to the build?

**Comment by nihil-admirari** [comment]
On Linux: yes, `macos-notification-state` doesn't look like being necessary.

On Windows, problems are caused by a different module: `windows-notification-state`, which is necessary.

**Comment by hovancik** [comment]
Ah, ok, I see. Might be worth making PR for that package and add `os` (https://docs.npmjs.com/cli/v7/configuring-npm/package-json#os) but I am not sure how all is interconnected.

**Comment by hovancik** [comment]
I've added PR to the macos package
