### ISSUE TITLE
setToolTip not working on macOS

### ISSUE THREAD

**Issue by hovancik** [hovancik/stretchly#98]
So I have notices that setToolTip is not working correctly on macOS. 
easy way to reproduce is:

start app, skip to next break, cancel break -> . tooltip is not there 

Seems to work on Linux.  @sxmanton how about Windows? I didn't tested there yet. 

I would like to solve this before making a release. I guess I should open issue with electron.

**Comment by sxmanton** [comment]
I have no problem having the tooltip show when reproducing that sequence of actions on windows. Testing it did make me realize that the initial tooltip wasn't showing for 10 seconds, so I fixed that in above PR. Does the tooltip show up on mac initially (after the 10 seconds, anyway) if you don't skip to break?

**Comment by hovancik** [comment]
Yeah, it shows up correctly.

But then it's kinda weird: 
- shows correct info when we wait for the first break (although sometimes I have to go around with my mouse for it to show up)
- it shows correct tooltip when first break is on
- after break is over there is no tooltip 
- on next break, the tooltip is correct again
- repeat

Function to update tooltip gets called correctly  every 10 seconds. 

From one point it seems that we do something wrong when break is over (as it works fine during break), from other point of view it seems it's macOS's problem as it works on Linux/Windows. 

I was trying to go through stuff happening in lifecycle, but I could not find anything in code that made me suspicious. I have tried updating whole tray when updating tooltip, but no change.

**Comment by hovancik** [comment]
So I figured it out: 

after first break, when tooltip is not showing, one does need to open some window, eg: about app. Then tooltip starts showing up again, until next break is over.

**Comment by sxmanton** [comment]
That's pretty strange. Maybe something in finishBreak or finishMicroBreak functions is what is breaking it? Does the tooltip disappear if you let the break finish naturally as well, or only if you cancel the break?

**Comment by hovancik** [comment]
With natural end as well. I've tried small program, and it works fine, so I guess we are doing something wrong. 

main.js 

```
const {app, BrowserWindow, Menu, Tray} = require('electron')
const path = require('path')
const url = require('url')

let win
let tray = null

function createWindow () {
  win = new BrowserWindow({width: 800, height: 600})
  win.loadURL(url.format({
    pathname: path.join(__dirname, 'index.html'),
    protocol: 'file:',
    slashes: true
  }))
  setTimeout(closeWindow, 5000)
}

app.on('ready', timeouts)
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('ready', () => {
  tray = new Tray('./Phone-icon.png')
  const contextMenu = Menu.buildFromTemplate([
    {label: 'Item1', type: 'radio'}
  ])
  tray.setContextMenu(contextMenu)
  updateToolTip()
  setInterval(updateToolTip, 10000)
})

function updateToolTip () {
  tray.setToolTip('Running application')
}

function timeouts () {
  setInterval(createWindow, 20000)
}

function closeWindow () {
  win.close()
  win = null
  updateToolTip()
}
```

**Comment by sxmanton** [comment]
I'm not really sure what this line does in finishBreak/finishMicroBreak but I have a feeling it might be causing issues?
```
if (process.platform === 'darwin') {
      // get focus on the last app
      Menu.sendActionToFirstResponder('hide:')
    }
```

**Comment by hovancik** [comment]
Yes, you are right. I commented it out and tooltip was showing correctly. (could be `app.hide()` as well) 

The mentioned code is there to bring focus to the last used application for macOS users. (https://github.com/electron/electron/blob/master/docs/api/app.md#apphide-macos)

**Comment by hovancik** [comment]
I've opened issue https://github.com/electron/electron/issues/9447

**Comment by sxmanton** [comment]
Ok, hopefully they can fix it before too long.

**Comment by hovancik** [comment]
No answer on electron side. I guess I will make new release and create `Known bugs` in readme and changelog.

**Comment by sxmanton** [comment]
Ok. Can we merge https://github.com/hovancik/stretchly/pull/99 before you do a new release?

**Comment by hovancik** [comment]
Done. Will probably release today.

**Comment by hovancik** [comment]
This is electron bug and mentioned in readme so I'm closing it.
