### ISSUE TITLE
[Feature request]: Alternate Breathing Methods

### ISSUE THREAD

**Issue by BradKML** [hovancik/stretchly#987]
### Version

- [X] I'm using version 1.7.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Windows

### Operating System Version

Windows 10 19043.1081

### Problem description

There are multiple breathing methods out there: 
https://medium.com/welltory/11-breathing-practices-to-get-you-through-a-rough-patch-cea987791dbe

Maybe there should be an option for people choose their own method of breathing?

### Possible solution

The ability to choose the breathing pattern in a break.

### Alternative solutions

Breathly does not have PC options but it does have information about good breathing patterns https://github.com/mmazzarolo/breathly-app/issues/80

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BradKML** [comment]
Other applications have this feature as well "BREATHING DIALOG" https://mindfulness-at-the-computer.gitlab.io/screenshots/

**Comment by hovancik** [comment]
Well, I am definitely not trying to copy other apps. Stretchly is "The break time reminder app" so that is my scope. If there is science behind it, we could add Long Break idea telling people to go research and try different methods.

**Comment by BradKML** [comment]
Regarding studies, this is a new field but there is a Review https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6137615

**Comment by hovancik** [comment]
I've added https://github.com/hovancik/stretchly/pull/994/files#diff-0e8c02efddc61fbdb3ba8b6004a939956b0a70a943a42e706d2e433cee6b5cf2R133 feel free to comment

**Comment by BradKML** [comment]
@hovancik another thing with this, maybe the app itself can have some interactive breathing bubbles?

This is the one with similar issue with the 7 minute workout, where the message does not provide guidance, prompting one self to "break the break" and search info online.

**Comment by hovancik** [comment]
Hi, that's out of scope for me. I would not be able to maintain Meditation, Breathing, Working out and much more apps under the umbrella of Stretchly. They should be separated apps.

**Comment by BradKML** [comment]
@hovancik in this case it is quasi-inept design on the end of Stretchly, but if there are ways of integrating this with Breathly https://github.com/mmazzarolo/breathly-app and others.
