### ISSUE TITLE
[Feature request]: Leaving Work Mantra

### ISSUE THREAD

**Issue by BradKML** [hovancik/stretchly#988]
### Version

- [X] I'm using version 1.7.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Windows

### Operating System Version

Windows 10 19043.1081

### Problem description

Cal Newport's Deep Work suggested creating a mantra for giving people the time to leave work and relax.

### Possible solution

Cues of Closing Work
- Check To-Do List
- Schedule Urgent Work
- Skim Tomorrows Task
- Plan for Tomorrow

Things to do as leisure: ...

### Alternative solutions

https://github.com/skidding/jobs-done

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, I don't plan to add this to Stretchly, as it is out of scope, but I also have another app where you can create custom reminders: https://lateron.app

**Comment by BradKML** [comment]
@hovancik a reminder app that takes over the whole screen would be more useful than just pinging in the corner.

**Comment by hovancik** [comment]
There's issue about this: https://github.com/hovancik/later-on/issues/2, but not sure when and such
