### ISSUE TITLE
[Feature request]: Added multimedia for Meditations and Workouts

### ISSUE THREAD

**Issue by BradKML** [hovancik/stretchly#989]
### Version

- [X] I'm using version 1.7.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Windows

### Operating System Version

Windows 10 19043.1081

### Problem description

Observing https://github.com/hovancik/stretchly/blob/trunk/app/utils/defaultBreakIdeas.js there are some ideas that can help people, but they have not nailed the function on its head yet.

### Possible solution

For example, for Meditation, there is an application that guides people through meditation https://github.com/mmazzarolo/breathly-app
Depending on the size, one can simply shoehorn the whole application into Stretchly. Alternatively the breathing animation noted in https://github.com/mmazzarolo/breathly-app/issues/87 can be used.

And for Exercise and Workout, perhaps there is a video that can be played so people can play along. Alternatively, there are more workouts at https://darebee.com/workouts.html

### Alternative solutions

Using Breathly separately isn't that good of an idea when Stretchly is blocking it on screen.
Also the "7 minute workout" just appearing on screen is not helpful, it can be turned off tho.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BradKML** [comment]
For search term purposes "micro-workout" provides some good information.
Reference on why:
https://medium.com/mattsthoughts/stop-going-to-the-gym-870936e2e827
https://www.mealenders.com/micro-workouts-the-most-efficient-way-to-benefit-from-exercise-in-half-the-time/
https://www.menshealth.com/fitness/a19518563/micro-workout/
Reference on method:
https://www.bustle.com/p/7-micro-workouts-that-are-super-effective-if-you-dont-have-much-time-to-exercise-51421
https://www.health.com/fitness/one-minute-workout-book
https://living.medicareful.com/micro-workouts-exercise-routines-for-a-busy-life
https://www.inlandweightloss.com/blog/8-micro-workouts-to-stay-fit-when-you-travel/
https://www.shape.com/featured/StriveMicroworkoutsAtYourDesk
https://www.azumio.com/blog/fitness/micro-workouts-are-the-future
https://www.sheknows.com/health-and-wellness/articles/2048626/short-quick-workouts-you-can-do-anywhere/

**Comment by hovancik** [comment]
Hi, sorry, but I don't plan to do that. That would be simply too difficult to maintain. Meditations could be added, but Stretchly is not meditation app, I believe in "do one thing and do it right" approach. 

I plan to have some sort of plugin system, where people can program different behaviors for breaks (https://github.com/hovancik/stretchly/issues/310#issuecomment-557877850), but TBH, not sure when it will happen.
