### ISSUE TITLE
[Bug]: Stretchly leaves many processes behind on Linux

### ISSUE THREAD

**Issue by DanijelDomazet** [hovancik/stretchly#991]
### Version

- [ ] I'm using version 1.7.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

Linux

### Operating System Version

Ubuntu 20.04

### Reproduction steps

Leave it running on Ubuntu for days. 
View your processes and you will see tens of Stretchly processes listed. 

### Expected Behavior

Single process, or not as much.

### Actual Behavior

After running Stretchly for days you will see tens of Stretchly processes listed. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
You did not check using version 1.7. There was issue in previous versions that was then fixed. Let me know if this is still case in 1.7. I am on Debian with 1.7 and do not observe any issue.
