### ISSUE TITLE
[Feature request]: Prevent from running when playing a game of chess on Lichess.com in a browser. :-) 

### ISSUE THREAD

**Issue by DanijelDomazet** [hovancik/stretchly#992]
### Version

- [ ] I'm using version 1.7.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Linux

### Operating System Version

Ubuntu 20.04

### Problem description

I loose on time as the games are mostly rapid 5min chess games.

### Possible solution

Prevent from running when playing a game of chess on Lichess.com in a browser. :-) 

### Alternative solutions

Prevent from running when playing a game of chess on Lichess.com in a browser. 
:-) 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, you can try finding whether your browser somehow leaks the name of url into process and pause when such a process run via advanced preferences: https://github.com/hovancik/stretchly#pauseresume-breaks-only-when-specific-command-is-running

**Comment by decadent** [comment]
More realistically this would be done by:

- having some generic browser extension that calls external processes/commands when a certain site is opened and the browser is active, and when it's inactive or the site is closed.

- configuring that extension to call Stretchly's command-line commands to pause and unpause.
