### ISSUE TITLE
[Feature request]: Show Stretchly break information on lock screen on Windows 10

### ISSUE THREAD

**Issue by ghost** [hovancik/stretchly#995]
### Version

- [X] I'm using version 1.7.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Windows

### Operating System Version

Windows 10 21H1 19043.1083

### Problem description

If you like to take a walk when on a long break, and you are the type to lock screens when stepping away, then there is no way to know if you have come back early without unlocking the screen.

### Possible solution

Essentially, allow seeing how much of the break time is left, or some indication of whether the break is over or not on the lock screen, when the screen is locked during an ongoing break.

The reason I think this would be good addition is that, if users like to step away from the laptop when on a break and want to lock their screens, then having this information on the lock screen would help them know if they have come back early. You could also include information on how much they overshot if you want. You could also include a button on the break window popup to lock the screen.

I am not sure if electron has built in support for this. This might end up being specific to Windows. But I feel it would be worth it for the Windows users.

The setting I am referring to is:

![stretchly](https://user-images.githubusercontent.com/878118/125075346-1d10cf80-e0dc-11eb-9f6e-ba950a8da758.png)

For a calendar app, the app might be able to display info like:

![win-10-detailed-info-lock-screen](https://www.tenforums.com/attachments/tutorials/215051d1543084926-choose-apps-detailed-quick-status-windows-10-lock-screen-lock_screen_detailed_status.jpg)

The second screenshot is from a post: https://www.tenforums.com/tutorials/122250-choose-apps-detailed-quick-status-windows-10-lock-screen.html

### Alternative solutions

None I could think of

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
I am not a Windows user so I am not sure how that works, but I was not able to find any information about how to add app there. Seems like it is only a selection of Microsoft apps like email etc?

**Comment by BunNybuger** [comment]
That is an excellent suggestion, but I request something simpler than that if doing so is not possible. Just do not reset breaks each time I lock my window. Sometimes, I lock my screen on mini-breaks, but unfortunately, Stretchly reset the breaks, so I should wait for a long break three more times!

**Comment by hovancik** [comment]
I don't plan to work on this, so closing.
